### ISSUE TITLE
Create Educational Screencasts

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#100]
A set of screencasts should be created to compliment the existing text-based documentation that show users how to contribute to the documentation. I don't see the need to cover everything in minute detail; just the essential workflows of creating issues and editing content via GitHub. 

- [x] **Series 1: Creating New Documentation Issues (_for Non-Developers_)**
  This is an, already completed, 5-part series that steps non-developers through the process of creating new documentation issues. 

- [x] **Series 2: Editing the Documentation with GitHub**
  This is a multi-part series, aimed primarily at non-developers, that steps users through the process of editing the documentation with GitHub.

**Comment by michaelstingl** [comment]
Series 1: 1-5 done: https://www.youtube.com/user/ownCloudofficial/videos

@spangtey could you make a playlist for them?

@settermjd What is the status of the sequel?

**Comment by voroyam** [comment]
@settermjd any update?

**Comment by voroyam** [comment]
@michaelstingl playlist is now visible at https://www.youtube.com/user/ownCloudofficial/playlists

**Comment by tboerger** [comment]
I guess he got to produce the second series.

**Comment by voroyam** [comment]
He has, the question is when :)

The first series is very relaxing and educational

**Comment by settermjd** [comment]
@micbar / @michaelstingl can we get this in a future sprint?

**Comment by michaelstingl** [comment]
> @micbar / @michaelstingl can we get this in a future sprint?

Sure, I'd love to see more of this. Is there anything I can help?

**Comment by settermjd** [comment]
Just getting it in a future sprint will give me the okay to get it done.

**Comment by settermjd** [comment]
Working through these this week.

**Comment by settermjd** [comment]
The second series (of 6 videos) [is available for review](https://cloud.owncloud.com/index.php/apps/files/?dir=/Shared/owncloud/Training&fileid=4975776).

**Comment by voroyam** [comment]
why is your voice is merely hearable in the first seconds? can you re record?

**Comment by voroyam** [comment]
apart from that - great videos

**Comment by settermjd** [comment]
> why is your voice is merely hearable in the first seconds? can you re record?

I don't quite follow what you mean? Was the problem in one particular video? If so, which one? Just need to track this down. Thanks for the feedback, btw.

**Comment by voroyam** [comment]
The first video of the new series. It's 4?

Just listen to the first 10 seconds or 20. At the beginning you are barely to hear and then it goes to 11 :)

**Comment by settermjd** [comment]
Thanks for that. I'll check it today.

**Comment by settermjd** [comment]
I had a listen and all of them start well, except for 4. So, I believe I see what you're referring to. I'll fix it in the next 20 mins.

**Comment by settermjd** [comment]
@voroyam, a revised copy of clip 4's now available.

**Comment by voroyam** [comment]
great. thanks
