### ISSUE TITLE
Make sure  https://doc.owncloud.org/desktop/2.6/  exists

### ISSUE THREAD

**Issue by guruz** [owncloud/docs#1002]
We're releasing 2.6.0 alpha1 soon-ish

**Comment by tboerger** [comment]
If the branch on the client repo already exists it just got to be added to the site.yml for the 4 branches on this repo.

**Comment by guruz** [comment]
@tboerger Hmm not sure what you mean by 4 branches, right now it only shows 'master' https://github.com/owncloud/docs/blob/master/site.yml#L22
And I don't see which branch you mean in this repo
There is a 10.0 branch here for example, but i'm speaking about desktop / client

**Comment by tboerger** [comment]
Master is the only branch that publishes the docs, but on the other 10.x branches it got to be part of the site.yml to be able to resolve cross references when validating the branch.

**Comment by guruz** [comment]
@tboerger but our client 'master' will be '2.7' soon.
Do i still need to put 2.6 in this site.yml?

**Comment by settermjd** [comment]
@guruz, if this hasn't been done already, I'll get it done.

**Comment by guruz** [comment]
@settermjd Thanks, that's maybe easier :]

**Comment by settermjd** [comment]
Actually, @guruz, do you want the 2.6.0 branch, when it's created, to be added to the docs configuration?

**Comment by guruz** [comment]
I want https://doc.owncloud.org/desktop/2.6/ to exist, that's all I want.
client branch is https://github.com/owncloud/client/tree/2.6 (without the .0)

**Comment by settermjd** [comment]
Fair enough.

**Comment by tboerger** [comment]
First we need to merge https://github.com/owncloud/client/pull/7179, after that we got to merge the PRs to the owncloud/docs repo on master/10.1/10.2 branches and everything will be tested and uploaded correctly.

**Comment by settermjd** [comment]
I see that you're already on the case, @tboerger. Thanks.

**Comment by tboerger** [comment]
https://doc.owncloud.com/desktop/2.6/ there you go, docs are available now.
