### ISSUE TITLE
Useful AsciiDoc Quick Reference link

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#104]
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

**Comment by settermjd** [comment]
Thanks. That's used as the description in the Rocket.Chat documentation channel. Hopefully, it makes it obvious that there is a quick ref guide. I'll also link to it in the README if it's not already linked to.

**Comment by settermjd** [comment]
OK, I see that it's not linked in [docs/blob/master/docs/what-is-asciidoc.md](https://github.com/owncloud/docs/blob/master/docs/what-is-asciidoc.md). I'll get that done.

**Comment by mmattel** [comment]
Adding here additional links, just to have them collected/documented, to be decided if or which one we want to use:

https://powerman.name/doc/asciidoc
https://is.muni.cz/el/1433/podzim2015/PB162/um/printable/asciidoc.html

**Comment by settermjd** [comment]
Take a look at #104, @mmattel, and let me know if you approve.

**Comment by mmattel** [comment]
will do, thanks
