### ISSUE TITLE
Weird Adblocker / Browser behavior.

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#106]
I suppose it is worth documenting that if you have for example Firefox and ublock origin enabled then it could happen that the sharing section does not appear for whatever reason.

A user in central has noticed that:

https://central.owncloud.org/t/missing-sharing-section-on-admin-page-oc-v10-0-9/15626/10

This fixes #116.

**Comment by tboerger** [comment]
Seriously? Than you will have to document a lot. Browsers always behave strange.

IMHO it's up to any user who installs such browser plugins.

**Comment by mmattel** [comment]
At least a note would be good...

**Comment by tboerger** [comment]
With regular ad b blockers like adblock plus nothing gets hidden

**Comment by settermjd** [comment]
@voroyam, please add a note, perhaps in a new troubleshooting section.

**Comment by voroyam** [comment]
Well, @tboerger , people are turning away from ad block plus because it got bought by someone or something, and they use ublock origin. This is my theory.

The concern is relevant, that you would have to document a lot.

My thought would be just to write something in the sharing section of the documentation, because that is where people would look for clues, if sharing did not work.

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/116

**Comment by PVince81** [comment]
I wonder if we could find out what is triggering the ad blocker and remove it / rename it

**Comment by voroyam** [comment]
That would be nice. But as I imagine it would have low priority, a note in the docs helps in the mean time
