### ISSUE TITLE
Documentation mediaviewer

### ISSUE THREAD

**Issue by PVince81** [owncloud/docs#1082]
Media viewer is intended to be a replacement for gallery and files_videoplayer.
Currently only comes with the slideshow view as a first step.

- [x] check where gallery is mentioned and replace with https://github.com/owncloud/files_mediaviewer.
- [x] for migrating from gallery to files_mediaviewer, one needs to make sure the gallery links still work using redirects: https://github.com/owncloud/gallery#uninstalling.

@pmaier1 FYI for the future docs

**Comment by mmattel** [comment]
FYI: https://doc.owncloud.com/server/user_manual/files/gallery_app.html
Plus some mentions in admin and user manual

**Comment by PVince81** [comment]
- [ ] add note in gallery uninstall + here in the docs that the gallery thumbnails must be deleted manually (if applicable)

**Comment by ho4ho** [comment]
> -  thubnails dont need to be removed - they are generated and maintained by the owncloud server aka core
> - gallery brings no own database tables
>
> There is no real clean up necessary

-> https://github.com/owncloud/docs/issues/1465#issuecomment-513696975

**Comment by ho4ho** [comment]
Also fix by https://github.com/owncloud/docs/pull/1515 ?
