### ISSUE TITLE
Update to always set headers

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#1094]
## What Needs to be Documented?
Refernces https://github.com/owncloud/core/pull/35099 (Avoid headers set twice in some situations)

## Where Does This Need To Be Documented?
https://doc.owncloud.com/server/admin_manual/installation/manual_installation.html#headers

## Why Should This Change Be Made? (Optional)
Make it clear wnat the backend is doing

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
@mmattel, is this issue fixed by https://github.com/owncloud/docs/pull/737/files? If so, please close this issue.
