### ISSUE TITLE
Database diagrams for core and common apps

### ISSUE THREAD

**Issue by PVince81** [owncloud/docs#1095]
To get a better overview, we should provide a database schema diagram for the core tables and their relationships. If applicable, also include tables from common apps like notifications, activity, etc.

To be included in the developer docs.

Note that there are currently no foreign keys in place and relationships are defined/resolved in code. We should still indicate the intended table relationships.

Some relationships are already listed in https://github.com/owncloud/core/issues/13143#issuecomment-73707838

**Comment by settermjd** [comment]
@PVince81, can you add a suitable priority label, pls?

**Comment by settermjd** [comment]
@PVince81, are you still keen to see this implemented?
