### ISSUE TITLE
Manual Upgrade Instructions

### ISSUE THREAD

**Issue by miqrogroove** [owncloud/docs#112]
There are a few problems that can be fixed in these instructions

https://doc.owncloud.org/server/10.0/admin_manual/maintenance/manual_upgrade.html

Under "Enable Maintenance Mode", the admin is instructed to stop the cron service. At no point in the page is the admin instructed when or how to restart the cron service, leaving cron totally disabled.

Under "The Power User Upgrade", the file extraction step is so vague that it never mentions file ownership or permissions. If the admin has extracted or copied the files as any user other than www-data, the remaining instructions on this page will cause file access errors. A good improvement here would be a link to https://doc.owncloud.org/server/10.0/admin_manual/maintenance/update.html#set-updating-permissions-label

Under "Copy Old Apps", the instructions are unnecessarily vague about "3rd party applications". Which apps are 3rd party? Which are not? For example, an earlier section explicitly shows how to disable the activity, files_pdfviewer, files_texteditor, and gallery apps. However, following all the instructions on the page results in a new /owncloud/ directory where these apps are missing, and it is not clear why these apps should be manually copied from /owncloud-old/. I think this just needs to be explained better.

Crosss posted from https://github.com/owncloud/core/issues/32783

**Comment by voroyam** [comment]
No.

Document is out of sync with the version on GitHub.

We should bring the online document in sync with GitHub and then see if the requested changed were not already implemented.

One example:

> Under "Enable Maintenance Mode", the admin is instructed to stop the cron service. At no point in the page is the admin instructed when or how to restart the cron service, leaving cron totally disabled.

![image](https://user-images.githubusercontent.com/24212810/46014493-c58e4a00-c0cf-11e8-8e72-dbae5626fdf0.png)

https://owncloud-docs.netlify.com/server/maintenance/manual_upgrade.html#finalize-the-installation

**Comment by settermjd** [comment]
Fair call. I'll sort this out.

**Comment by settermjd** [comment]
@voroyam, which PR wasn't backported?

**Comment by voroyam** [comment]
No idea. The changes I made were months ago

**Comment by settermjd** [comment]
OK. I'll try and find it.

**Comment by settermjd** [comment]
#891 has been created to address these issues.
