### ISSUE TITLE
Missing image in ldap_proxy_cache_server_setup

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#1173]
## What Needs to be Documented?
An image is missing in: https://doc.owncloud.com/server/admin_manual/configuration/ldap/ldap_proxy_cache_server_setup.html#configure-the-ldap-application

I can not find this image neither in this docs or in old docs.
```
modules/admin_manual/assets/images$ find . -type f -name "*ldap*.png"
./enterprise/external_storage/ldap-home-connector-1.png
./enterprise/external_storage/ldap-home-connector-2.png
./enterprise/external_storage/ldap-home-connector-3.png
./ldap-advanced-1-connection.png
./ldap-advanced-2-directory.png
./ldap-advanced-3-attributes.png
./ldap-expert.png
./ldap-fetched-avatar.png
./ldap-wizard-1-server.png
./ldap-wizard-2-user.png
./ldap-wizard-3-login.png
./ldap-wizard-4-group.png
```

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@settermjd @butonic @jvillafanez

**Comment by mmattel** [comment]
I have found the image that can be used, just replace the wrong link with
`image:ldap-wizard-1-server.png[LDAP wizard, server tab]`

**Comment by jvillafanez** [comment]
Not sure what I should do here...
I don't see any problem in using that image there. We should consider to update the screenshots at some point, maybe when the new LDAP interface is out is a good moment.

**Comment by michaelstingl** [comment]
Here is the wrong link:

https://github.com/owncloud/docs/blob/701e8904a4fc3c895580ca6a7e280e512040b4f1/modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc#L191-L193

This doesn't look nice in my statistics:

<img width="914" alt="Graylog_-_Dashboard_Docs_errors" src="https://user-images.githubusercontent.com/214010/58342605-1c137a00-7e51-11e9-835d-863b460331ba.png">
