### ISSUE TITLE
Contact information for troubleshooting out-dated

### ISSUE THREAD

**Issue by enbrnz** [owncloud/docs#1181]
## What Needs to be Documented?
In [General Troubleshooting](https://doc.owncloud.org/server/admin_manual/configuration/general_topics/general_troubleshooting.html#introduction) the IRC channel and the mailing list are still mentioned, however they are no longer active.

Also, there is no mention of [talk.owncloud.com](https://talk.owncloud.com/home)

## Where Does This Need To Be Documented?
This would have to be added into
[modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc](https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc)

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual

**Comment by michaelstingl** [comment]
Here you can find our official recommendations:
https://owncloud.org/help/

(Footer on https://owncloud.org/ mentions IRC channel and the mailing list as well /cc @lefherz @hurradieweltgehtunter )

**Comment by settermjd** [comment]
Thanks for linking to all of these @enbrnz & @michaelstingl

**Comment by hurradieweltgehtunter** [comment]
sorry for the late response.
fixed on owncloud.org

![image](https://user-images.githubusercontent.com/16665512/58088495-19035a00-7bc3-11e9-9051-7a82b66c2940.png)

**Comment by settermjd** [comment]
Thanks @hurradieweltgehtunter.

**Comment by voroyam** [comment]
Any idea what that is?

The ownCloud User mailing list

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1522

**Comment by settermjd** [comment]
Closing, as all relevant PRs have now been implemented and merged.
