### ISSUE TITLE
[dev] [OCS] API for pending shares in 10.0.9+

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#1193]
## What Needs to be Documented?

10.0.9 introduced pending shares. This also needs to be added to the developer docs. I'd assume it looks similar to pending [federated shares](https://doc.owncloud.com/server/developer_manual/core/ocs-share-api.html#federated-cloud-shares)

## Where Does This Need To Be Documented?

https://doc.owncloud.com/server/developer_manual/core/ocs-share-api.html

## Why Should This Change Be Made? (Optional)

Information is needed for implementation in ownCloud clients.

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

/cc @DeepDiver1975

**Comment by phil-davis** [comment]
The acceptance tests currently get pending/accepted/rejected/all shares with `getAllSharesSharedWithUser()`
https://github.com/owncloud/core/blob/master/tests/acceptance/features/bootstrap/Sharing.php#L1633

that uses a URL like:
```
		$url = "/apps/files_sharing/api/v{$this->sharingApiVersion}/shares" .
			   "?format=json&shared_with_me=true&state=$stateCode";


```

**Comment by michaelstingl** [comment]
Hint from @DeepDiver1975 : 

> please note that 'state' is only valid in combination with the param 'shared_with_me'

**Comment by settermjd** [comment]
@michaelstingl / @phil-davis can one of you assign an appropriate priority label to this issue, pls?

**Comment by settermjd** [comment]
@michaelstingl, which commits / issues relate specifically to this issue?

**Comment by settermjd** [comment]
At a guess, I only estimate a 1/2 day for this.

**Comment by settermjd** [comment]
@michaelstingl / @phil-davis where can I find out more information about this?

**Comment by michaelstingl** [comment]
@hosy you did reverse engineer pending user / group shares. Any hints?

**Comment by DeepDiver1975** [comment]
@settermjd you basically have to add the state parameter in here https://github.com/owncloud/docs/blob/143bdefd67f2fd995bb1e0279b2847bda9c1cdf4/modules/developer_manual/pages/core/apis/ocs-share-api.adoc#get-shares-from-a-specific-file-or-folder

**Comment by settermjd** [comment]
Closing as this has been implemented.
