### ISSUE TITLE
Rate-Limiting

### ISSUE THREAD

**Issue by IljaN** [owncloud/docs#1195]
## What Needs to be Documented?
Currently ownCloud deliberately does not provide any form of rate-limiting. The reason being that the product needs to integrate in to different environments with a diverse infrastructure which often already provide a specialized rate-limiting solution (nginx, haproxy, F5 etc.)

## Where Does This Need To Be Documented?
Advanced documentation / Hardening

## Why Should This Change Be Made?
As we offer no rate-limiting out of the box (except brute-force protection) it is possible to overflow the database by mass-creating shares or custom-groups. We should at least have a documentation with rate-limiting recommendations for the customer. For this we should create a list with different routes and their recommended limits. 

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by IljaN** [comment]
@PVince81 mentioned that there should be a command which dumps all routes

**Comment by phil-davis** [comment]
```
php occ security:routes
```
