### ISSUE TITLE
[desktop] stable 2.5 docs missing

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#1197]
![ownCloud_Documentation_Overview____ownCloud_Documentation](https://user-images.githubusercontent.com/214010/57568009-a1bf1080-73e1-11e9-985f-956631604ad6.png)

## What Needs to be Documented?

ownCloud desktop sync client 2.5 is the current stable version, but it's not in the navigation. (2.6 is still alpha)

## Where Does This Need To Be Documented?

Somewhere in the config or in the navigation where you can switch platforms and versions.… (Every page on https://doc.owncloud.org/ and https://doc.owncloud.com/)

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [x] Other

**Comment by tboerger** [comment]
The 2.5 branch have never been migrated to the new format, that's why it's not listed here.

**Comment by settermjd** [comment]
Migrating it would be an excellent test for [kramdown-asciidoc](https://github.com/asciidoctor/kramdown-asciidoc).

**Comment by michaelstingl** [comment]
We plan some UI improvements, then it will be easier to guide users what are the relevant docs, and which one are outdated.

I see no urgency to migrate 2.5 docs to Antora. Close https://github.com/owncloud/client/pull/7186 ?
