### ISSUE TITLE
Can't link to some categories

### ISSUE THREAD

**Issue by cortho** [owncloud/docs#1199]
Similar to https://github.com/owncloud/docs/issues/800 I cannot link to some sub categories as well, e.g. Encryption or Server at https://doc.owncloud.org/server/admin_manual/configuration/
I guess there are several more.

Shouldn't every folder provide an index.html/adoc?

**Comment by settermjd** [comment]
From reading through the [component index page](https://github.com/owncloud/client/pull/7187) section of the documentation, an `index.adoc` file has no special significance other than when present in the root directory of a module. 

You can link to whatever page you want using xrefs. What are the specific pages that you're wanting to link to?

**Comment by cortho** [comment]
Thank you for clarification, then I misread tboerger's comment in #800

I wanted to link to ownCloud Server -> Admin Manual -> Configuration -> Encryption

When right-clicking did not reveal a link, I thought it would not be possible to link to that section. Now I found out, that https://doc.owncloud.org/server/admin_manual/configuration/files/encryption/ can be reached. (same for the breadcrumbs on the page)

So the page is there, but there is no link in the navigation, so it cannot be reached by clicking on "Encryption". (maybe this is the real issue)

More general, I thought there would be a way to automatically have some kind of linked index page, when there are subpages.

**Comment by michaelstingl** [comment]
Sounds like a duplicate for https://github.com/owncloud/docs/issues/800 , but it was closed. (accidentally by some automation magic?)

**Comment by settermjd** [comment]
Closing as this has been implemented.
