### ISSUE TITLE
Remove page 'Linux Package Manager Installation'

### ISSUE THREAD

**Issue by enbrnz** [owncloud/docs#1203]
## What Needs to be Documented?
[This page](https://doc.owncloud.com/server/admin_manual/installation/linux_installation.html) is explaining how to install ownCloud using the package 'owncloud-files'. Searching through the any recent Ubuntu/Debian/CentOS/OpenSuse distribution, I could not find the package.

As the installation method is problematic anyway, perhaps it would be best to remove the page all together.

## What Type Of Content Change Is This? (Optional)
- [x] Old Content Deprecation

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual

@mmattel && @settermjd What are your opinions?

**Comment by settermjd** [comment]
Hey @enbrnz, thanks for reporting this! 

After adding ownCloud's repository, as per the instructions at https://download.owncloud.org/download/repositories/stable/owncloud/index.html, `owncloud-files` will be available via your package manager. I'll get the relevant instructions added to https://doc.owncloud.com/server/admin_manual/installation/linux_installation.html.

**Comment by patrickjahns** [comment]
@enbrnz 
`owncloud-files` is very much relevant in the context for larger companies - they prefer to utilize packages

**Comment by michaelstingl** [comment]
> After adding ownCloud's repository

@settermjd looks like that's the missing piece on https://doc.owncloud.com/server/admin_manual/installation/linux_installation.html

**Comment by michaelstingl** [comment]
Solution in this PR: https://github.com/owncloud/docs/pull/1205

@enbrnz works for you?

**Comment by enbrnz** [comment]
Sorry for the late reply! All good!
