### ISSUE TITLE
LDAP Docs improvements

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#1212]
https://doc.owncloud.com/server/admin_manual/configuration/user/user_auth_ldap.html

- the link to the occ page links to users command, not specifically to the user:sync command
- the link to the cron job has no user:sync example

User sync has to be on the top of the document, since it's an important change from 9 to 10 and it's being at the bottom in a large text block with links to other parts of the docs is not optimal.

**Comment by mmattel** [comment]
@voroyam I am linking issue https://github.com/owncloud/docs/issues/1173 because that could be made in one shot so both ldap files would be corrected

**Comment by settermjd** [comment]
@voroyam, where you wrote "_the link to the cron job has no user:sync example_", were you referring to http://127.0.0.1:8080/server/admin_manual/configuration/server/background_jobs_configuration.html#cron-jobs?

**Comment by settermjd** [comment]
@voroyam, with respect to your point below:

> User sync has to be on the top of the document, since it's an important change from 9 to 10 and it's being at the bottom in a large text block with links to other parts of the docs is not optimal.

You can see in the screenshot below, that the information's only halfway down the page, and comes after the intro, configuration, and testing sections. I'd have thought that that would be the correct order.

![user ldap toc](https://user-images.githubusercontent.com/196801/57848283-bed85280-77d8-11e9-8430-09e42cabcda3.png)

I'm not against a restructure of the page, but how would you organise it in a way that makes more sense, and is easier to navigate for the user?

**Comment by voroyam** [comment]
pr is merged, closing. Thanks @settermjd for your work
