### ISSUE TITLE
consolidate different server installation docs

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#1218]
We have 
 * an excellent https://doc.owncloud.org/server/10.1/admin_manual/installation/deployment_recommendations.html which discusses several scenarios.
     - It has a reference to details regarding ubuntu 14.04 -- which is no longer supported
     - It is high level for the experienced sysadmin, but has no link to a step by step owncloud server installation.
 * https://doc.owncloud.com/server/admin_manual/installation/server_prep_ubuntu_18.04.html
     - has many details regarding apache setup, not available in the above.
     - but does not discuss any enterprise scenario, as the above does. Although enterprise users are more likely to see docs on owncloud.com than on owncloud.org ?
 * https://doc.owncloud.com/server/admin_manual/installation/manual_installation.html which has detailled steps for multiple platforms
     - it has a confusing prerequisites section near the end, explaining php module details. This is not needed(an possibly confusion). Users most likely already installed all dependency packages through the systems package manager, before they come to that section. I assume this is only there, if someone wants to bypass the systems package manager and use `pecl install` for a specific reason.
     - it lists 'installation wizard' and 'command line installation' as alternatives to 'docker', 'manual', and 'packages' -- that is misleading. I believe that either 'installation wizard' or 'command-line' should be done after doing 'docker', 'manual' or 'packages'.
     - The section #enable-ssl mentions self-signed certificates, but has no steps how to create either self-signed nor proper certificates.
     - the platform specific lists of dependency packages do not mention how an sqlite package is called. (`apt-get install sqlite` is not sufficient to make it work on ubuntu)

In general, I'd suggest to apply more cross linking amongst the individual parts of the documentation. There are many details presentet, one easily gets lost in mid-install and fails to locate the document for the next step.

Maybe add a another scenario "quick test setup (not for production)" 
 has a concise list of minimum steps (for only one recommended ubuntu 18.04 platforms) e.g. not much more than this:
```
...
cp /usr/share/doc/owncloud-files/owncloud-config-apache.conf.default /etc/apache2/conf-available/owncloud.conf
a2enconf owncloud
sudo apt-get install php-mysql php-intl php-mbstring php-gd php-json php-sqlite3 php-curl php-xml php-xml php-imagick php-apcu php-zip
systemctl reload apache2
...
```

**Comment by jnweiger** [comment]
@HanaGemela hope that may be helpful in future :-)

**Comment by settermjd** [comment]
Thanks for creating this issue, @jnweiger. I'll get it actioned asap.

**Comment by mmattel** [comment]
Imho, deployment recommandation is different to server preparation. The first one is a layout guide.
As more you go into enterprise, as better the admins knowledge is required - else that would not work by design. What I could imagine is, to have additional server prep docs describing what you need to do to achieve more complex scenarious - but doesn´t that go too far  except maybe best practices as we know them?
For the manual installation document, I think it would be good to create for each OS a page like we have linked for Ubuntu - which can be used as a template. That would streamline things a lot.

Just my 2c :smile:

**Comment by voroyam** [comment]
@jnweiger is this what you had in mind?

https://doc.owncloud.com/server/10.2/admin_manual/installation/ubuntu_18_04.html

**Comment by settermjd** [comment]
@jnweiger, can you provide feedback on https://github.com/owncloud/docs/issues/1218#issuecomment-513736712 pls?

**Comment by jnweiger** [comment]
Thanks @voroyam that updated ubuntu 18_04 document looks great!

**Comment by voroyam** [comment]
Great
