### ISSUE TITLE
[iOS] Initial docs for new ownCloud iOS app

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#1247]
I'll provide the outline, some bullet points and screenshots. @settermjd I need your help to bring this to a proper format.

## Where Does This Need To Be Documented?

Top level in https://doc.owncloud.org/

## Why Should This Change Be Made? (Optional)

[New ownCloud iOS app](https://github.com/owncloud/ios-app) needs a new documentation.

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [x] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
Happy to help, @michaelstingl. Can you set an appropriate priority label for this issue?

**Comment by michaelstingl** [comment]
I dumped everything in this PR https://github.com/owncloud/ios-app/pull/398

@settermjd please take over and let me know if you have any questions

**Comment by settermjd** [comment]
@michaelstingl, shall do.

**Comment by micbar** [comment]
@settermjd @michaelstingl Any status update?

**Comment by settermjd** [comment]
It's now in review.

**Comment by michaelstingl** [comment]
> It's now in review.

You didn't add reviewers to the PR?

**Comment by michaelstingl** [comment]
Finally !!! https://doc.owncloud.com/ios-app/
