### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#1248]
I would like to understand how the search does the rating on results.

If I type in occ, I would think that the document with the occ in the name would be the first on the list, but it's not. I would like to understand how it's being calculated what get's more points.
Then the 10.1 version is rated higher on the list then 10.0. Is there a reason?

![image](https://user-images.githubusercontent.com/24212810/58317173-8dcdd280-7e15-11e9-833a-4aa889050bf2.png)

@tboerger @settermjd

**Comment by tboerger** [comment]
The ordering beside the score is undefined. The more often the searched keywords are present in a document the higher score it gets. With the same score the ordering could be random.

We are simply dropping all documents into elasticsearch without any further configuration.

If you got ideas how to improve it look at the index function at https://github.com/owncloud/docs/blob/master/generator/generate-site.js#L38 and improve the index weighting. Reading the index is handled at https://github.com/owncloud/docs-ui/blob/master/src/js/vendor/elastic.js#L36

**Comment by tboerger** [comment]
https://github.com/owncloud/docs-ui/issues/76 could be also relevant

**Comment by settermjd** [comment]
Relates to #797.

**Comment by settermjd** [comment]
Thanks for the feedback, @tboerger.

**Comment by voroyam** [comment]
the other issues are better for finding a solution than this one.
