### ISSUE TITLE
Invalid Piwik URL in 2.5 desktop docs

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#1257]
```
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https//piwik.owncloud.org/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '4']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
```

## What Needs to be Documented?

`https//piwik.owncloud.org/` is missing the colon ("`:`" )

## Where Does This Need To Be Documented?

I think it needs a template fix in the `2.5` docs. `2.6` templates and `master` templates look different.

https://doc.owncloud.org/desktop/2.5/

## Why Should This Change Be Made? (Optional)

<img width="847" alt="Graylog_-_Dashboard_Docs_errors" src="https://user-images.githubusercontent.com/214010/58341162-e28d3f80-7e4d-11e9-9593-d482c8b88383.png">

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [x] Desktop Client
- [ ] Other

@settermjd please fix

**Comment by michaelstingl** [comment]
Related: https://github.com/owncloud/docs/issues/1135

**Comment by settermjd** [comment]
@michaelstingl, time permitting, can you review https://github.com/owncloud/docs-themes/pull/2 pls?

**Comment by tboerger** [comment]
I will fix the broken link manually as the old Sphinx-based docs are not built at all anymore.

**Comment by tboerger** [comment]
I have updated the links to Piwik within the legacy docs now. Besides that I have also added the redirects for 10.2 to get rid of the 404 errors related to that at https://gitea.owncloud.services/devops/websites/commit/0794691c56de848c4ba352dea51707b8347a9d4c.
