### ISSUE TITLE
Redirect needed source_installation ==> manual_installation

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#1258]
I see requests for `admin_manual/installation/source_installation.html` everyday:

- https://doc.owncloud.com/server/10.0/admin_manual/installation/source_installation.html
- https://doc.owncloud.com/server/10.1/admin_manual/installation/source_installation.htm

It got renamed in https://github.com/owncloud/docs/pull/63

- https://doc.owncloud.com/server/10.0/admin_manual/installation/manual_installation.html
- https://doc.owncloud.com/server/10.1/admin_manual/installation/manual_installation.html

## What Needs to be Documented?

@settermjd @voroyam If you rename files, please also create redirects.

## Where Does This Need To Be Documented?

- https://doc.owncloud.com/server/10.0/admin_manual/installation/source_installation.html
- https://doc.owncloud.com/server/10.1/admin_manual/installation/source_installation.htm

## Why Should This Change Be Made? (Optional)

I see requests for `admin_manual/installation/source_installation.html` everyday

<img width="844" alt="Graylog_-_Dashboard_Docs_errors" src="https://user-images.githubusercontent.com/214010/58346803-4ae31d80-7e5c-11e9-8446-7c25c8abcc9b.png">

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

Related: #1135

**Comment by voroyam** [comment]
Thanks for spotting this @michaelstingl . Redirect should be easy to add.

If you are interested:

just add 
`:page-aliases: <followed by the old path written in the nav.adoc>`

like this:

`:page-aliases: appliance/installation.adoc`

**Comment by michaelstingl** [comment]
> just add
> `:page-aliases: <followed by the old path written in the nav.adoc>`

cool. thanks for explaining!

**Comment by tboerger** [comment]
We should add that for all the redirects to get rid of the static go.php redirects by nginx.
