### ISSUE TITLE
Outdated UI Screenshot and wrong description Managing Apps

### ISSUE THREAD

**Issue by micbar** [owncloud/docs#127]
https://github.com/owncloud/docs/blob/master/modules/ROOT/pages/installation/apps_management_installation.adoc#viewing-enabled-apps

This page contains an old screenshot and the wrong Path to the App Management UI.

Should be Settings > Apps(Tab).

**Comment by micbar** [comment]
@settermjd How do i upload a new screenshot? Directly to the folder and hard link it?

**Comment by settermjd** [comment]
It's a little complicated at first, until you become familiar with the file/directory structure. That said, [here's a link to the relevant documentation](https://docs.antora.org/antora/1.0/asciidoc/insert-image/). In case it's a little unclear, you need to insert an image `image::file-name.ext[optional alt text]`. The path to the file needs to be relative to the `modules/ROOT/assets/images` directory.

**Comment by settermjd** [comment]
@micbar, any luck in adding the new screenshot?

**Comment by settermjd** [comment]
@micbar, can you let me know if you added a screenshot?

**Comment by voroyam** [comment]
@micbar @settermjd looks like I changed the screenshot and either did not know that there is this issue or have forgotten to write here. ( I think I saw and fixed it without knowing this issue)

I think this is resolved, isn't it?

**Comment by voroyam** [comment]
https://doc.owncloud.com/server/10.1/admin_manual/installation/apps_management_installation.html#viewing-enabled-apps

**Comment by voroyam** [comment]
![image](https://user-images.githubusercontent.com/24212810/61638870-98cca400-ac9a-11e9-8a7b-5e49cfa34d7e.png)

**Comment by voroyam** [comment]
Fixed. Closing.
