### ISSUE TITLE
Add Redis to deployment recomendations

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#1288]
https://doc.owncloud.com/server/admin_manual/installation/deployment_recommendations.html#scenario-2-mid-sized-enterprises

we need to add redis here both in the picture and in the description, also we should tell what we recommend that the redis server should run in a separate node.

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1289

**Comment by settermjd** [comment]
Closing as the implementing PR's been merged.
