### ISSUE TITLE
Documentation of activity app got lost

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#1314]
The activity app, as e.g. seen in server 10.1 has this intro text:
![image](https://user-images.githubusercontent.com/1108546/59492753-e9760380-8e89-11e9-9486-cb440716edb0.png)

The link Admin Documentation points to https://doc.owncloud.org/server/10.1/admin_manual/configuration_server/activity_configuration.html which is a 404.

**Comment by jnweiger** [comment]
The new URL seems to be https://doc.owncloud.org/server/10.1/admin_manual/configuration/server/activity_configuration.html

**Comment by michaelstingl** [comment]
Is this just wrong in the Marketplace listing, or did this change in the past? (`…/configuration_server/… ` ==> `…/configuration/server/… `)

Fix in the Marketplace or add a general redirect?
