### ISSUE TITLE
Android 2.11 documentation upgrade

### ISSUE THREAD

**Issue by jesmrec** [owncloud/docs#1323]
## What Needs to be Documented?

New features in version 2.11 to be included in official documentation

## Where Does This Need To Be Documented?

official documentation of the platform -> https://doc.owncloud.com/android/

## Why Should This Change Be Made? (Optional)

Keep documentation upgraded with the latest changes

## What Type Of Content Change Is This? (Optional)
- [X] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [X] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by jesmrec** [comment]
I will add here the changes to be done.

**Comment by jesmrec** [comment]
### Section: Create New Content 

https://doc.owncloud.com/android/#creating-new-content

**Reason for the change**: We have merged the `Upload` and the `Content from other apps` buttons into an unique option `Upload` . With that option you can upload content from everything (photos, internal storage, other apps etc...)

**Changes:** 

1) The introduction text

`To add new content, whether files, folders, or content from other apps, click the blue button at the bottom right to expose the Upload, Content from other apps, and New folder buttons.`

will change to:

`To add new content, whether files, folders, or content from other apps, click the blue button at the bottom right to expose the [Upload] and [New folder] buttons.`

2) Next paragraph:

`Use the Upload button to add files to your ownCloud account from your Android filesystem. Use Content from other apps to upload files from Android apps, such as the Gallery app.`

will change to:

`Use the Upload button to add files to your ownCloud account from your Android filesystem, from other apps, or from every storage attached to your device`

3) The screenshot below:

https://doc.owncloud.com/android/_images/android-4.png

should be replaced for the following one, since the options are different:

![device-2019-06-17-131141](https://user-images.githubusercontent.com/14894746/59600486-90b0a000-9101-11e9-95ce-475cbbb5d32f.png)

**Comment by jesmrec** [comment]
### Section: Upload Pictures Directly From The Camera

https://doc.owncloud.com/android/#upload_pictures_directly_from_the_camera_label

**Reason for the change:** screenshots are outdated. The floating button shows only two options, and the available offline mark is now a purple circle. 

**Changes:**

Replace the first two screenshots for the following ones (third one is still valid):

![device-2019-06-17-132513](https://user-images.githubusercontent.com/14894746/59601246-c060a780-9103-11e9-8da2-606e27fe2e9b.png)

![device-2019-06-17-132529](https://user-images.githubusercontent.com/14894746/59601253-c48cc500-9103-11e9-9c82-41fb80200902.png)

**Comment by jesmrec** [comment]
### Section: Select All and Inverse in Uploads View

https://doc.owncloud.com/android/#select-all-and-inverse-in-uploads-view

**Reason for the change:**  Manual upload picker was removed.

**Changes: Remove this section. The upload picker is now android native, and is not part of the app itself anymore.

**Comment by jesmrec** [comment]
### Section: Make Folders Available Offline

https://doc.owncloud.com/android/#make-folders-available-offline

**Reason for the change:**  Screenshots are outdated. Available offline mark is now a purple circle

**Changes:** 

1) This paragraph:

`When the folders have been locally cached, the icon will change to have a yellow, down-arrow icon in the bottom right-hand corner, as in the screenshot below.`

will change to:

`When the folders have been locally cached, the icon will change to have a purple circle with a white tick icon in the bottom right-hand corner, as in the screenshot below.`

2) The screenshot below:

https://doc.owncloud.com/android/_images/files_folders_view.png

will change to:

![device-2019-06-17-133744](https://user-images.githubusercontent.com/14894746/59601696-20a41900-9105-11e9-924a-95738520c41d.png)

**Comment by jesmrec** [comment]
### Section: Connecting to your owncloud server

https://doc.owncloud.com/android/#connecting-to-your-owncloud-server

**Reason for the change:** This is not a matter of Android 2.11, but the screenshot in such section was taken several years ago. Feel free to address that to another PR, since this is not something new in 2.11.

**Changes**: Change the current screenshot for this one:

![Screenshot 2019-06-17 at 13 40 45](https://user-images.githubusercontent.com/14894746/59601924-c9eb0f00-9105-11e9-9977-3a79c6bfdf04.png)

**Comment by jesmrec** [comment]
Those were the changes.

Now, new stuff to be included

**Comment by jesmrec** [comment]
### New Feature: Document Provider integration [WIP]

**What is it about:** Document provider is an Android feature that provides integration with other apps. It is accessed from the native apps `Files` (Android O), or `Downloads` (Android P and older). Within those apps you are able to perform actions as well as in the ownCloud app.

**Where to include it:**: Inside ' Create new content` section (https://doc.owncloud.com/android/#creating-new-content), as a new section

**Title**: `

**Text**:

**Screenshot**:

![device-2019-06-17-135438](https://user-images.githubusercontent.com/14894746/59602684-a5903200-9107-11e9-8a35-e4dab4527650.png)

**Comment by jesmrec** [comment]
### New Feature: Logs 

**Where to include it**: Inside  `Application Settings` section (https://doc.owncloud.com/android/#application-settings), at the end of the document

**Title:** Logs 

**Text**: `If you detect a problem or bug, you can send us logs about the problem. You will find the logs section in the Settings view, after enabling it. To enable, you have to tap five times on the Version and build information:`

**Screenshot:**

![Screenshot 2019-06-18 at 08 47 24](https://user-images.githubusercontent.com/14894746/59659111-c1e2ac00-91a5-11e9-83fe-96338a18994e.png)

**Text**: `Inside the log section, options to `Send` and `Delete` history are available, as well as searching in the logs (lens icon on the top). If you select `Send` your mail app is opened to address the log file.` 

**Screenshot:**

![device-2019-06-18-084924](https://user-images.githubusercontent.com/14894746/59659209-02dac080-91a6-11e9-8dfb-0babc732508d.png)

**Comment by jesmrec** [comment]
That's all for 2.11. If you need anything else, please ping.

**Comment by settermjd** [comment]
@jesmrec, is this still required, or was it implemented already?

**Comment by jesmrec** [comment]
@settermjd what do you mean? these are the changes to be included in documentation after the Android 2.11 release. I tried to detail it, so it is only needed to format, so it will be part of https://doc.owncloud.com/android/.

do i miss something?

**Comment by settermjd** [comment]
Thanks for the clarification.
