### ISSUE TITLE
Sharing API claims that permission cannot be changed for a public link share

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs#1328]
## What Needs to be Documented?
Remove the note in the sharing API docs:
```
Also, a permission cannot be changed for a public link share.
```

## Where Does This Need To Be Documented?
 modules/developer_manual/pages/core/ocs-share-api.adoc

## Why Should This Change Be Made? (Optional)
We have acceptance tests that demonstrate changing the permissions of a public link share. So it is possible. And in discussion with others, it should be possible (it is actually a requirement)
So the note seems to be an error from the past.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by phil-davis** [comment]
PR to fix #1329

**Comment by micbar** [comment]
@settermjd Please check If we need this in other docs too.

**Comment by settermjd** [comment]
I've grepped the documentation and don't find any references to this string. If it is still there, in another form, please reopen this issue. Otherwise, closing.
