### ISSUE TITLE
Document federated system addressbook sync

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#133]
Migrated from https://github.com/owncloud/documentation/issues/4288.

Federation between ownCloud's has not yet taken off as it actually should due to many UX issues for the average user. One major issue is that users frequently don't understand the concept because they're used to centralized platforms. Remembering a federation ID and entering this in the share dialog goes way beyond the skills of the average user which is why federation currently is reserved to power users.

We have a feature that can solve these UX issues partly by automatically synchronizing user lists between federated instances. This way users don't have to think about the "location" of a recipient and don't have to remember federation IDs since they will just find them via the autocomplete in the sharing dialog once both instances know each other (e.g. one successful fed share has been established or the admins added both instances as trusted). 

The feature was introduced here https://github.com/owncloud/core/pull/20948 (Syncing system addressbooks across federated ownClouds). It's completely undocumented and maybe has some more prerequisites to work nicely.

@settermjd @DeepDiver1975 

---

Some input based on research I did with @micbar and @cdamken:

### Requirements / prerequisites
- Valid SSL certs
- `overwrite.cli.url` must match the domain the instance is available at for other instances (incl. `https://`)
- what else?

### Syncing address books

- Mutual trust and shared secret exchange
  - Add server 2 in server 1 via UI
  - Add server 1 in server 2 via UI
  - Run cron.php on server 1
  - Run cron.php on server 2
  - Run cron.php on server 1 (?)

- Synchronization
  - Run `occ dav:sync-system-addressbook` on both servers
  - Run `occ federation:sync-addressbook` on both servers

### Needs more info
- Possibility that admin has to approve new trusted servers before address books will be exchanged?
- Do users need to be able to decide which personal data is available to be synced with other servers?
- When something went wrong in the process, will it auto-heal? (e.g. tokens lost?)
- Error handling and improved stability?
- sync_token: Sabre.io link?? is confusing
- How will it work when servers get to know each other via a fed share created by a user?
- What else?

**Comment by settermjd** [comment]
Thanks for doing @pmaier1, and for your understanding.

**Comment by voroyam** [comment]
After discussing with @micbar it seems like this project need dedicated time and efford to figure out and test.

As it is now, I can not document this.

**Comment by voroyam** [comment]
The sync command was included in the PR with an explanation.

Since we don't have a verification process that is easy triggered from the webUI we have to execute DB commands.

A easy to use verification process like it's in the email server setup would make a great FR.
