### ISSUE TITLE
Link docs for new iOS app

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#1356]
## What Needs to be Documented?

New awesome docs for new awesome iOS app should be accessible from `https://doc.owncloud.org/` and `https://doc.owncloud.com/`

Related:
- https://github.com/owncloud/docs/issues/1247
- https://github.com/owncloud/ios-app/pull/398

Existing docs for legacy iOS app need to be kept for a while.

## Where Does This Need To Be Documented?

<img width="881" alt="ownCloud_Documentation_Overview____ownCloud_Documentation" src="https://user-images.githubusercontent.com/214010/60170383-9f393e80-9808-11e9-9d66-f5cad33aa60d.png">

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [x] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [x] Other

**Comment by michaelstingl** [comment]
@settermjd When will the changes from https://github.com/owncloud/docs/pull/1358 be deployed? Does it need backport or something? /cc @tboerger

**Comment by settermjd** [comment]
The build is currently broken, which prevents the changes from being deployed. This should be fixed when a pending PR is reviewed and merged.

**Comment by michaelstingl** [comment]
> when a pending PR is reviewed and merge

link?

**Comment by michaelstingl** [comment]
@settermjd How can I help to get this deployed?

**Comment by michaelstingl** [comment]
Finally !!! https://doc.owncloud.com/ios-app/

**Comment by tboerger** [comment]
I dislike the `ios-app` naming. maybe you should rename the legacy one and just name it `ios` like it's done for `android`.

**Comment by michaelstingl** [comment]
> maybe you should rename the legacy one and just name it `ios` like it's done for `android`.

Yeah, that was exactly my plan 👍
