### ISSUE TITLE
Improve Client Configuration documentation

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/docs#1365]
## What Needs to be Documented?
The client provides various configuration options - however not all of them are documented.
For 2.5 an overview of available configuration options is in the code here:
https://github.com/owncloud/client/blob/2.5/src/libsync/configfile.cpp#L51-L94

## Where Does This Need To Be Documented?
Configuration File in Client Documentation 
https://doc.owncloud.org/desktop/advanced_usage/configuration_file.html

## Why Should This Change Be Made? (Optional)
Have up to date client configuration documentation

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [x] Desktop Client
- [ ] Other

**Comment by patrickjahns** [comment]
@michaelstingl 
please state which ones need to be documented, and which ones are better left untouched

**Comment by michaelstingl** [comment]
@HanaGemela After the 2.6.0 release, please check with @owncloud/desktop-core-developers which parameters are still supported. Please remove all from the docs that are no longer working.

**Comment by HanaGemela** [comment]
@ckamm @ogoffart @guruz @TheOneRing Please review https://doc.owncloud.org/desktop/advanced_usage/configuration_file.html and add missing configuration options and remove the ones that are not supported anymore

**Comment by ckamm** [comment]
@HanaGemela I've gone over the documentation. `maxLogLines` is no longer used, the remaining options still exist. It's definitely not an exhaustive list though.
