### ISSUE TITLE
New API for 10.3: trashbin api via webdav endpoint

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/docs#1366]
## What Needs to be Documented?
refs https://github.com/owncloud/core/pull/35716

10.3 will come with a new api on webdav for accessing the trashbin - including restore operations and permanent delete.

Details on the API can be found here https://github.com/owncloud/core/pull/35636

## Where Does This Need To Be Documented?
Server API/WebDAV

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
_Where ever all WebDAV APIs are documented_
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
Successfully tested all functionality and am working through documenting the API endpoints.
