### ISSUE TITLE
Save vertical space in the code examples of the API docs

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#1388]
## What Needs to be Documented?

<img width="821" alt="OCS_Share_API____ownCloud_Documentation" src="https://user-images.githubusercontent.com/214010/60671618-c11f6a80-9e73-11e9-8a81-1f1aa073826e.png">

## Where Does This Need To Be Documented?

- API Docs

## Why Should This Change Be Made? (Optional)

The different code examples in the API docs need very much vertical space, so it's breaks the flow to read and understand request parameters and responses.

Maybe there's a quick and easy way to save space with tabs or a kind of expandable blocks…

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by michaelstingl** [comment]
@settermjd Please check if there's a quick and simple approach to improve here. Otherwise I'd postpone…

**Comment by settermjd** [comment]
@michaelstingl, shall do. I believe that there may be a community contribution that makes this possible. I'll have to do some research to find out.

**Comment by settermjd** [comment]
Thanks to [an extension from Antora project lead, Dan Allen](https://gitlab.com/antora/antora-asciidoctor-extensions/tree/master/tabs-block), I've gotten a basic implementation of tabs working in the documentation. Here's a rudimentary example of what it looks like, without any further styling:

![Bildschirmfoto 2019-07-08 um 11 24 09](https://user-images.githubusercontent.com/196801/60799204-ffb66d00-a172-11e9-85da-23580557172a.png)

**Comment by settermjd** [comment]
I've refined the tabs CSS (but will leave further styling to others). Below is a working example:

![Bildschirmfoto 2019-07-08 um 13 00 49](https://user-images.githubusercontent.com/196801/60805504-96d5f180-a180-11e9-9b2c-15a1400055c2.png)
![Bildschirmfoto 2019-07-08 um 13 00 56](https://user-images.githubusercontent.com/196801/60805505-96d5f180-a180-11e9-98ea-e3c76e7df358.png)

**Comment by settermjd** [comment]
Closing as #1397, #1398, and owncloud/docs-ui#82, which implement this functionality, have been merged.
