### ISSUE TITLE
subscription-manager is not installed by default.

### ISSUE THREAD

**Issue by surapuramakhil** [owncloud/docs#1438]
https://doc.owncloud.org/server/10.2/admin_manual/installation/manual_installation.html

pls, refer output of my shell so that docs can be updated.

`sudo subscription-manager repos --enable rhel-server-rhscl-7-eus-rpms`
output `sudo: subscription-manager: command not found`

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by voroyam** [comment]
The rhel ownCloud installation has been moved to central.

**Comment by voroyam** [comment]
added here: https://central.owncloud.org/t/doc-manual-installation/20999/3
