### ISSUE TITLE
 Configure the Web Server part - commands needed sudo rights

### ISSUE THREAD

**Issue by surapuramakhil** [owncloud/docs#1439]
## What Needs to be Documented?

few console commands need sudo permissions. in ubuntu

## Where Does This Need To Be Documented?

https://doc.owncloud.org/server/10.2/admin_manual/installation/manual_installation.html#install-owncloud

## Why Should This Change Be Made? (Optional)

IN Configure the Web Server part

console commands should be prepended with sudo.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by voroyam** [comment]
This issue can be closed as the part of the docs has been moved to central

**Comment by voroyam** [comment]
@jnweiger is this what you had in mind?

https://doc.owncloud.com/server/10.2/admin_manual/installation/ubuntu_18_04.html
