### ISSUE TITLE
Fix ROOT --> administration_manual

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#145]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] General
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

In: https://github.com/owncloud/docs/blob/master/book.adoc where changes have been made recently, the path containing ``ROOT`` must be adopted to the new path element ``administration_manual``.

## Why Should This Change Be Made?

If not fixed, all of these links will fail !

**Comment by settermjd** [comment]
Thanks for catching this @mmattel. I'll check it out and see about adding build tooling that can avoid this in future.

**Comment by settermjd** [comment]
This has been implemented. Closing.
