### ISSUE TITLE
Server side encryption docs outdated

### ISSUE THREAD

**Issue by va1entin** [owncloud/docs#146]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

Up to date manual for the server side encryption app. 

## Why Should This Change Be Made?

The [docs for server side encryption](https://doc.owncloud.org/server/10.0/admin_manual/configuration/files/encryption_configuration.html) seem to be pretty outdated.

One documented command does not exist:
<pre># occ encryption:select-encryption-type masterkey

                                                               
  Command "encryption:select-encryption-type" is not defined. </pre>

Also the app comes without encryption modules to use, I made an [issue](https://github.com/owncloud/encryption/issues/58) for that in the repo of the app

**Comment by settermjd** [comment]
@va1entin, thanks for creating this issue, and @PVince81, thanks for adding to the discussion. I'll review the linked documentation and see how it can be improved to avoid this misunderstanding.

**Comment by va1entin** [comment]
@PVince81 thanks for the clarification
I thought that the checkbox in the web interface enables the app because it says "Enable server-side encryption"

**Comment by PVince81** [comment]
not really and I realize that the distinction is not easy to grasp at first look

OC core has an encryption subsystem that is actually a plugin system for encryption apps to register themselves. By checking the checkbox you only enable that subsystem.
Then you need to enable an app that provides an encryption plugin, which is the default "encryption" app, also called "default encryption module", which itself provides two submodules "master key" and "user key" (which we'll likely separate to two apps at some point, see https://github.com/owncloud/core/issues/27438)

Overview:

- core: encryption subsystem
    - default encryption module (provided by "encryption" app)
       - submodule "master key mode"
       - submodule "user key mode"

At this day I'm not aware of any other apps that implement encryption as a replacement for "default encryption module"

**Comment by mmattel** [comment]
@PVince81 reading that and to avoid misunderstandings in future, a small change in core would solve that. A text that highlights to install and enable the encryption app first then enabe that you can enable the subsystem. A torture in the syntax, I know...
Would that make sense ?

**Comment by settermjd** [comment]
@mmattel, that sounds quite reasonable to me. Is it workable @PVince81?

**Comment by settermjd** [comment]
I'm looking into this at the moment, but have come across the following, quite perplexing functionality (which I've asked about in #engineering):

```
$ ./occ encryption:select-encryption-type masterkey
Kindly enable encryption to select the encryption type.
$ ./occ encryption:status
  - enabled: true
  - defaultModule: OC_DEFAULT_MODULE
```

**Comment by voroyam** [comment]
Isn't it solved by https://doc.owncloud.org/server/10.0/admin_manual/configuration/files/encryption/encryption_configuration_quick_guide.html ?

This new document provides the correct commands for enabling and disabling encryption.

**Comment by voroyam** [comment]
@va1entin please use the new document. closing.
