### ISSUE TITLE
Document Media Viewer

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#1465]
## What Needs to be Documented?

New Media Viewer app (`files_mediaviewer`; https://marketplace.owncloud.com/apps/files_mediaviewer) that replaces `gallery` and `files_videoplayer`. Blog post: https://owncloud.org/news/good-bye-gallery-say-hi-to-the-new-media-viewer/

- oC community (GPLv2)
- Replaces gallery and files_videoplayer => please remove before installing
- Same basic feature set as old gallery and videoplayer
- Pre-loading of images surrounding the currently watched image in slideshow => performance
- Conversion of "old" album view public links https://github.com/owncloud/gallery#redirect-gallery-link-shares
- Gallery and videoplayer deprecated

Check `gallery` readme and wiki for what we can copy over
- e.g. https://github.com/owncloud/gallery#supporting-more-media-types
- https://github.com/owncloud/gallery/wiki

## Where Does This Need To Be Documented?

- User docs, e.g. https://doc.owncloud.com/server/10.2/user_manual/files/gallery_app.html
- Admin docs

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by ho4ho** [comment]
<- Interested how full uninstall old gallery database

**Comment by DeepDiver1975** [comment]
- thubnails dont need to be removed - they are generated and maintained by the owncloud server aka core
- gallery brings no own database tables

There is no real clean up necessary

**Comment by ho4ho** [comment]
Thanks for clarify :+1:

**Comment by settermjd** [comment]
@pmaier1, I found the configuration snippet below, in https://github.com/owncloud/gallery#supporting-more-media-types, which you linked to above, however it doesn't quite work in the Media Player app.

```
'enabledPreviewProviders' => [
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    11 => 'OC\\Preview\\Illustrator',
    12 => 'OC\\Preview\\Postscript',
    13 => 'OC\\Preview\\Photoshop',
    14 => 'OC\\Preview\\TIFF'
  ],
```

Specifically:

- PNG, JPEG, GIF, and TIFF images render correctly, both as thumbnails and in the image image preview window. 
- Photoshop files only render a thumbnail, but aren't rendered in the image preview window.
- Illustrator and Postscript files don't display a thumbnail and aren't rendered in the image preview window.

Imagick is installed and enabled.

**Comment by settermjd** [comment]
I've revised the preview providers functionality to remove documentation for Illustrator, Postscript, and Photoshop support, and qualified support for TIFF images.

**Comment by mmattel** [comment]
@DeepDiver1975 , just a note
> thubnails dont need to be removed  - they are generated and maintained by core

not wrong, but also not true. Core does only create thumbs, but ist does not delete, so you get orphans. A lot of orphans physically and in the database. Just search for orphans in issue/core to read more about. oC should take care of it. It would have had been cool if the new mediaviewer emtied on first run the thumbnails for the user and recreates them on demand... just my 2c

**Comment by DeepDiver1975** [comment]
Nevertheless. Nothing related to the Gallery removal

**Comment by ho4ho** [comment]
Checked data folder, still see old ``gallery`` folder:

/var/www/owncloud/data/<username>/gallery/<username>/

Possible delete?

**Comment by settermjd** [comment]
Is that an older installation, @ho4ho, because I don't see such a folder on a recent installation when using the gallery app.

**Comment by ho4ho** [comment]
Yes, older updated install (can not renember, maybe 9.0 :-/)

**Comment by pmaier1** [comment]
Admin docs are missing...

**Comment by pmaier1** [comment]
Done with https://github.com/owncloud/docs/pull/1700
