### ISSUE TITLE
Don't advise to disable certain apps on upgrade

### ISSUE THREAD

**Issue by PVince81** [owncloud/docs#147]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## Why Should This Change Be Made?
See https://doc.owncloud.org/server/10.0/admin_manual/maintenance/manual_upgrade.html#disable-core-apps

Would be good to research why and when this was added. This was likely added due to misunderstanding. The admin should not disable these apps during upgrade.

Maybe this was part of an attempt to do an offline upgrade from OC < 10 to OC 10 in which case sometimes an admin might need to disable apps. Or rather, in offline mode, the admin would need to update these app's code manually before doing the upgrade instead of disabling.

For now I suggest removing this section after finding out why it was added.

@settermjd @tomneedham

**Comment by settermjd** [comment]
@PVince81, I think that I might have added this, or at least ported this information, as part of documenting upgrading from 9.x to 10.x. At that stage, (assuming that I got it wrong) my knowledge of ownCloud wasn't what it is today. I'll investigate and get the documentation amended.

**Comment by settermjd** [comment]
Closing as it was implemented in #241, which has been merged and deleted.
