### ISSUE TITLE
Development Environment Setup

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#1472]
After a conversation with @michaelstingl and @settermjd I decided to make an issue here, because chat is fleeting.

We came to a conclusion that we all can save time when we have the same development / testing conditions.

At the moment development, documentation and support have each a local testing environment.
The huge drawback of this is, that each department has to spend time to research how to deploy, develop and test against their environment. If a feature is then developed, it comes to documentation, and there again the research has to start again. In Support it's the same thing.

# What we could do:
* have one global testing environment that can be used by developers, documentation and support
* have the steps how to deploy the testing environment documented specifically
* or a third solution that could save time

**Comment by michaelstingl** [comment]
> * have one global testing environment that can be used by developers, documentation and support

Not sure what "one global testing environment" means? One ownCloud instance? That doesn't scale.

Everybody should be able to fire up a Hetzner Wölkchen. (coordinate with your teamlead/supervisor and admin team)

Setups can be documented with a few bullet points, but better in a `docker-compose` file or an Ansible playbook. Worst cast, snapshot the Hetzner Wölkchen, so dev can handover to qa and docs…

**Comment by michaelstingl** [comment]
Work continues in internal tickets…
