### ISSUE TITLE
Issue/PR Template improvement

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#148]
**Current**
## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

**Proposal**
## Which Manual Does This Relate To?

- [ ] General
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

The new item ``General`` would cover all those things which are not in the other three

@settermjd what is your opinion ?

**Comment by settermjd** [comment]
How does that work, because at the current moment, the manuals that aren't part of the core three are located in the respective codebases?

**Comment by mmattel** [comment]
Example, question, where do you checkmark for a change in ``docs/docs/build-the-docs.md`` ?

**Comment by settermjd** [comment]
I don't understand what you're asking @mmattel.

**Comment by voroyam** [comment]
I have a few improvement suggestions. 

- In my original template there were no check boxes.

Now we have tickets with, what I find confusing, checked items 2 of 7.

![image](https://user-images.githubusercontent.com/24212810/46812161-6a698200-cd74-11e8-8869-e807d4d10e67.png)

This looks strange for me. But I can live with that.

----------------------

What I find worse, is the **function** that the check boxes replaced.

In my template in the section "where should this be documented" I wanted a **path** to a document on GitHub or at least in the online docs. I don't understand the use for someone who will make a PR to know in what manual he has to do the changes in. He would still spend time and look for the specific page or ask people.

In my opinion - If you want to have something documented but don't want to spend time making a PR - write exactly **What Where and How** the thing needs to be documented. That way we don't need an documentation expert and issues don't pile up and our docs are up to date.

-------------------

Also in general I find the new template has too much description text. In my view - Make the title clear enough and you don't need a long description. After all we all know what we are doing here, right?

**Comment by mmattel** [comment]
I am proposing an additional [x] General item due to the reason I explained

**Comment by settermjd** [comment]
All this sounds fine to me. Fwiw, the approach that I took originally, made sense at the time. But I see where this is going and appreciate the input.

**Comment by mmattel** [comment]
I am fine with all improvements as long it gets improved 😄

**Comment by voroyam** [comment]
template still unchanged... needs rework

**Comment by voroyam** [comment]
This can be closed IMHO. Since January there was no real progress.
