### ISSUE TITLE
Major upgrade in packages?

### ISSUE THREAD

**Issue by ho4ho** [owncloud/docs#1551]
https://doc.owncloud.org/server/10.2/admin_manual/maintenance/package_upgrade.html read:

```
Make sure that you don’t skip a major release when upgrading via repositories. For example you can’t upgrade from 8.1.x to 9.0.x directly as you would skip the 8.2.x major release. See Upgrading Across Skipped Releases for more information. 
```

but https://doc.owncloud.org/server/10.2/admin_manual/maintenance/upgrade.html read:

```
Skipping major releases is not supported. However you can migrate from latest 8.2.x and latest 9.0.x straight to latest ownCloud 10.x.x
```

Possibly to make text same/similar and add more detail?

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by voroyam** [comment]
You can skip major releases with the manual upgrade but not with the packages.

**Comment by ho4ho** [comment]
Are sure? Packages not doing same like manual upgrade by copying new files to /var/www/owncloud ?

**Comment by voroyam** [comment]
You might be right. We need to test this. Have you tested this already?

**Comment by pmaier1** [comment]
You can upgrade from oC >= 8.2 to 10.x skipping the versions in between. It does not matter which way of upgrading you use.

**Comment by pmaier1** [comment]
Needs to be aligned in the mentioned docs, of course. Thanks for opening the issue!

**Comment by settermjd** [comment]
@pmaier1, can we get this in a future sprint, pls?

**Comment by pmaier1** [comment]
> @pmaier1, can we get this in a future sprint, pls?

Sure, please go for the change. THX.
