### ISSUE TITLE
Migration guide from user keys encryption to master key

### ISSUE THREAD

**Issue by sharidas** [owncloud/docs#157]
## What Type Of Content Change Is This?

- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

We need to provide a migration guide for users to migrate from user keys encryption to master key encryption. The doc should provide step by step guide what to be done from the command line to achieve this task.

## Why Should This Change Be Made?

This change would help users to migrate easily from user keys encryption to masterkey encryption.

**Comment by settermjd** [comment]
Thanks for raising this issue, @sharidas. Can you provide the initial text or some links from which we can do proper research?

**Comment by sharidasan** [comment]
@settermjd @thommierother In one of my old pr, where I have written down the steps. Just look at the comment shared https://github.com/owncloud/encryption/pull/35#issuecomment-393127490.

**Comment by settermjd** [comment]
Hi @thommierother, thanks for the interesting in getting involved. Have a look at [the doc's docs](https://github.com/owncloud/docs/blob/master/docs/getting-started.md). They'll give you all you need to know to get started. If they don't just let me know and I'll see what I can do.

**Comment by thommierother** [comment]
@settermjd Hi, I am preparing my environment (Atom), will come back when I am ready and made the first steps with asciidoc ...

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1528

**Comment by voroyam** [comment]
Here is a new migration guide. If it's merged, we can close this.

**Comment by voroyam** [comment]
merged and backported. closing.
