### ISSUE TITLE
404 docker-compose.yml does not exists

### ISSUE THREAD

**Issue by eppak** [owncloud/docs#1585]
"Installing with Docker" point to outdated/deprecated installation procedure, the "https://raw.githubusercontent.com/owncloud-docker/server/master/docker-compose.yml" does not exists enymore. Following the documentation get stuck when you try to download compose yaml file.

## What Needs to be Documented?
Installing with Docker

## Where Does This Need To Be Documented?
https://doc.owncloud.org/server/10.2/admin_manual/installation/docker/

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [x] Other

**Comment by michaelstingl** [comment]
As an alternative, link to the one that is embedded later on the page?

https://github.com/owncloud/docs/blob/341a22f83d906833d33904614d82c456839339ff/modules/admin_manual/pages/installation/docker/index.adoc#L184-L187

https://github.com/owncloud/docs/blob/341a22f83d906833d33904614d82c456839339ff/modules/admin_manual/examples/installation/docker/docker-compose.yml#L1-L73

**Comment by michaelstingl** [comment]
> "https://raw.githubusercontent.com/owncloud-docker/server/master/docker-compose.yml" does not exists enymore

This was the latest working version:
https://raw.githubusercontent.com/owncloud-docker/server/d3d68525d840057e6528ac3445019c044e30e36f/docker-compose.yml

**Comment by michaelstingl** [comment]
Both are identical, except the empty line at the end  of the [`docker-compose.yml`](https://raw.githubusercontent.com/owncloud/docs/341a22f83d906833d33904614d82c456839339ff/modules/admin_manual/examples/installation/docker/docker-compose.yml) in the docs repo

**Comment by tboerger** [comment]
Yeah the github repo refs just got to be replaced

**Comment by eppak** [comment]
Cannot undestand, docker compose is no longer supported? There is another way? Or the missing docker composer file was a mistake?

Thanks

**Comment by patrickjahns** [comment]
@eppak 
You are free to use docker compose. 

However, you need to take care of how to provision / maintain docker compose yourself. We won't be providing active support for compose files

**Comment by eppak** [comment]
@patrickjahns Just to understand better, you do not support docker anymore on only composer way?
Thanks

**Comment by michaelstingl** [comment]
> you do not support docker anymore on only composer way?

ownCloud Docker setup is one of the recommended methods to deploy the ownCloud server. But the `docker-compose.yml` is only an example. You need a good understanding what is going on in this example file. To get an idea, you could start with the `docker-compose.yml` that is included at the end of the page:
https://doc.owncloud.org/server/10.2/admin_manual/installation/docker/#docker-compose-yaml-file

**Comment by michaelstingl** [comment]
@settermjd with the removal of the instructions in the Docker repo, another part got invalid:

https://github.com/owncloud/docs/blob/478a4318ec192d164e3212e7878872aae2dee9ea/modules/admin_manual/pages/installation/docker/index.adoc#L52-L53

**Comment by settermjd** [comment]
@eppak, after the merge of https://github.com/owncloud/docs/pull/1588, can you check if the instructions now work for you, as expected?

**Comment by eppak** [comment]
@settermjd 
Followed the step and now is up and running with the new guide.
We can close, thank you.
