### ISSUE TITLE
WOPI: document group restrictions

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/docs#1608]
A new config.php setting can be used to limit the use of WOPI to a group.

The setting is called 'wopi_group'

If no groups is defined all user have access to WOPI

This option is available with the next version (1.3.0?? @pmaier1 )

refs https://github.com/owncloud/enterprise/issues/3426
refs https://github.com/owncloud/wopi/pull/64

**Comment by settermjd** [comment]
ping @pmaier1 https://github.com/owncloud/enterprise/issues/3426#issuecomment-519002389.
