### ISSUE TITLE
Mark old docs as outdated and link to the current version

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#1656]
I see a lot of traffic on pages of outdated docs, and also in other GH issues [or Central posts,](https://central.owncloud.org/t/build-client-help/21385) users refer to old docs. Could we mark old docs as outdated and link to the current version?

Here is an example from the Microsoft docs:

<img width="1280" alt="Windows_Server_2012_R2_and_Windows_Server_2012___Microsoft_Docs" src="https://user-images.githubusercontent.com/214010/63092202-3eed9000-bf61-11e9-8327-233178dc455b.png">

(Source: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh801901(v=ws.11))

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [x] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [x] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [x] Desktop Client
- [x] Other

Maybe @LukasHirt can help us with some frontend adjustments…

/cc @pmaier1 @voroyam FYI

**Comment by settermjd** [comment]
I'm, honestly, not sure if this is feasible in Antora. I'll do some research and find out.

**Comment by settermjd** [comment]
@michaelstingl, I've done some research and there doesn't appear to be a lot that can be done quickly. However, in the screenshot below is an example of what can be done. Can you share your feedback?

<img width="781" alt="oC unsupported version label" src="https://user-images.githubusercontent.com/196801/65132782-c1a2b880-da01-11e9-8101-4b48c29e7a91.png">

**Comment by voroyam** [comment]
My proposal wold be to just de-publish the online docs for unsupported version and provide a link to the last pdf of the docs for 10.0. Much cleaner solution in my view.

**Comment by settermjd** [comment]
> My proposal wold be to just de-publish the online docs for unsupported version and provide a link to the last pdf of the docs for 10.0. Much cleaner solution in my view.

@tboerger @michaelstingl?

**Comment by settermjd** [comment]
I'd rather keep them there if people are still on those versions. Need to get the search results to reference the newer versions though.

**Comment by voroyam** [comment]
I don't think the search will be touched by @tboerger in the next foreseeable future. So if we add now 10.3 we will have 10.0 10.1 10.2 and 10.3 search results?

**Comment by settermjd** [comment]
That doesn't specifically relate to the purpose of this issue. However, it's well worth covering in a future issue.

**Comment by settermjd** [comment]
> @michaelstingl, I've done some research and there doesn't appear to be a lot that can be done quickly. However, in the screenshot below is an example of what can be done. Can you share your feedback?
> 
> <img alt="oC unsupported version label" width="781" src="https://user-images.githubusercontent.com/196801/65132782-c1a2b880-da01-11e9-8101-4b48c29e7a91.png">

@michaelstingl, can you add feedback please?

**Comment by michaelstingl** [comment]
> @michaelstingl, can you add feedback please?

Hm, this is not actionable. How can users find the current version?

**Comment by settermjd** [comment]
> > @michaelstingl, can you add feedback please?
> 
> Hm, this is not actionable. How can users find the current version?

By using the version selector.

**Comment by michaelstingl** [comment]
> By using the version selector.

Yeah, hard to find and hard to use on mobile/touch devices.

**Comment by settermjd** [comment]
That's arguably a task for @LukasHirt, and not specifically for this issue. The solution listed above, as limited as it is, seems to be about the only thing that I can do, at least in the immediate future.

**Comment by tboerger** [comment]
Lukas has worked on a better version switch, but nobody commented on that

**Comment by settermjd** [comment]
I commented on the last one that he shared with me. Is there a new one?

**Comment by tboerger** [comment]
It's months ago

**Comment by settermjd** [comment]
@LukasHirt, any suggestions on how to implement this in the UI?

**Comment by settermjd** [comment]
@LukasHirt, do you have time to discuss this today (or later in the week)?

**Comment by michaelstingl** [comment]
Example from Keycloak docs:

![Server_Administration_Guide](https://user-images.githubusercontent.com/214010/78461914-45d23a00-76cd-11ea-9bda-ca03e5b7cb87.png)

(Source: https://www.keycloak.org/docs/4.8/server_admin/)

**Comment by settermjd** [comment]
Closing, as the feature has now been implemented.

**Comment by phil-davis** [comment]
The change in PR https://github.com/owncloud/docs-ui/pull/155 seems to have been reverted in PR https://github.com/owncloud/docs-ui/pull/158 but there is no reasoning written in PR 158???

Is there some record of what was wrong with 155 and why it had to be reverted?
