### ISSUE TITLE
Appliance troubleshooting

### ISSUE THREAD

**Issue by cdamken** [owncloud/docs#1672]
I didn't find the troubleshooting for the appliance

[ ] Log files 
[ ] Config report
[ ] Restore snapshot.

(Add more if you know some)

**Comment by settermjd** [comment]
@voroyam, can you provide more information for this issue, please?

**Comment by voroyam** [comment]
There is no troubleshooting in the appliance because:

1) In the normal circumstances the appliance just runs if it's set up correctly.
2) The troubleshooting is the same as in the usual server. The custom paths are in the "Login Information" document.

**Comment by settermjd** [comment]
It seems that @cdamken is talking about troubleshooting the appliance, not the ownCloud within the appliance.

**Comment by voroyam** [comment]
Are you sure? Because ownCloud runs within the Appliance. We support only ownCloud within the Appliance. So the Troubleshooting should be for ownCloud within the Appliance, right?
