### ISSUE TITLE
How does encryption version used in oC

### ISSUE THREAD

**Issue by sharidas** [owncloud/docs#1676]
The idea behind this documentation is to let users aware of what encryption version is and how its used in the encryption app.

## What Needs to be Documented?

I would add the details in the comments.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by sharidas** [comment]
Pre-requisites: In this doc I have used the master-key encryption

### How does a file get encrypted
Lets assume a text file is created/uploaded to an oC instance with master-key encryption enabled. In this case below are the sequence that happens

- Check if the public master key exist else create one ( you can find the one in `data/files_encryption/OC_DEFAULT_MODULE/master_xxxxxxx.publicKey`
- Create file key, it would be created at `$user/files_encryption/keys/files/file1.txt/OC_DEFAULT_MODULE/`
- Access the type of cipher, by default `AES-256-CTR` is used.
- Create a header for the file. The header usually consist of `HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:` + `AES-256-CTR` + `signed:true` + `HEND` i.e, `HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:AES-256-CTRsigned:true:HEND`
- Add padding to the header. That is add `-`'s to the header. Its calculated internally and it would look something like this `HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:AES-256-CTRsigned:true:HEND------------------` 
- Write the data to the file by encrypting it. So lets take a simple file with say data `Hello world`, once the data is read it encrypts the data by following the logic described below:
    - Increment the version by 1 ( it starts from zero )
    - Generate a random bytes of length 16 ( generate IV). It might look something `��W�Yw+�u��`J�` 
    - Using openssl we encrypt the data with the cipher mentioned above + the filekey + iv generated 
    - Create a signature using this encrypted data + filekey + version ( in this case version is 1 ) + position ( here the position would be `0end`, end of the stream ). The algorithm used for generating the signature is `sha256`
    - Concatenate or combine the encrypted data + `00iv00` + generated iv
    - The resultant above is combined with `00sig00` + signature generated above
    - finally add padding to the resultant above with `xxx`
    - Now create the filekey
    - Append the file with the encrypted data we have generated above ( note the step till padding `xxx` )

So this is how a simple file would be encrypted. Now the point we need to have a look here is that it uses the version along with the encrypetd data. Each time the file gets modified, the encrypted version does increment by 1. And hence the signature does change. This version number is also updated accordingly in the filecache. For any case lets say the updated version number is older, then the file cannot be downloaded. The user would see a `Bad Signature` issue in the UI. Inorder to handle this situation there is a command `encryption:fix-encrypted-version` which when executed, would help to update the encrypted version in the filecache.

**Comment by settermjd** [comment]
I've gone through your notes and done some experimenting with uploading files to get a better, hands-on, feel for the process. Here are a few questions that I have now.

You wrote: "_Create a file key_". What is the file key, exactly? Or, where can I find more information about them?

**Comment by voroyam** [comment]
After reading this I don't know what encryption version is or where general encryption description starts and the version encryption begins. Also this seems to me like a bug if we have an extra occ command to fix it. Please correct me if I am wrong.

**Comment by settermjd** [comment]
Closing after discussion with @sharidas.
