### ISSUE TITLE
AppInfo Path Confusion

### ISSUE THREAD

**Issue by miqrogroove** [owncloud/docs#168]
## What Type Of Content Change Is This?
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?
- [ ] Developer Manual

## What Needs to be Documented?
There is some confusion between the Routing doc and the DI Container doc.  For Routing, the given path is `appinfo/application.php` but then in the DI Container the path for apparently the same file is `lib/AppInfo/Application.php` and it is unclear what would be the difference, if any?

https://doc.owncloud.org/server/10.0/developer_manual/app/fundamentals/routes.html
https://doc.owncloud.org/server/10.0/developer_manual/app/fundamentals/container.html

**Comment by miqrogroove** [comment]
p.s. There is also a discrepancy with Controllers where the `class Application extends application` rather than `class Application extends App` so which one is correct?

https://doc.owncloud.org/server/10.0/developer_manual/app/fundamentals/controllers.html

**Comment by miqrogroove** [comment]
Doing some basic testing, I found that using `appinfo/application.php` as the path causes ownCloud to log an error like `"Class 'OCA\\\\MyApp\\\\AppInfo\\\\Application' not found\"` whereas if I move the entire `appinfo` directory to `lib/AppInfo` then the Settings page can't even find the app.  I think all of this needs to be explained more clearly.

**Comment by miqrogroove** [comment]
If I'm understanding correctly so far, the info file needs to be at `appinfo/info.xml` but the container file needs to be at `lib/AppInfo/Application.php` and any other combination I've tried based on the documented examples did not work.

**Comment by voroyam** [comment]
Can you find something helpful here:

https://doc.owncloud.org/phpdoc/

**Comment by settermjd** [comment]
@PVince81, can you provide input here, pls?
