### ISSUE TITLE
Unresolved include directive in modules/admin_manual/pages/maintenance/upgrade.adoc

### ISSUE THREAD

**Issue by ho4ho** [owncloud/docs#1710]
## What Needs to be Documented?

Fix:

```
Unresolved include directive in modules/admin_manual/pages/maintenance/upgrade.adoc - include::partial$maintenance/major_release_note.adoc[]
```

\+

```
Unresolved include directive in modules/admin_manual/pages/maintenance/package_upgrade.adoc - include::partial$maintenance/major_release_note.adoc[]
```

caused of #1657 shown in links below.

## Where Does This Need To Be Documented?
https://doc.owncloud.org/server/admin_manual/maintenance/upgrade.html
https://doc.owncloud.org/server/admin_manual/maintenance/package_upgrade.html
https://doc.owncloud.org/server/10.2/admin_manual/maintenance/upgrade.html
https://doc.owncloud.org/server/10.2/admin_manual/maintenance/package_upgrade.html

## Why Should This Change Be Made? (Optional)
Bugfix

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
@ho4ho, pls review, time permitting.
