### ISSUE TITLE
A config-to-docs run is necessary for the upcoming 10.3 release

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#1724]
@settermjd this is a reminder that for the upcoming 10.3 release, a config-to-docs run is needed to update config.sample.php / config.apps.sample.php with the changes coming from core.

**Comment by settermjd** [comment]
Closed, as has been done.

**Comment by mmattel** [comment]
can you reference the PR?

**Comment by mmattel** [comment]
I reopen this issue because:

https://doc.owncloud.com/server/admin_manual/release_notes.html#other-notable-changes
`previews_path` has been added in core and in core config sample file,
but not present in:
https://doc.owncloud.com/server/admin_manual/configuration/server/config_sample_php_parameters.html

Therefore something either went wrong or the config-to-docs run was whyever not made.
Pls add the generated PR after the run so we can properly close that issue.
Doc backport to 10.3 will then be necessary.

@micbar imho urgent as there are for sure other changes made just waiting to appear in docs

**Comment by settermjd** [comment]
I ran it and the diff between the existing and generated file was empty.

**Comment by mmattel** [comment]
Strange, because comparing core/master to docs web, the config parameter is missing in doc web...

**Comment by settermjd** [comment]
Closing, as the request has been carried out. Thanks, @mmattel
