### ISSUE TITLE
Document White List for guest App

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#1726]
Our customers use the guest app but we have nearly no documentation about it.

I would like to document the features and usage of the guests app especially the app white list.

https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/configuration/user/user_roles.adoc#guest

**Comment by settermjd** [comment]
Sounds like a good idea. What usage statistics are collected, btw?

**Comment by voroyam** [comment]
None

**Comment by settermjd** [comment]
That's a bit disappointing, but it's understandable given privacy laws such as the GDPR.

**Comment by voroyam** [comment]
why so many labels? :)

![image](https://user-images.githubusercontent.com/24212810/64110102-72ae1f80-cd81-11e9-87a6-a662582a2766.png)

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1730

**Comment by settermjd** [comment]
> why so many labels? :)
> 
> ![image](https://user-images.githubusercontent.com/24212810/64110102-72ae1f80-cd81-11e9-87a6-a662582a2766.png)

Because they're relevant, and cost nothing.
