### ISSUE TITLE
Correct references to occ in configuration/files/encryption_configuration.adoc 

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#180]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [X] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [X] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

As highlighted in #176, all of the examples of calling `occ` were not following the convention throughout the rest of the documentation, which is to prefix them with `sudo -u www-data php`. 

## Why Should This Change Be Made?

These need to be corrected to keep the documentation consistent.

**Comment by mmattel** [comment]
closein PR merged
