### ISSUE TITLE
prefer route remote.php/webdav over remote.php/dav/files/USERNAME

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#1823]
A webdav mount done according to the current documentation with the gnome file manager nautilus looks like this

![image](https://user-images.githubusercontent.com/1108546/65188482-cea9c100-da6e-11e9-9b35-a8f11fe94670.png)

It works fine, but note that the mouse over displays a truncated URL. The files/USERNAME part is missing. (That may be an artefact, how gnomeVFS works, not sure why it behaves like this. Nemo also truncates in the same way.)

This becomes an issue, if you click again:
![image](https://user-images.githubusercontent.com/1108546/65188833-92c32b80-da6f-11e9-9c56-2dd857a59cfc.png)

It shows the truncated route. Same, if you create a bookmark. The bookmark will also open the truncated route.

It is not trivial to navigate back to the home folder. Clicking on the intermediate 'files' folder throws an error (which is good, it prevent exposure of usernames):

![image](https://user-images.githubusercontent.com/1108546/65188980-006f5780-da70-11e9-95e8-bfe2aafea1f1.png)

A workaround for this gnome(?) issue is to use the shorter remote.php/webdav route.
This one works correctly with re-clicking and bookmarking.

**Comment by jnweiger** [comment]
Suggested fix for the documentation: https://github.com/owncloud/docs/pull/1822

**Comment by settermjd** [comment]
Thanks @jnweiger. Closing as it's been merged (#1822) and backported.
