### ISSUE TITLE
Update docker guide 

### ISSUE THREAD

**Issue by tboerger** [owncloud/docs#185]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

Currently the docker guide still refers to the docker ports 80 and 443, but 443 isn't used at all anymore and port 80 have been changed to 8080.

## Why Should This Change Be Made?

Just reflect the latest docker container changes to get it up to date again.

**Comment by tboerger** [comment]
For reference the report within the docker image repository.

**Comment by theScrabi** [comment]
Please also add a mention of [OWNCLOUD_SUB_URL](https://github.com/owncloud-docker/server/issues/95).
