### ISSUE TITLE
[API] Roles API needs documentation

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/docs#1857]
all information shall be written down in https://github.com/owncloud/core/pull/36024

**Comment by settermjd** [comment]
Muchos gracias.

**Comment by settermjd** [comment]
@DeepDiver1975, for the implementing PR, do you only want the Roles API documented, as you mention an attributes addition to the shares API, that's also covered in owncloud/core#36024?

**Comment by DeepDiver1975** [comment]
> s you mention an attributes addition to the shares API, that's also covered in [owncloud/core#36024](https://github.com/owncloud/core/pull/36024)?

oh - yes - these attribute changes need to be documented as well - thx

**Comment by settermjd** [comment]
Can you review #1874, which handles those changes?
