### ISSUE TITLE
Limitation of WND to Windows is wrong.

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#1858]
https://doc.owncloud.com/server/admin_manual/enterprise/external_storage/windows-network-drive_configuration.html#windows-network-drive-listener

"The notifier only works with remote storage on Windows servers. It does not work reliably with Linux servers due to technical limitations."

This needs to be verified.

"It depends if the smb supports the notify protocol." @hodyroff

**Comment by settermjd** [comment]
@voroyam, can you provide further details, so that this section of the docs can be appropriately amended?

**Comment by voroyam** [comment]
I don't have any details.

@hodyroff can provide details.

**Comment by settermjd** [comment]
@hodyroff, can you provide more details for this issue, please?

**Comment by hodyroff** [comment]
Correct wording IMHO: "The listener capabilities depend on the ability of the used SMB/CIFS storage to provide notifications. Some of those, will have restrictions. Please check with your respective storage provider."

**Comment by jvillafanez** [comment]
If I remember correctly, notifications for Samba only works for the target folder you're listening, but they won't go deep down.
If you're listening on the "/top" folder, you won't receive notifications for "/top/middle/bottom" folder. You'd need to setup listeners for every existing folder and also for the new ones that could be created.

Windows doesn't have this limitation. You'll receive notifications for every file or folder inside the folder you're listening to.
