### ISSUE TITLE
Document new public link endpoints

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#1871]
## What Needs to be Documented?

ownCloud Server 10.3 comes with new endpoints to access public links via WebDAV and to send public link mail notifications.

- https://github.com/owncloud/core/pull/35932
- https://github.com/owncloud/core/pull/36063

To make use of both an admin needs to set `'dav.enable.tech_preview' => true,` in config.php.

## Where Does This Need To Be Documented?

Developer documentation

## Why Should This Change Be Made? (Optional)

New backend functionality should be documented for developers.

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
Closed as has been implemented.
