### ISSUE TITLE
Encryption: Use envrironment vars for recovery and oc password

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#19]
Referencing: https://github.com/owncloud/core/pull/32172
Core PR merged, stable10 created
``encryption:decrypt-all [-m|--method [METHOD]] [-c|--continue [CONTINUE]] [--] [<user>]``
For details please see the referenced PR

**Issue was originally created by mmattel.**

**Comment by mmattel** [comment]
original issue from documentation: 
https://github.com/owncloud/documentation/issues/4346

I am reopening it because the documentation repository will close soon - so we do not forget it
