### ISSUE TITLE
Broken link to install Antora command line tools

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#190]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

In https://github.com/owncloud/docs/blob/master/docs/getting-started.md

**The link to install Antora's command-line tools is dead:** https://github.com/owncloud/docs/blob/master/docs/docs/install-antora.md

Wrong: https://github.com/owncloud/docs/blob/master/docs/docs/install-antora.md
Correct: https://github.com/owncloud/docs/blob/master/docs/install-antora.md

## What Needs to be Documented?
Reestablish broken link

## Why Should This Change Be Made?
Fix

@settermjd , I asigned you this case as you originally wrote the Getting Started Guide

**Comment by tboerger** [comment]
Can be closed?

**Comment by mmattel** [comment]
sure, thanks
