### ISSUE TITLE
[iOS] Update documentation for iOS app version 1.1.0

### ISSUE THREAD

**Issue by hosy** [owncloud/docs#1900]
The new iOS app got some new features in version 1.1.0, which should be documented.

## What Needs to be Documented?

- [x] Avail­able Off­line Sup­port (https://github.com/owncloud/ios-app/pull/456)
- [x] UI im­prove­ments for the Nav­i­ga­tion Bar (https://github.com/owncloud/ios-app/pull/478)
- [x] Added In­dex Bar in File list (https://github.com/owncloud/ios-app/pull/469)
- [x] Added change sort or­der for all sort meth­ods (https://github.com/owncloud/ios-app/pull/474)
- [x] Back­ground Sync Sup­port, Back­ground Im­age Up­load (https://github.com/owncloud/ios-app/pull/484)
- [ ] Im­port Files from Share Sheet (https://github.com/owncloud/ios-app/pull/445)
- [ ] Added "Cre­ate Fold­er" Ac­tion in Di­rec­to­ry Pick­er (https://github.com/owncloud/ios-app/pull/445)

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [x] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by hosy** [comment]
@michaelstingl in cc for you

**Comment by settermjd** [comment]
Thanks for creating this, @hosy. I'll get it implemented.

**Comment by settermjd** [comment]
@hosy, I've been able to document most of the features listed in the description. However, on the version of the app that I have, Im­port Files from Share Sheet (owncloud/ios-app#445) doesn't work. I'm redirected to the app, and nothing further happens. Can you help me debug it please?

**Comment by settermjd** [comment]
@hosy, are "Im­port Files from Share Sheet" & "Added "Cre­ate Fold­er" Ac­tion in Di­rec­to­ry Pick­er" meant to refer to the same PR (owncloud/ios-app#445)?

**Comment by settermjd** [comment]
@hosy, do you have more information on "Added "Cre­ate Fold­er" Ac­tion in Di­rec­to­ry Pick­er"? Secondly, I've just created #530 to document the task scheduling functionality. Time permitting, can you review it please?
