### ISSUE TITLE
[iOS] Update documentation for iOS app version 1.1.1

### ISSUE THREAD

**Issue by hosy** [owncloud/docs#1928]
The new iOS app got some new features in version 1.1.0, which should be documented.

### System Dark Mode Support

https://github.com/owncloud/ios-app/pull/489

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [x] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
@hosy, please add some screenshots for the documentation of the system dark mode (owncloud/ios-app#489).
