### ISSUE TITLE
blc shows errors

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#193]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## Why Should This Change Be Made?

Fixing links

Running ``blc`` (npm broken links checker)
```
blc http://localhost:5000 -ro | grep BROKEN | grep ".png"
├─BROKEN─ http://localhost:5000/server/_images/docker/owncloud-ui-login.png (HTTP_404)
├─BROKEN─ http://localhost:5000/server/_images/installation/ssllabs.png (HTTP_404)
├─BROKEN─ http://localhost:5000/server/_images/configuration/mimetypes/json-alias-before.png (HTTP_404)
├─BROKEN─ http://localhost:5000/server/_images/configuration/mimetypes/json-alias-after.png (HTTP_404)
```
But they are present in the source
```
grep -r owncloud-ui-login.png
 administration_manual/pages/installation/docker/index.adoc:image:docker/owncloud-ui-login.png[The ownCloud UI via Docker]
grep -r ssllabs.png
 administration_manual/pages/installation/letsencrypt/index.adoc:image:installation/ssllabs.png[image]
grep -r json-alias-before.png 
 administration_manual/pages/configuration/mimetypes/index.adoc:image:configuration/mimetypes/json-alias-before.png[image]
grep -r json-alias-after.png 
 administration_manual/pages/configuration/mimetypes/index.adoc:image:configuration/mimetypes/json-alias-after.png[image]
```

The broken links refer to a folder ``_images`` which is NOT present in ``public``

**Comment by tboerger** [comment]
_images folders had been part of the sphinx setup.

**Comment by settermjd** [comment]
@tboerger, the `_images` folder is part of the generated Antora documentation.

**Comment by voroyam** [comment]
@mmattel is this still relevant?

**Comment by settermjd** [comment]
I've just run it again and don't see any issues. Closing.
