### ISSUE TITLE
Replace go.php links with page aliases

### ISSUE THREAD

**Issue by tboerger** [owncloud/docs#1937]
Currently we are maintaining a static list of redirect rules within the documentation deployment with a high effort. For every release we got to extend the list of redirects. To avoid that and to keep the maintainence more simple we should simply use page aliases.

You can see an example at [admin_manual/pages/appliance/configuration/clamav.adoc](https://raw.githubusercontent.com/owncloud/docs/master/modules/admin_manual/pages/appliance/configuration/clamav.adoc).

For the naming I would suggest aliases in the form of `go/alias-name`, e.g. `https://doc.owncloud.com/server/10.4/go/admin-install.html` which will redirect to `https://doc.owncloud.com/server/10.4/admin_manual/installation/`.

**Comment by settermjd** [comment]
I'm having a look into this at the moment. What you've said make sense to me. However, there will need to be further redirects, to redirect to the new redirects. That said, it'll be a one-time setup that no longer needs to be maintained.
