### ISSUE TITLE
Documentation/WebDAV mounting on Linux: Warn about usage of "auto" in /etc/fstab

### ISSUE THREAD

**Issue by NMertsch** [owncloud/docs#1948]
In `docs/modules/user_manual/pages/files/access_webdav.adoc` there is a section "Creating WebDAV Mounts on the Linux Command Line", describing how to auto-mount owncloud to a Linux file system.

In (currently) line 168 it is recommended to use "auto" in `/etc/fstab`, so owncloud is mounted automatically.
At lines 182 to 184 it says:
"Now every time you login to your Linux system your ownCloud share should
automatically mount via WebDAV in your `~/owncloud` directory. If you
prefer to mount it manually, change `auto` to `noauto` in `/etc/fstab`."

This is not exactly correct, at least not for my freshly installed Debian Buster: Auto-mounting via fstab does not happen on **login**, but on **boot**, before login.

Why is this important? Because when using "auto", mounting owncloud seems to be part of the target "Local File System" in the boot process. And if mounting owncloud fails for some reason, the PC won't boot:

```
...
[FAILED] Failed to mount /home/[my username]/owncloud
[DEPEND] Dependency failed for Local File System
[  OK  ] Started Emergency Shell.
[  OK  ] Stopped Dispatch Password Request to Console Directory Watch
[  OK  ] Reached target Emergency Mode.
[FAILED] Failed to start Dispatch Password Request to Console Directory Watch
...

Cannot open access to console, the root account is locked.
Press Enter to continue.
```
On pressing Enter, the message just appears again, I had to poweroff the machine manually.

This is easily fixable (I just changed to "noauto" in `/etc/fstab`, using a live Ubuntu DVD), and it is quite straight-forward to understand why auto-mounting an online-resource on boot is not a good idea on a laptop without constant internet access, but I wish the documentation had warned me about this, or recommended "noauto" with a comment on the possible "auto" option.

At least the sentence "Now every time you login to your Linux system..." should be changed to "Now every time you boot your Linux system", if I understand this correctly.

I am no expert on these topics, sorry if I misunderstood something.

**Comment by settermjd** [comment]
Thanks for contributing such a detailed issue @NMertsch. I'll review and get the docs updated, where required.

**Comment by settermjd** [comment]
@NMertsch, #2076 has been created to revise the documentation.

**Comment by NMertsch** [comment]
Thanks a lot for your work, it's much appreciated!

**Comment by settermjd** [comment]
yw.
