### ISSUE TITLE
occ system command seems to be undocumented

### ISSUE THREAD

**Issue by SimonSpi** [owncloud/docs#1949]
After having upgraded to OwnCloud 10.3 I had to change as correctly documented in the Release Notes the cron job to trigger the occ command instead of cron.php. Changing the command resulted in an output as shown below:

1 [->--------------------------]
2 [-->-------------------------]
3 [--->------------------------]
4 [---->-----------------------]
5 [----->----------------------]
6 [------>---------------------]
7 [------->--------------------]
8 [-------->-------------------]
9 [--------->------------------]
10 [---------->-----------------]
11 [----------->----------------]
12 [------------>---------------]
13 [------------->--------------]
14 [-------------->-------------]
15 [--------------->------------]
16 [---------------->-----------]

I'm unsure if the cron now is working correctly. Searching the documentation I found that the occ command system:cron is undocumented thus not providing any further information. It would be beneficial to have this documented as well.

Especially information required to verify that the command is working correctly would be very helpful.

Many thanks for the great work being done with owncloud in general. Keep it up!

**Comment by settermjd** [comment]
@SimonSpi, sorry that the documentation for that has not been released yet. It should be out later today. In the meantime, you can read about the changes in https://github.com/owncloud/docs/pull/1234.
