### ISSUE TITLE
broken link: password-policy.adoc

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#203]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [x] Site

## What Needs to be Documented?

![image](https://user-images.githubusercontent.com/3321281/48021410-da331880-e138-11e8-9d10-81d722fd945f.png)

## Why Should This Change Be Made?

Make content available in ``administration_manual/configuration/server/``

@settermjd

**Comment by settermjd** [comment]
Closing as already corrected and deployed.
