### ISSUE TITLE
Fix Cron Background Job document

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2040]
The PR removed the full path of the php script and the occ script. The note about the full path was left behind.

https://github.com/owncloud/docs/pull/1998#issuecomment-550267202

**Comment by voroyam** [comment]
soo, no more PRs? @settermjd

**Comment by settermjd** [comment]
Does there need to be?

**Comment by voroyam** [comment]
Since the creation of the issue nothing changed, right?

**Comment by settermjd** [comment]
As I've said previously, the use of a site-wide variable was used to make the docs more maintainable and to reduce the time in doing so. While at first site-wide variables can be a little harder to read, the tradeoff seems well and truly worth it.

**Comment by voroyam** [comment]
the core problem of this ticket has not been addressed. Why are you closing this with a general statement of your variables?

**Comment by garrettboone** [comment]
Also, the "Cron Jobs" section is duplicated with the first instance showing php and not full path (as being discussed), and the second instance showing full path, with an additional sub-item of "Available Background Jobs".

![image](https://user-images.githubusercontent.com/47018474/71642673-fe2ab500-2c7c-11ea-8d4e-00e8f82c6045.png)
