### ISSUE TITLE
Document OIDC

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#2100]
## What Needs to be Documented?

We need to document the OpenID Connect integration, the new way for authentication and authorization between ownCloud components as well as third party integrations.

- Basic OpenID explanation https://developer.okta.com/blog/2019/10/21/illustrated-guide-to-oauth-and-oidc
- Explain flows within ownCloud 10 server
- Describe integration with different IdPs (e.g., Ping Identity / Kopano Konnect / Keycloak)
- how to integrate ownCloud clients
  - Current iOS on appstore can be used for testing
  - Desktop client daily builds can be used for testing
- supported cyphers - technical detail on integration with different IdPs
- Integration => Recommend consulting
- SAML migration => Recommend consulting
- OAuth2 and OIDC are mutually exclusive

**Information**
- Readme in repo
- Docker-compose setup in repo
- Deployment, configuration and test setup @mrkwenzel @TheOneRing 
- Further technical or content questions @DeepDiver1975 

## Where Does This Need To Be Documented?

- Admin docs, configuration (SSO and user management might be key words)

## Why Should This Change Be Made? (Optional)

- New feature will soon be released

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@DeepDiver1975 can provide input/briefing and answer questions.

**Comment by settermjd** [comment]
@pmaier1, in the description, you've written: "_OAuth2 and OIDC are mutually exclusive_". However, according to :https://developer.okta.com/blog/2019/10/21/illustrated-guide-to-oauth-and-oidc "_OpenID Connect (OIDC) is a thin layer that sits on top of OAuth 2.0 that adds login and profile information about the person who is logged in._". Was your comment added by mistake?

**Comment by pmaier1** [comment]
> @pmaier1, in the description, you've written: "OAuth2 and OIDC are mutually exclusive". 

This just refers to the ownCloud features. There's an OAuth2 (marketplace.owncloud.com/apps/oauth2) and an OpenIDConnect app. You can only use one at a time, otherwise you might run into issues, that's all. Also it does not make much sense to offer both as  OIDC builds on top of OAuth2. Either you use OAuth2 (simple way, just install the app, ownCloud provides server-side for auth) or you use OIDC (advanced way, requires IdP, IdP provides server-side for auth).

**Comment by DeepDiver1975** [comment]
From a future vision point of view we should only do OpenIdConnect based instllations. This will evolve more and more into best practice and state of the art.

**Comment by DeepDiver1975** [comment]
There is a lot of information already in the readme: https://github.com/owncloud/openidconnect#openid-connect-for-owncloud

Please let me know for which parts you need more information. @settermjd

**Comment by settermjd** [comment]
> There is a lot of information already in the readme: https://github.com/owncloud/openidconnect#openid-connect-for-owncloud
> 
> Please let me know for which parts you need more information. @settermjd

Thank you.

**Comment by settermjd** [comment]
@DeepDiver1975, I already have all of the information in the README. However, I also need the following:

- How to integrate with different IdPs, such as _Ping Identity_, _Kopano Konnect_, and _Keycloak_. Perhaps the existing information covers this sufficiently.
- How to integrate OIDC with ownCloud clients
- The supported cyphers (technical detail on integration with different IdPs)
- Details on SAML migration

**Comment by micbar** [comment]
@settermjd @DeepDiver1975 How could we move on with this topic?
IMO this is all part of the Phoenix MVP and therefore has some prio.

**Comment by settermjd** [comment]
> @settermjd @DeepDiver1975 How could we move on with this topic?
> IMO this is all part of the Phoenix MVP and therefore has some prio.

Two PRs need to be merged: #2110 and https://github.com/owncloud/core/pull/36526. As soon as they're done, then this has been implemented.
