### ISSUE TITLE
Document app settings in the appliance

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2106]
Document app settings in the appliance

**Comment by settermjd** [comment]
Do you have more information on this, @voroyam?

**Comment by voroyam** [comment]
I want to document how you can access the settings in the appliance and what they are.

Since I made this issue, assigned my self to it, I would expect that I do it when I have the time.

**Comment by settermjd** [comment]
Fair enough.

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/2176
