### ISSUE TITLE
Document encryption:hsmdaemon occ commands

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#2112]
## What Needs to be Documented?

The occ commands related to the hsmdaemon are not documented. See `occ encryption:hsmdaemon --help`.

## Where Does This Need To Be Documented?

- https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command.html#encryption
- https://doc.owncloud.com/server/admin_manual/configuration/server/security/hsmdaemon/

## Why Should This Change Be Made? (Optional)

Document available/supported functionality.

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
I've just setup my test ownCloud instance with hsmdaemon integration, so I think I may well have all that I need to document this issue. I'll keep you posted if not.
