### ISSUE TITLE
Clarify trash bin expiration

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2113]
We need to write in more clear and precise words how the trash bin expiration works.

The two parameter that we have now are trashbin_retention_obligation and purge_limit.

**Comment by settermjd** [comment]
Sounds like a good idea to me. Are you referring to `./modules/admin_manual/pages/configuration/files/trashbin_options.adoc`?

**Comment by voroyam** [comment]
I was thinking more on the config sample php command page. The language there is to little to vague.

**Comment by settermjd** [comment]
Thanks for clarifying. :+1:

**Comment by settermjd** [comment]
I just had a read of the documentation for both settings. Makes sense to me. Can you clarify what is unclear about the existing documentation?

**Comment by voroyam** [comment]
For me it was unclear what the target of those settings is. Is it the user quota which is related to user storage or is it the trash bin. We had a lengthy discussion in RC and in the office, and now I seem to understand it better. That's why I want to clarify the existing explanation of the config parameters so that other users have a clear understanding on what to expect.

**Comment by settermjd** [comment]
Fair enough. Feel free to contribute a PR with the changes that will improve it.

**Comment by voroyam** [comment]
I will :) That's why I created the issue and assigned myself :)
