### ISSUE TITLE
Docs miss install apps by marketplace

### ISSUE THREAD

**Issue by ho4ho** [owncloud/docs#2128]
## What Needs to be Documented?
> @wom-bat https://github.com/owncloud/calendar/issues/1039#issuecomment-543353011:
> Doesn't visiting your Owncloud page as an administrator, finding the Market, finding the calendar app in the market, and clicking the 'Install' button do it?

and

> @insanity54 https://github.com/owncloud/calendar/issues/1039#issuecomment-543363030:
> That's the undocumented process that I would have loved to see in one in the aforementioned places.
>
>It is not what I intuitively tried. I first tried the settings page,/settings/admin?sectionid=apps. I saw the installed apps so naturally it looked like I was in the right place for adding more. However, the screen lacks any method of installing new plugins.

Install needs to be done by manual:

https://doc.owncloud.org/server/10.3/admin_manual/installation/apps_management_installation.html#manually-installing-apps 

or by marketplace app but marketplace app install undocumented by docs above

## Where Does This Need To Be Documented?

Describe install apps by marketplace in:

https://github.com/owncloud/docs/blob/6723796/modules/admin_manual/pages/installation/apps_management_installation.adoc

Linking page above by this page more generically:

https://github.com/owncloud/docs/blob/6723796/modules/user_manual/pages/pim/contacts.adoc
https://github.com/owncloud/docs/blob/6723796/modules/user_manual/pages/pim/calendar.adoc
https://github.com/owncloud/docs/blob/6723796/modules/admin_manual/pages/configuration/user/user_configuration.adoc ("To enable Custom Groups" part)
https://github.com/owncloud/docs/blob/6723796/modules/admin_manual/pages/configuration/user/guests_app.adoc ("Installation" part)
https://github.com/owncloud/docs/blob/672379/modules/admin_manual/pages/configuration/files/external_storage/dropbox.adoc ("1.  Click btn:[Market] in the ownCloud web" part)
https://github.com/owncloud/docs/blob/672379/modules/admin_manual/pages/configuration/server/security/oauth2.adoc ("or use the Market application." part)
https://github.com/owncloud/docs/blob/672379/modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc ("The Anti-Virus app needs to be installed from the ownCloud Market " part)
https://github.com/owncloud/docs/blob/672379//modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc ("please install `the FTP Storage Support app`_ from the ownCloud market." part)

## Why Should This Change Be Made? (Optional)
Better help for users, see https://github.com/owncloud/calendar/issues/1039

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by ho4ho** [comment]
> Clicking the Install button installs the app. If the app is not part of your ownCloud installation, it will be downloaded from the ownCloud Marketplace, installed, and enabled.
>
> https://doc.owncloud.org/server/10.3/admin_manual/installation/apps_management_installation.html#adding-apps

Look wrong by me. Only possible to do this by having installed app previously, if not need install by marketplace app first.

**Comment by settermjd** [comment]
To the best of my knowledge, the Market app should be available by default, unless you're basing your ownCloud installation from source.

**Comment by ho4ho** [comment]
This not the problem. Only docs above describe app enabling/disabling for app included by ownCloud (like "Admin Config Report", "Default encryption module ", ...) and uninstall apps via mycloud/settings/admin?sectionid=apps

But app not included by ownCloud like calendar, contacts, ... needs manual install or install by Marketplace and second (Marketplace) is miss in https://doc.owncloud.org/server/10.3/admin_manual/installation/apps_management_installation.html#adding-apps

**Comment by settermjd** [comment]
@michaelstingl, can you provide guidance here, please?

**Comment by settermjd** [comment]
Closing as has been implemented in #2154.
