### ISSUE TITLE
New config-to-docs run neccessary

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#2140]
## What Needs to be Documented?
A new config-to-docs run for [10.4] is necessary because of:
https://github.com/owncloud/core/pull/36413 ([For 10.4] Set 599 HTTP code on error)
https://github.com/owncloud/core/pull/36526 (Add sample OIDC configuration to the sample app config file)

## Why Should This Change Be Made? (Optional)
Sync core and docs

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@settermjd @micbar @jvillafanez @phil-davis

**Comment by settermjd** [comment]
Would you mind doing this, @mmattel?

**Comment by mmattel** [comment]
Yes, when 36526 is merged. the other one is already merged.

**Comment by mmattel** [comment]
After a successful run, additional changes are made in core which need another run when merged.

- [x] https://github.com/owncloud/core/pull/36413
- [ ] https://github.com/owncloud/core/pull/36526
- [ ] https://github.com/owncloud/core/pull/36796
- [ ] https://github.com/owncloud/core/pull/36815
