### ISSUE TITLE
update of occ command reference necessary

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#2141]
## What Needs to be Documented?
New options proposed in https://github.com/owncloud/core/pull/36520 (Filter app:list for just enabled or disabled apps)

## Where Does This Need To Be Documented?
occ command reference

## Why Should This Change Be Made? (Optional)
Sync with core

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@settermjd @micbar @phil-davis

**Comment by phil-davis** [comment]
So far nobody has reviewed the core PR, so I have no idea if it will even be noticed for 10.4
