### ISSUE TITLE
Clarify how to grab the URL for enterprise TarBalls

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2148]
https://doc.owncloud.com/server/10.3/admin_manual/maintenance/manual_upgrade.html#download-the-latest-installation

`wget https://username:password@customer.owncloud.com/link-to-tarball`

It's not obvious to customers how to get the "link-to-tarball".

We need to clarify it with text and pictures to make it foolproof. This way it's less work for support.

**Comment by settermjd** [comment]
We could add it, and update it with every version, but that would also expose information about the directory structure of customer.owncloud.com as well, information that should only be available to authorised users.

**Comment by voroyam** [comment]
My Idea was actually to ad a note how to grab the URL. Like not change the link to the actual folder the tar balls are in, but to say, you need to navigate to the tarballs first, then you need to grab the url of the tar ball and put it behind the link we have in the example. something like that.

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/2158
