### ISSUE TITLE
Rework "Big file upload Configuration"

### ISSUE THREAD

**Issue by haukman** [owncloud/docs#2152]
This part of the docs confuses some customers, as some of the statements in there are not valid anymore as we use chunking:

https://doc.owncloud.com/server/10.3/admin_manual/configuration/files/big_file_upload_configuration.html

> The default maximum file size for uploads, in ownCloud, is 512MB.

The goal of this ticket is to collect input what of the mentioned configuration still makes sense and what needs to be changed.

As far as I know, the following two things still make sense in combination with chunking:

```
php_value max_input_time 3600
php_value max_execution_time 3600
```
```
Your temp file or partition has to be big enough to hold multiple parallel uploads 
from multiple users;
e.g. if the max upload size is 10GB and the average number of users 
uploading at the same time is 100: temp space has to hold at least 10x100 GB
```

Do we need an extra section for public links? 

fyi @voroyam 

@cdamken @pako81 can you have a look and provide your input?

**Comment by pako81** [comment]
Infos that apply to chunked uploads: PHP timeouts, Apache modules, temp directory size.

Infos that apply to non-chunked uploads (public links): PHP timeouts, Apache modules.

It makes probably sense to split up the page in two different sections.

**Comment by settermjd** [comment]
Thanks for the feedback, @pako81

**Comment by settermjd** [comment]
From some further investigation, there are a number of changes to the file in master that haven't been backported to 10.3. I'll get a backport done now, and see if any further changes still need to be made.

**Comment by settermjd** [comment]
@pako81 / @haukman, I updated the file in #2160. Can you review that PR and let me know if further changes are required?

**Comment by settermjd** [comment]
Closing, as the implementing PR (#2160) has been merged and no further changes have been requested.
