### ISSUE TITLE
Missing document: core/apis/ocs/notifications/notification-workflow.adoc

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#2165]
## What Needs to be Documented?
Missing document: `core/apis/ocs/notifications/notification-workflow.adoc`
FullPath: `docs/modules/developer_manual/pages/core/apis/ocs/notifications/`

## Where Does This Need To Be Documented?
developer manual

## Why Should This Change Be Made? (Optional)
Missing document == doc validation fails and merging is impossible
Fixing: https://github.com/owncloud/docs/pull/2163

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@settermjd @voroyam

**Comment by settermjd** [comment]
I don't get that error. Which branch are you running the validator on?

**Comment by mmattel** [comment]
See referenced PR above (#2163)

**Comment by settermjd** [comment]
`yarn validate` wasn't failing for me on that branch, until I ran `yarn install`. FWIW, to me, it makes more sense to add a comment on the PR, instead of creating a new issue.

**Comment by settermjd** [comment]
Closing, as the change has been implemented.
