### ISSUE TITLE
the update examples need an update

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#2169]
https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc

* mentions updates from 7.x 8.x 9.x, it should also mention updates from 10.0, 10.1 or 10.2
* it mentions updates to 10.2.1 -- but we are at 10.3 already.

**Comment by settermjd** [comment]
Thanks for mentioning this, @jnweiger.
