### ISSUE TITLE
Publish server/10.4/user_manual/

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#2192]
This is needed for https://github.com/owncloud/enterprise/issues/3722, please.
The build of the tar requires access to https://doc.owncloud.com/server/10.4/user_manual/ownCloud_User_Manual.pdf

**Comment by settermjd** [comment]
The 10.4 branch is now available, and there are three PRs that are being backported to it. Just need approval on those, and the branch is ready to be published. I think I need to also update the master branch wrt the 10.4 branch being published.

**Comment by jnweiger** [comment]
I just saw an error in https://drone.owncloud.com/owncloud/docs/6622
```
Error: Duplicate nav: master@server:ROOT:nav.adoc
```

@settermjd Is that blocking the update?

**Comment by settermjd** [comment]
It would have been, but is resolved now.

**Comment by settermjd** [comment]
The 10.4 branch is currently available. It is not being automatically redirected to from latest, but that is coming after a current PR is reviewed and merged.

**Comment by settermjd** [comment]
You can find it at https://doc.owncloud.com/server/10.4/.

**Comment by settermjd** [comment]
The links to the PDFs are not, currently, working. Am working to fix that.

**Comment by jnweiger** [comment]
The 10.4 overview page page https://doc.owncloud.com/server/10.4/ says "Latest Stable Release (version 10.2)" and links into the 10.2 tree. 

![image](https://user-images.githubusercontent.com/1108546/72511424-7089c080-384b-11ea-849f-1816f90af12f.png)

10.3 and 10.4 should be added to the overview.

**Comment by settermjd** [comment]
> The 10.4 overview page https://doc.owncloud.com/server/10.4/ with the version switcher set to "10.4" says "Latest Stable Release (version 10.2)" and links into the 10.2 tree.

I thought that I submitted a PR for that. If not, I'll get right on it.

> 
> 10.3 and 10.4 should be added to the "10.4" switch, -- they are present though when I set the switch to "master". (But as noted above, the link to the 10.4 PDF is a 404)

Not quite sure what's going on there, yet. Will aim to have a PR created for it today, if not to have it resolved.

**Comment by jnweiger** [comment]
Success!
https://doc.owncloud.com/server/10.4/user_manual/ownCloud_User_Manual.pdf is now there!

@settermjd should we wait for https://github.com/owncloud/docs/issues/2236 before progressing with https://github.com/owncloud/enterprise/issues/3722 ?

**Comment by settermjd** [comment]
If @pmaier1 has the time to create the release notes, otherwise I'll create them based off of #2236.

**Comment by settermjd** [comment]
Closing, as the PDFs for the 10.4 release are now being successfully generated.
