### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by cdamken** [owncloud/docs#2209]
Checking the documentation:

https://doc.owncloud.com/server/10.3/admin_manual/maintenance/manual_upgrade.html

The verion now is 10.3.2 now and the URL fro the Upgrade shows:

wget https://download.owncloud.org/community/owncloud-10.2.1.tar.bz2

@voroyam @settermjd  Could you please help?

**Comment by cdamken** [comment]
Here is the Pull request: https://github.com/owncloud/docs/pull/2210

**Comment by cdamken** [comment]
I think I forgot other places too, ;)

**Comment by jnweiger** [comment]
Do we want to have the current URL there for each release?
If so, I suggest to use a `*latest*` symlink to reduce maintenance.

**Comment by settermjd** [comment]
@cdamken, I agree with @jnweiger. Use "latest", which will always redirect to the latest version of the documentation. I'll do a bit of grepping for other places that might have hardcoded version strings.
