### ISSUE TITLE
10.4 branch has no release notes for 10.4.0

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#2236]
* https://github.com/owncloud/docs/blob/10.3/modules/admin_manual/pages/release_notes.adoc

   has release notes for up to 10.3.1 and warns that " The next minor version of ownCloud Server  (around the end of 2019) no longer supports PHP 7.0" -- OK.

* https://github.com/owncloud/docs/blob/10.4/modules/admin_manual/pages/release_notes.adoc

   has one additional release notes section for 10.3.2, and the same deprecation warning.
 BAD. It should have a section for 10.4.0 and say that 10.4.0 is the minor version release that  deprecates php 7.0 as announced.

* Switching to 10.2 or 10.1, there are also 10.3.x sections. WEIRD.

The missing 10.4.0 section is a release blocker as that should go into the included PDF as per https://github.com/owncloud/docs/issues/2192

**Comment by phil-davis** [comment]
There are more PRs waiting to be reviewed/merged for 10.4, so actually the details of what "is" in the release are not yet known, so it would be hard to have release notes yet :)

**Comment by jnweiger** [comment]
We have a comprehensive https://github.com/owncloud/core/blob/release-10.4.0/CHANGELOG.md in the release branch (top section of that files, still flagged as UNRELEASED).

How are release notes done? Based on the changelog entries, or independantly?

I disagree with Phil's implication that late additions should block a start :-)

**Comment by phil-davis** [comment]
I agree with @jnweiger disagreeing ;)
That CHANGELOG should be a good start. (Thosse things at least should end up in 10.4)
Just note that `release-10.4.0` branch has been merged back to `master` (it got old over Christmas and New Year...). So we "stopped" it. We are doing "development for 10.4" in `master` and a whole new core branching/release process will start when core `master` has all the features we know we want and can deliver.

**Comment by settermjd** [comment]
Up to this point, @pmaier1 has provided the basis of the release notes for each release, which are then reviewed, and ultimately merged.

**Comment by settermjd** [comment]
@pmaier1, can you add your input, please?

**Comment by pmaier1** [comment]
> @pmaier1, can you add your input, please?

Sure, will do this week. 

> The missing 10.4.0 section is a release blocker as that should go into the included PDF as per #2192

The release notes are part of the admin manual. Do we also include that part in a release? Afair it is only the user manual which is included. In the past we never blocked a technical release for missing release notes.

**Comment by settermjd** [comment]
> > @pmaier1, can you add your input, please?
> 
> Sure, will do this week.

Thanks kindly!

> 
> > The missing 10.4.0 section is a release blocker as that should go into the included PDF as per #2192
> 
> The release notes are part of the admin manual. Do we also include that part in a release? Afair it is only the user manual which is included. In the past we never blocked a technical release for missing release notes.

If we've never blocked a release in the past, then it makes sense, to me at least, to continue that tradition.

**Comment by pmaier1** [comment]
Here we go https://github.com/owncloud/docs/pull/2299
