### ISSUE TITLE
Documentation has two sections called Release Notes

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#2240]
The navigation sidebar at https://doc.owncloud.com/server/10.4/ has 
![image](https://user-images.githubusercontent.com/1108546/72884161-f2736100-3d05-11ea-92e8-ee055e7decf7.png)

<hr>

The two 'Release Notes' sections are confusing.
If there are two with a purpose, then 
* the first one at the top should talk about the product
* the second one in the Administation Manual would maybe talk about major revisions of the manual?

Currently 
* the first one has a few items about antora (outdated?)
* the second one is about the product.

To resolve the confusion, I suggest to remove the first 'Release Notes' section.
Or move it near the end of the document tree, with a proper heading, that clearly says it describes the documentation itself, and not the product.

**Comment by jnweiger** [comment]
Thanks to @voroyam for pointing out that there are two of them.

**Comment by settermjd** [comment]
Thanks for raising this, @jnweiger. After reviewing the documentation, I'm keen to go a little further by also moving the "_What's New_" pages from the Admin and User manuals to the top-level of the documentation, where the first "_Release Notes_" and "_How to Contribute_" pages are.

**Comment by mmattel** [comment]
Closed via #3745
