### ISSUE TITLE
PDF navigation issues

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#2244]
The navigation of the PDF document has the headings 
* ownCloud User Manual
* Table of Contents
* Introduction
at the top level.
Everything else is indented under Introduction.

![image](https://user-images.githubusercontent.com/1108546/72886639-73ccf280-3d0a-11ea-908f-f50ce901ab1f.png)

The stucture in that screenshot should be linear, not indented.

**Comment by settermjd** [comment]
This looks like there is a formatting error in either the section/page titles or in the generated navigation page. I'll investigate and find out what's going on.

**Comment by settermjd** [comment]
I had a look at the respective navigation files and have come up with a solution. I'll push the PR shortly.

**Comment by settermjd** [comment]
![Bildschirmfoto von 2020-02-05 14-15-24](https://user-images.githubusercontent.com/196801/73845236-7f4c0d80-4822-11ea-81bf-94bd6b263f31.png)

This is the new result in the user manual.

**Comment by oliviercailloux** [comment]
I suppose that the text of the PDF version is the same as the text of the [HTML version](https://doc.owncloud.org/server/10.4/user_manual/) of the user manual, isn’t it?

If so, it would be nice if these headings would be exactly the same in both versions, and if the PDF structure would also display the sub-headings. For example, the HTML version has a `The WebUI` / 
`Navigating the WebUI` sub-heading.

**Comment by oliviercailloux** [comment]
I don’t think the patch solves the problem I just mentioned. Should I open another bug report?
