### ISSUE TITLE
PDF fails to render menu:[] btn:[] and some images correctly

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#2246]
Here the section about the Market app is shown. Other parts may be affected similarily.

The HTML version at https://doc.owncloud.com/server/10.4/user_manual/apps/market.html renders the elements nicely:
![image](https://user-images.githubusercontent.com/1108546/72893120-96fe9e80-3d18-11ea-846f-413de4db15bd.png)

The PDF version at https://doc.owncloud.com/server/10.4/user_manual/ownCloud_User_Manual.pdf
only has one image, and shows raw markup syntax for GUI elements:

![image](https://user-images.githubusercontent.com/1108546/72893303-fc528f80-3d18-11ea-8394-a0d404ddec49.png)

**Comment by settermjd** [comment]
There might be a way of better integrating the experimental functionality into asciidoctor-pdf. I'll do some research and comment further when I know more.

**Comment by settermjd** [comment]
I just did a bit of checking and found 72 instances that would need to be updated, likely with [a conditional preprocessor directive](https://asciidoctor.org/docs/user-manual/#conditional-preprocessor-directives), if there isn't a suitable workaround in asciidoctor-pdf. I've asked about a workaround in the Antora forum, but have yet to hear back from someone there. 

If there isn't a suitable workaround, to me, it makes no sense to wrap 72 lines in `ifdev` or `ifeval` directives, as it would be a lot of work and likely lead to a lot of confusion and errors in future mainteance.

**Comment by settermjd** [comment]
It would, but I think that might turn into a maintenance nightmare. After doing some further research, I think adding [a supplemental stylesheet](https://github.com/Mogztter/asciidoctor-pdf.js/) might suffice. Not sure yet, as I need to experiment with the idea.

**Comment by settermjd** [comment]
The project's author said that it likely should work. Currently experimenting to find out if it does work or not.

**Comment by settermjd** [comment]
Might have a simple solution to the issue, setting the experimental attribute when building the PDFs. Have a look in the image below.

![pdf](https://user-images.githubusercontent.com/196801/72907189-c66ed480-3d33-11ea-9288-a731657dc20f.png)

**Comment by jnweiger** [comment]
That looks great!
Seems that we now want experimental features in our production pipelines. Sigh. That is a different breed of Nightmares, is it?
