### ISSUE TITLE
occ occ db:convert-type is broken

### ISSUE THREAD

**Issue by enbrnz** [owncloud/docs#2254]
## What Needs to be Documented?

Currently there is no way to migrate from SQLite to MySQL/MariaDB/PostgreSQL as there is the following issue:

https://github.com/owncloud/core/issues/27075

Therefore we should take out this part out of the docs until the issue is fixed.

## Where Does This Need To Be Documented?
https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command.html#database-conversion

## Why Should This Change Be Made?

Confusing information for users.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
Thanks, @enbrnz. I'll get a PR for that done today.

**Comment by pmaier1** [comment]
With 10.3.0 we released fixes for the command (https://github.com/owncloud/core/pull/35390). It's still experimental but we're waiting for feedback from the community. So, please don't change it unless there's a good reason for it.

**Comment by settermjd** [comment]
> With 10.3.0 we released fixes for the command ([owncloud/core#35390](https://github.com/owncloud/core/pull/35390)). It's still experimental but we're waiting for feedback from the community. So, please don't change it unless there's a good reason for it.

Okay. I'll close #2258, based on this feedback.
