### ISSUE TITLE
https://owncloud.org/community/documentation/ misses 10.3 and 10.4

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#2259]
The community web page has latest links, that already point to 10.4 -- but the links further down only list versions up to 10.2 but nothing later.

**Comment by jnweiger** [comment]
btw: the background photo is intimidating, imho.

**Comment by settermjd** [comment]
> btw: the background photo is intimidating, imho.

It is rather imposing, yes.

**Comment by settermjd** [comment]
After discussing this with @michaelstingl earlier, I'm going to talk with Flo tomorrow about getting an account, so that I can address this directly.

**Comment by settermjd** [comment]
I've removed 10.0 and added 10.3 & 10.4
