### ISSUE TITLE
Documentation needed for Group-based retention policies based on upload time

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/docs#2265]
@settermjd please get in touch with @micbar and @davitol they'll help you to get all the information  you need 

GitHub issue: https://github.com/owncloud/enterprise/issues/3361 Group-based retention policies based on upload time

PRs:
https://github.com/owncloud/workflow/pull/191
https://github.com/owncloud/workflow/pull/214

**Comment by settermjd** [comment]
Thanks, @HanaGemela. Shall do.

**Comment by settermjd** [comment]
ping @micbar @davitol

**Comment by davitol** [comment]
New Implementation:
   - There is a config option `'workflow.tag-based-retention.use-upload-time'` false by default.
   - It can be set to true in the config.php using occ command `php occ config:system:set workflow.tag-based-retention.use-upload-time --type boolean --value true`
   - False means current behavior
   - True should switch getMtime() to upload time in the lines.

**Note: It needs files_lifecycle and workflow apps enabled**

**Comment by settermjd** [comment]
@davitol is there an installation available that has these changes available?

**Comment by davitol** [comment]
> @davitol is there an installation available that has these changes available?

AFAIK, right now no.

**Comment by micbar** [comment]
@settermjd  This is how you set that up

1)`php occ a:e files_lifecycle`
2) `php occ a:e workflow`
3) `php occ config:system:set workflow.tag-based-retention.use-upload-time --type boolean --value true`
4) log in create user and group
5) `php occ lifecycle:set-upload-time 2019-11-01` for unset upload times
6) Create new tag "expire"
7) Create tagging workflow based on a group membership
8 ) Create Retention for the tag "expire", set value "1 day"
9) Run `php occ system:cron` and the new background job for the tag should appear (set the time values the Retention Meta Job to 0 before )
10) Modify some upload times in `oc_properties` to simulate that the time period has expired 
11) Run `php occ system:cron` and the new job will expire files according to the rules
=> Warning for this step:10) Modify some upload times in `oc_properties` to simulate that the time period has expired 
If they don't want to modify their Database for testing, then I think they have to wait until the expiration

**Comment by settermjd** [comment]
Thanks for the feedback, @micbar @davitol

**Comment by settermjd** [comment]
@davitol / @micbar https://github.com/owncloud/workflow/pull/214 adds support for using upload time for retention checking for user-based retention and https://github.com/owncloud/workflow/pull/191 adds support for user-based retention for tag-based retention. However, the new property in this issue is named `tag-based-retention.use-upload-time`. Am I correct in believing that it applies to both user and tag-based retention, and not just tag-based retention?

**Comment by settermjd** [comment]
@davitol / @micbar do one of you have time tomorrow to discuss group-based retention?

**Comment by settermjd** [comment]
Closing after feedback from @micbar.
