### ISSUE TITLE
Add missing content to the developer docs theming guide

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#2279]
@voroyam pointed out that some of the content in the original (RsT) theming guide is missing from the current version of the developer docs theming guide. Please migrate it from https://github.com/owncloud/documentation/blob/5f32f2ae3c3f4b8e45fc034bc0dbe5d41948640f/developer_manual/core/theming.rst#L50.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [X] Missing Content
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [X] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by voroyam** [comment]
It was actually @ChrisEdS who noticed it. So whole credit goes to him. I am just the messenger :D

**Comment by settermjd** [comment]
Thanks for clarifying. Thanks for spotting that the content was missing, @ChrisEdS.
