### ISSUE TITLE
add our mimetype mapping to the firewall document

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2293]
https://github.com/owncloud/core/blob/master/resources/config/mimetypemapping.dist.json

this file contains helpful mimetypes which are needed if you want to block upload of a certain type via the file firewall app.

We need to add this to the firewall config document.

https://doc.owncloud.com/server/admin_manual/enterprise/firewall/file_firewall.html

**Comment by settermjd** [comment]
Is this what you and @ChrisEdS were discussing yesterday?

**Comment by settermjd** [comment]
I'll have a review of file_firewall.adoc and get on this one. Should have it finished today.

**Comment by voroyam** [comment]
Yes, this was, what we were discussing. I noticed every time a customer asks us about firewall we start to search google. Would be easier if it were in our docs.

**Comment by voroyam** [comment]
I want to add the 5 most common extensions and their mimetype on top of the PR from you @settermjd . Please don't close this issue until I do :)

**Comment by voroyam** [comment]
@settermjd what was my last comment in this issue?

**Comment by voroyam** [comment]
Okay, then I answer it myself. 

My comment was please don't close until I do.

reading helps, sometimes.

**Comment by settermjd** [comment]
Sorry for overlooking that.

**Comment by settermjd** [comment]
Can this be closed?

**Comment by voroyam** [comment]
yes.
