### ISSUE TITLE
Clarify doc about sharing

### ISSUE THREAD

**Issue by oliviercailloux** [owncloud/docs#2294]
I recently [tried to use file sharing](https://central.owncloud.org/t/how-does-shared-folder-work/23490) and found two points quite unclear in the user manual.

First, I did not realize, reading the user manual, that the [Guest sharing](https://doc.owncloud.org/server/10.4/user_manual/files/webgui/sharing.html#sharing-files-with-guest-users) feature enables my guest to use the ownCloud client to sync. I thought it would only provide access to the server web interface.

Second, I think that the user manual never mentions that it is hopeless to try to use [Federated sharing](https://doc.owncloud.org/server/10.4/user_manual/files/federated_cloud_sharing.html) when the administrator of the server has not explicitly trusted the other server before. 

It seems it is necessary to read the Administrator manual to find [this information](https://doc.owncloud.org/server/10.4/admin_manual/configuration/files/federated_cloud_sharing_configuration.html) (and even if you reach there, it is hard to find as it is to be found under the `Configuration` / `Files` section whereas it does not appear under the `Files` section in the User manual).

 As a user (and not an administrator) of the server, I didn’t think about reading the Administrator manual in detail (I only had taken a cursory look at it).

Not sure how to correct it but I thought I’d mention my experience in case someone sees how to improve this aspect.

**Comment by settermjd** [comment]
Hi @oliviercailloux. Thanks for taking the time to detail your experiences in this issue. In collaboration with the developers, I'll review this section of the documentation and make all the required changes.

**Comment by voroyam** [comment]
Hello @oliviercailloux ,

so from what I understood you want the documentation to mention:

- Guests can use the ownCloud client to sync.

The place for this information is probably [here](https://doc.owncloud.org/server/user_manual/files/webgui/sharing.html#sharing-files-with-guest-users)

Do you agree?

----

Then you want to have the documentation mention that federated sharing has to be established before creating a new federated share. Correct?

probably a hint somewhere in [here](https://doc.owncloud.org/server/user_manual/files/federated_cloud_sharing.html#how-federated-sharing-works)

Tell me if my assumptions are correct, and I get to work right away.

**Comment by oliviercailloux** [comment]
Yes, and yes! And ideally, let the reader know how she can check whether her adminsitrator has established federated sharing.

**Comment by voroyam** [comment]
Other than asking - I don't know if there is a check a user can do.

PRs are open, thanks for noticing and notifying us.
