### ISSUE TITLE
Move API key information to Admin guide - Appliance - Configuration - Enterprise Trial 

### ISSUE THREAD

**Issue by CaptionF** [owncloud/docs#2302]
Currently information of the API key (used in the Marketplace) is documented in the developer guide:
https://doc.owncloud.com/server/developer_manual/app/fundamentals/market_app.html 

However, everyone who wants to test enterprise apps needs to know the API key, and for that this information should be part of the Admin Guide under "Appliance / Configuration / Enterprise Trial"

**Comment by voroyam** [comment]
the dev docs are representing a planed state, planed 2 years ago. Now the plans have changed, and the reality is different.
