### ISSUE TITLE
Handle redirects from the old documentation to the new

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#231]
## What Type Of Content Change Is This?

- [X] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [X] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [X] Admin Manual
- [X] Developer Manual
- [X] User Manual

## What Needs to be Documented?

This doesn't involve documentation per se but ensuring that links to the existing documentation are handled (in one way or another) by the new documentation.

## Why Should This Change Be Made?

So that nothing breaks as far as the user is concerned.

**Comment by settermjd** [comment]
## Required Redirects

| From | To | Netlify or Antora | New Page Required? |
|---|---|---|---|
| /server/latest/admin_manual | /server/administration_manual/ | Netlify | No |
| /server/latest/admin_manual/installation/ | server/latest/administration_manual/installation/index.html | Antora | Yes |
| /server/latest/admin_manual/installation/source_installation.html | server/latest/administration_manual/installation/manual_installation.html | Antora | No |
| /server/latest/admin_manual/installation/docker/ | server/latest/administration_manual/installation/docker/index.html | Antora | No |
| /server/latest/admin_manual/installation/letsencrypt/ | server/latest/administration_manual/installation/letsencrypt/index.html | Antora | No |
| /server/latest/admin_manual/upgrading/ | server/latest/administration_manual/upgrading/index.html | Antora | Yes |
| /server/latest/admin_manual/configuration/ | server/latest/administration_manual/configuration/index.html | Antora | Yes |
| /server/latest/admin_manual/configuration/database | server/latest/administration_manual/configuration/database/index.html | Antora | Yes |
| /server/latest/admin_manual/configuration/files | server/latest/administration_manual/configuration/files/index.html | Antora | Yes |
| /server/latest/admin_manual/configuration/mimetypes | server/latest/administration_manual/configuration/mimetypes/index.html | Antora | Yes |
| /server/latest/admin_manual/configuration/server | server/latest/administration_manual/configuration/server/index.html | Antora | Yes |
| /server/latest/admin_manual/configuration/user | server/latest/administration_manual/configuration/user/index.html | Antora | Yes |
| /server/latest/admin_manual/maintenance/ | server/latest/administration_manual/maintenance/index.html | Antora | Yes |
| /server/latest/admin_manual/issues/ | server/latest/administration_manual/issues/index.html | Antora | Yes |
| /server/latest/user_manual/ | server/latest/user_manual/index.html | Antora | Yes |
| /server/latest/user_manual/files/ | server/latest/user_manual/files/index.html | Antora | Yes |
| /server/latest/user_manual/pim/ | server/latest/user_manual/pim/index.html | Antora | Yes |
| /server/latest/user_manual/files/troubleshooting.html | /server/user_manual/troubleshooting.html | Antora | No |
| /server/latest/user_manual/pim/troubleshooting.html | /server/user_manual/troubleshooting.html | Antora | No |
| /server/latest/developer_manual/commun/ | /server/developer_manual/commun/help_and_communication.html | Antora | Yes |
| /server/latest/developer_manual/app/ | /server/developer_manual/app/introduction.html | Antora | No |
| /server/developer_manual/app/fundamentals/ | /server/latest/developer_manual/app/fundamentals/index.html | Antora | Yes |
| /server/developer_manual/app/advanced/ | /server/latest/developer_manual/app/advanced/index.html | Antora | Yes |
| /server/developer_manual/app/tutorial/ | /server/latest/developer_manual/app/tutorial/index.html | Antora | No |
| /server/developer_manual/app/core/ | /server/latest/developer_manual/app/core/index.html | Antora | No |
| /server/developer_manual/app/general/ | /server/latest/developer_manual/app/general/index.html | Antora | No |
| /server/developer_manual/app/mobile_development/ | /server/latest/developer_manual/app/mobile_development/index.html | Antora | No |
| /server/developer_manual/app/mobile_development/android_library/ | /server/latest/developer_manual/app/mobile_development/android_library/index.html | Antora | No |
| /server/developer_manual/app/mobile_development/ios_library/ | /server/latest/developer_manual/app/mobile_development/ios_library/index.html | Antora | No |
| /server/developer_manual/app/bugracker/ | /server/latest/developer_manual/app/bugracker/index.html | Antora | No |
| /android_app/ | /android_app/android_app_app.html | Antora | No |
| /ios/ | /ios/ios_app.html | Antora | No |
| /desktop/latest/ | /desktop/introduction.html | Antora | No |
| /desktop/latest/advanced_usage.html | /desktop/advanced_usage/options.html | Antora | No |
| /desktop/latest/autoupdate.html | /desktop/automatic_updater.html | Antora | No |

## Missing Links

- https://doc.owncloud.org/server/latest/user_manual/pim/troubleshooting.html

## General TODO

- Rename "client" module to "desktop"
- Rename "administration_manual" module to "admin_manual"

**Comment by mmattel** [comment]
Info: I am just working on a lot of those issues...

**Comment by settermjd** [comment]
I just created two new issues for the module renames. I believe it will make, as the issues state, managing redirection and migration to the new documentation easier and smoother.

**Comment by settermjd** [comment]
I'm planning to sort these link issues, where possible, using Antora's redirect functionality.

**Comment by michaelstingl** [comment]
> I'm planning to sort these link issues, where possible, using Antora's redirect functionality.

@settermjd Where to configure redirects in Antora?

**Comment by tboerger** [comment]
The redirects are handled by the deployment which is part of our internal Gitea repository. Most of the mentioned redirects aren't required anymore since we named the administration_manual back to admin_manual.
