### ISSUE TITLE
Client autostart setting save location windows

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2322]
`Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`

This is where this setting is stored in windows for the windows desktop client. Maybe we should document this in the client docs.

Clarifying the reason behind this PR:

it may be helpful if users want to disable the autostart and having trouble with it.
For example if they already disabled the autostart in the windows task manager but the client keeps starting on windows start. Then users need to know where to find the autostart setting in the registry to disable it.

**Comment by settermjd** [comment]
Where should this be documented?

**Comment by voroyam** [comment]
Good question

**Comment by voroyam** [comment]
https://doc.owncloud.com/desktop/2.6/installing.html

**Comment by mschreml** [comment]
@voroyam are you ok with the suggestion to put the info here https://doc.owncloud.com/desktop/navigating.html#general-window ?

**Comment by voroyam** [comment]
I think here is better, since we already have some paths there

https://doc.owncloud.com/desktop/advanced_usage/configuration_file.html

**Comment by voroyam** [comment]
https://github.com/owncloud/client/pull/8480

**Comment by voroyam** [comment]
Closing. Client expert thinks this is not necessary.
