### ISSUE TITLE
installation/deployment_recommendations.adoc needs a update

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#2326]
## What Needs to be Documented?

`installation/deployment_recommendations.adoc` needs a update, see comments in https://github.com/owncloud/docs/pull/2321#pullrequestreview-361023746

## Why Should This Change Be Made? (Optional)
Scripts are out of date,
URL´s need to be changed to macro definition

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@JKawohl @enbrnz @settermjd

**Comment by enbrnz** [comment]
Please also change it to primary-secondary opposed to master-slave:
https://github.com/owncloud/docs/pull/2321#issuecomment-588287637
