### ISSUE TITLE
Cleanup merged branches

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#2327]
There are many branches which have been merged, which should be deleted as they are not used anymore.

Seems that a merge does not automatically delete a branch like it does in other repros.

@settermjd @tboerger

**Comment by tboerger** [comment]
The delete merged branches bot is already enabled, the mess seems to be older.

**Comment by mmattel** [comment]
This is bad. Can you take a look to make it run successully?

**Comment by phil-davis** [comment]
The bot is running correctly - as you merge a PR the branch gets deleted.
It does not cleanup old branches from before the time of the bot. That will need to be done manually.

**Comment by mmattel** [comment]
Thanks for the work @phil-davis 
Q: based on the example: `10.0-1c1e0a7-1205` This for me looks like an "orphand" branch too, and there are many of them. Guess this was a backport... How to handle these?

**Comment by phil-davis** [comment]
IMO there was the time when we were making backports to 10.0 10.1 10.2 and 10.3
Then we changed policy and backport doc fixes only to the "current" and "1 previous" doc version (10.3 and 10.4 at the moment)

So any branches that look like they were for 10.0 10.1 and 10.2 can be deleted.

**Comment by tboerger** [comment]
This only happens to repos which are not following the common way of using GitHub: create a fork, create your branch, create a PR from this fork branch, cleanup is up to you. At ownCloud nearly anybody is creating branches on the docs repo and nobody else knows if the branch is still required.

**Comment by phil-davis** [comment]
I suspect we have the same "problem" in core (and other repos). If people push a branch, then never get around to creating a PR and getting it merged, then the branch sits there forever "lost".

**Comment by settermjd** [comment]
Thanks for the effort so far, @phil-davis. There are [quite a number of stale branches](https://github.com/owncloud/docs/branches/stale?page=1), which I'd be willing to suggest could also be removed. I'm more than happy to do that.

**Comment by settermjd** [comment]
Closing as all stale branches have now been cleaned up.
