### ISSUE TITLE
"Edit this page" Documentation

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#2336]
With all the issues and discussions regarding _"Edit this page"_,
one thing we could do is to write a document about when to use this function.

As as starting point, this doc should (to be completed):
- be placed at the very beginning
- what you can / cant change in a branch and what you must change in master
- backporting
- ...

This highlights the issue of showing _"master"_ in the owncloud server list.

This would be a step to educate the writer about the impact of this procedure.
For sure, it does not prevent mistakes, but it would be a step in the right direction

@settermjd @phil-davis

**Comment by phil-davis** [comment]
We can encourage people to select "master" first, then edit the page.
But there might still be cases where the information is correct in master but wrong in a branch, so if we want corrections to come via "edit this page"  then we will need to leave the option possible from branches.
Whatever happens, there needs to be "someone" who is monitoring all merges to docs, and initiating the appropriate back/forward-ports, because we should not (and cannot) rely on the originator to sort that out.

**Comment by settermjd** [comment]
> We can encourage people to select "master" first, then edit the page.
> But there might still be cases where the information is correct in master but wrong in a branch, so if we want corrections to come via "edit this page" then we will need to leave the option possible from branches.

Absolutely. No matter what approach is put in place, there's always the potential for something to fall between the proverbial cracks. However, with the new branch merging requirements, I'd have thought that this would be very difficult.

> Whatever happens, there needs to be "someone" who is monitoring all merges to docs, and initiating the appropriate back/forward-ports, because we should not (and cannot) rely on the originator to sort that out.

That's been me for the longest time. The recent enforcement of merge requirements has made the job a lot easier and less error-prone.

**Comment by settermjd** [comment]
> With all the issues and discussions regarding _"Edit this page"_,
> one thing we could do is to write a document about when to use this function.
> 
> As as startingpoint, this doc should (to be completed):
> 
>     * be placed at the very beginning
> 
>     * what you can / cant change in a branch and what you must change in master
> 
>     * backporting
> 
>     * ...
> 
> 
> This highlights the issue of showing _"master"_ in the owncloud server list.
> 
> This would be a step to educate the writer about the impact of this procedure.
> For sure, it does not prevent mistakes, but it would be a step in the right direction
> 
> @settermjd @phil-davis

I agree. The challenge would then be getting the contributor to 1) know about the document and 2) to read and respect it. How do we do that, I'm not sure. I think I might need to ask in the Write the Docs community.

**Comment by voroyam** [comment]
I don't think that writing another guide is the way to go.

We already have many guides and no one reads them.

Working on the docs is work. People don't like work. Reading a guide how to work on the guide is work squared.

I think education the people who work on the docs is the way to go. So far the people who work on the docs on a daily basis already know, and new people will ask the senior people and get educated that way.

Thank you for the suggestion, but I don't think that something will happen in here, a year is enough time.
