### ISSUE TITLE
Cron missing in the warnings on the admin page

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2351]
https://doc.owncloud.com/server/admin_manual/configuration/server/security_setup_warnings.html

there is no cron chapter:

![image](https://user-images.githubusercontent.com/24212810/75389897-a8266680-58e7-11ea-9318-926b677c518c.png)

despite cron being included in this warnings.

**Comment by settermjd** [comment]
So, you want that warning added to the image in [the introduction](https://doc.owncloud.com/server/admin_manual/configuration/server/security_setup_warnings.html#introduction)?

**Comment by voroyam** [comment]
Yes. And a link to resolve the warning.

**Comment by mschreml** [comment]
@voroyam done
