### ISSUE TITLE
no example how to select cron

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2353]
although we recommend it.

https://doc.owncloud.com/server/10.4/admin_manual/configuration/server/occ_command.html#background-jobs-selector

**Comment by settermjd** [comment]
Can you more fully clarify what you mean?

**Comment by voroyam** [comment]
We recommend using corn as the background job. But in our docs we do not provide an example how to select corn as the background job on the occ page. In the example Ajax is used.

**Comment by settermjd** [comment]
@voroyam, 🌽?

**Comment by voroyam** [comment]
I was on vacation and did not have time yet to review everything.

But this PR is good. Thanks
