### ISSUE TITLE
remove ldap:update-group from occ commands

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2355]
This command has been removed

https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command.html

**Comment by voroyam** [comment]
one again I can't find the text because it's **once again** included and hidden somewhere.

@settermjd since you changed it - please make the change I suggest in this issue.

**Comment by settermjd** [comment]
What do you mean "hidden". It's readily available: https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command.html#ldap-integration.
