### ISSUE TITLE
Missing Redis server

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2356]
https://doc.owncloud.com/server/10.4/admin_manual/installation/deployment_recommendations.html#recommended-system-requirements-2

The description says redis server, but there is none on the picture

**Comment by settermjd** [comment]
Are you referring to the final bullet point in "Recommended System Requirements"?

**Comment by voroyam** [comment]
Yes. I think I already uploaded an updated picture

**Comment by settermjd** [comment]
From checking the available images, the image for that section does not include Redis. Can you add another one, please? Attaching to this issue is fine.

**Comment by voroyam** [comment]
Yes. Will do when I got more time.
