### ISSUE TITLE
Clarify supported env vs recommended envs

### ISSUE THREAD

**Issue by PVince81** [owncloud/docs#237]
See https://doc.owncloud.com/server/10.0/admin_manual/installation/system_requirements.html#officially-recommended-supported-options

The officially recommended table contains a lot of different environments, including Oracle.

In general we mostly recommend using some Ubuntu version (which one?) and MariaDB, and nothing else.

I suggest we split the table in a way that makes it more clear what the **recommended** setup is and list everything else under **supported**. This way we'd make it clearer what the actual recommeded setup is (we could even put docker at the very top...)

So it would look like:
- strongly recommended setup:
    - OS: Ubuntu 16.04 and 18.04
    - Database: MariaDB 10.1+
    - Web server: Apache 2.4 with prefork mpm and mod_php
    - PHP 7.1+
- support setup / reported working
    - OS: ...
    - Databases: Postgres, Oracle, Sqlite (not recommended for big systems)
    - PHP 5.6+
- not supported
    - OS: Freebsd (or "reported worked by the community but not officially supported")
    - php_fcgi
    - ...

@cdamken @voroyam @DeepDiver1975 @hodyroff thoughts?

**Comment by voroyam** [comment]
I agree. I suppose most of the users don't read the docs anyway, but at least we would have something to point to.

I am wondering about Debian, we say we support 6 and 7, but apparently there is already Debian 10 out there. Does anyone uses that?

**Comment by voroyam** [comment]
pr created.
