### ISSUE TITLE
Activity app - Add a config option to send notifications ASAP

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/docs#2388]
We need to document new setting and the new occ command.
https://github.com/owncloud/activity/pull/833

**Comment by HanaGemela** [comment]
I've got some feedback on the documentation that it is not clear enough

`occ system:cron` is the command that allows to send notifications ASAP. But It is not a new command and also hasn't the same purpose than `occ activity:send-emails` that flushes the entire queue

@davitol please help if needed

**Comment by settermjd** [comment]
Unless I'm mistaken, `activity:send-emails` was the command to send all pending activity emails asap and `system:cron` executes background jobs as Cron.

**Comment by mmattel** [comment]
> ...executes background jobs as Cron

Which is never asasp in terms of immediate as it is dependent on how cron is setup and usually you have 15min cycles....

**Comment by davitol** [comment]
@VicDeo probably is the Guru than can clarify us if everything is OK documented, which command should we use with ASAP option etc

**Comment by VicDeo** [comment]
ASAP stands 'as soon as possible' and it's not the same with 'immediately' 

1.  `occ activity:send-emails` sends all pending activity notifications **immediately** regardless the time they are scheduled.

2.  `ASAP` is a per-user setting, so all notifications are added to the queue with no time lag  for this user. But the queue itself is still being processed by cron.

**Comment by settermjd** [comment]
> I've got some feedback on the documentation that it is not clear enough

@HanaGemela, can you clarify, specifically, how it is not clear enough?

**Comment by HanaGemela** [comment]
@davitol please check the documentation if it is precise enough

**Comment by davitol** [comment]
> @davitol please check the documentation if it is precise enough

The OP says:


> We need to document new setting and the new occ command.


But ASAP is not done with a new command. Everything to be documented is this post:

 https://github.com/owncloud/docs/issues/2388#issuecomment-598080577

That's everything that should be documented IMHO.

**Comment by settermjd** [comment]
> > @davitol please check the documentation if it is precise enough
> 
> The OP says:
> 
> > We need to document new setting and the new occ command.
> 
> But ASAP is not done with a new command. Everything to be documented is this post:
> 
> [#2388 (comment)](https://github.com/owncloud/docs/issues/2388#issuecomment-598080577)
> 
> That's everything that should be documented IMHO.

Thanks for the feedback, @davitol. Will make all relevant changes.

**Comment by settermjd** [comment]
@HanaGemela, were you referring to the changes in https://github.com/owncloud/docs/pull/2393/files, which have already been merged and backported? If so, this issue should be able to be closed.

**Comment by HanaGemela** [comment]
@davitol are you happy with closing this issue?

**Comment by davitol** [comment]
Yes, @settermjd is right IMHO. Let's close the ticket

> @HanaGemela, were you referring to the changes in https://github.com/owncloud/docs/pull/2393/files, which have already been merged and backported? If so, this issue should be able to be closed.
