### ISSUE TITLE
Possible orphaned branches

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#2391]
It seems that there are still possible orphaned branches.
- `10.3-95c4202-2179`
This should become a backport for merged PR #2179 but never made it to be a PR.
I propose deleting this branch and resetup a BP to 10.3 (and 10.4?)
- `10.3-00282f6-1999` same as above but for merged PR #1999
- `10.4-80e5658-2344` same as above but for merged PR #2344, BP only to 10.4
- `pmaier1-patch-3` I also doubt that all 4 pmaier branches are still valid as no PR is currently opened by pmaier.

@settermjd

**Comment by settermjd** [comment]
Thanks for spotting these, @mmattel.

**Comment by mmattel** [comment]
@settermjd any update on this?
atm, it is a good point in time to fix this as we have only very view (8) open PR´s.

**Comment by settermjd** [comment]
Well said.

**Comment by settermjd** [comment]
[The changes in 10.3-95c4202-2179](https://github.com/owncloud/docs/pull/2346/files) are already available in 10.4. However, the change is only for 10.4, as this issue shows: https://github.com/owncloud/core/issues/33187.

**Comment by settermjd** [comment]
Done!
