### ISSUE TITLE
Missing user pages screenshot

### ISSUE THREAD

**Issue by Akidxx** [owncloud/docs#2398]
https://doc.owncloud.com/server/admin_manual/configuration/user/user_auth_ldap.html#syncing-users

![image](https://user-images.githubusercontent.com/15052479/75998553-46768580-5f01-11ea-9273-a882afddc43b.png)

After synchronysing my users to the owncloud server I was not able to check them fastly because it's not clear from the documentation how to access the user page.

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/2399

**Comment by voroyam** [comment]
Pr.
