### ISSUE TITLE
click on admin-manual -> installation -> installation-options shows nothing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#2403]
the rendered web view at doc.owncloud.com of the admin manual has a navigation on the left side.
Clicking on a navigation entry usually shows the entry, and if it has sub-entries unfolds the tree so that sub entries can be seen.
This does not work for installation-options. It does not reveal its subsections, and shows only a useless one liner saying
"In this section, you will find all the information you need for installing ownCloud."
![image](https://user-images.githubusercontent.com/1108546/76035329-7fcee580-5f41-11ea-8be7-a0fa6180a5bc.png)
Nothing is shown.

Expected behaviour, the subentries should be exposed: docker, manual, linux packages etc.

**Comment by settermjd** [comment]
Thanks for creating this. I'll work through it early next week.

**Comment by settermjd** [comment]
> the rendered web view at doc.owncloud.com of the admin manual has a navigation on the left side.
> Clicking on a navigation entry usually shows the entry, and if it has sub-entries unfolds the tree so that sub entries can be seen.
> This does not work for installation-options. It does not reveal its subsections, and shows only a useless one liner saying
> "In this section, you will find all the information you need for installing ownCloud."
> ![image](https://user-images.githubusercontent.com/1108546/76035329-7fcee580-5f41-11ea-8be7-a0fa6180a5bc.png)
> Nothing is shown.
> 
> Expected behaviour, the subentries should be exposed: docker, manual, linux packages etc.

That page, and a number of similar ones, were added in the documentation because the decision was made some time back that every option in the navigation needed to be clickable, and I believe that that was only possible if the element was linked to a page.

**Comment by settermjd** [comment]
> https://github.com/owncloud/docs/blame/master/modules/admin_manual/nav.adoc#L12
> refers to its parent "Installation" via `xref:installation/index.adoc` -- this cannot be correct, can it?

Perhaps it's changed since you created this issue, but are you referring to `**** xref:installation/docker/index.adoc[Installing With Docker]`?

**Comment by settermjd** [comment]
ping @jnweiger.

**Comment by jnweiger** [comment]
Clicking on the little triangle left of `Installation Options` exposes the enties below.
Clicking on the text `Installation Options` does not expose the entries.

Afaik this is till the case.
It is not important. It is a small inconsistency, but we can still navigate the tree nicely, using the triangles.
I cannot easily tell, which xref I am actually referring to. I did not inspect the source. Sorry.

**Comment by voroyam** [comment]
workaround - I wrote a couple of links to click:

![image](https://user-images.githubusercontent.com/24212810/110403611-b02df000-807d-11eb-804a-6c655c2c18f7.png)

**Comment by voroyam** [comment]
closed with no explanation or link to the PR that fixed the issue? classy.

**Comment by mmattel** [comment]
@voroyam 
you have forgotten to reference your own PR, doing it for you now:
https://github.com/owncloud/docs/pull/2826 (Update index.adoc)

**Comment by voroyam** [comment]
I wasn't the one who closed the issue. Closing issue should always be done by referencing the PR which solved the issue. At least this is how it has been done in the past. I don't know what process or practice you are using now.
