### ISSUE TITLE
linux installation instructions are self-contradicting

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#2404]
* [ ] https://doc.owncloud.com/server/admin_manual/installation/deployment_recommendations.html#general-recommendations recommends has three scenarios only recommending RHEL and SLES,
**but** we give details only for Ubuntu 18.04 in https://doc.owncloud.com/server/admin_manual/installation/manual_installation.html#install-the-required-packages and have a dedicated examples setion also only on https://doc.owncloud.com/server/admin_manual/installation/ubuntu_18_04.html

* [x] https://doc.owncloud.com/server/admin_manual/installation/manual_installation.html#install-the-required-packages mentions "many people use automatic updates",
**but** https://doc.owncloud.com/server/admin_manual/installation/linux_installation.html#avoid-automatic-upgrades strongly suggests to avoid automatic updates.

* [x] https://doc.owncloud.com/server/admin_manual/installation/ubuntu_18_04.html claims to be "an ultra-short guide",
**but** with a total of 28 commands and 4 script files it is obviously quite comrehensive.

**Comment by jnweiger** [comment]
An ultra-short install instruction for Ubuntu 18.04 in less than 10 commands:

As root user do:
```
curl https://download.owncloud.org/download/repositories/production/Ubuntu_18.04/Release.key  | apt-key add -
echo 'deb http://download.owncloud.org/download/repositories/production/Ubuntu_18.04/ /' > /etc/apt/sources.list.d/owncloud-files.list
apt update
apt install owncloud-files libapache2-mod-php php-bz2 php-mysql php-curl php-gd php-imagick php-intl php-mbstring php-xml php-zip
cp /usr/share/doc/owncloud-files/owncloud-config-apache.conf.default /etc/apache2/conf-available/owncloud-config-apache.conf
a2enconf owncloud-config-apache
a2enmod php7.2
systemctl reload apache2
```

As normal user do:
```
firefox http://localhost/owncloud
```

**Comment by settermjd** [comment]
Thanks for creating the PR, @jnweiger.

**Comment by voroyam** [comment]
> https://doc.owncloud.com/server/admin_manual/installation/ubuntu_18_04.html claims to be "an ultra-short guide",
> but with a total of 28 commands and 4 script files it is obviously quite comprehensive

The term was not given by me. It is however „ultra short“ if you compare it to the manual installation guide or the one from @mmattel 

Furthermore we recommend manual installation, that’s why the example installation guide is longer. 

Plus - I wanted it to be copy/paste-able, to avoid errors from user entry.

**Comment by mmattel** [comment]
Let´s differenciate things a bit.
A condensed set of commands installing packages does not make a working installation.
A guide on the other hand side has beside the set of commands also a description of how using the installed applications to make things working together.
You may argue, and this is a valid point, people should know how to use it. But making a software successful also means to lower the hurdles and challenges and increase satifaction. This includes tips to solve issues from real world scenarious people are facing when using the software.

So you have the choice either making a very brief command set or making a guide.

I am writing this because I am mentioned and I have a lot of experience in that topic.

**Comment by settermjd** [comment]
@jnweiger, regarding your first point, this seems like a bit of a challenging situation. The official position for examples in the documentation is that they are to only be for Ubuntu. However, if there are official recommendations, in certain situations, for other distributions, then it makes sense to me that there should be examples for those distributions. 

Regarding the second point, I agree that the wording in both sections does come across as contradictory. After reading https://doc.owncloud.com/server/admin_manual/installation/manual_installation.html#install-the-required-packages a few times, it seems that "_, as many people use automatic updates._" could be removed; making the two pages positions consistent with each other.

Regarding point 3, given the length and depth of the guide, I suggest changing the initial sentence in the preamble to the following:

> This guide shows how to install ownCloud on a fresh installation of Ubuntu 18.04.

**Comment by jnweiger** [comment]
@settermjd  the above looks good to me. Thanks. Go ahead!

Let's discuss adding more examples later. It is certainly a strange position to avoid examples here for the platforms that we recommend elsewhere.

**Comment by settermjd** [comment]
> @settermjd the above looks good to me. Thanks. Go ahead!
> 
> Let's discuss adding more examples later. It is certainly a strange position to avoid examples here for the platforms that we recommend elsewhere.

I appreciate that the support team is trying to make the documentation simpler to maintain and for users as well. However, in this specific use case, it makes sense to break from that new continuity and have examples.

**Comment by voroyam** [comment]
> to break from that new continuity

a broken continuity is no continuity.
