### ISSUE TITLE
Improvements for OIDC docs

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#2424]
- What is the role of OIDC in ownCloud? Which purpose does it serve?
- Marketplace link
- Example configuration for the different components e.g., with Konnect?
- How to migrate from OAuth2 to OIDC?
- How to authenticate local users via OIDC?
- Which client versions support OIDC?
- What configuration do clients require?
- Replace flow sequence diagram with one that suits OIDC or remove it

**Comment by voroyam** [comment]
@pmaier1 please check https://doc.owncloud.com/server/admin_manual/configuration/user/oidc/

I think some of the things you asked for were implemented but no PR was linked back to here.

Is there still something missing?

If yes - please provide the information 
If no -please close this issue.
