### ISSUE TITLE
LDAP: Easier tls

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/docs#2425]
Please document changes in https://github.com/owncloud/user_ldap/pull/512

**Comment by settermjd** [comment]
Thanks for creating this, @HanaGemela. What is the priority for completing this?

**Comment by HanaGemela** [comment]
Ldap release has a priority P3 and you can see it in https://github.com/orgs/owncloud/projects/20
Currently the app is waiting for QA and the documentation has to be done before the app goes live

**Comment by settermjd** [comment]
> Ldap release has a priority P3 and you can see it in https://github.com/orgs/owncloud/projects/20
> Currently the app is waiting for QA and the documentation has to be done before the app goes live

Okay. Thank you.
