### ISSUE TITLE
Admin manual: "What's New" is old -- drop?

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#2437]
The website https://doc.owncloud.com/server/10.4/admin_manual/whats_new_admin.html has only one poor reference to what was new in 10.0 -- it seems no updates were added since then.

This website is referenced from README files in the customer portal and elsewhere.
It is mentioned in addition to the Release Notes at https://doc.owncloud.com/server/10.4/admin_manual/release_notes.html

Suggestion:
* Drop this, as all relevant info should be highlighted in the Release Notes and detailled in the changelog.
* Remove all known references from READMEs and elsewhere.
* Redirect https://doc.owncloud.com/server/10.4/admin_manual/whats_new_admin.html to the changelog, in case we don't catch all references.

@frankaellen Marketing team, do you have references to https://doc.owncloud.com/server/10.4/admin_manual/whats_new_admin.html ?

**Comment by settermjd** [comment]
This makes perfect sense to me. The release notes are very thorough as @pmaier1 puts a lot of effort into them. @pmaier1, unless you have an objection, I'll add this issue to the queue.

**Comment by pmaier1** [comment]
Yep, I agree. Thanks!
