### ISSUE TITLE
master and 10.4 branches still have references to PHP 7.0

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs#2441]
## What Needs to be Documented?
"random" references to PHP 7.0 need to be removed from current documentation in master and 10.4 branches so that they do not cause confusion.

## Where Does This Need To Be Documented?
See PR #2442 which proposes a couple of "easy" changes.

`modules/developer_manual/pages/testing/unit_testing.adoc` - the whole section about unit testing of ownCloud versions <10 could be removed?

`modules/developer_manual/examples` has various `.travis.yml` that mention PHP 5.5 5.6 7.0
Actually we do not use Travis any more, so the whole context of those examples could be reviewed (rather than just trying to update the examples with newer PHP versions that might or might not work)

`modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc` - talks about PHP 5.6 and 7.0, needs to talk about currently-supported PHP versions.

`modules/admin_manual/pages/configuration/server/caching_configuration.adoc` - talks about PHP 5.6 and 7.0, needs to talk about currently-supported PHP versions.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
Thanks for raising this, @phil-davis. I'll get them fixed up.
