### ISSUE TITLE
local docs ui-bundle.zip for testing purposes

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#245]
## What Type Of Content Change Is This?

- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [x] General

## What Needs to be Documented?

There should be the possibility of having a local docs ui-bundle.zip (preferred in the root of docs) for  testing purpopses. Useful when you test unmerged changes made in docs-ui if they compile in the documentation properly. Changes made on this file should be gitignored.

## Why Should This Change Be Made?

Testing purposes, else any file copy will show up as commitable change.

@settermjd

**Comment by tboerger** [comment]
The ui bundle repo got already an preview feature where you can see the behavior with dummy content. Why do you need that as part of this repo?

**Comment by settermjd** [comment]
Well said, @tboerger. Running `gulp preview` will generate a preview version of the site that demos what it will look like.

**Comment by mmattel** [comment]
See my comment at https://github.com/owncloud/docs-ui/pull/12#issuecomment-439938783

**Comment by voroyam** [comment]
@mmattel is this still relevant?

**Comment by settermjd** [comment]
I don't see this as relevant as, while it involves a little bit of manual effort, this is already available locally. Here's how:

1. Clone [the docs-ui repo](https://github.com/owncloud/docs-ui) and build the ui-bundle.zip by using `gulp pack`.
2. In the local copy of the docs repo, build the docs, overriding the remote ui-bundle.zip file with the one that has just been built, by running `yarn antora --ui-bundle-url ../docs-ui/build/ui-bundle.zip`.

Sure, it's a little bit of effort, but it does what's required. 

Closing.
