### ISSUE TITLE
WOPI: Document Chrome Document Locking

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2469]
We found out that when you use chrome and edit a document via ownCloud in Office Online - the lock is not released with the closing of the document, but after the 30 min time out or a manual release.

This needs to be documented.

Probably after this part:

https://doc.owncloud.com/server/admin_manual/enterprise/collaboration/msoffice-wopi-integration.html#lock-timeout

Maybe as "Known Issues"

**Comment by voroyam** [comment]
background: https://github.com/owncloud/docs/pull/2459#issuecomment-600119419

**Comment by settermjd** [comment]
Thanks, @voroyam. I'll get the relevant docs updated.

**Comment by settermjd** [comment]
I'm guessing it does, but I need to check and be sure; does this issue apply to both Google Chrome and Chromium?

**Comment by voroyam** [comment]
From my pov it would make sense to write both. But as far as I know it was only tested with chrome.
