### ISSUE TITLE
Possible incorrect description for occ files:transfer-ownership

### ISSUE THREAD

**Issue by thommierother** [owncloud/docs#2484]
I am struggling  with the transfer of ownership for data from a subdirectory of one user to another in OC 10.4.

The documentation at https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command.html#file-operations says:

`sudo -u www-data php occ files:transfer-ownership --path="folder/to/move" <source-user> <destination-user>
`
And for the --path option:

```
["user_id/files/path"
"user_id/files/mount_name"
"user_id/files/mount_name/path"
```

When testing on 10.4 I get:

```
root@www:/var/www/owncloud# sudo -u www-data php occ files:transfer-ownership --path="thommie4/files/gruenerheiner" thommie4 gruenerheiner
Unknown path provided: thommie4/files/gruenerheiner
root@www:/var/www/owncloud# sudo -u www-data php occ files:transfer-ownership --path=thommie4/files/gruenerheiner thommie4 gruenerheiner
Unknown path provided: thommie4/files/gruenerheiner
root@www:/var/www/owncloud# sudo -u www-data php occ files:transfer-ownership --path="/thommie4/gruenerheiner" thommie4 gruenerheinerUnknown path provided: thommie4/gruenerheiner
```
What finally works is the following:

`sudo -u www-data php occ files:transfer-ownership --path="gruenerheiner" thommie4 gruenerheiner`

Do we have documentation or a code error?

**Comment by settermjd** [comment]
Thanks for raising this, @thommierother. I'll investigate and find out.

**Comment by settermjd** [comment]
I had a read through the documentation and don't see any reference to an array of paths. Can you show me where you saw that please, @thommierother?

**Comment by thommierother** [comment]
The --path Option
https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command.html#file-operations

> When using the --path option, the path must be in one of the following formats:
> 
> "user_id/files/path"
> "user_id/files/mount_name"
> "user_id/files/mount_name/path"
> 
>

**Comment by settermjd** [comment]
Ah, I see. That section isn't meant to suggest that you can use all of them. They are examples of what you could use. I'll have think through how I can remove any ambiguity.

**Comment by settermjd** [comment]
Got it. I'll change the source block to a bullet list instead. The change will be in a PR later today.
