### ISSUE TITLE
OAuth2 app configuration in ownCloud Server is needed

### ISSUE THREAD

**Issue by cdamken** [owncloud/docs#2491]
Seeing some issues: 
https://github.com/owncloud/docs/issues/1882
https://github.com/owncloud/android/issues/2685

to use correctly the OAuth you need some prerequisites:
Redis Server and php-redis newer than 4.2 
add this configuration in the php.ini:

```
- SESSION_SAVE_HANDLER=redis
- SESSION_SAVE_PATH=tcp://[REDIS SERVER]:6397
- REDIS_SESSION_LOCKING_ENABLED=1
- REDIS_SESSION_LOCK_RETRIES=750
- REDIS_SESSION_LOCK_WAIT_TIME=20000
```
@jvillafanez  Any other recommendation?

@settermjd Please document it, many users have this problem in the client because the server is not properly configured.

**Comment by settermjd** [comment]
Shall do, @cdamken.

**Comment by cdamken** [comment]
Thanks a lot!

**Comment by jvillafanez** [comment]
As far as I know, oAuth doesn't require redis. You should be able to use the default file handler for the sessions normally.
If you choose to use redis to store sessions, you'll need to ensure that session locking is active is redis.

**Comment by cdamken** [comment]
It means that there are 2 methods

With 
```
- SESSION_SAVE_HANDLER=files
```
The server takes care of the session.
@jvillafanez : 
Does it work with Multi-server?
And if works: Should be sticky sessions in the load balancer?

Which is the most recommended?

**Comment by settermjd** [comment]
Thanks for the further feedback, @cdamken & @jvillafanez.

**Comment by jvillafanez** [comment]
> Does it work with Multi-server?
And if works: Should be sticky sessions in the load balancer?

I can't say for sure, but I guess it depends on the overall setup.
If sessions are stored in the local server, you'll need sticky sessions in the load balancer in order to ensure all the requests goes to the same server.
On the other hand, you might store the session in a NFS folder shared among all the servers. This might work without sticky sessions.

In any case, for multi-server I think it makes more sense to use redis. It feels a more generic solution.

**Comment by cdamken** [comment]
@jvillafanez Some users are asking why should we use these values:
```
- REDIS_SESSION_LOCKING_ENABLED=1
- REDIS_SESSION_LOCK_RETRIES=750
- REDIS_SESSION_LOCK_WAIT_TIME=20000
```
Is there any special reason? How can they tune it?

**Comment by jvillafanez** [comment]
Parameters are taken from the available ones in the library (https://github.com/phpredis/phpredis/blob/develop/README.markdown#session-locking)
The default ones are claimed (in one of the issues of the phpredis repo) to be very small for common usage, and those were the "new" suggested ones. Users can adjust to whatever value they want

**Comment by settermjd** [comment]
> Parameters are taken from the available ones in the library (https://github.com/phpredis/phpredis/blob/develop/README.markdown#session-locking)
> The default ones are claimed (in one of the issues of the phpredis repo) to be very small for common usage, and those were the "new" suggested ones. Users can adjust to whatever value they want

Do you have a link to the issue, as I've not been able to find it. I used the following search: https://github.com/phpredis/phpredis/issues?q=is%3Aissue+is%3Aopen+lock.

**Comment by jvillafanez** [comment]
https://github.com/phpredis/phpredis/issues/1267#issuecomment-355454252

**Comment by settermjd** [comment]
> [phpredis/phpredis#1267 (comment)](https://github.com/phpredis/phpredis/issues/1267#issuecomment-355454252)

Added to the PR in bf0bcbf330983867fdddc39cd17a1fce937cd676.
