### ISSUE TITLE
[Admin Manual] fix broken link to sync-exclude.lst

### ISSUE THREAD

**Issue by Marmo** [owncloud/docs#2496]
## What Needs to be Documented?

Fix link to sync-exclude.lst, should be https://github.com/owncloud/client/blob/master/sync-exclude.lst

## Where Does This Need To Be Documented?

https://doc.owncloud.org/server/10.4/admin_manual/faq/#platform-wide-known-limitations-excluded-files

## Why Should This Change Be Made? (Optional)

Link broken

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
Thanks for raising this, @Marmo

**Comment by mmattel** [comment]
Closing?

**Comment by settermjd** [comment]
> Closing?

Agreed
