### ISSUE TITLE
knowledgebaseenabled parameter description

### ISSUE THREAD

**Issue by mrlinux1** [owncloud/docs#250]
https://doc.owncloud.org/server/10.0/admin_manual/configuration/server/knowledgebase_configuration.html

This option seems to work only for community edition. And it seems to be a legacy thing.

Then there is a problem to write " you have to use it to disable ..." 
but showing "knowledgebaseenabled" => true.

And please change "knowledgebaseenabled" to 'knowledgebaseenabled'.

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1536

legacy content removed.
