### ISSUE TITLE
can't share folders after upgrade to 10.4.0.4

### ISSUE THREAD

**Issue by soniqsoft** [owncloud/docs#2505]
Hi support Team,
URGENT CASE!
I'm owncloud user and admin for some time and recently I did upgrade to 10.4.0.4.
Upgrade was smooth and easy but... 
AFTER UPGRADE I CAN'T SHARE ANY FOLDER TO ANY USER UNLESS I SET EXPIRATION DATE LESS THAN 7 DAYS FROM TODAY!
ANY LONGER DATE OR MISSING DATE CAUSES ERROR "The expiration date cannot exceed 7 days!".
WHATS ALSO STRANGE - ALL EXPIRATION DATES FOR EVERY USER AND SHARED FOLDER ARE NULL!
I tried to switch on and off several times the option "Set default expiration date for user shares" and Expire after 365 days and "Enforce as maximum expiration date" but no result!
Help me pls as nobody can share any folder to anybody at all!
Thanks!

## What Needs to be Documented?

All users need to be able to share the folders again!

## Why Should This Change Be Made? (Optional)

This is just crucial functionality!

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ X] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ X] Admin Manual
- [ ] Developer Manual
- [ X] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ X] Desktop Client
- [ ] Other

**Comment by michaelstingl** [comment]
@soniqsoft this is the issue tracker for the ownCloud documentation, not a help forum. Please use https://central.owncloud.org/ instead.

**Comment by soniqsoft** [comment]
Unfortunately does not work right now - displays empty page. But thank you for info.

**Comment by phil-davis** [comment]
https://github.com/owncloud/password_policy/issues/287
Are you using Password Policy. If so, it could be this issue.
Workaround: do not use the "public link expiration policies" in the password policy app for now (fix is coming)
