### ISSUE TITLE
Password special charakters

### ISSUE THREAD

**Issue by meisterleise** [owncloud/docs#251]
I’m surprised there’s no question about it yet:
Which special characters can be used for entering passwords? Where can I find more information?
So far I have found out that the following characters do not work:

Space
Underscore _

Surely there are many more…?

**Comment by phil-davis** [comment]
I raised an issue in core to make acceptance tests that verify various valid and invalid passwords.
Underscore works in a password set using the Provisioning API - I will find out in due course if it works in the webUI...

Only space(s) is invalid. Anyone with ideas about what else might be invalid, feel free to comment.

**Comment by michaelstingl** [comment]
> Which special characters can be used for entering passwords?

Web UI or any of the clients? (Android bug with "§" in passwords: https://github.com/owncloud/android/issues/2451)

**Comment by voroyam** [comment]
Apparently there are no limitations on the passwords, spaces and § were fixed in prior PRs.

Closing.

**Comment by phil-davis** [comment]
Note: you cannot set your password to:
- just 1 or more space characters
- the single character "0"
In both cases the webUI complains "password cannot be empty"

Probably these are OK - production users setting their password like that is not at all secure anyway.

**Comment by voroyam** [comment]
> * just 1 or more space characters

So like "space space space space"? If it's just the space characters then it does not work?

**Comment by phil-davis** [comment]
> > * just 1 or more space characters
> 
> So like "space space space space"? If it's just the space characters then it does not work?

Correct. It might be just something in the front-end JavaScript that  still thinks the "new password" field is still empty, and so it never even sends it to the backend.

Anyway, maybe a user should not be able to set their password to "space space space space"

**Comment by voroyam** [comment]
ehm, I just created a new user via WebUI with the password "0".

**Comment by phil-davis** [comment]
Yes, you can do that.
In Personal General Settings you cannot change your own password to `0`
Probably in some places (provisioning API, user management add/edit user, reset password from email link...) `0` works and in some it does not - it depends if the validation code in each front-to-back-end code path is good, or if it accidentally rejects `0`

**Comment by voroyam** [comment]
we just tested it, and you can create a user with the password 0spacespacespace but you can not login with this user

**Comment by phil-davis** [comment]
I just created a user with password `0   ` using the user management webUI page. I could login OK.
Maybe you are using the provisioning API or? to create the user.

Likely we need tests for all ways of creating/changing passwords that have test cases with space at the front and end of the password. (There are already tests with space in the middle of the password). I suspect that various code paths might trim spaces front and back, so we should find those.

**Comment by voroyam** [comment]
we set in in the occ.

**Comment by phil-davis** [comment]
When entering a password interactively from `php occ user:resetpassword`  any spaces at front and back are being stripped.

To make it work with leading/trailing spaces, I had to:
```
OC_PASS="  3"  php occ user:resetpassword phil --password-from-env
```

And the `occ` command also complains `Password cannot be empty` if you put just `0` as the password (with or without spaces).
```
OC_PASS="  0  "  php occ user:resetpassword phil --password-from-env

In User.php line 294:
                            
  Password cannot be empty  
                            

user:resetpassword [--password-from-env] [--send-email] [--output-link] [--] <user>
```

**Comment by voroyam** [comment]
So 0 is a special character?

**Comment by phil-davis** [comment]
> So 0 is a special character?

A special test for `0` was added here: https://github.com/owncloud/core/pull/32261/files#diff-a347192ed164de0ed89af460b1860e0bR666
PR #32261

That can easily be removed, and then ordinary `0` works as a password.

Using space at the beginning or end of (or as the only characters in) a password, and entering it interactively to the `occ` command is more complex. Because the Symfony Console system in Symfony 3.4.* automatically trims whitespace from the front and back of whatever you type. For Symfony 4.4 they just added the ability to make that trimming optional - https://github.com/symfony/symfony/pull/31626 - so "fixing" that requires upstream Symfony stuff.
