### ISSUE TITLE
Lists of PHP extensions are different in 2 docs

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs#2513]
The lists of PHP extensions are different in:
https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/installation/ubuntu_18_04.adoc
https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc

Only in server_prep_ubuntu_18.04 list:
php-bcmath
php-bz2
php-gettext
php-gmp
php-igbinary
php-seclib
(6 items)

Only in ubuntu_18_04 list:
php-common
php-json
php-xml
(3 items)

In both:
php-apcu
php-curl
php-imagick
php-gd
php-imap
php-intl
php-mbstring
php-mysql
php-redis
php-ssh2
php-zip
(11 items)

Optional in ubuntu_18_04 list:
php-smbclient
php-ldap

Sort out why, and get the lists correct and consistent.

**Comment by phil-davis** [comment]
And what is the different purpose of these 2 docs? As an admin, which document do I want to read?

**Comment by settermjd** [comment]
I'll have a look and get the corrections made.

**Comment by settermjd** [comment]
The most recently created file is https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/installation/ubuntu_18_04.adoc. From what I remember, @voroyam created it to be a comprehensive guide to installing ownCloud on Ubuntu. Given that, it would make sense to me to remove https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc (after merging any relevant information from it). Thoughts?

**Comment by phil-davis** [comment]
I don't really have time to look through the detail of what is in each document and think why.

@voroyam over to you for your opinion.

**Comment by mmattel** [comment]
The stack of documents has grown over the time and I agree that the manual installation documents could be harmonized for a more streamlined finding/reading/doing.
The Ubuntu server prep document has been created to much shorten the over all installation document and to ease future ubuntu specialities. It also contains very helpful real life content for a successful ownCloud installation. Additionally, it was some work to gather all the modules for php, just thinking of encryption, oidc ect. It is not wise just say "let´s incorporate the stuff in the referencing original" which would counteract the idea and you would usually lose content by shortening. As written in the originating PR, it does not matter adding more php modules during installation, if not used there is no harm. But always looking and maintaining php libraries to be included when using a particular ownCloud function is imho nonsense. It is much easier to say, "please see the Ubuntu server prep documentation for php and other prerequisites". Then you can match your situation vs the required one.

**Comment by settermjd** [comment]
@mmattel, I see what you're saying, however, if by having multiple documents, it becomes confusing to the reader as to which one is the correct one to follow, then the documentation runs the risk of becoming a problem not a solution. Secondly, I disagree with "_It is not wise just say "let´s incorporate the stuff in the referencing original" which would counteract the idea and you would usually lose content by shortening._". By carefully merging the two documents, then the user has one document to follow which contains all of the relevant information.

**Comment by mmattel** [comment]
IMHO, for a manual installation you need a master doc with subsections / subpages containing a overview, sizing thoughts, general OS (server preparation), oC preparation/installation, upgrade notes. If you put all that into a single document, you very quickly lose overview. Shortening content based on - admins should know that - is always critical. Success depends on covering real life topics.

The real point imho is, the structue is a mess. We first have to discuss what does the install doc wants to achive, then the structure, then the topics, then the content. Not the other way round.

**Comment by voroyam** [comment]
@phil-davis the document written by me and the support team was written to ensure a customer or a user has a straight forward guide from zero to a complete ownCloud installation. If packages are missing - they are apparently not vital. We got no complaints so far.

@mmattel has written a more detailed guide.

The discrepancy comes from no communications between the authors.

IMHO - as long as my guide works I have no problems with it. My guide was written by the support team and myself, tested by the support team, myself, and customers.

**Comment by phil-davis** [comment]
In current master there are:
https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc

and similar double-documents for Ubuntu 20.04

As asked above: what is the different purpose of these 2 docs? As an admin, which document do I want to read?

I really don't have the time to compare the documents... And having this "almost duplication" causes confusion.

**Comment by mmattel** [comment]
@phil-davis The difference is about, that the quick guide adresses admins with limited knowledge and a more standard environment while the detailed guide adresses admins with deeper knowledge, special and/or customizable environments or requirements. This difference is described in the manual installation overview document and the reader can clearly decide the path to go. There is no and cant be, a "one fits all" and it is good to have them both being complementary.

**Comment by phil-davis** [comment]
The relevant docs are now:
Ubuntu 18.04:
https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc

Ubuntu 20.04:
https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc

**Comment by phil-davis** [comment]
PR #4515 is probably enough to close this.
