### ISSUE TITLE
User creation UI changes

### ISSUE THREAD

**Issue by sharidas** [owncloud/docs#252]
For the release 10.0.10 we have made changes to the users page or the user_management app. Prior to 10.0.10 release the user can be created from the users page using username and password. Now it has been changed to Username and Email address. So by default when user opens the users page, user would see Username and Email text box to fill in order to create the user.

![default-mail](https://user-images.githubusercontent.com/3600427/44990505-d5be7800-afae-11e8-9eb7-5e4869cced0a.gif)

User still have the option to get the Username and Password option back. This can be achieved by clicking the global settings icon available at the bottom left of the page. 

![change-to-passwd](https://user-images.githubusercontent.com/3600427/44990683-6d23cb00-afaf-11e8-8dfb-ff3880afbfc1.gif)

When user is created using Username and Email address, an email will be sent to the email address specified. The user will have to click the link shared in the email. Once the link is clicked,  and the token associated with the link is not expired, the user is expected to land in a page where a password is required to be set for the user. 

![password-set-login](https://user-images.githubusercontent.com/3600427/44991744-b295c780-afb2-11e8-9137-8758e5af6e08.gif)

If the token is expired the user is expected to land in a resend activation link page, where a button will be available which when clicked the user will get a new email with an updated link.

![resend-link](https://user-images.githubusercontent.com/3600427/44992034-bb3acd80-afb3-11e8-906c-f6a87d0ed763.gif)

**Comment by voroyam** [comment]
New/Updated Pictures
https://github.com/owncloud/docs/pull/1540

**Comment by voroyam** [comment]
page rework:

https://github.com/owncloud/docs/pull/1543
