### ISSUE TITLE
Document sharing.federation.allowHttpFallback config option

### ISSUE THREAD

**Issue by davitol** [owncloud/docs#2529]
`sharing.federation.allowHttpFallback` config option, allows to create federated shares. It helps local testing for federated sharing.

Would be good to have it documented in Developer documentation.

@mrow4a Please add the info need that you consider worthy in this ticket and help @settermjd with this stuff

https://github.com/owncloud/core/pull/37153

**Comment by mrow4a** [comment]
@davitol @settermjd it appears to be already documented in https://doc.owncloud.com/server/admin_manual/configuration/files/federated_cloud_sharing_configuration.html

**Comment by mrow4a** [comment]
Reopening, as I in fact noticed in dev documentation it could be more clear to explicitly mention that for development http should be enabled, and to refer to configuration page for more info. If you think it is clear enough please close.

**Comment by settermjd** [comment]
Thanks, @mrow4a. I'll review it today.
