### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs#253]
My IDE shouts at me about errors in this example code:

https://github.com/owncloud/documentation/blob/47c1dbfc8771f00d935fc3bf6518f0cc1bb41413/developer_manual/examples/storage-backend/OCA/MyStorageApp/Storage/MyStorage.php#L33

Undefined variable `$params`

**Comment by phil-davis** [comment]
@settermjd this code was ported over into the new docs repo. 
https://github.com/owncloud/docs/blob/master/modules/developer_manual/pages/examples/storage-backend/OCA/MyStorageApp/Storage/MyStorage.php

The undefined variables are still in the code.

**Comment by voroyam** [comment]
errors removed?

https://github.com/owncloud/docs/blob/master/modules/developer_manual/examples/app/storage-backend/OCA/MyStorageApp/Storage/MyStorage.php
