### ISSUE TITLE
brute_force_protection: settings/admin

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#254]
Needs documentation in panel: settings/admin

Keys:

- ``brute_force_protection_fail_tolerance``
- ``brute_force_protection_time_threshold``
- ``brute_force_protection_ban_period``

as of /lib/BruteForceProtectionConfig.php line 107 onwards

```php
public function setBruteForceProtectionFailTolerance($attempts) {
    $this->config->setAppValue(
        'brute_force_protection', 
        'brute_force_protection_fail_tolerance', 
        $attempts
    );
}
public function setBruteForceProtectionTimeThreshold($seconds) {
    $this->config->setAppValue(
        'brute_force_protection', 
        'brute_force_protection_time_threshold', 
        $seconds
    );
}
public function setBruteForceProtectionBanPeriod($seconds) {
    $this->config->setAppValue(
        'brute_force_protection', 
        'brute_force_protection_ban_period', 
        $seconds
    );
}
```

@settermjd @voroyam

**Comment by settermjd** [comment]
Do you mean that it should be documented in https://doc.owncloud.com/server/administration_manual/configuration/server/security/password_policy.html? If so, then I think it's time to break the security section out and have a security apps directory.

**Comment by mmattel** [comment]
As far I remember,
we have described the keys in https://doc.owncloud.com/server/administration_manual/configuration/server/occ_app_command.html
but we lack a reference where these keys are used in the settings-admin/panel. So how do they look like there, a screenshot maybe. Not in the occ app configuration but in the settings description page (if we haev any, not looked at)

**Comment by voroyam** [comment]
We don’t have a settings description page. Looked in the admin manual and user manual.

**Comment by voroyam** [comment]
I document this in the page @settermjd suggested.

**Comment by voroyam** [comment]
So this
![image](https://user-images.githubusercontent.com/24212810/62030096-957a7080-b1e4-11e9-83ac-400bfa0c428c.png)
 should be documented in here:
https://doc.owncloud.com/server/administration_manual/configuration/server/security/password_policy.html
Or maybe it should get it's own document in the security section.

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1569

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1576

**Comment by voroyam** [comment]
documented, merged, backported.
