### ISSUE TITLE
update installation examples to php7

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#255]
https://doc.owncloud.com/server/10.0/admin_manual/installation/source_installation.html
starts by saying that we recommend php7 over php5, but ends with RHEL, SLE and Ubuntu examples 
showing only the php5 dependencies.

As we no longer maintain owncloud-deps packages, we need to keep the documentation up to date, please!

**Comment by settermjd** [comment]
Closing, as it appears that all the changes requested here have been implemented.
