### ISSUE TITLE
Script on install document causes Ubuntu system to be unbootable

### ISSUE THREAD

**Issue by cgarrovillo** [owncloud/docs#2566]
A part on the owncloud Ubuntu 18.04 installation guide provides a script that breaks ALL permissions throughout the whole system, causing the system to be unbootable

## What Needs to be Documented?

The "Finalise the Installation" part of the [owncloud Ubuntu 18.04 installation](https://doc.owncloud.org/server/10.4/admin_manual/installation/ubuntu_18_04.html) executes a chmod at the very root of the file system and causes the whole system to break

## Why Should This Change Be Made? (Optional)

This is a critical issue. This script needs to be fixed

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ X ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ X ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by ibaranov-cp** [comment]
+1 this happens to me as well. Suspect it is the variables at the top of the file finalise-install.sh

https://github.com/owncloud/docs/blob/163d0a4db9135b5c2289e22b497ab0f9cb825462/modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh#L8

Dangerous to leave this kind of stuff in a guide for new folks

**Comment by cgarrovillo** [comment]
I should've known tbh. Even the guide uses an old link to ownCloud 10.2 or something like that. Didn't expect something as destructive as this though.

Looking at the script too, it looks like it's specifically setup to break ALL permissions and set it to ownCloud user. No idea if it is by design but surely destructive as hell.

https://github.com/owncloud/docs/blob/163d0a4db9135b5c2289e22b497ab0f9cb825462/modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh#L22

Imagine deploying this for a small client. Someone should claim responsibility for this

**Comment by phil-davis** [comment]
The variables displayed there are  in the top of https://raw.githubusercontent.com/owncloud/docs/master/modules/admin_manual/pages/installation/ubuntu_18_04.adoc

```
:webserver-user: www-data
:webserver-group: www-data
:install-directory: /var/www/owncloud
```

But they are not getting substituted in the code/script section when the docs are rendered.

It loks like attempts are being made to fix this: #2554 #2557 

@settermjd this needs to be sorted out urgently so people do not destroy their systems.

**Comment by settermjd** [comment]
Fixes for this issue have been created and backported in the following (merged) PRs:

- #2570
- #2571
- #2572
- #2573
- #2574
- #2575
- #2576
- #2577

Versions 10.1 - 10.4 of the documentation should now be updated.

**Comment by phil-davis** [comment]
![Screenshot_2020-04-17 Install ownCloud on Ubuntu 18 04](https://user-images.githubusercontent.com/1535615/79563719-0ba16900-80cd-11ea-982c-170751289b5c.png)

That looks better.

**Comment by settermjd** [comment]
@cgarrovillo, thanks for creating this issue. Please let me know if the issue can be closed.

**Comment by ibaranov-cp** [comment]
Looks good to me now

**Comment by ibaranov-cp** [comment]
Actually, new issue:

copying and executing in command line:
`FILE="/usr/local/bin/ocpermissions"

/bin/cat <<EOM >$FILE
#!/bin/bash

ocpath="/var/www/owncloud"
datadir="${ocpath}/data"
htuser="www-data"
htgroup="www-data"
rootuser="root"

printf "Creating any missing directories"
sudo -u "${htuser}" mkdir -p "${ocpath}/assets"
sudo -u "${htuser}" mkdir -p "${ocpath}/updater"
sudo -u "${htuser}" mkdir -p "${datadir}"

printf "Update file and directory permissions"
sudo find "${ocpath}/" -type f -print0 | xargs -0 chmod 0640
sudo find "${ocpath}/" -type d -print0 | xargs -0 chmod 0750

printf "Set web server user and group as ownCloud directory user and group"
sudo chown -R "${rootuser}:${htgroup}" "${ocpath}/"
sudo chown -R "${htuser}:${htgroup}" "${ocpath}/apps/"
sudo chown -R "${htuser}:${htgroup}" "${ocpath}/apps-external/"
sudo chown -R "${htuser}:${htgroup}" "${ocpath}/assets/"
sudo chown -R "${htuser}:${htgroup}" "${ocpath}/config/"
sudo chown -R "${htuser}:${htgroup}" "${datadir}"
sudo chown -R "${htuser}:${htgroup}" "${ocpath}/updater/"
sudo chmod +x "${ocpath}/occ"

printf "Set web server user and group as .htaccess user and group"
if [ -f "${ocpath}/.htaccess" ]; then
  sudo chmod 0644 "${ocpath}/.htaccess"
  sudo chown "${rootuser}:${htgroup}" "${ocpath}/.htaccess"
fi

if [ -f "${datadir}/.htaccess" ]; then
  sudo chmod 0644 "${datadir}/.htaccess"
  sudo chown "${rootuser}:${htgroup}" "${datadir}/.htaccess"
fi

EOM`

and then looking at the file with nano, I can see that the variables are missing:

`
#!/bin/bash

ocpath="/var/www/owncloud"
datadir="/data"
htuser="www-data"
htgroup="www-data"
rootuser="root"

printf "Creating any missing directories"
sudo -u "" mkdir -p "/assets"
sudo -u "" mkdir -p "/updater"
sudo -u "" mkdir -p ""

printf "Update file and directory permissions"
sudo find "/" -type f -print0 | xargs -0 chmod 0640
sudo find "/" -type d -print0 | xargs -0 chmod 0750

printf "Set web server user and group as ownCloud directory user and group"
sudo chown -R ":" "/"
sudo chown -R ":" "/apps/"
sudo chown -R ":" "/apps-external/"
sudo chown -R ":" "/assets/"
sudo chown -R ":" "/config/"
sudo chown -R ":" ""
sudo chown -R ":" "/updater/"
sudo chmod +x "/occ"

printf "Set web server user and group as .htaccess user and group"
if [ -f "/.htaccess" ]; then
  sudo chmod 0644 "/.htaccess"
  sudo chown ":" "/.htaccess"
fi

if [ -f "/.htaccess" ]; then
  sudo chmod 0644 "/.htaccess"
  sudo chown ":" "/.htaccess"
fi
`

**Comment by ibaranov-cp** [comment]
Side note: for usability, I suggest inserting \n just before the ending " in every printf line

**Comment by cgarrovillo** [comment]
> Side note: for usability, I suggest inserting \n just before the ending " in every printf line

Quick q, have you tested it even with the missing variables issue?

I'm thinking of testing this in a VM to save future hassles

**Comment by ibaranov-cp** [comment]
Tested it, still broke things (luckily I had a backup image, it broke network settings for me by setting wrong chown...)
I'd honestly steer clear of this script for now, and set things manually, slowly

**Comment by settermjd** [comment]
I'm progressively working through this, using a Ubuntu Docker container and so far, don't see any issues, at least with the chagnes in #2589.
