### ISSUE TITLE
Document Notifications features

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#257]
When looking at user/admin docs there is not much about notifications. In the latest server versions we made a lot of progress in this area. We should document the different kinds of notifications, especially the points that are relevant for admins. In some other context I summarized the different notification types. This might not yet be complete/comprehensive as it was written for some other context. The basics should be understandable and sufficient as a basis for further research and doc writing.

- [x] user docs about notification types, channels, config options (+screenshots)
- [x] admin docs about notification types, channels, config options (+screenshots)

---

## Activity mails
- These digest notifications are tasked to inform users about all events in their account in a regular, configurable manner.
- The composition of the mails and the activity stream can be configured granularly by every user in self-service via the "Activity" panel in the user settings. If users don't want to be informed about incoming shares, they should just untick the respective checkbox.
- Activity mails are not integrated with the new notification framework and live in parallel with their own logic.

## User-triggered share notification ("Notify" button)

- These notifications provide an opportunity for users to notify ("ping") users about contents they have shared.
- The mails are only triggered when users hit the respective button
- The whole feature can be enabled/disabled by administrators using the option "Allow users to send mail notifications for shared files to other users" in "Sharing" setting

## Sending public links from webUI

# Notification framework
## Pending share notification
- These notifications are for federated and regular user/group shares
- These notifications are part of the recently introduced notification framework and can be sent via mail, internal notification (bell) and displayed by the clients.
- Sending these via mail can be vital to inform users about new shares
- AFAIK they are only sent when "Automatically accept new incoming local shares" is disabled (pending shares are enabled, respectively)
  - There are two admin options, one for federated shares from trusted instances, one for regular user shares
  - Both options also exist on the user level
- The configuration options for the new notification framework are very limited currently. To date it is only possible to configure mail notifications in the user settings.
- When pending shares is enabled and users don't want to receive these notifications via mail, they can configure not to receive mail notifications at all. Activity mails will still be sent. The only mails that the user won't get currently are notifications from e.g. custom groups or announcementcenter. These will still appear in the web interface and on the clients.
- Regarding the "reply-to" field: What is the expectation? Actually these are no-reply mails sent by the system.

## ?
There are some more apps that integrate with the notification framework. Needs collecting them.

**Comment by settermjd** [comment]
@pmaier1, the notifications that you have documented here, are these the only ones?

**Comment by pmaier1** [comment]
So far, this should be it.

**Comment by settermjd** [comment]
@pmaier1, please add the appropriate priority to this.

**Comment by settermjd** [comment]
@pmaier1, I'm working through documenting [the Activity app](https://marketplace.owncloud.com/apps/activity) (from a normal user's perspective) as part of implementing this issue. As part of that, I read the following in the app's description, but don't know how to do that. Can you shed light on how, please?

> For users with lots of activity it is possible to limit the Activity stream to 'Favorites' in order to avoid noise.

**Comment by pmaier1** [comment]
![Screenshot from 2019-11-05 12-36-38](https://user-images.githubusercontent.com/21193500/68204754-faeeb200-ffc8-11e9-9508-f72536251e65.png)

User personal settings => Activity, third row

**Comment by settermjd** [comment]
I'm blind as a proverbial bat today. Thanks.

**Comment by voroyam** [comment]
seems like everything has been implemented. closing.
