### ISSUE TITLE
Encryption: Use environment vars for recovery and occ password

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#258]
Referencing: https://github.com/owncloud/core/pull/32172
Core PR merged, stable10 created
``encryption:decrypt-all [-m|--method [METHOD]] [-c|--continue [CONTINUE]] [--] [<user>]``
For details please see the referenced PR

**Comment by voroyam** [comment]
documented with here 
https://doc.owncloud.com/server/10.2/admin_manual/configuration/files/encryption/encryption_configuration_quick_guide.html
