### ISSUE TITLE
current nginx config eats webm/mp4, starts with a Big Blue Window

### ISSUE THREAD

**Issue by grinapo** [owncloud/docs#2595]
I guess it's not an IBM™ advertisement that First Run Wizard (as well as About) starts with an empty, big, blue pupup window.

The reason is that it tries to pull up a `webm` or `mp4` movie file but nginx handles neither so redirects them to `apps/files/` which won't help much (also provides wrong content-type).

Fixing up config as
```
        location ~ ^\/.+[^\/]\.(?:png|html|ttf|ico|jpg|jpeg|webm|mp4)$ {
```
may make it a bit more ownloudy. 

Strictly speaking this cannot be fixed by firstrunwizard but I'm sure you're more familar with the OC ecosystem and the proper ways to fix this than I am.

**Comment by settermjd** [comment]
Thanks for creating the PR, @grinapo. I'll work through it this week.

**Comment by settermjd** [comment]
Actually, I'm not quite sure how to handle this, as the official policy of the docs is to include references for the supported platforms, which doesn't include NGINX. @michaelstingl, can you provide some guidance here, please?

**Comment by settermjd** [comment]
@grinapo, unfortunately, the official policy of the docs is to include references for the supported platforms, which doesn't include NGINX, so I'm not able to proceed further with this issue.

**Comment by settermjd** [comment]
But, I don't want to close this issue, without providing further support. My recommendation is to add it to https://central.owncloud.org/t/nginx-documentation-unofficial-community/22365/2, which is where the existing NGINX documentation has been moved to.
