### ISSUE TITLE
Ubuntu 18.4 installation script removes +x from every file on the root filesystem

### ISSUE THREAD

**Issue by AGoliath** [owncloud/docs#2620]
I´m trying to install owncloud on my ubuntu 18.4 for the first time following
modules/admin_manual/pages/installation/ubuntu_18_04.adoc 
to the letter, starting out with a fresh Ubuntu 18.04 minimal and only executing what is mentioned in the docs (apart from setting up an ssh key)

Everything works perfectly fine until I get to "Finalise the Installation".
As soon as I executed the created /usr/local/bin/ocpermissions file my console is flodded with 
lines such as

```
chmod: changing permissions of '/proc/sys/net/ipv4/tcp_ecn_fallback': Operation not permitted
chmod: changing permissions of '/proc/sys/net/ipv4/tcp_fack': Operation not permitted
chmod: changing permissions of '/proc/sys/net/ipv4/tcp_fastopen': Operation not permitted
```
for pretty much any file below the root of the filesystem, and after the script finishes not a single binary remains executable, e.g. I can´t use binaries such as `chmod `or `ls `anymore as it seems they have lost their +x flag.

Unfortunately I didn´t pinpoint where the script went wrong, but since https://github.com/owncloud/docs/commit/ff29126df4403920dd04ef70da5cfc5b1003d139?diff=split made quite some significant changes on how the script changes file permissions I hope @settermjd  can shed some light on this?

Only way to recover for me is to reinstall the VM from scratch... luckily it was a brand new one, but this sure can ruin some peoples day...

**Comment by AGoliath** [comment]
Sorry for the follow-up, but i restored from a backup and tried again and now i see what went wrong.

The way I followed the instruction was to simply copy and paste the content of the docs into my shell. So this is what I pasted in my shell:

```
root@mymachine:~# /bin/cat <<EOM >$FILE
> #!/bin/bash
>
> ocpath="/var/www/owncloud"
> datadir="${ocpath}/data"
> htuser="www-data"
> htgroup="www-data"
>
> printf "Running ${0}"
> echo
>
> echo "Creating any missing directories."
> sudo -u "${htuser}" mkdir -p "${ocpath}/assets"
> sudo -u "${htuser}" mkdir -p "${ocpath}/updater"
> sudo -u "${htuser}" mkdir -p "${datadir}"
>
> echo "Updating file and directory permissions."
> sudo find "${ocpath}/" -type f -print0 | xargs -0 chmod 0644
> sudo find "${ocpath}/" -type d -print0 | xargs -0 chmod 0754
...snip...
>
> echo "Exiting"
> echo
> EOM
root@mymachine:~#
```

and this is what was actually written into the file:

```
root@mymachine:~# less ${FILE}
#!/bin/bash

ocpath="/var/www/owncloud"
datadir="/data"
htuser="www-data"
htgroup="www-data"

printf "Running -bash"
echo

echo "Creating any missing directories."
sudo -u "" mkdir -p "/assets"
sudo -u "" mkdir -p "/updater"
sudo -u "" mkdir -p ""

echo "Updating file and directory permissions."
sudo find "/" -type f -print0 | xargs -0 chmod 0644
sudo find "/" -type d -print0 | xargs -0 chmod 0754
*snip*
```
so the shell tried to replace the variables that where supposed to go into the script but as they where not defined simply replaced them with empty strings, and there you have it
`sudo find "/" -type f -print0 | xargs -0 chmod 0644`
is executed which is not a line i want to see under any circumstances with sudo rights...

If these scripts are indeed intended to be copy-pastad like that there is some proper escape-sequencing needed. Otherwise please add a warning and a how-to on how these scripts are supposed to be run, as the EOF-Piping seems to imply that I did it the intended way

**Comment by ho4ho** [comment]
Related by #2566 ?

**Comment by ho4ho** [comment]
Look like permission script removed by https://github.com/owncloud/docs/pull/2624

**Comment by AGoliath** [comment]
yup, closed
