### ISSUE TITLE
Documentation update required for 'user:expire-password' command in password_policy

### ISSUE THREAD

**Issue by sharidas** [owncloud/docs#263]
Add 'group' and 'all' options to 'user:expire-password' command in password_policy app. 
PR for reference: https://github.com/owncloud/password_policy/pull/77

**Comment by settermjd** [comment]
It seems that some of the work for this issue was completed in 215ad22a. I'll complete the rest this week.

**Comment by voroyam** [comment]
PR is merged. Closing
