### ISSUE TITLE
Missing warnings in document about Upgrading from Package

### ISSUE THREAD

**Issue by enbrnz** [owncloud/docs#2631]
Many users install owncloud through their package manager from our repositories. However when upgrading using the package manager, they neglect to do critical upgrade steps because they expect the process to be batteries included.

## What Needs to be Documented?
1. The `owncloud-files` package must not be used with automated system upgrades
2. How to exclude the package from automated system upgrades
3. The general upgrade process description is missing the first step: reading the `Release Notes`
4. To be aware that you'll have to manage the PHP installation independently
5. Just because the files get installed automatically doesn't mean the process is complete

## Where Does This Need To Be Documented?
`admin_manual/pages/maintenance/package_upgrade.adoc`

## Why Should This Change Be Made?
(Community) users keep running into problems when using the owncloud-files package and automated system upgrades.

## What Type Of Content Change Is This?
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? 
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by voroyam** [comment]
Thanks for creating this

**Comment by ho4ho** [comment]
Happening by #37104, #36330. Some really unhappy :disappointed:

**Comment by mmattel** [comment]
This is a comment I did in talk based in a discussion started there:

**snip...**
Q: you install a instance via a packag manager, but you should not upgrade the installation with the pm - the reasons mentioned are clear. This is counteracting the idea using a pm. It is not that complex to document RTFM and put the owncloud files on automatic upgrade hold. But then I ask, what is the benefit of using PM and why do we use it? Just for first installation including php, webserver and db? Just think about that Ubuntu 18.04 limits php to 7.2, but the world is going for 7.3 and 7.4. MySQL vs MariaDB ect. How do you want to solve this? My very personal pov, remove pm installation and put more effords into a better and streamlined installation and upgrade documentation for beginners and experts. This would be a multiple win. Just my 2c...
**snip...**

**Comment by ho4ho** [comment]
https://github.com/owncloud/core/issues/37808 also :disappointed:

**Comment by voroyam** [comment]
@enbrnz need more info to document this

**Comment by voroyam** [comment]
I need specifics. 

What do you want to document where. The steps you wrote down are not detailed enough and do not contain the important information.

**Comment by EParzefall** [comment]
In the upgrade introduction, all the warnings are present, including the recommendation not to upgrade via package manager:
https://doc.owncloud.com/server/10.7/admin_manual/maintenance/upgrade.html
or: admin_manual/pages/maintenance/upgrade.adoc.
I'm repeating the warning in admin_manual/pages/maintenance/package_upgrade.adoc now in case users skip the intro and point them to the release notes again.

**Comment by mmattel** [comment]
Closing, PR merged #3551
