### ISSUE TITLE
doc 10.1 + 10.2 show 10.2 latest

### ISSUE THREAD

**Issue by ho4ho** [owncloud/docs#2637]
https://doc.owncloud.org/server/10.2/ showing 10.2 latest but should 10.4:

![oc](https://user-images.githubusercontent.com/42564859/80862946-294c0200-8c79-11ea-8668-d40779c936af.png)

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by phil-davis** [comment]
And 10.2 `modules/admin_manual/pages/release_notes.adoc` has release notes up to only 10.3.1

I would have thought that when reading 10.2 docs, an admin will want to see at least the release notes up to 10.3.2

**Comment by voroyam** [comment]
branches removed.

closing.
