### ISSUE TITLE
occ federation:sync-addressbooks description improvement

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#264]
The command is described in https://github.com/owncloud/documentation/blob/master/admin_manual/configuration/server/occ_command.rst

The description text tells only:
"Servers connected with federation shares can share user address books, and auto-complete usernames in share dialogs."
- What exactly does sync addressbook mean
Getting the users from the foreign instance and store them locally?
Pushing the own users so that they get stored on the foreign instance?
or...
- If there are more than one federation relations set up
Are all of them syned ?
- Sync ways
Is this bi-directional or uni-directional only?
- What is the benefit in doing so
What happens if you don´t do it?
How often do you need to do it - regulary, cron job?
- What does the progress bar tell
Believing how many feds are beeing synced, it does not tell which one is in progress.

@PVince81 @settermjd @voroyam

**Comment by voroyam** [comment]
no progress due to lack of developer time.
