### ISSUE TITLE
Add fed shares scanner batched cronjob

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#2648]
## What Needs to be Documented?
**Upcoming changes from core:**
https://github.com/owncloud/core/pull/37391 (Add fed shares scanner batched cronjob)

**Text change:**
WARNING: `incoming-shares:poll` has been deprecated and replaced by periodic external shares cronjob. Please check Federated Cloud Sharing settings and documentation.

**Command change:**
```
# required
occ config:app:set files_sharing cronjob_scan_external_enabled --value yes

# optionaly 
occ config:app:set files_sharing cronjob_scan_external_min_login --value 14400
occ config:app:set files_sharing cronjob_scan_external_min_scan --value 3600
occ config:app:set files_sharing cronjob_scan_external_batch --value 100
```
## Where Does This Need To Be Documented?
occ command set

## Why Should This Change Be Made? (Optional)
New and deprecated commands

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

Note: this is most likely for 10.5 only ! To prepare, a new branch "10.5" needs to be created (anyway...)

@mrow4a @pmaier1

**Comment by mrow4a** [comment]
@mmattel not sure if useful https://github.com/owncloud/core/pull/37391#issuecomment-640047599
