### ISSUE TITLE
Link to open file sidebar from permalink

### ISSUE THREAD

**Issue by PVince81** [owncloud/docs#265]
"http://host/owncloud/f/$fileId?details=$tabId"

This will open the files app, scroll down to the file as before then automatically open the sidebar with the given tab id.

From https://github.com/owncloud/core/pull/32152

cc @DeepDiver1975

@michaelstingl I think you requested something like this for clients so they could link to the versions panel directly. For the versions panel, replace $tabId with "versionsTabView"

**Comment by settermjd** [comment]
ping @pmaier1

**Comment by pmaier1** [comment]
> @pmaier1, can you give your feedback, please?

Not sure what to give feedback on. I think this is something for the dev docs. Regular users will not use this. Rather it can be used for e.g. context menu options in the desktop client.

**Comment by michaelstingl** [comment]
> @michaelstingl I think you requested something like this for clients so they could link to the versions panel directly. For the versions panel, replace $tabId with "versionsTabView"

👍

**Comment by michaelstingl** [comment]
> @michaelstingl I think you requested something like this for clients so they could link to the versions panel directly. For the versions panel, replace $tabId with "versionsTabView"

@PVince81 @pmaier1 What server version will support this? Is there a capability for the clients to check if this is supported?

**Comment by PVince81** [comment]
@karakayasemi mind taking care of adding a capabilities entry for the files app that advertises support for this ?

**Comment by PVince81** [comment]
for the record: this parrameter exists since 10.0.10.

we'll add a capability nonetheless

**Comment by PVince81** [comment]
capability will be in 10.2

**Comment by karakayasemi** [comment]
@PVince81 If nothing left for me, I am removing my assignment in here?

**Comment by micbar** [comment]
@michaelstingl @pmaier1 Is there anything left open in this ticket?
Documentation?

**Comment by michaelstingl** [comment]
@settermjd I can't find a docs-PR linking to this issue? Already done?

**Comment by settermjd** [comment]
@michaelstingl, not yet. I've only started documenting it today. Next question; is this only to be backported to 10.2?

**Comment by settermjd** [comment]
After reading the acceptance tests, this looks straight-forward enough to me.

**Comment by michaelstingl** [comment]
> is this only to be backported to 10.2?

@settermjd yeah, 10.2+

**Comment by settermjd** [comment]
Thanks, @michaelstingl.
