### ISSUE TITLE
Core: new functionality: file action to explicitly lock a file

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#2663]
## What Needs to be Documented?
New functionality in core relevant for the user doc

## Where Does This Need To Be Documented?
https://doc.owncloud.com/server/latest/user_manual/files/webgui/overview.html#the-overflow-menu

## Why Should This Change Be Made? (Optional)
Document new functionality.
Core: https://github.com/owncloud/core/pull/37460 (Add file action to explicitly lock a file)

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@micbar @DeepDiver1975 @pmaier1

**Comment by voroyam** [comment]
implemented with https://github.com/owncloud/docs/pull/2888

**Comment by voroyam** [comment]
my mistake, the PR was closed

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/2903

this is the PR
