### ISSUE TITLE
cgroupsV2 errors even with backwards compatibility enabled. un-Resolved

### ISSUE THREAD

**Issue by Sudnym** [owncloud/docs#2673]
I'm writing this script: https://github.com/Sudnym/fedora-30-32-owncloud10.5-setup to automatically run a docker container of owncloud in fedora 30-32 where if the third argument in the setup command is "yes" it will enable backwards compatibility for groups using the command:
```grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"```
I receive an error saying "this version of runs doesn't work on cgroups v2"

**Comment by Sudnym** [comment]
I thought it was fixed, and then it wasn't. same error.

**Comment by ho4ho** [comment]
@Sudnym How related by ownCloud docs or by ownCloud? Nothing there: https://github.com/owncloud/docs/search?q=cgroups&unscoped_q=cgroups

**Comment by voroyam** [comment]
no feedback, no progress. Closing
