### ISSUE TITLE
Clarifying WND null Permission manager

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2683]
need to clarify that if filed is empty - null permission manager will be used. String is not necessary to enable it.

![image](https://user-images.githubusercontent.com/24212810/84746592-80523000-afb6-11ea-85aa-f05c94c6e011.png)

https://doc.owncloud.com/server/admin_manual/enterprise/external_storage/windows-network-drive_configuration.html#access-control-lists

**Comment by mschreml** [comment]
@voroyam done

**Comment by voroyam** [comment]
@mschreml that's not what I wanted in the docs.

If you aren't sure what the author of the issue wants - ask.

The Permission manager option is confusing to beginner admins, so I just wanted to clarify, that on standard deployments with standard ADs you don't need any string. The current documentation make it seem like you need to enter `NullPermissionManager` in order to use the default manager, but that's not true. You just need to leave the field empty. This is what I wanted to document.

What has been documented now is even more confusing.

```
The `Null Permission Manager` is the default permission manager for ACL´s and is used, if no other ACL manager is specified. This is also the case, when no permission is explicitly set.
```

I think you also used the wrong single quote. It should be like this **ACL's** not like this **ACL´s**. That's a back tick not a quote.

The second sentence is completely irrelevant to the feature. You don't need anything if no permissions are set.

Please re-do the PR.

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/3282

**Comment by voroyam** [comment]
fixed with https://github.com/owncloud/docs/pull/3287
