### ISSUE TITLE
Need VFS documentation

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2686]
We need an official documentation about the state, how to use and the risk involved when using VFS on windows Mac or linux.

Right now we have 2 blog articles, which is not sufficient from my POV.

https://owncloud.org/news/desktop-client-2-6-release-native-virtual-file-system-on-windows-10/ https://owncloud.org/news/owncloud-client-goes-virtual-sync-files-demand/

**Comment by mmattel** [comment]
This has to go into the client repro, as that repro is included into docs. Nothing to be written here.
Please file a issue there and reference it to this one.

**Comment by voroyam** [comment]
Thanks

https://github.com/owncloud/client/issues/7913

**Comment by voroyam** [comment]
no progress, closing

**Comment by michaelstingl** [comment]
Next attempt: https://github.com/owncloud/docs/issues/3508
