### ISSUE TITLE
Unlimited loading

### ISSUE THREAD

**Issue by FlavienDev** [owncloud/docs#2698]
Hello, 
I am just starting to use OwnCloud and when I go to the main menu where I should have my files, I have unlimited loading and unable to upload any file. Namely that there is no file already present, and that due to the loading, I cannot add a file either.
When I look at the console it is noted this following error:

Failed to load resource: the server responded with a status of 501 ()
Uncaught (in promise) TypeError: Cannot read property 'getElementsByTagNameNS' of null
    at Client._getSabreException (client.js?v=551b3844162d44e93382c25e8c5bd0da:430)
    at client.js?v=551b3844162d44e93382c25e8c5bd0da:494

Could you help me please ?
Thanks in advance.
Regards.

D.F

**Comment by ho4ho** [comment]
@FlavienDev This not supporting forum, better ask help by https://central.owncloud.org/

**Comment by FlavienDev** [comment]
Ok Thanks
