### ISSUE TITLE
Ubuntu manual installation documentation doesn't specify data directory explicitly

### ISSUE THREAD

**Issue by jersey99** [owncloud/docs#2717]
The documentation in the [ubuntu install webpage](https://doc.owncloud.com/server/admin_manual/installation/ubuntu_18_04.html) doesn't make the data directory explicit. Which can force the user to unintentionally install OC with data directory set to the default. And manually changing the data directory doesn't seem to be much fun :)

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by voroyam** [comment]
Hello,

if you read the documentation - the first sentence is:

**This is an ultra-short guide to installing ownCloud on a fresh installation of Ubuntu 18.04.**

In order to make this documentation short we let as much on default as possible.
