### ISSUE TITLE
Improvement: Remove CleanupChunks background job

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#273]
Referencing merged: https://github.com/owncloud/documentation/pull/3799 (Remove CleanupChunks background job)

The text can be improved when the backport of 
https://github.com/owncloud/core/pull/31630 (Adding background:queue commands: status and delete) (merged) 
Because you can use the new occ command to do so.

@PVince81 

@DeepDiver1975 @butonic pls take care that 31630 is merged in master but no stable10 backport has been made since 26 days (at the time of this note). As you see, such things can cause issues for improving the documentation...

**Comment by voroyam** [comment]
I am closing this issue as there is no real progress that I can see here.
