### ISSUE TITLE
 Missing pages with 10.5 Documentation

### ISSUE THREAD

**Issue by davitol** [owncloud/docs#2737]
we have some missing pages with 10.5 Documentation

https://doc.owncloud.org/server/10.5/go.php?to=user-sync-calendars
https://doc.owncloud.org/server/10.5/go.php?to=user-sync-contacts
https://doc.owncloud.org/server/10.5/go.php?to=user-webdav
Those links from First run Wizard window clicking on the below buttons

<img width="891" alt="Screenshot 2020-08-03 at 14 36 55" src="https://user-images.githubusercontent.com/10596560/89190354-a1d89c80-d5a1-11ea-8c5e-368433c4664b.png">

Available for 10.4 but not for 10.5 (404)

Looks like the redirects with "go.php" are broken for 10.5

**Comment by jnweiger** [comment]
@pmaier1 This is one of the last tickets in https://github.com/orgs/owncloud/projects/139 -- reschedule for 10.6?
