### ISSUE TITLE
Document activity extension for the windows network drive app

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/docs#2738]
Related tickets:
* https://github.com/owncloud/windows_network_drive/pull/299
* https://github.com/owncloud/enterprise/issues/4074

## What Needs to be Documented?

New windows network drive feature to allow sending activity events from the windows network drive's listener

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by jvillafanez** [comment]
PR in https://github.com/owncloud/docs/pull/2739

**Comment by ChrisEdS** [comment]
The config.php parameter is `'wnd.activity.registerExtension' => false,` or `true`
