### ISSUE TITLE
Review API examples

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs#274]
See comment https://github.com/owncloud/documentation/pull/4249#issuecomment-402943648

- ``Authentication is done by sending a Basic HTTP Authorization header``
This should be clarified more. I strongly believe that it is meant to authenticate the request itself and not the user to be enabled/disabled. What about:
``To authentication this request by a user who has proper ownCloud rights, you need to send a Basic HTTP Authorization header``

- userid   string The id of the user to enable
Enable the user ``Frank`` --> Enable the user with userid ``Frank``

- [ ] decide what the improved wording should be
- [ ] implement in the User Provisioning API page
- [ ] implement in any other API doc pages

**Comment by settermjd** [comment]
@phil-davis, how about this variation: 

> The Basic Authorization HTTP header must be used to authenticate this request, by a user who has sufficient access rights.

Currently, I've only found the original string (re point 1 in the description above) in `./modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc`.

**Comment by phil-davis** [comment]
Looks good. This issue is so old, I have completely forgotten exactly what I was thinking when I wrote it!
