### ISSUE TITLE
Default version is 10.4. but 10.5 has been release

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#2742]
If you open https://docs.owncloud.com, you get 10.4 as the default release.
It should be 10.5 as it has bee officially released.

**Impact:**
1.) you do not know that 10.5 is released
2.) you see the release notes of 10.4 and not 10.5

-->
## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@pmaier1 @micbar @phil-davis

**Comment by phil-davis** [comment]
The values in `site.yml` of the `master` and `10.5` branches look OK.
How does that very first redirect from https://doc.owncloud.com decide to go to https://doc.owncloud.com/server/10.4/ ?

**Comment by jnweiger** [comment]
There is a caddy webserver on dagmar, that needs an update:
```
$ curl -I https://doc.owncloud.com/
HTTP/2 302 
content-type: text/html; charset=utf-8
date: Thu, 06 Aug 2020 10:37:30 GMT
location: /server/10.4
referrer-policy: strict-origin-when-cross-origin
server: Caddy

**Comment by pmaier1** [comment]
> There is a caddy webserver on dagmar, that needs an update:

Thanks for checking. Can you do it?

**Comment by jnweiger** [comment]
Yes, I can give it a try. This machine is managed by a non-trivial ansible setup. My PR needs a good internal review, please:
https://gitea.owncloud.services/devops/websites/pulls/57

@mmattel Thanks for catching this! You can only review after it is deployed, I am afraid.

**Comment by mmattel** [comment]
np, just le me know :smile:

**Comment by mmattel** [comment]
Closing, retested, seems to be fixed now 😃
