### ISSUE TITLE
Doc improvements for commands occ config:xxx necessary

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#275]
The command set config:xxx is documented vary basic and not with all parameters available.
Pls see:  https://github.com/owncloud/documentation/blob/master/admin_manual/configuration/server/occ_command.rst#L329

I came across this with https://github.com/owncloud/core/issues/32006

**Based on the example:**
```
sudo -uwww-data ./occ config:list --help

Usage:
  config:list [options] [--] [<app>]

Arguments:
  app                    Name of the app ("system" to get the config.php values, "all" for all apps and system). [default: "all"]

Options:
      --output[=OUTPUT]  The output format to use (plain, json or json_pretty, default is plain). [default: "json_pretty"]
      --private
```

**But this is currently documented:**
```
sudo -u www-data php occ config:list

By default, passwords and other sensitive data are omitted from the report, so the output can be posted publicly (e.g., as part of a bug report). 
In order to generate a full backport of all configuration values the ``--private`` flag needs to be set:
```

**Missing in the example above:**
- ``app``
- ``--output[=OUTPUT]``

In addition, if I take the example from the referenced core issue:
```
./occ config:list files_sharing
{
    "apps": {
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "0.10.1",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        }
    }
}
```
How to identify the app key where you can apply changes?
Which datatypes and/or values are allowed for a key?
I do not believe that eg ``installed_version`` is a changeable key,
but ``outgoing_server2server_share_enabled`` is...
Pls see also the new key ``shareapi_public_notification_lang`` at https://github.com/owncloud/core/pull/31869

(Maybe config:list needs and extension with a new option to show which datatypes and/or values are allowed for a key)

@phil-davis @PVince81

**Comment by voroyam** [comment]
the rudimentary examples are included in the docs. Can you provide feedback what you want to be documented? 

To go through every app and identify every key that can be set is quite an effort that can not be done by one person. So if we don't make a project out of this - it won't be done and can be closed.

**Comment by mmattel** [comment]
@voroyam 
I highlight the mismatch of the current situation.
It is up to oC to decide to go thru and document it properly.
