### ISSUE TITLE
Search box miss https://doc.owncloud.org/server/10.5/

### ISSUE THREAD

**Issue by ho4ho** [owncloud/docs#2757]
Go by mobile @ https://doc.owncloud.org/server/10.5/:

https://www.screenshotmachine.com/serve.php?file=doc-owncloud-org-480x800phone-d931c0.jpg&attachment

search box miss up right, go by tabled / desktop there:

https://www.screenshotmachine.com/serve.php?file=doc-owncloud-org-800x1280tablet-d931c0.jpg&attachment

Related by https://github.com/owncloud/marketplace-issues/issues/34 ?

Offline:

![screen_mobile](https://user-images.githubusercontent.com/42564859/90662364-8ed3f680-e248-11ea-9652-afa498f3836d.png)

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by voroyam** [comment]
limitation of current setup
