### ISSUE TITLE
List of all WebDAV properties

### ISSUE THREAD

**Issue by PVince81** [owncloud/docs#276]
- files
    - oc:checksum
    - ...

Best is to look at the network console when the files app is doing a query as it already contains a lot.

**Comment by settermjd** [comment]
@PVince81, what are `lockdiscovery` and `share-types`?

**Comment by PVince81** [comment]
lockdiscovery will return lock information according to the [Webdav spec](https://tools.ietf.org/html/rfc4918#section-6.8). We added this as part of the "persistent file locking" backend feature.

"share-types" is an OC-specific property which summarizes what outgoing share types are applied to the current item.
```
        <oc:share-types>
          <oc:share-type>1</oc:share-type>
          <oc:share-type>3</oc:share-type>
        </oc:share-types>
```
The above response would mean that the item has shared with group (share type 1) and shared by link (share type 3). The share type values are:
0 - user share
1 - group share
2 - used internally, will not be returned here
3 - link shares

**Comment by settermjd** [comment]
The list that i have found is (_adding here for documentation purposes_):

```xml
<?xml version="1.0"?>
<d:propfind  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:prop>
    <d:getlastmodified />
    <d:getetag />
    <d:getcontenttype />
    <d:resourcetype />
    <oc:fileid />
    <oc:permissions />
    <oc:size />
    <d:getcontentlength />
    <oc:tags />
    <oc:favorite />
    <d:lockdiscovery />
    <oc:comments-unread />
    <oc:owner-display-name />
    <oc:share-types />
  </d:prop>
</d:propfind>
```
