### ISSUE TITLE
Missing backports and config-to-docs run (+ its backports)

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#2767]
[x] Missing backports from https://github.com/owncloud/docs/pull/2761
[ ] Missing `confing-to-docs` (see that repro) because of https://github.com/owncloud/core/pull/37859 incl its backports

For how to backport see: https://doc.owncloud.com/server/developer_manual/general/backporting.html#backporting-steps

@voroyam @phil-davis fyi

**Comment by phil-davis** [comment]
10.5 - #2768

**Comment by mmattel** [comment]
PR based on core 10.6 changes see: https://github.com/owncloud/docs/pull/2945

**Comment by mmattel** [comment]
closing because of merging #2945 and #2946
