### ISSUE TITLE
lifecycle_restored description

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs#2770]
https://github.com/owncloud/docs/blob/master/modules/user_manual/pages/apps/enterprise/admin_audit/file_lifecycle.adoc#lifecycle_restored

The table has a row:
`fileId | integer | The number of days interval specified during expiration
-- | -- | --`

Maybe the description should be `The file ID for the file that was restored` ?

**Comment by mmattel** [comment]
Closing, fixed with: https://github.com/owncloud/docs/pull/3619
