### ISSUE TITLE
LDAP: Renaming of groups not supported / propagated

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2774]
We ned to document that we don't support the renaming of LDAP groups.

Here is what happens:

-  The new name does not appear anywhere in ownCloud - neither in the LDAP config nor in the sharing dialogue 
- If you clear the user / group mapping the users in the renamed group get deleted / disabled and then added back / re enabled

**Comment by mschreml** [comment]
I think I don't have to descripe what happens. Just the "Note:" should be enough, right?

Like:

NOTE: Renaming of groups is not supported. We recommend to use [Custom Groups](https://doc.owncloud.com/server/user_manual/files/webgui/custom_groups.html#creating-custom-groups)

If the text is ok, canI write it in the Troubleshooting Area on [User Auth LDAP](https://doc.owncloud.com/server/admin_manual/configuration/user/user_auth_ldap.html#troubleshooting-tips-and-tricks) or should I write it in [LDAP Integration](https://doc.owncloud.com/server/admin_manual/configuration/server/app_commands/ldap_integration_commands.html)

**Comment by voroyam** [comment]
Just the note about Renaming is okay. Important is the propagated.

For example.

I sync LDAP users and LDAP groups to ownCloud
I then change the name of the LDAP group in LDAP
The change will not be visible in ownCloud
So the change is not propagated from LDAP to ownCloud

So a note or a warning in the User Auth with LDAP in the Group Filter Section is fine with me.

**Comment by mschreml** [comment]
@voroyam done
