### ISSUE TITLE
incorrect or misleading link when explaining where to find a docker-compose.yml file

### ISSUE THREAD

**Issue by maw** [owncloud/docs#2775]
https://doc.owncloud.com/server/admin_manual/installation/docker/ references a `docker-compose.yml` file in https://github.com/owncloud-docker/server, but it doesn't exist:

```
mw@reed:~/src/owncloud/server <master> % find . | rg '(yml|yaml)'
./.github/settings.yml
```

There is a sample `docker-compose.yml` file on the same page, though.  I think you should reference that instead.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by maw** [comment]
https://github.com/owncloud/docs/pull/2776 is my proposed fix for this.

**Comment by phil-davis** [comment]
PR has been merged.
