### ISSUE TITLE
Document new search API

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/docs#278]
Most of the information should be in https://github.com/owncloud/core/pull/31873

https://github.com/owncloud/core/issues/25373#issuecomment-401040193 also contains some interesting information about how to check the available reports for a specific folder.

There is also a capability entry in the OCS capabilities endpoint for this.

**Comment by settermjd** [comment]
Closing, as this was implemented in https://github.com/owncloud/docs/pull/224.
