### ISSUE TITLE
New openid connect config parameter 'allowed-user-backends'

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/docs#2783]
## What Needs to be Documented?
A new config for openidconnect has been added for version 1.0.0
https://github.com/owncloud/openidconnect/pull/100

## Where Does This Need To Be Documented?
openid

## Why Should This Change Be Made? (Optional)
new config option ....

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Fixed in:
https://github.com/owncloud/docs/pull/2830
and some follow up PR´s (text improvements)
