### ISSUE TITLE
Document: system:cron (Execute background jobs as cron) 

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#281]
References: https://github.com/owncloud/core/pull/31914 (Have a real controller handling cron requests)

@DeepDiver1975

**Comment by settermjd** [comment]
You [make a good point](https://github.com/owncloud/docs/issues/281#issuecomment-423923876). I'm thinking that the best option we have is to create an oC 11 milestone and add all PRs to it that only relate to that release.

**Comment by pmaier1** [comment]
This change will be released with Server 10.3 and needs to be documented. The "old" way of executing the basic background job still works but will be removed in a later version. The 10.3 docs should reflect the new way via occ and that the "old" way is deprecated and should not be used anymore.

**Comment by pmaier1** [comment]
We also need to adapt the doc page that covers background job handling https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc

**Comment by settermjd** [comment]
Completed in #1234
