### ISSUE TITLE
Unable to install php_gettext / Ubuntu 20.04.1 LTS - php 7.4

### ISSUE THREAD

**Issue by manuel-owncloud** [owncloud/docs#2853]
When following the manual for installing owncloud from this link:

https://doc.owncloud.com/server/admin_manual/installation/server_prep_ubuntu_18.04.html

I get an error while trying to install the PHP- extensions: 

```
# PHP extensions needed to use ownCloud
sudo apt install php-mysql php-mbstring php-gettext php-intl php-redis \
     php-imagick php-igbinary php-gmp php-bcmath php-curl php-gd php-zip \
     php-imap php-ldap php-bz2 php-ssh2 php-phpseclib
```
Error:

(E: Unable to locate package php-gettext)

(Using Ubuntu 20.04.1 LTS and php 7.4)

**Comment by manuel-owncloud** [comment]
@mmattel

**Comment by phil-davis** [comment]
I see the same - on Ubuntu 18.04 I can install php-gettext. On 20.04 there is no such package. It seems that you can `sudo apt install gettext` and it should do the job.

**Comment by phil-davis** [comment]
What do we do about documenting little differences for 16.04 18.04 20.04...?

**Comment by mmattel** [comment]
Hello @manuel-owncloud the documentation describes the installation for Ubuntu 18.04. The package `php-gettext` is currently not available for Ubuntu 20.04, pls see: https://launchpad.net/php-gettext/+packages. You can continue installating your environment. Pls also see the purpose of php-gettext (https://launchpad.net/php-gettext/):
`This library provides PHP functions to read MO files even when gettext is not compiled in or when appropriate locale is not present on the system.`
The suggestion to install gettext of @phil-davis above is correct.
Thanks for writing the issue!

> What do we do about documenting little differences for 16.04 18.04 20.04...?

Cloning and renaming the document to 20.04 and adopting to the specifics and the changes

**Comment by phil-davis** [comment]
> Cloning and renaming the document to 20.04 and adopting to the specifics and the changes

The challenge becomes keeping up-to-date and correct the instructions for different OS+releases

**Comment by manuel-owncloud** [comment]
Thank You for your help! Appreciate it :) @mmattel 

And thank you for the solution @phil-davis!!! :)
