### ISSUE TITLE
Document "accept shares" feature

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/docs#286]
I guess the root ticket is https://github.com/owncloud/enterprise/issues/557

@settermjd I'm not sure if you need more information.

**Comment by micbar** [comment]
@settermjd @michaelstingl 
Please clarify, is there something left to be documented?

**Comment by settermjd** [comment]
I'm currently checking this at the moment, @micbar.

**Comment by settermjd** [comment]
During research for this issue, I lodged [an issue in core](https://github.com/owncloud/core/issues/35952), because incorrect HTTP status codes are returned when pending shares are unsuccessfully declined, and pending shares are declined on multiple occasions.

**Comment by voroyam** [comment]
Isse was closed with comment: https://github.com/owncloud/core/issues/35952#issuecomment-519059040

Can this issue be closed?

**Comment by jvillafanez** [comment]
no problems on my side
