### ISSUE TITLE
CORS White-listed Domains add examples

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/docs#2869]
## What Needs to be Documented?

CORS White-listening URIs had be limited in favor of https://tools.ietf.org/html/rfc6454
we should provide examples for the users, which statements are legal:

- http://example.com (usual http domain)
- https://example.com (usual https domain)
- http://example.com:80 (usual domain including port)
- http://127.0.0.1 (protocol + ip)
- http://127.0.0.1:8080 (protocol + ip + port)
- 

or illegal:

- ftp://example.com (only http/https portocols are allowed)
- http://*/path (paths are not allowed, including the '/' path)
- http://*?user=jan (query parameters are not allowed)
- http://user:password@* (user and password are not allowed)
- http://*#sorted (fragments are not allowed )

## Where Does This Need To Be Documented?

modules/user_manual/pages/personal_settings/security.adoc

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
**Note:**
To be written in master and then, if already present, backport to the 10.6 branch.
If upcoming PR merged to master before the 10.6 brach is created, no backport needed as 10.6 contains all merged PR´s from master.

@HieronymusPerro  Thanks for creating the issue

**Comment by JanAckermann** [comment]
Backport needed for 10.6

**Comment by mmattel** [comment]
Closing in favour of #38101
