### ISSUE TITLE
Document: Adding background:queue commands: status and delete

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#287]
https://github.com/owncloud/core/pull/31630 (Adding background:queue commands: status and delete)

**Core PR already merged**

Note:
https://github.com/owncloud/core/issues/31727 (Harmonize printout: background:queue/execute commands)
https://github.com/owncloud/documentation/issues/4180 (Document: Add background:execute occ command for running cron jobs manually)

**Comment by mmattel** [comment]
@phil-davis @DeepDiver1975 @PVince81
Because of
https://github.com/owncloud/core/pull/34783 ([stable10] Adding background:queue commands: status and delete), 
do I get this right that this will appear in 10.2, a doc PR needs to be filed and it must not be backported.

@settermjd

**Comment by voroyam** [comment]
Seems like PR is merged. Closing
