### ISSUE TITLE
[QA] add 10.6 branch

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#2870]
Server 10.6.0beta1 and RC1 are built using https://doc.owncloud.com/server/10.5/user_manual/ownCloud_User_Manual.pdf
For the final we need 10.6 branch there.

**Comment by phil-davis** [comment]
And for the next week (or so...) it will be easy to wait before branching. Then we will automagically capture whatever good doc changes we make in master, without having to bother doing backports of every PR.

**Comment by jnweiger** [comment]
TODO;
* [ ] review open PRs, merge e.g. https://github.com/owncloud/docs/pull/2858
* [ ] create a 10.6 branch
* [ ] prepare update of https://gitea.owncloud.services/devops/websites/src/branch/master/ansible/roles/docs/templates/config.j2
* ... anything else?

**Comment by mmattel** [comment]
closing, branch has been created
