### ISSUE TITLE
Remove All branches from online docs except last 2.

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2871]
here https://github.com/owncloud/docs/blob/master/site.yml

![image](https://user-images.githubusercontent.com/24212810/100344833-ba057900-2fe1-11eb-920a-716ec68d16b6.png)

I think it makes sense to remove branches that are too old. Remove: 
    - '10.3'
    - '10.2'
    - '10.1'

It should be only the current branch of the current release (NEW) and the previous branch of the last release (Current).
Currently it would mean that only the 10.5 and 10.4 would stay online.
The 10.3, 10.2, 10.1 would remain on the site but only as a PDF download.

Reason for this is primarily our search. It displays all the entries in each branch. If you search for WND it will display the article of the appliance 5 times. The max search results you get are 7 and then you have to scroll til

**Comment by mmattel** [comment]
I fully agree that search is a mess.
It would be better to aggregate results based on the branches for better selectivity.
I hear quite often, that there are too many companies around using versions lower than 10.4
For a decision I suggest adding and asking @pmaier1 and/or @micbar about their pov.

**Comment by voroyam** [comment]
fixed. now we have only master, 10.6, 10.5

![image](https://user-images.githubusercontent.com/24212810/110409456-972a3c80-8087-11eb-99fc-2fc525929f21.png)
