### ISSUE TITLE
Allow admin to blacklist groups for the files_sharing app

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#288]
Core: 
https://github.com/owncloud/core/pull/31672 (Allow admin to blacklist groups for the files_sharing app) 
--> merged
https://github.com/owncloud/core/pull/31740 ([stable10] Sharing blacklist groups stable10) 
--> open

It is something that is shown on the settings panel 
(apps/files_sharing/lib/Panels/Admin/SettingsPanel.php)
and
(apps/files_sharing/templates/settings.php)

Quote:
```
These groups will not receive shares. 
Members of the group can still send and receive shares outside of the group
```
This new info should be described in the panel documentation.

**Comment by micbar** [comment]
![screenshot_2019-03-04 settings - owncloud enterprise edition 1](https://user-images.githubusercontent.com/4378513/53723639-757a9700-3e68-11e9-8c0d-9016acedcd20.png)

Does that help?
We need to document this.

**Comment by voroyam** [comment]
@mic thanks. This helps.

@jvillafanez @mmattel this is the documentation repo, not the "here, we have something new. You figure out how to deal with it and document it while you are doing it"- repo.

Putting a little effort in describing your new feature that you want / you need to be documented goes a long way.

**Comment by voroyam** [comment]
https://doc.owncloud.com/server/admin_manual/configuration/files/file_sharing_configuration.html#blacklist-groups-from-receiving-shares

already implemented
