### ISSUE TITLE
Extract code samples to includeable files

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#289]
In the current documentation (using AsciiDoc/Antora build as a reference point), there are a number of [inline code samples](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code). The list below gives an approximation.

---

   1 Objective
   1 apache
   1 text
   2 yaml
   3 asciidoc
   3 conf
   4 css
   5 apacheconf
   6 sql
   7 javascript
   9 java
  13 json
  14 bash
  16 js
  20 objective
  22 html
  22 nginx
  62 xml
 141 console
 315 php

The list was compiled using `grep -r -P '(?<=source,)([a-zA-Z]*)' --only-matching --include="*.adoc" ./* | awk -F ":" '{print $2}' | sort | uniq -c | sort`. It doesn't cover all code examples, but should cover the majority of them.

---

What I propose doing is extracting these out into examples files and then using an [include directive](https://docs.antora.org/antora/1.0/asciidoc/include-content/#include-example) to include them again. The reasons for this are:

- They can be linted and validated.
- They can be reviewed in IDEs and code editors.
- They're easier to check and review.
- They're easier to organise and maintain.

**Comment by settermjd** [comment]
More than likely, @voroyam.

**Comment by voroyam** [comment]
So can we close this or has it not yet been finished? What is the status? 

I have seen this in the style guide document.

**Comment by settermjd** [comment]
It's a work in progress.

**Comment by settermjd** [comment]
After looking at this in-depth yesterday, quite a bit of time will be required to implement it, and I'm not sure how much benefit it will offer. Yes, each of the code samples will be lintable and can be run through QA tools, a la PHPCS etc. But will the tradeoff be worth it, if it's done as one large PR. I'm thinking that this should be done as a smaller set of PRs in among all the other tasks, than as one big one.

**Comment by settermjd** [comment]
Will do this periodically.
