### ISSUE TITLE
Install ownCloud on Ubuntu 20.04

### ISSUE THREAD

**Issue by Akidxx** [owncloud/docs#2896]
This is an ultra-short guide to installing ownCloud on a fresh installation of Ubuntu 20.04. Run the following commands in your terminal to complete the installation.

**Prerequisites**  

-  A fresh install of Ubuntu 20.04 with SSH enabled.

- This guide assumes that you are connected as the root user.

- This guide assumes your ownCloud directory is located in /var/www/owncloud/

**Preparation**

First, ensure that all of the system packages and repositories are entirely up to date.To do so, follow the instructions below:

apt update && \
  apt upgrade -y

**Create the occ Helper Script**

Create a helper script to simplify running occ commands.

FILE="/usr/local/bin/occ"
/bin/cat <<EOM >$FILE
#! /bin/bash

cd /var/www/owncloud
sudo -u www-data /usr/bin/php /var/www/owncloud/occ "\$@"
EOM

Make helper script executable:

chmod +x /usr/local/bin/occ

**Install the Required Packages**

apt install -y \
  apache2 \
  libapache2-mod-php \
  mariadb-server \
  openssl \
  php-imagick php-common php-curl \
  php-gd php-imap php-intl \
  php-json php-mbstring php-mysql \
  php-ssh2 php-xml php-zip \
  php-apcu php-redis redis-server \
  wget

Note : php 7.4 is default version installable with ubuntu 20.04

**Install the Recommended  Packages**

the package php-smbclient was removed from the offical repository, so you have to add ondrej’s ppa:
You will need the php-smbclient from ondrej

sudo add-apt-repository ppa:ondrej/php
sudo apt-get update

echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/php.list

and add the key:

apt-key adv --recv-keys --keyserver hkps://keyserver.ubuntu.com:443 4F4EA0AAE5267A6C

Now you can install the recommended pachages using the following command 
apt install -y \
  ssh bzip2 rsync curl jq \
  inetutils-ping smbclient\
  php-smbclient coreutils php-ldap

**Installation**

Configure Apache

Change the Document Root

sed -i "s#html#owncloud#" /etc/apache2/sites-available/000-default.conf

service apache2 restart

**Create a Virtual Host Configuration**

FILE="/etc/apache2/sites-available/owncloud.conf"
sudo /bin/cat <<EOM >$FILE
Alias /owncloud "/var/www/owncloud/"

<Directory /var/www/owncloud/>
  Options +FollowSymlinks
  AllowOverride All

 <IfModule mod_dav.c>
  Dav off
 </IfModule>

 SetEnv HOME /var/www/owncloud
 SetEnv HTTP_HOME /var/www/owncloud
</Directory>
EOM

**Enable the Virtual Host Configuration**

a2ensite owncloud.conf
service apache2 reload

**Configure the Database**

mysql -u root -e "CREATE DATABASE IF NOT EXISTS owncloud; \
GRANT ALL PRIVILEGES ON owncloud.* \
  TO owncloud@localhost \
  IDENTIFIED BY 'password'";

**Enable the Recommended Apache Modules**

echo "Enabling Apache Modules"

a2enmod dir env headers mime rewrite setenvif
service apache2 reload

**Download ownCloud**

cd /var/www/
wget https://download.owncloud.org/community/owncloud-10.5.0.tar.bz2 && \
tar -xjf owncloud-10.5.0.tar.bz2 && \
chown -R www-data. owncloud

**Install ownCloud**

occ maintenance:install \
    --database "mysql" \
    --database-name "owncloud" \
    --database-user "owncloud" \
    --database-pass "password" \
    --admin-user "admin" \
    --admin-pass "admin"

**Configure ownCloud’s Trusted Domains**

myip=$(hostname -I|cut -f1 -d ' ')
occ config:system:set trusted_domains 1 --value="$myip"

**Set Up a Cron Job**

Set your backgroud job mode to cron

occ background:cron

echo "*/15  *  *  *  * /var/www/owncloud/occ system:cron" \
  > /var/spool/cron/crontabs/www-data
chown www-data.crontab /var/spool/cron/crontabs/www-data
chmod 0600 /var/spool/cron/crontabs/www-data

**Configure Caching and File Locking**

Execute these commands:

occ config:system:set \
   memcache.local \
   --value '\OC\Memcache\APCu'

occ config:system:set \
   memcache.locking \
   --value '\OC\Memcache\Redis'

occ config:system:set \
   redis \
   --value '{"host": "127.0.0.1", "port": "6379"}' \
   --type json

**Configure Log Rotation**

Execute this command to set up log rotation.

FILE="/etc/logrotate.d/owncloud"
sudo /bin/cat <<EOM >$FILE
/var/www/owncloud/data/owncloud.log {
  size 10M
  rotate 12
  copytruncate
  missingok
  compress
  compresscmd /bin/gzip
}
EOM

**Finalise the Installation**

Make sure the permissions are correct

cd /var/www/
chown -R www-data. owncloud

ownCloud is now installed. You can confirm that it is ready to use by pointing your web browser to your ownCloud installation.

**Comment by voroyam** [comment]
Did you just add the ondrej repo and the note about php 7.4 and that's the whole "rewrite"?

**Comment by Akidxx** [comment]
Yes I just added the 2 notes about adding the ondrej repo and about php 7.4 but I will edit it, it was the first draft..

**Comment by voroyam** [comment]
So you did only 2 edits to my guide and you spelled Ubuntu wrong... `ubunto`

Please correct it and prepare a Pull Request. As these are the only 2 edits, and the rest of the guide is still correct - I would expect that it still works. Please test it on a clean 20.04 UbuntU before making the PR.

**Comment by voroyam** [comment]
Where is the PR?

**Comment by voroyam** [comment]
fixed with.

https://github.com/owncloud/docs/pull/2987


thanks to @Akidxx for the great work.
