### ISSUE TITLE
Document: Add background:execute occ command for running cron jobs manually

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#290]
References: https://github.com/owncloud/core/pull/31617 (Add background:execute occ command for running cron jobs manually)

@butonic

**Comment by mmattel** [comment]
NOTE: this will be 10.2 only, no backporting, label is set !

**Comment by phil-davis** [comment]
In `stable10` the `background` commands are now:
```
 background
  background:ajax                     Use ajax to run background jobs.
  background:cron                     Use cron to run background jobs.
  background:queue:delete             Delete a job from the queue
  background:queue:execute            Run a single background job from the queue
  background:queue:status             List queue status
  background:webcron                  Use webcron to run background jobs.
```
In `modules/admin_manual/pages/configuration/server/occ_command.adoc` I can see words about ajax, cron, webcron. But nothing yet about `background:queue:*`

All 3 `background:queue` commands have been recently added to core `stable10`. So doc needs to be added to cover all 3.

**Comment by mmattel** [comment]
For ease of implementation, see following link, this just needs some copy / paste and adoption to .adoc :smile: https://github.com/owncloud/documentation/pull/4207/files#diff-0380163502e27936a0c96cf3eb64fe58R269

**Comment by voroyam** [comment]
seems fixed as PR for this issue was merged. Closing
