### ISSUE TITLE
10.0.8 changelog issue on owncloud.org/changelog/server/ (unreleased)

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#294]
**10.0.8 tells the status ``Unreleased``**
![image](https://user-images.githubusercontent.com/3321281/39469402-4c79dcca-4d38-11e8-9bb6-a2de5a894441.png)

**Please see here how it would be expected**
![image](https://user-images.githubusercontent.com/3321281/39469436-72be8318-4d38-11e8-9d80-fa7b7ff9f39d.png)

Link: https://owncloud.org/changelog/server/

**Comment by michaelstingl** [comment]
> I proposed just to add the following text on top: `The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)`

The text is there. @mmattel close now?

**Comment by mmattel** [comment]
closing
