### ISSUE TITLE
Advice on Upgrade PHP on RedHat 7 and CentOS 7 in admin_manual breaks version consistency on updates

### ISSUE THREAD

**Issue by schomaecker** [owncloud/docs#2943]
## WHAT Needs to be Documented?

The advice in the admin_manual for "Upgrade PHP on RedHat 7 and CentOS 7" to...
cp /opt/rh/httpd24/root/etc/httpd/modules/librh-php73-php7.so /etc/httpd/modules/
...breaks the version consistency between the running Apache-PHP-Module and PHP itself (PHP Modules).

It should be a better solution to edit /etc/httpd/conf.modules.d/15-rh-php73-php.conf and change the path of the Apache-PHP-Module.

From...
LoadModule php7_module modules/librh-php73-php7.so
...to...
LoadModule php7_module /opt/rh/httpd24/root/usr/lib64/httpd/modules/librh-php73-php7.so

If it's done this way, no manual interaction is needed after updates to the PHP and Apache-PHP-Module packages.

## WHERE Does This Need To Be Documented (Link)?

https://doc.owncloud.com/server/admin_manual/maintenance/upgrading/upgrade_php.html#update-the-apache-configuration-files-3

## WHY Should This Change Be Made?

Copying the PHP-Apache Module from the /opt/rh/httpd24/root/etc/httpd/modules/ path into /etc/httpd/modules breaks the consistency between the versions of the Apache-PHP-Module and the PHP installation on updates.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by voroyam** [comment]
ownCloud docs are Ubuntu only. For RedHat and CentOS please refer to our forum: https://central.owncloud.org/
