### ISSUE TITLE
Developer Guide: php-cs-fixer

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#295]
This is a reminder that this needs to be documented in the developer guide when the referenced PR gets merged: https://github.com/owncloud/core/pull/31198 (php-cs-fixer fix . --rules=native_function_invocation) 

- [x] document php-cs-fixer owncloud-codestyle checker #1963 
- [ ] document `squizlabs/php_codesniffer` used on acceptance test code @phil-davis

**Comment by phil-davis** [comment]
Re-opening and assigning myself to write a few words about `squizlabs/php_codesniffer`
