### ISSUE TITLE
Missing documentation in Fixing Invalid Code Integrity Messages for missing file error message 

### ISSUE THREAD

**Issue by enbrnz** [owncloud/docs#2994]
## WHAT Needs to be Documented?

The documentation on Code Signing has a `How-to` section which explains the different error messages. However the message `FILE_MISSING` is not specifically explained. 

```
Results
=======
- web
	- FILE_MISSING
		- .htaccess

Raw output
==========
Array
(
    [web] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => 85ad7b1b88ad984f11f7f24f84e6aa9935eb75a36c50bf08efdbc5c295e67b3762a1bfacd8f981fb33e5c7c30d65eff7ebd6a47cb1f0de24e936a71cca2f023e
                            [current] => 
                        )

                )

        )
```

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/admin_manual/configuration/general_topics/code_signing.html#fixing-invalid-code-integrity-messages

Line 77, perhaps my example can just be copied in to the current example and explained as an extra point (5.)

## WHY Should This Change Be Made?
Documentation is incomplete otherwise

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by voroyam** [comment]
I think it is already documented but maybe wrong.

It's listed in Errors under `MISSING_FILE`. Maybe we should simply correct this to `FILE_MISSING`.

![image](https://user-images.githubusercontent.com/24212810/103594442-fdb0a400-4ef8-11eb-8f87-738b0b3505b8.png)

**Comment by enbrnz** [comment]
Thanks for pointing that out, I didn't notice it before. 
This highlights another issue as this part seems to be for developers looking to implement code signing, as it says in the text to edit the `signature.json` which an admin should never do.

In the Technical Information part it should document the steps an admin has to do when they encounter that error in their ownCloud instance. 

However the difference between these two parts of the documentation are not very obvious, as neither you or me noticed them immediately.

I think we should clarify which part is for admins and which for developers. Fix the `Errors` part in the dev section and add an explanation what an admin should do if they encounter this issue in the section I initially highlighted.
