### ISSUE TITLE
Issue related to dep html-entities v2.x 

### ISSUE THREAD

**Issue by xoxys** [owncloud/docs#3014]
Build was broken after merging https://github.com/owncloud/docs/commit/653cf01b12b243c6f25d972e9bec1c716ee26c26 two weeks ago... Someone needs to check how to upgrade. Second issue: The related PR was **not** failing for whatever reason maybe that's a caching thing.

The master branch is fixed again, I've downgraded the dependency to v1.x

@phil-davis Can you pin html-entities to v1.x in dependabot?

**Comment by phil-davis** [comment]
Yes, the PR passed the docs-validate docs-build etc steps. So I assumed that everything was fine, and the new major version was good-to-go (that whatever backward-compatibility breaks it had, they did not effect us)

Actually there needs to be someone who knows and understands the workflow and dependencies... of all this, and who can make informed decisions about this stuff. I really don't know who that is.
