### ISSUE TITLE
Change "Finalise the installation" to "Finalise the Upgrade" in Upgrade docs

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#3026]
## WHAT Needs to be Documented?
- [x] "Finalise the installation" should be rephrased to "Finalise the Upgrade" since it's an upgrade documentation. #3148 
- [x] The Anchor has to be changed as well - this happens automagically when the docs are generated and published

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/admin_manual/maintenance/manual_upgrade.html#finalize-the-installation

## WHY Should This Change Be Made?
Because it's coherent. 

## (Optional) What Type Of Content Change Is This? 
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual

**Comment by jnweiger** [comment]
Please consider using "finalize" instead of "finalise" -- ownCloud documentation follows US spelling.

**Comment by phil-davis** [comment]
https://doc.owncloud.com/server/admin_manual/maintenance/manual_upgrade.html#finalize-the-upgrade is now available.
