### ISSUE TITLE
Change X-XSS-Protection "1; block" -> "0"

### ISSUE THREAD

**Issue by ho4ho** [owncloud/docs#3037]
## WHAT Needs to be Documented?

- Change X-XSS-Protection "1; block" to "0"
- Why now "0" using

Reasons why:

https://github.com/OWASP/CheatSheetSeries/issues/376#issuecomment-602663932:

> I've been studying this issue for a while and it's *dangerous* to set this header. It makes sites that are not vulnerable to XSS, vulnerable.
> ...
> Developers need to either remove the header or set it to zero, I think the debate is over. There is NO good reason to set this header to blocking mode.

and:

https://github.com/helmetjs/helmet/issues/230#issuecomment-611904252
https://github.com/helmetjs/helmet/issues/230#issuecomment-611706715
https://github.com/helmetjs/helmet/issues/230#issuecomment-614106165

## WHERE Does This Need To Be Documented (Link)?

https://doc.owncloud.com/server/10.6/admin_manual/configuration/server/harden_server.html#serve-security-related-headers-by-the-web-server

## WHY Should This Change Be Made?

Explain why changed X-XSS-Protection "1; block" to "0"
https://github.com/owncloud/core/pull/38305
https://github.com/owncloud/core/issues/38236

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Closed via #3664
