### ISSUE TITLE
Transition plan from sphinx-doc to Antora

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#304]
It is well past time to migrate the ownCloud documentation away from sphinx-doc to something simpler, something more forgiving, something easier for developers to use. After a lot of research, Antora has been settled on as the platform of choice to migrate to. 

[Antora](https://antora.org) is based on [the Asciidoctor toolchain](https://asciidoctor.org) and ultimately [the AsciiDoc file format](https://asciidoctor.org/docs/what-is-asciidoc/). This format is a simpler and easier to learn for all concerned and the toolchain is easier to install. The end-effect of this is that it should encourage developers to be more engaged in maintaining the documentation. 

### Antora's Benefits

- Easier to set up, whether as a CI build or locally for developers, writers and other maintainers.
- Builds on a well-supported file format, AsciiDoc.
- Builds on a well-supported toolchain, Asciidoctor.
- Designed to make technical documentation creation and maintenance easy.
- Provides a default UI theme that uses UI conventions that most users have learned and are used to.

![Antora default UI](https://user-images.githubusercontent.com/196801/37710972-9dd99a0e-2d0f-11e8-8f2a-53a2c0a45680.png)

  1. Standard left-hand side content navigation structure
  2. Standard top-level / high level navigation structure
  3. Standard breadcrumb navigation links
  4. Project version switcher

- The default UI theme provides a switcher, which allows users to switch between various versions of a manual.

![Antora project version switcher](https://user-images.githubusercontent.com/196801/37710980-a4d042cc-2d0f-11e8-84d7-91f128f89b93.png)

Available both from the bottom of the left-hand side navigation panel or on the far right-hand side of the breadcrumb navigation, this lets you change between different versions of documentation, so you can quickly match the version of the documentation with your installed software version. Secondly, you don't have to remember URLs.

### AsciiDoc's Benefits

- A documented file format.
- Similar syntax to Markdown, which most developers are already familiar with.
- Consistent syntax conventions, that will make it easier to learn, quickly.
- A strong toolchain, using common languages (_Ruby_ and _JavaScript_).
- Exports to a large range of formats, including _HTML_, _PDF_, _ePub_, & _Mobi_.
- Individuals files can be previewed natively, using _browsers_, _text editors_, and _IDEs_.
- Readable by non-developers.
- Significant learning resources available. 

### Challenges & Limitations

As sphinx-doc uses a series of extensions to the reStructuredText file format, which is the base file format that sphinx-doc uses, there is no one tool that can completely migrate sphinx-doc content to AsciiDoc (or any other format). 

Given that, migration from the current sphinx-doc implementation will not be able to be 100% automated. A majority of the content can be exported using tooling, but the exported content will need to be manually checked and finalised.

#### Migration

- [ ] Setup base installation
- [ ] Settle on documentation structure (one monolithich manual, or separate, siloed, manuals)
- [ ] Script up the migration of content from each manual to AsciiDoc
  - [ ] Migration of core content
  - [ ] Migration of navigation (currently a WIP)
- [ ] Review exported AsciiDoc documentation for errors and non-migratable content
- [ ] Setup a new Jenkins build process for the Antora-based documentation
  - [ ] Integrate linters/validators into the build process

#### Ancilliary Tasks

- [ ] Create a project bootstrap script to make creating new manuals quick and easy.

#### Demos

- [ ] Create introductory documentation, blog post, & videos
- [ ] Antora introductory demo
- [ ] AsciiDoc introductory demo

### Available Content

- ownCloud Styleguide
- [Asciidoc cheatsheet (short)](https://github.com/powerman/asciidoc-cheatsheet)

### Browser plugins 

  - [Chrome](https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia?hl=en)
  - [Firefox](https://addons.mozilla.org/en-US/firefox/addon/asciidoctorjs-live-preview/)

### Editor/IDE plugins

  - [SublimeText](https://github.com/SublimeText/AsciiDoc)
  -  [Atom](https://atom.io/packages/asciidoc-preview)
  - [Vim](https://github.com/dahu/vim-asciidoc)
  - [PhpStorm](https://plugins.jetbrains.com/plugin/7391-asciidoc)
  - [Emacs](https://www.emacswiki.org/emacs/AsciiDoc)
  - [Eclipse](https://marketplace.eclipse.org/content/asciidoc-tools)
  - [NetBeans](https://blogs.oracle.com/geertjan/asciidoctorj-and-netbeans-ide)
  - [Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode)

**Comment by michaelstingl** [comment]
Everything Antora now 👍
