### ISSUE TITLE
duo MFA generate, save, clear settings and advanced button not clickable.

### ISSUE THREAD

**Issue by axelseetoh** [owncloud/docs#3059]
## WHAT Needs to be Documented?
<img width="309" alt="problem" src="https://user-images.githubusercontent.com/50671764/105564095-a06f7c00-5d5b-11eb-8dd3-936a7e3ce7b4.png">

Clicking on any of the button does not load anything nor lead to anywhere. How do I fix this problem? 

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by michaelstingl** [comment]
Please report the issue in https://github.com/elie195/duo_provider/issues
