### ISSUE TITLE
config-to-docs run necessary if core PR gets merged

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#3060]
When the core PR https://github.com/owncloud/core/pull/38337 (Encryption: new config.sample parameter to define the file format) gets merged, a `config-to-docs` run must be made to transport the changes into the documentation. No backporting to 10.6 or below as this is a new functionality only available with an upcoming release of core.

@karakayasemi @jvillafanez @phil-davis FYI

**Comment by mschreml** [comment]
done!

#3360
