### ISSUE TITLE
Theming update needed

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#307]
- In a running instcance / settings:
![image](https://user-images.githubusercontent.com/3321281/37647837-8e91ebb0-2c2d-11e8-8490-1fc673b7fb7d.png)
Following the given link: https://doc.owncloud.org/server/10.0/developer_manual/core/theming.html
(btw should´t that be ``latest`` instead of ``10.0`` ?)
But in ``admin_manual/configuration/server/email_configuration``  you see another description at the bottom about eMail configuration.
This confusing, inconsistent and needs imho improvements.

- Try to find theme development guides...
Currently this is in core which has imho historical backgrounds.
This should be moved to ``latest/developer_manual/theming``
![image](https://user-images.githubusercontent.com/3321281/37660069-d0b5df32-2c51-11e8-93e3-a138d12a6b5d.png)

Note: ``latest`` and a new location for theming need a new link for core

- In case of improving the text, consider adding content to describe 
  - Issue https://github.co:m/owncloud/core/issues/29094 (No signature validation for theme apps)
  PR https://github.com/owncloud/core/pull/30819 (Add a config option to ignore missing signature)

**Comment by voroyam** [comment]
link now points to https://doc.owncloud.org/server/10.6/developer_manual/core/theming.html


fixed.
