### ISSUE TITLE
Guide the admin, how to run proper occ commands in a docker installation

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/docs#3071]
## WHAT Needs to be Documented?
We need to document, how to run occ commands in a docker environment.

## WHERE Does This Need To Be Documented (Link)?
admin_manual/installation/docker/index.html#configuration/server/occ_command

## WHY Should This Change Be Made?
Admins (also devs) gets confused while running the ordinary `php occ` command, leads to errors. 
It is important to show that the `occ` command must be run without the php prefix, to work properly in docker environment. 

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by JanAckermann** [comment]
Backport highly recommended.

**Comment by phil-davis** [comment]
Fixed by #3072 

@JanAckermann close?
