### ISSUE TITLE
User Manual: describe settings : section : personal

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#308]
If you look on https://doc.owncloud.org/server/latest/user_manual/, there is no part describing the personal settings section. There are many parts that are worth describing it especially for first time users or users who look for a particular answer in this section as they see items in the browser and want to know what it is about.

The left is the doc, the right is the personal settings page.

![image](https://user-images.githubusercontent.com/3321281/36792698-897309f8-1c9b-11e8-99a9-27a081f097e4.png)

**Comment by voroyam** [comment]
@michaelstingl what is your opinion on this matter?
