### ISSUE TITLE
Review occ user:setting command docs

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#310]
Due to the introduction of the accounts table in ownCloud 10 the `occ user:setting` command does not work anymore as it's documented. Especially the examples given in https://doc.owncloud.com/server/10.0/admin_manual/configuration/server/occ_command.html#setting-a-setting do not work anymore. 

We plan to add a new command `occ user:modify` to enable changing a user's mail address or display name again, for example. https://github.com/owncloud/core/issues/30529

We need to check for all `occ user:setting` commands if they are still valid and replace the invalid ones with `occ user:modify` once implemented.

**Comment by settermjd** [comment]
Closing, as it appears that the required changes have been implemented, starting in 61e5bc21b4e566149bbba4a1c5fb5e80c319546c.
