### ISSUE TITLE
Need to document the usage of symfony event dispatchers

### ISSUE THREAD

**Issue by sharidas** [owncloud/docs#312]
Recently we have made changes in the core, by using symfonys dispatcher events. Basically the intention is to call the before and after events. These before and after events can be used by apps or any listener of the events. The before event has an array which carries the details to be used by the listener. Similarly for after event we have an array of key value pairs for the event listener.  The after events are triggered if the after event array has at least an element and if the closure returns true. This rule applies for before event too. As an example user can try :
```
class Foo {
     use EventEmitterTrait;
     public function __construct() {
       //Do something
    }

    public function hello($world) {
         return $this->emittingCall(function () use (&$world) {
         }, ['before' => [$world], 'after' => [$world]], 'test', 'fun');
    }
}
```
In this example emittingCall is the function which does the magic to call events `test.beforefun` and `test.afterrun`. 

Arguments to `emittingCall`:
- Closure
- an array with `before` and `after` indices.
- A class name. like `file`, `user` etc ( basically a string )
- An event name. This is also a string

**Comment by settermjd** [comment]
@sharidas, do you still need https://github.com/owncloud/docs/issues/312 implemented?
