### ISSUE TITLE
SEO: Canonical URLs for documentation versions

### ISSUE THREAD

**Issue by guruz** [owncloud/docs#314]
Noticed for example by @hurradieweltgehtunter

If I google for ```owncloud client documentation``` I get sitelinks to outdated pages:
https://doc.owncloud.org/desktop/1.8/
https://doc.owncloud.org/desktop/1.8/advancedusage.html
https://doc.owncloud.org/desktop/2.1/
https://doc.owncloud.org/desktop/2.2/

We're at 2.3 or even 2.4!

Can we use https://support.google.com/webmasters/answer/139066?hl=en#6 for the 10-20 most returned URLs and point them to the specific file in the /latest/ subdirectory?
I think this should be best for Google..

(Can also be done with a HTML tag, but then the files would need to be modified or re-generated with the tag. Maybe easier to just make the HTTP server return more headers..)

(I don't think we should do redirects..)

**Comment by guruz** [comment]
Still an issue, e.g. this guy follows 2.3 documentation (see his link)
https://central.owncloud.org/t/building-owncloud-client-on-windows-10/17730

As I proposed above we could add HTTP headers to the server config for the most requested pages.
```
Link: <http://www.example.com/downloads/white-paper.pdf>; rel="canonical" 
```

**Comment by guruz** [comment]
This is not done yet.
When I search for ownCloud client documentation I get 1.8

> ownCloud Desktop Client Manual - ownCloud Documentation
https://doc.owncloud.org/desktop/1.8/

**Comment by settermjd** [comment]
Who manages access to Google Search Console?

**Comment by hurradieweltgehtunter** [comment]
currently me
