### ISSUE TITLE
Desktop: Document how the crash reporter can be turned off

### ISSUE THREAD

**Issue by guruz** [owncloud/docs#318]
It can be done via the config dialog.
But sometimes you'd want to turn it off from outside so you can debug on-startup-crashes.

Example for macOS: https://github.com/owncloud/client/issues/6191#issuecomment-347182142
https://github.com/owncloud/client/issues/6191#issuecomment-347182142

**Comment by michaelstingl** [comment]
@dschmidt another one for you?
