### ISSUE TITLE
Update the `adding a License Key` method

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/docs#3180]
## WHAT Needs to be Documented?
The new way of adding an enterprise license key. The method has changed for Server 10.5.+ from the need to adding the key to the `config.php` file to simply adding the key via the WebUI.

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/admin_manual/enterprise/installation/install.html#license-keys

## WHY Should This Change Be Made?
We should update that part of the docs to cover the new license key mechanism.
Has to go into master and should be backported to 10.5. 

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by pmaier1** [comment]
Thanks for creating the ticket. Should be updated, yes. The way via config.php still works as well and I think there's a way to do it via occ.

**Comment by mschreml** [comment]
fixed with #3361
