### ISSUE TITLE
App Development: Unit-Testing not clear

### ISSUE THREAD

**Issue by cortho** [owncloud/docs#320]
The documentation https://doc.owncloud.org/server/latest/developer_manual/core/unit-testing.html#running-php-unit-tests-for-owncloud-10-0 did not help me without further research.

What I found out:
* "_To run test for a specific app with the provided PHPUnit version, change into `<webroot>/apps/<appnname>/<testfolder>` and call `<webroot>/lib/composer/phpunit/phpunit/phpunit` plus optional parameters when needed._" was not working for me. In my app I have this structure:
tests
┣ integration
┃┗ ...
┣ unit
┃┗ ...
┣ bootstrap.php
┗TestCase.php
  -> I had to change into `<webroot>/apps/<appnname>/` and call phpunit from there
  -> The optional parameters are meaning phpunit parameters I guessed
* When I have a directory structure like in the notes app https://github.com/owncloud/notes/tree/master/tests I cannot get phpunit running with the provided information
* A recommended basic structure would have been a big time-saver for me

**Comment by settermjd** [comment]
@phil-davis, can you help out here?

**Comment by phil-davis** [comment]
apps "should" have their own ``make test-php-unit``
You change into the app root folder and then just ``make test-php-unit`` - it should load whatever dependencies... that it needs and then run the unit tests.
@DeepDiver1975 this is the theory, true?

I just tried with ``customgroups`` and with ``systemtags_management`` (random apps that I have in my development computer) and they both worked.

And we just need to find any out-of-date app infrastructure and give them a working ``make test-php-unit``.

**Comment by settermjd** [comment]
@phil-davis, I'm having a look at this now and on quick scan, very few of the default apps in my development/testing installation have a Makefile. The ones that do are encryption, files_external, and market. It might just be my installation though.

**Comment by phil-davis** [comment]
"apps" that are actually part of core do not have their own `Makefile` - comments, dav, federatedfilesharing, federation, files, files_external, files_sharing, files_trashbin, files_versions, provisioning_api, systemtags, updatenotification.

apps that are in their own repo 95% have `Makefile` - activity, files_pdfviewer, oauth2 (a couple of examples from about 40 apps that I have cloned from github)

**Comment by settermjd** [comment]
> "apps" that are actually part of core do not have their own `Makefile` - comments, dav, federatedfilesharing, federation, files, files_external, files_sharing, files_trashbin, files_versions, provisioning_api, systemtags, updatenotification.
> 
> apps that are in their own repo 95% have `Makefile` - activity, files_pdfviewer, oauth2 (a couple of examples from about 40 apps that I have cloned from github)

Thanks for the clarification regarding the internal apps.
