### ISSUE TITLE
App Development: fix database.xml in tutorial

### ISSUE THREAD

**Issue by cortho** [owncloud/docs#321]
Since I read that the xml is not in use any more the initial database must be created with the migrations syntax as well at https://doc.owncloud.org/server/10.0/developer_manual/app/tutorial.html#database

**Comment by VicDeo** [comment]
@cortho I'd say migrations are preferable but schema is still supported, we haven't deprecated it yet

**Comment by settermjd** [comment]
> @cortho I'd say migrations are preferable but schema is still supported, we haven't deprecated it yet

Thanks for the clarification, @VicDeo.

**Comment by cortho** [comment]
@VicDeo thank you. I was not aware of this. However, especially for a developer who is new to ownCloud this might be confusing, which db creation/variant to use

**Comment by settermjd** [comment]
@VicDeo, can this now be close?

**Comment by VicDeo** [comment]
https://github.com/owncloud/docs/pull/2103 clarifies that migrations are preferable.
