### ISSUE TITLE
Document on how to add custom icons to settings page

### ISSUE THREAD

**Issue by sharidas** [owncloud/docs#325]
There is a small change made to the settings panel to add custom icons (https://github.com/owncloud/core/pull/29358)
Prior to this change, a user can specify the icons residing at `core/core/img` location. Now it has been updated. 

An app developer can have their own icons located at `core/apps/$(appname)/img`. `img` is the folder name. Just place it in that location and then use the old API. For example, lets take a look at the snippet: https://github.com/owncloud/core/blob/master/lib/private/Settings/SettingsManager.php#L204
In this example encryption section gets the password icon from core. 

Now, let's say user places an icon `gnu.svg` inside the encryption app folder as `img/gnu.svg`. Then the user can use: `new Section('encryption', $this->l->t('Encryption'), 85, 'gnu')` to get the gnu image displayed in the panel.

If the user follows something like this to create the settings: https://github.com/owncloud/firewall/blob/master/lib/AdminSection.php#L33
Then just return the name of the svg file excluding the extension. Just like: `return 'gnu';`

**Comment by settermjd** [comment]
@sharidas, is this issue still required? 

I have been having a read through the documentation and found an example under http://localhost:8080/server/10.1/developer_manual/app/tutorial/development_environment.html#appinfoapp-php, which seems to already document what this issue requires, specifically, the following line:

```php
// The icon that will be shown in the navigation, located in img/
'icon' => $urlGenerator->imagePath('ownnotes', 'ownnotes.svg'),
```

**Comment by sharidas** [comment]
@settermjd This method plays the vital role in the PR mentioned in the ticket: https://github.com/owncloud/core/blob/master/settings/Controller/SettingsPageController.php#L119-L130
In essence it would first search for the image in "appPath/img/", if not available then it would fetch the icon from the section object. So it avoids blindly fetching the image from the section object ( which it was doing previously ). Let me know if you need further clarification on this.

**Comment by settermjd** [comment]
That's fine. Thanks for letting me know.
