### ISSUE TITLE
Add SMBv2 and beyond instructions for smb.conf to the installation part of documentation

### ISSUE THREAD

**Issue by zapotah** [owncloud/docs#326]
Add instructions for adding SMBv2 and beyond configuration to /etc/samba/smb.conf now that SMBv1 has been officially deemed extremely unsecure and removed from all windows server and windows 10 operating systems by default.

These two lines _need_ to be added to smb.conf for php-smbclient to work at all in modern environments. For whatever reason just adding minimum version does not suffice for php-smbclient but maximum protocol version has to be defined...

client min protocol = SMB2
client max protocol = SMB3

without these, owncloud silently fails mounting remote SMB shares with normal logging debug output with no way to see what the issue actually is without 'wnd.logging.enable' => true.

**Comment by voroyam** [comment]
2 Years without progress. closing
