### ISSUE TITLE
new config parameter http.cookie.samesite

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/docs#3260]
https://github.com/owncloud/core/pull/38458

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
For more details on the three values see:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by mmattel** [comment]
Beside a `config-to-docs` run, a note must be made in https://doc.owncloud.com/server/admin_manual/configuration/user/oidc/ for setting this key

**Comment by jnweiger** [comment]
> For more details on the three values see:
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

While that is the perfect reference, it cannot make the connection from our rather obscure login error message "Unable to determine state" to this setting.

**Comment by mmattel** [comment]
> it cannot make the connection from our rather obscure login error message...

well said, this leads to the point if the error message could be improved in core.
@DeepDiver1975 can you pls give us an insight why this was made so and if freely creatable improve the error message?
It is a bad way to find nice words in docs for a improvable error message...

**Comment by mschreml** [comment]
done!

#3360
