### ISSUE TITLE
New docs branch needed: 10.7

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#3278]
The release process for 10.7.0 has started. Entering beta phase now.

When we enter RC phase I'd like to have https://doc.owncloud.com/server/10.7 operational.

**Comment by phil-davis** [comment]
Agree, best to leave it until "close to release" to minimize the amount of constant backports that have to be done.

**Comment by jnweiger** [comment]
The beta tarballs currently contain the 10.6 user manual pdf. 
This needs to become a 10.7 manuals when "close to release" -- challenge accepted :-)

**Comment by mmattel** [comment]
FYI, I would like to get #3337 merged first, as it enables proper pdf creation, also for 10.5.
When this is done, we can go for 10.7 as with that, 10.5 will be phased out (keeping only two releases active)

**Comment by jnweiger** [comment]
10.7.0 reached Codefreeze. Buidling RC1. 
Please prepare the 10.7 branch do be online by the end of this week. In particular an shiny new pdf is needed when building the final 10.7.0
https://doc.owncloud.com/server/10.7/user_manual/ownCloud_User_Manual.pdf

**Comment by mmattel** [comment]
Closing, fixed by #3367
