### ISSUE TITLE
installation instruction for different distributions (additional to Ubuntu procedure)

### ISSUE THREAD

**Issue by skriesch** [owncloud/docs#330]
Different distributions have got  different installation instructions. We offer only Ubuntu for ownCloud 10 at the moment.

We need that for openSUSE Leap/SLES and RedHat, too.
You can use [https://github.com/iosifidis/owncloud-opensuse-leap](url) as an example for openSUSE.

**Comment by settermjd** [comment]
Closing, as there are instructions for Ubuntu 16.04 LTS Server, SLES (SUSE Linux Enterprise Server) 12, RHEL (RedHat Enterprise Linux) 7.2, and Centos 7
