### ISSUE TITLE
Incorrect API endpoint for share creation

### ISSUE THREAD

**Issue by enbrnz** [owncloud/docs#3300]
## WHAT Needs to be Documented?
https://doc.owncloud.com/server/developer_manual/core/apis/ocs-share-api.html#create-a-new-share
Is showing as API endpoint `ocs/v1.php/apps/files_sharing/api/v1/shares/pending`
However the actual endpoint is `ocs/v1.php/apps/files_sharing/api/v1/shares`

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/developer_manual/core/apis/ocs-share-api.html#create-a-new-share

## WHY Should This Change Be Made?
It's currently wrong

BTW, the examples seem to be correct already.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by phil-davis** [comment]
I think that this got mixed up in a big refactoring "a year or 2 ago". Whoever fixes this particular error, it would be good to scan through as many API docs as you can to see if there are other "accidents"

**Comment by voroyam** [comment]
yeah, found this PR https://github.com/owncloud/docs/pull/3165

**Comment by mmattel** [comment]
Fixed with #3488 (The share api endpoint does not end in /pending)
Closing
