### ISSUE TITLE
Update Anti-Virus Documentation

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#333]
- [x] "ClamAV is the only officially supported virus scanner available for use with ownCloud. It:"". "It" looks chopped off. Move "It:" to newline and drop initial capitalisation.
- [x] "operating system ... mac". Change "mac" to "macOS" (plus grep for other references)?
- [x] Quick link at the top of a longer page, directly to the sections within it, such as down to integration with owncloud
- [ ] "Back to the top" link. Something like https://www.jqueryscript.net/animation/Scroll-To-Top-Button-backToTop.html could be worth while. [A new docs-ui issue](https://github.com/owncloud/docs-ui/issues/new) would be required to implement this.
- [x] "Enabling the Antivirus App for Files" - add something with ownCloud maybe: "Settings -> Admin -> Apps.", or Admin -> settings -> apps. _Existing path relates to an older version of ownCloud._
- [ ] ~~"It should already be enabled.". It's now under the "disabled apps", so needs to be enabled.~~
- [x] Update the screenshot for the latest version
- [x] "Configuring ClamAV within ownCloud" -> "Log" configuration
  - [x] Next, go to your ownCloud Admin page and set your ownCloud logging level to Everything."
  - [x] It's the general tab in the Settings page.
- [x] "Now, navigate to Settings -> Admin -> Additional, where you’ll find the “Antivirus Configuration” panel. There, as below, you’ll see the configuration options which ownCloud will pass to ClamAV.". After the previous step, you are already in the settings tab, now you just have to go to the Security Tab

### Mode Configuration

- [x] why is the screenshot after the daemon, daemon socket has no screenshot, and the screenshot for daemon socket is under daemon. should change

#### Deamon (socket)

- [x] "In this mode, ClamAV runs in the background on the same server as the ownCloud installation",  or the socket is made available via a share mount.

**Comment by settermjd** [comment]
@pmaier1, can you review the changes in this PR and confirm if all of the requirements have been met?

**Comment by pmaier1** [comment]
> @pmaier1, can you review the changes in this PR and confirm if all of the requirements have been met?

Well, https://github.com/owncloud/docs/issues/333#issuecomment-394714462 is more than one year old now and I don't remember exactly. I think my only point here was that an admin who sets virus scanning up in a production environment has to properly configure the app before enabling it using `occ config:app:set files_antivirus`. Otherwise the installation will not accept any uploads until the app is configured properly.
