### ISSUE TITLE
Delete tag changes need to be adjusted on user manual

### ISSUE THREAD

**Issue by karakayasemi** [owncloud/docs#3336]
## WHAT Needs to be Documented?
https://github.com/owncloud/core/pull/38498
Delete tag functionality has changed. Previously, a system tag could be deleted within the rename step.
Now, users can delete tags directly from the system tags tab view dropdown menu.

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/user_manual/files/webgui/tagging.html#delete-tags

## WHY Should This Change Be Made?
Behavior has changed.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [x] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by JanAckermann** [comment]
No backport required

**Comment by EParzefall** [comment]
@karakayasemi @micbar The documentation appears to be up to date with regard to deleting system tags in the dropdown menu, but according to the release notes, the tags dialog on the right-hand side is gone, when you click on the overflow menu. Correct? If so I'll update the section accordingly.

**Comment by karakayasemi** [comment]
![image](https://user-images.githubusercontent.com/14157973/112171162-a91dea80-8c04-11eb-8856-fd0dd50e5ce0.png)

As you can see from above, the delete button no more appearing after clicking to pencil icon (inside of the rename operation). The user can directly delete a tag from dropdown in Tags tab.

**Comment by EParzefall** [comment]
Great, thank you. Now I also have access to a 10.7 installation.

**Comment by EParzefall** [comment]
Fixed by #3391, closing.
