### ISSUE TITLE
"Table of Contents" does nothing

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#335]
![owncloud_documentation_overview_ _owncloud_documentation](https://user-images.githubusercontent.com/214010/29132223-d52f450c-7d2f-11e7-9b2d-114685bb68d9.png)

Clicking the "Table of Contents" link does exactly nothing on https://doc.owncloud.org/ https://doc.owncloud.com/

**Comment by settermjd** [comment]
Closing, as this isn't an issue in the new docs, that are set to be released this week.
