### ISSUE TITLE
Redis is 6379 und not 6397 (typo)

### ISSUE THREAD

**Issue by orgaralf** [owncloud/docs#3354]
## WHAT Needs to be Documented?

Wrong Port in the ownCloud Documentation: https://doc.owncloud.com/server/admin_manual/configuration/server/security/oauth2.html

Redis is 6379 und not 6397 (typo)
doc.owncloud.com
OAuth2

## WHERE Does This Need To Be Documented (Link)?

https://doc.owncloud.com/server/admin_manual/configuration/server/security/oauth2.html

## WHY Should This Change Be Made?

Typo

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Thanks a lot @orgaralf we will fix this!

**Comment by mschreml** [comment]
fixed!

backported to 

10.6 - #3356
10.5 - #3357
