### ISSUE TITLE
Document WND 2 Major Release Features

### ISSUE THREAD

**Issue by micbar** [owncloud/docs#3377]
## WHAT Needs to be Documented?

We have a new feature which is called "Collaborative SMB". Now we can use files on a external smb storage for collaborative editing Document editors. Before this change, every user could only get access to files on an external storage with an individual fileID. 

This Feature is really a "new" thing, It will be shipped as WND 2 in a 2.0.0 Release.
The legacy WND implementation will not change.

The WND 2 implementation uses a "service account" for accessing the windows files. See detailed description below.

# WND2 implementation

Basic expected setup
------------

windows machine
* AD installed
* SMB2 share accessible (SMB should also work)
* Service account -> any user with read access to the whole target SMB share should do.

ownCloud
* user_ldap connected to the windows' AD
* WND2 (collaborative) mount:
  - authentication: "login credentials, saved in DB" or "user entered, saved in DB"
  - configuration: connected to the windows machine. Service account matching the one in the windows machine
  

Things to test
-------------
1. `occ wnd:set-service-account` command encrypts the password without disrupting the mount (users can access to the mount normally)
2. oc_filecache table will only register the storage for the service account independently of the users accessing to it
3. any file access by the users will use their own accounts (based on the authentication method)
    1. if a user doesn't have read permission over a file in the windows machine, that user shouldn't be able to see the file listed
    2. if a user who doesn't have read permission over a file see the file listed (could happen due to desync*), the user will receive an error trying to open the file
    3. if a user doesn't have write permission over a file, the user will see the file but will get an error when he tries to write it
    4. ownCloud's permissions will reflect the windows' file attributes, but not the ACLs for a specific user
4. Password reset feature (when the password changes in windows) must work
    1. for the service account, it must work regardless of the wnd authentication (in the mount config)
    2. for specific auth methods, "login credentials, saved in DB" won't work (not implemented), and "user entered, saved in DB" must work
    3. "username and password" and "global credentials" should also be reset if applicable
    4. password reset feature must work across WND and WND2 storages. This means that if a WND triggers a password reset, WND2 storages will also be affected (if applicable), and viceversa
5. wnd listener must work and must update the filecache info without issues
    1. process-queue should also be "affected" by the password reset feature
6. memcache will be used (not tested if it isn't available) using a ttl of 30 minutes by default. It's possible to disable by setting a negative number in the config.php file (config key in the readme file)
    1. we'll cache things by oc storage, which using the basic expected setup would be almost the same as cache per user.

(*) desync could happen because changing permissions in the windows machine won't trigger a change in the mtime, so the change won't be visible to ownCloud

Additional setups
------------

Along with the basic setup:

ownCloud:
* guests app installed
* WND2 (collaborative) mount:
  - authentication: "username and password"
  - configuration: connected to the windows machine. Service account matching the one in the windows machine
  - applicable: guests group

This will allow guests users to access to the windows machine using all of them the same account (probably more restricted)
The same expectations explained in the "things to test" are applied in this case.

Notes
-------

* Password reset feature applies only to "user entered, saved in DB", "username and password" and "global credentials", as well as the service account. The rest of the auths won't reset the password
* As said, password reset feature works across WND and WND2 mounts.
* Using any auth for the WND2 implementation should work, although there might not be a real use case for them.
* Permissions:
  * We'll use only the windows' file attributes as ownCloud permissions. This should cause less problems in ownCloud because the ownCloud permissions will be the same for the service account and the user
  * ACLs won't be taken into account. In practice, this means that the user is allowed to upload files and windows will return an error if he hasn't enough permissions to do so.
  

## WHERE Does This Need To Be Documented (Link)?

Admin Docs, only relevant for 10.7.0 and windows_network_drive 2.0.0

IMO we need a dedicated section and explain the difference between WND 1 and WND 2

### WND 1
- Existing implementation, no collaborative editing of files possible

### WND 2
- New implementation, colaborative editing, needs a "service user"

## WHY Should This Change Be Made?

- New Feature needs to be documented
- The existing functionality will still be available as WND1

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by jnweiger** [comment]
If possible, please also include a clear differentiator between SMB and WND mount options. They are alternatives to each other with possibly different advantages and disadvantages. Each of them has a "collaborative" and "normal/personal" flavour. 
I could offer some guesswork.

**Comment by voroyam** [comment]
@micbar speaking only for my self, but this is very difficult to document.

There is a reason why I changed the template to give the answers the doc team needs to know:

- what
- where (link to doc]
- why

You can’t just put a link in the what section and leave the why section empty.

Each new feature needs an introduction, installation and configuration section.

Please provide the missing information:

Where does this needs to be documented [ if a new page then what section ] 
What is this feature? Why was it developed, what advantages does it provide, what limitations does it have, what prerequisites do you need to have?

**Comment by micbar** [comment]
@voroyam added the missing info.

I don't know where this should be published -> docs team decision.

If we need a call with engineering, no problem. This is really a new feature and a breaking change.

BUT the existing WND implementation will still be supported.

**Comment by mmattel** [comment]
Closing, fixed with https://github.com/owncloud/docs/pull/2739

**Comment by pmaier1** [comment]
If I'm not mistaken, only the Activity integration feature has been taken care of. The other new feature, Collaborative SMB, is still undocumented (https://github.com/owncloud/windows_network_drive/issues/332). Let me know if I'm just missing it.

**Comment by mmattel** [comment]
Missing CWND fixed with: https://github.com/owncloud/docs/pull/3529
