### ISSUE TITLE
Add Google Analytics or Piwik to the documentation & Setup Google Search Console

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#338]
As a matter of urgency, we need to get Google Analytics setup for the documentation, along with Google Search Console. I'm happy to do it if necessary. This will help us know which sections of the documentation are most in demand, as well as help us know about errors and any related issues.

**Comment by tboerger** [comment]
Is this issue still relevant? Piwik is already integrated into the docs, just missing a colon within the URL.

**Comment by michaelstingl** [comment]
FYI @MichaelvanLaar

**Comment by tboerger** [comment]
This had been disabled since Antora 2.0.0, but I have started to reintroduce it as part of the search feature base on environment variables provided to the build process: https://github.com/owncloud/docs-ui/blob/96523904323ec202fe68dd6497f10d24e42a3901/src/partials/head-scripts.hbs

**Comment by MichaelvanLaar** [comment]
> FYI @MichaelvanLaar

Thanks for the info. I have to get an overview of the web analytics implementation and configuration anyway. ;-)
