### ISSUE TITLE
Add sitemap.xml generation to the documentation build process

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#339]
There's no [sitemap.xml](https://www.sitemaps.org/protocol.html) file for the documentation. Given that it's hard to influence the indexing and re-indexing of the documentation by the various search engine bots; essential as the content is updated so often. 

Please update the documentation build process to build a sitemap.xml file for the documentation, after a PR is merged to any of the branches. 

To simplify the process, I've created [a small package](https://github.com/owncloud/owncloud-documentation-sitemap-builder) to do it. All the instructions for how it works and what to do are in the repository. It's also available via [Packagist](https://packagist.org/packages/owncloud/owncloud-documentation-sitemap-builder).

**Comment by tboerger** [comment]
This will be solved with the new documentation, Antora is generating a `sitemap.xml`.

**Comment by settermjd** [comment]
Pls disregard the previous comment. I found the generated sitemaps.

**Comment by settermjd** [comment]
Closing as Antora generates sitemaps for each module and playbook.
