### ISSUE TITLE
[QA] https://doc.owncloud.com/server/10.7/user_manual/ownCloud_User_Manual.pdf is a 404

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#3398]
* https://doc.owncloud.com/server/10.6/user_manual/ownCloud_User_Manual.pdf works fine.
* https://doc.owncloud.com/server/10.7/user_manual/ownCloud_User_Manual.pdf fails.

All links to PDFs are in https://doc.owncloud.com/server/10.7/#releases
The 10.6 links work, the 10.7 PDF links don't.

**Comment by mmattel** [comment]
@xoxys adding you, maybe you can give more insights what is missing

**Comment by micbar** [comment]
fixed by #3399
