### ISSUE TITLE
admin-transactional-locking link in settings webinterface

### ISSUE THREAD

**Issue by guruz** [owncloud/docs#340]
I have a link here in the oC config interface for my server "Transactional file locking should be configured to use memory-based locking, not the default slow database-based locking. See the documentation ↗ for more information."... but this documentation link points to a 404 .. it points to https://doc.owncloud.org/server/10.0/go.php?to=admin-transactional-locking which goes to 404 https://doc.owncloud.org/server/10.0/admin_manual/configuration_files/files_locking_transactional.html

**Comment by voroyam** [comment]
fixed
