### ISSUE TITLE
occ files_external:list `-i, --importable-format` is missing a trailing backtick

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#3405]
## WHAT Needs to be Documented?
Fix a missing trailing backtick in option`-i, --importable-format` causing bad rendering

## WHERE Does This Need To Be Documented (Link)?
Referencing: https://doc.owncloud.com/server/10.7/admin_manual/configuration/server/occ_command.html#files_externallist

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

Backporting to 10.7 and 10.6 necessary

**Comment by EParzefall** [comment]
Fixed with PR #3406.
