### ISSUE TITLE
Search in desktop docs shows results from server docs

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#341]
On https://doc.owncloud.com/desktop/latest/ , I searched for the string "silent", and got the following result:

![search_ _owncloud_client_manual_2_3_3_documentation](https://user-images.githubusercontent.com/214010/28517664-6eb24b5c-7065-11e7-9698-04bd309dce21.png)
 (URL: https://doc.owncloud.com/desktop/latest/search.html?q=silent&check_keywords=yes&area=default)

**Comment by settermjd** [comment]
This is being closed, as the new search supersedes this.
