### ISSUE TITLE
Appliances look different now, update doc page?

### ISSUE THREAD

**Issue by lefherz** [owncloud/docs#344]
Hey, in the 10.0 appliances you specify your passphrase yourself instead of being given a random one. This site needs to be updated: https://doc.owncloud.org/server/10.0/admin_manual/installation/appliance_installation.html

maybe it would be worth your while to install a test instance and try out what needs to be changed.

**Comment by voroyam** [comment]
no response for a year. issue is not urgent and probably fixed.
