### ISSUE TITLE
upgrade steps out of order

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#3445]
## WHAT Needs to be Documented?
currently the steps are 

https://doc.owncloud.com/server/admin_manual/maintenance/manual_upgrade.html#preparation

- maintenance mode
- stop apache
- backup and rename current installation
- review and disable apps

I would say you first have to disable the apps, and then rename the ownCloud root dir.

## WHERE Does This Need To Be Documented (Link)?

https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/maintenance/manual_upgrade.adoc

## WHY Should This Change Be Made?

because you can not disable apps when you rename the ownCloud folder

----

rest of the steps:

- Download the Latest "Installation" > need to change Installation to something more fitting.
- extract new packages
- copy config 
- copy data
![image](https://user-images.githubusercontent.com/24212810/113702964-7da60000-96da-11eb-8880-cc06ce7b49a6.png)

this font is confusing. Need to switch that out of the note in to normal text and highlight the config setting.

- copy old apps
- change permissions
- start upgrade
- disable maintenance mode
- start apache

second thought:

maybe we could improve the process by preparing the upgrade and then switching over.

**Comment by voroyam** [comment]
`sudo` should be removed from the cp command here

![image](https://user-images.githubusercontent.com/24212810/113711911-c9aa7200-96e5-11eb-9be7-00ed779c37d3.png)


we should split the long command in two lines

**Comment by voroyam** [comment]
@mmattel here are some things that you might coriander when re writing the upgrade section.

**Comment by voroyam** [comment]
and this https://github.com/owncloud/docs/issues/3383

**Comment by mmattel** [comment]
Great - thanks a lot, just drop more if you see something ! 👍

**Comment by voroyam** [comment]
Contact me if you need help writing the upgrade section.
