### ISSUE TITLE
Document reworked password policy feature

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#346]
Currently you only find [this](https://doc.owncloud.com/server/10.0/admin_manual/configuration_files/file_sharing_configuration.html?highlight=password%20policy#password-policy-label) regarding password policy in our docs. The feature has lately been reworked to apply to all password endpoints, not only link shares (e.g. user passwords when creating a user, when a guest user sets a password, when a password is reset, did I miss something?). Therefore it's relation to sharing has also been diluted. We probably should find a new location somewhere around 'security' and link there from the current location.

**Comment by voroyam** [comment]
https://doc.owncloud.com/server/admin_manual/configuration/server/security/password_policy.html

I think this is the solution. closing
