### ISSUE TITLE
9.0 recommended upgrade method

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#349]
https://doc.owncloud.org/server/9.0/admin_manual/maintenance/upgrade.html

From the document:

> How to Upgrade Your ownCloud Server
There are three ways to upgrade your ownCloud server:
Using your Linux package manager with our official ownCloud repositories. This is the recommended method.
>

As far as I know, we don't recommend using the repositories, do we?

**Comment by michaelstingl** [comment]
@voroyam oC 9.0 is EOL for a long time? Update this issue or just close it?
