### ISSUE TITLE
Metrics App is not compatible with IE 11

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#3494]
## WHAT Needs to be Documented?
A hint in the Metrics app documentation that the integrated admin dashboard is not compatible with IE 11 as new technologies have been used that are not supported by IE 11.

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/admin_manual/enterprise/reporting/metrics.html

## WHY Should This Change Be Made?
To make users aware of the limitations.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@mmattel

**Comment by mmattel** [comment]
References: https://github.com/owncloud/metrics/issues/109

**Comment by mmattel** [comment]
Closing with #3618
