### ISSUE TITLE
[OIDC] Add Client ID, Client Secret, Redirect URIs to general OIDC docs

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#3498]
## WHAT Needs to be Documented?
Add Client ID, Client Secret, Redirect URIs to general OIDC docs

![CleanShot 2021-04-23 at 09 58 50@2x](https://user-images.githubusercontent.com/214010/115839786-4db96500-a41b-11eb-9332-a69b5625ef67.png)

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/admin_manual/configuration/user/oidc/oidc.html

## WHY Should This Change Be Made?
Client ID, Client Secret, Redirect URIs from unbranded ownCloud desktop and mobile clients are not specific to the Kopano IdP, they are needed for all IdP's.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by michaelstingl** [comment]
Only Kopano-specific thing is, it doesn't like the `http://localhost:*` syntax:

Related:
- https://github.com/owncloud/openidconnect/issues/125#issuecomment-756042396 (also see following discussion)
- https://github.com/owncloud/appliance/issues/90

**Comment by jnweiger** [comment]
References:
* https://github.com/owncloud/openidconnect/blob/master/README.md
* https://github.com/owncloud-docker/compose-playground/blob/master/compose/kopano/konnect/konnectd-identifier-registration.yaml

**Comment by michaelstingl** [comment]
Please check our new recommended Kopano Konnect: https://github.com/owncloud/ocis/pull/2026/files

**Comment by michaelstingl** [comment]
Client ID's, secrets and redirect URI's are needed for EVERY IdP. That's why it's general information about ownCloud OIDC, and not related to the specific IdP.

IdP's that also support DCR (https://github.com/owncloud/docs/issues/3499) could choose to only use DCR, not the client ID's, secrets and redirect URI's. But then they're limited to the latest client versions. So support a Little older clients, you could register client ID's, secrets and redirect URI's

Azure AD has another speciality why it doesn't work, unrelated to Client ID s, secrets and redirect URI's.

**Comment by michaelstingl** [comment]
@mmattel can be closed?
