### ISSUE TITLE
[QA] Server release notes should be about the server

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#3515]
https://doc.owncloud.com/server/release_notes.html
which is in a very prominent place, but it is 
* outdated and
* mostly irrelevant, as we do not do "releases" of the documentation itself.
* thus irritating and in the worst case leaves a completely false first impression about server development at ownCloud.

Expected behaviour: This prominent place should refer to the server release notes, and also mention the existance of ocis.

This is a follow-up to https://github.com/owncloud/docs/issues/2240 which imho was closed unfixed.

**Comment by mmattel** [comment]
Closed via #3745
