### ISSUE TITLE
Documentation required for switch between master and user specific keys

### ISSUE THREAD

**Issue by sharidas** [owncloud/docs#352]
Regarding the feature to select either master key or user specific key encryption implemented here: https://github.com/owncloud/core/pull/27512 needs documentation.

**Comment by settermjd** [comment]
ping @sharidas. Can you provide further feedback pls?

**Comment by sharidas** [comment]
The idea behind this ticket was to document the master key and user specific key split in the UI. Isn't the UI and command line to achieve master key based encryption or user specific key based encryption documented (from scratch installation)? If we have already documented the masterkey and user specific key with screenshots (for the UI) in the documentation, then this ticket can be closed.

**Comment by voroyam** [comment]
https://doc.owncloud.com/server/admin_manual/configuration/files/encryption/migration-guide.html
