### ISSUE TITLE
SEO: high rankings of old versions

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#3528]
### Whats this issue about?
please document here search requests that return not helpful / outdated / not official search results.

### Whats the goal?

- The goal is to provide most helpful search results from the official ownCloud docs for people who are searching for docs/help. This should increase admin & user experience.
- if we have good solutions documented, they should be upon the top  5 search results

Example searches that have old versions ranked on top:

* owncloud webdav
* owncloud admin manual

**Comment by jnweiger** [comment]
Fyi: @tbsbdr

**Comment by tbsbdr** [comment]
![image](https://user-images.githubusercontent.com/26610733/117270423-7d279300-ae59-11eb-9c77-24b29629c034.png)

**Comment by mmattel** [comment]
![image](https://user-images.githubusercontent.com/3321281/117632511-7f516080-b17d-11eb-9626-361dcf53c05a.png)

**Comment by jnweiger** [comment]
![image](https://user-images.githubusercontent.com/1108546/117657743-38be2f00-b19a-11eb-8d99-7e9ea16be312.png)

**Comment by tbsbdr** [comment]
![image](https://user-images.githubusercontent.com/26610733/120603239-17c0c500-c44c-11eb-8c98-a2419e3815bb.png)

**Comment by jnweiger** [comment]
DuckDuckGo nennt client 1.8 vor 2.4.4 -- beide sehr alt, wir sind bei 2.8

![image](https://user-images.githubusercontent.com/1108546/120809422-52108c00-c54a-11eb-9def-fc558a3a0b2f.png)

----

Google nennt den gleichen 1.8er link auch als erstes, schreibt aber die Versionsnummer nicht dazu, dadurch noch hinterhältiger:

![image](https://user-images.githubusercontent.com/1108546/120809662-9bf97200-c54a-11eb-98d5-e28499136540.png)

**Comment by jnweiger** [comment]
Workaround suggestion:
 - Make a redirect rule, that replaces all client versions older than xxx with 'latest'.

**Comment by jnweiger** [comment]
![image](https://user-images.githubusercontent.com/1108546/122364684-41a0de00-cf5a-11eb-90ca-ef9921cb24e4.png)

**Comment by jnweiger** [comment]
Many queries point to ocloud.de and their 8.0 admin manual. They pop up a nextcloud 21 overlay, when viewing the manual for a while.

**Comment by tbsbdr** [comment]
![image](https://user-images.githubusercontent.com/26610733/124580788-c5126880-de50-11eb-9941-63259dfb45ab.png)

**Comment by xoxys** [comment]
More important, duplicate content produced by multiple domains:
- https://doc.owncloud.org/server/10.7/
- https://doc.owncloud.com/server/10.7/

Its not a redirect right now...

**Comment by tbsbdr** [comment]
Can you think of any bad sideffects if we would redirect all doc.owncloud.org requests to the corresponding .com url? (apart from the effort...) and also I dont know the background of having both subdomains coexisting. the canonical tag is setup up right, but i still experience a lot of .org in my serps so maybe the domainauthority of .org seems to be higher than that of .com.. Changing (sub)domains usualy goes hand in hand with loosing rankings on the short term, but on the long term I think we should provide a single source of truth for the docs-url, just to be clear for the people who try to find the right docs page. what do you think, @xoxys ? 

correct canonical tag:
![image](https://user-images.githubusercontent.com/26610733/125609585-6decc171-2ee4-434c-ac1d-94393b3cc2e5.png)

**Comment by xoxys** [comment]
The historical reason is that we had different documentations/content for community/enterprise version of oC. These days it's not necessary anymore and we should fix it as dotcom and dotorg delivers the exact same content now. The effort for the docs setup is quite low, so I would just do it and fix the web server config to redirect dotorg to dotcom as a first step.

> I think we should provide a single source of truth for the docs-url, just to be clear for the people who try to find the right docs page

Fully agree with you!

**Comment by tbsbdr** [comment]
would be awesome🤩

**Comment by xoxys** [comment]
Lets do it 👍 Will schedule it for next week.

**Comment by mmattel** [comment]
https://github.com/owncloud/docs/pull/3849 (config-to-docs run)

**Comment by mmattel** [comment]
Closing as this has been fixed 😅
