### ISSUE TITLE
Document auto-provision for AzureAD OIDC

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/docs#3537]
## WHAT Needs to be Documented?

When auto provision is not needed you have to set it explicitly to false in order to make OIDC working.

```
 'auto-provision' =>
    array (
      'enabled' => false,
    ),
```
If you want to create the account in ownCloud automatically you can do that with:

```
 'auto-provision' =>
    array (
      'enabled' => true,
      'email-claim' => 'email',
      'display-name-claim' => 'name',
    ),
```
(Example for default Azure AD)

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/admin_manual/configuration/user/oidc/ms-azure-setup.html#example-config-php-setup

## WHY Should This Change Be Made?
It will not work without that information. 

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Fixed with #3631 and #3634
