### ISSUE TITLE
occ encryption:change-key-storage-root is limited to data directory

### ISSUE THREAD

**Issue by PVince81** [owncloud/docs#354]
Change this:
https://doc.owncloud.org/server/10.0/admin_manual/configuration_server/occ_command.html#encryption

and provide an example inside the data directory, ex: "data/allkeys".

An admin can first mount a separate volume to "data/allkeys" if they want the keys to be stored elsewhere.

Add warning that it's not supported to store keys outside of the data directory path.

@settermjd

**Comment by voroyam** [comment]
Need to implement this.

**Comment by voroyam** [comment]
Was already implemented. By me. Is wrong in the old docs, correct in the new docs:

https://doc.owncloud.com/server/administration_manual/configuration/files/encryption_configuration.html#move-key-location

https://github.com/owncloud/docs/blob/master/modules/administration_manual/pages/configuration/files/encryption_configuration.adoc#move-key-location

I was made aware of this on 15 August 2018 on central: https://central.owncloud.org/t/cant-move-key-location/14961/8?u=dmitry

and made a fix (PR) on 15 Aug.

@PVince81 closing this.
