### ISSUE TITLE
Full Text Search - Lost Sibling Page?

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#3547]
## WHAT Needs to be Documented?

"Official" page:
https://doc.owncloud.com/server/admin_manual/configuration/search/

"Hidden" page:
https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command/full_text_search_commands.html
(not in nav, only accessible via search)

## WHERE Does This Need To Be Documented (Link)?

Maybe unite or link here?
https://doc.owncloud.com/server/admin_manual/configuration/search/

## WHY Should This Change Be Made?

User experience could be improved.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Needs to be added as include in the occ main file.

To get rid of these orphans, we need a `find-orphand-adoc` script.
Either a `.adoc` file is included via `xref` or included via `include`

**Comment by mmattel** [comment]
To get rid of this kind of issues, see: https://github.com/owncloud/docs/pull/3556 😄

**Comment by EParzefall** [comment]
Fixed the link to the occ search commands. The file full_text_search_commands.adoc is included via occ_command.adoc.
