### ISSUE TITLE
Add UNIQUE_ID to logging section

### ISSUE THREAD

**Issue by butonic** [owncloud/docs#356]
On https://doc.owncloud.org/server/9.1/admin_manual/configuration_server/logging_configuration.html we should 

- [ ] add a dedicated section on how to install mod_unique_id and and changin the log format to add the unique_id. If the UNIQUE_ID environment variable is present OC will also use it for the owncloud log file, which allows matching log entries from apache to oc and vice versa. 

- [ ] recommend the mod_user_id module for apache in https://doc.owncloud.org/server/9.1/admin_manual/installation/source_installation.html#apache-web-server-configuration with a link to the new section in the logging config

**Comment by settermjd** [comment]
I hadn't heard of mod_unique_id before now, so thanks for the info. I should be able to have this documented tomorrow (all being well).

**Comment by settermjd** [comment]
This has taken a bit of fiddling around with, but I've got it working now. I should have it documented in a PR by tomorrow at the latest.
