### ISSUE TITLE
downgrade from php8.0 to php7.4

### ISSUE THREAD

**Issue by isantanaowncloud** [owncloud/docs#3570]
## WHAT Needs to be Documented?
After running the "apt-get update" command the php version changes from the 7.4 to the 8.0
This way, users can't start ownCloud in the browser.
The solution for this problem is to downgrade from php8.0 to php7.4
Here is a website where it is explained step by step what to do for the downgrade: https://ostechnix.com/how-to-switch-between-multiple-php-versions-in-ubuntu/

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.7/admin_manual/installation/quick_guides/ubuntu_20_04.html

## WHY Should This Change Be Made?
It is a common issue, that we can now solve easily by giving the solution from the start.

## (Optional) What Type Of Content Change Is This? 
- [ x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
@isantanaowncloud thanks for reporting this issue.

There is already a detailed instruction when using multiple-concurrent-php-versions, see link:
https://doc.owncloud.com/server/10.7/admin_manual/installation/manual_installation/server_prep_ubuntu_20.04.html#multiple-concurrent-php-versions

The downside of the quick install guide is, that if you handle all possible options and changes, you end up in the full install guide.

@EParzefall @jnweiger

**Comment by isantanaowncloud** [comment]
I see. But still If the users have a quick look at the link I added in the issue they know how to solve the issue fast, without having to look at the complete manual.

**Comment by mmattel** [comment]
I will add a note for the case if issues arise and link to our corresponding manual (section).
May take some days...
