### ISSUE TITLE
Give a recommendation for a JSON based Apache log file

### ISSUE THREAD

**Issue by butonic** [owncloud/docs#358]
After https://doc.owncloud.org/server/9.1/admin_manual/installation/source_installation.html#additional-apache-configurations add a section on how to make apache log json. Rationale: [structured data](https://www.loggly.com/blog/why-json-is-the-best-application-log-format-and-how-to-switch/) is perfect for machine readable log files.

```
LogFormat "{\"reqId\":\"%{UNIQUE_ID}e\",\"time\":\"%{%Y-%m-%dT%H:%M:%S%z}t\",\"remoteAddr\":\"%a\",\"user\":\"%u\",\"host\":\"%V\",\"method\":\"%m\",\"request\":\"%U\",\"query\":\"%q\",\"status\":%>s,\"userAgent\":\"%{User-agent}i\",\"referer\":\"%{Referer}i\",\"duration\":%D}" jsonlog

CustomLog /var/log/apache2/access_log jsonlog
```

* UIQUE_ID is optional, see https://github.com/owncloud/documentation/issues/2967
* we could also ad bytes received and bytes sent? Requires mod_logio
```
LogFormat "{\"reqId\":\"%{UNIQUE_ID}e\",\"time\":\"%{%Y-%m-%dT%H:%M:%S%z}t\",\"remoteAddr\":\"%a\",\"user\":\"%u\",\"host\":\"%V\",\"method\":\"%m\",\"request\":\"%U\",\"query\":\"%q\",\"status\":%>s,\"userAgent\":\"%{User-agent}i\",\"referer\":\"%{Referer}i\",\"duration\":%D,\"bytesReceived\":%I,\"bytesSent\":%O,\"pid\":%P,\"keepAlive\":%k,\"conStatus\":\"%X\"}" jsonlog

CustomLog /var/log/apache2/access_log jsonlog
```
* maybe if we target ELK this makes more sense: http://untergeek.com/2012/10/11/getting-apache-to-output-json-for-logstash/ but we need to ask someone with logstash know how

**Comment by voroyam** [comment]
no progress after 2 years. closing
