### ISSUE TITLE
Generating a user report includes now guest users 

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/docs#3580]
## WHAT Needs to be Documented?
With this PR https://github.com/owncloud/core/pull/38742 the command occ user::report now includes a new row for guest users count

## WHERE Does This Need To Be Documented (Link)?
https://github.com/owncloud/docs/edit/master/modules/admin_manual/pages/configuration/server/occ_command.adoc

## WHY Should This Change Be Made?
Keep docs in sync

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
@JanAckermann thanksfor reporting the issue.
Can you post an example of the new output which would ease documentation a lot.

**Comment by JanAckermann** [comment]
@mmattel please see linked PR

**Comment by mmattel** [comment]
> @mmattel please see linked PR

I did, but there is no example printout of the new version (at least I have not identified it)
