### ISSUE TITLE
occ command "lifecycle:" for files_lifecycle

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#3584]
## WHAT Needs to be Documented?
Found in: https://doc.owncloud.com/server/admin_manual/enterprise/file_management/files_lifecycle.html

These commands found in: https://github.com/owncloud/files_lifecycle/tree/master/lib/Command
`./occ lifecycle:archive` 
`./occ lifecycle:expired`
`./occ lifecycle:restore`
`./occ lifecycle:restore-all`
`./occ lifecycle:set-upload-time`

## WHERE Does This Need To Be Documented (Link)?
occ command set

## WHY Should This Change Be Made?
Complete the docs

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@jnweiger fyi

**Comment by jnweiger** [comment]
fyi: files_lifecycle 1.3.1 is released.

**Comment by mmattel** [comment]
Closing, fixed by #3607
