### ISSUE TITLE
[QA] add files_antivirus.av_* variables to admin_manual/configuration/server/config_sample_php_parameters.html

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#3586]
As discussed in https://github.com/owncloud/core/pull/38753, https://github.com/owncloud/files_antivirus/issues/442 (and elsewhere :-) ):

```
                | files_antivirus | av_cmd_options       |                           |
                | files_antivirus | av_path              | /usr/bin/clamscan         |
```
are now removed from the oc_appconfig database table, and moved into config.php as 
files_antivirus.av_path and files_antivirus.av_cmd_options

Since files_antivirus-1.0.0-rc2 the admin UI no longer allows editing the variables, but refers to https://doc.owncloud.com/server/admin_manual/configuration/server/config_sample_php_parameters.html

![image](https://user-images.githubusercontent.com/1108546/119061024-a73d9100-b9d3-11eb-90cd-90c32cb63a09.png)

Please update the docs. We plan to release files-antivirus 1.0.0 next week.

**Comment by mmattel** [comment]
1.) see merged core PR: https://github.com/owncloud/core/pull/38753 The content is already present in core
2.) needs a `config-to-docs` run to transport the changes to docs
3.) needs a review of the current `files_antivirus` documentation to reflect the changes made

**Comment by jnweiger** [comment]
![image](https://user-images.githubusercontent.com/1108546/119504423-3e0ba400-bd6c-11eb-98be-f6f9ef6ae5d8.png)

**Comment by mmattel** [comment]
Closing with #3592
