### ISSUE TITLE
occ in the appliance not clearly documented

### ISSUE THREAD

**Issue by cortho** [owncloud/docs#3590]
## WHAT Needs to be Documented?
Running an occ command in the appliance

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/admin_manual/appliance/

## WHY Should This Change Be Made?
Several solutions include the usage of occ which has got examples all over the docs. For the appliance it looks to me, that you first have to enter the docker container and then run occ w/o sudo. This is not documented at all.
Lots of users who are using the appliance do not have operating system knowledge. They will never find how to run such commands in their appliances.

See the questions in central:
https://central.owncloud.org/t/you-need-to-activate-own-theme-to-edit-mail-templates/32221/3
https://central.owncloud.org/t/reindex-files-via-occ-in-docker-appliance/29522
https://central.owncloud.org/t/server-side-encryption-help/13369/5

and several more

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by voroyam** [comment]
You are correct, this has to be better documented.

There are basically 2 ways of using occ for the appliance.

1. log in using `univention-app shell owncloud` and then using occ without sudo because in our docker image we have a wrapper script taking care of it
2. Using occ right on the host system, with `univention-app shell owncloud occ files:sync —all``

**Comment by EParzefall** [comment]
Thanks for reporting this @cortho and thanks to @voroyam for providing the solution.
