### ISSUE TITLE
New occ commands for richdocuments

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#3608]
## WHAT Needs to be Documented?
References:
https://github.com/owncloud/richdocuments/pull/400
https://github.com/owncloud/richdocuments/pull/402

## WHERE Does This Need To Be Documented (Link)?
1) occ app section changes
2) Text changes in `enterprise/collaboration/collabora_secure_view.adoc`

## WHY Should This Change Be Made?
Completeness

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

Backports to 10.7 or below ?

@EParzefall @JanAckermann

**Comment by phil-davis** [comment]
https://github.com/owncloud/richdocuments/issues/401 release 2.6.0 is in progress. So this doc will be a bit ahead. But that should be fine - the release will happen "real soon now" (tm)

**Comment by JanAckermann** [comment]
@phil-davis @mmattel 
We are not quite sure if the customer will give green light to the feature. So I don't feel good have this merged yet, still waiting for feedback.

**Comment by mmattel** [comment]
@JanAckermann @jnweiger nobody told that there is a possible hon-hold issue... Just the other way round - will be part of the next release coming very soon 🤔
