### ISSUE TITLE
Document share permissions and allowed file operations

### ISSUE THREAD

**Issue by PVince81** [owncloud/docs#361]
This was always a bit obscure.
There was a day where I wrote smashbox tests and had to figure them all out.

They are currently documented inline in the code: https://github.com/owncloud/smashbox/blob/master/lib/oc-tests/test_sharePermissions.py#L43.

I've taken them out and put them below for better readability:

Permissions masks:
- **READ** = 1
- **UPDATE** = 2 ("can update" in web UI)
- **CREATE** = 4 ("can create" in web UI)
- **DELETE** = 8 ("can delete" in web UI)
- **SHARE** = 16 ("can reshare" in web UI)

File operations shorthand for the later table:
- **download**: download/read/get a file or display a folder contents
- **upload**: a new file can be uploaded/created (file target does not exist)
- **upload_overwrite**: a file can overwrite an existing one
- **rename**: rename file to new name, all within the shared folder
- **move_in**: move a file from outside the shared folder into the shared folder
- **move_in_overwrite**: move a file from outside the shared folder and overwrite a file inside the shared folder (note: SabreDAV automatically deletes the target file first before moving, so requires DELETE permission too)
- **move_in_subdir**: move a file already in the shared folder into a subdir within the shared folder
- **move_in_subdir_overwrite**: move a file already in the shared folder into a subdir within the shared folder and overwrite an existing file there
- **move_out**: move a file to outside of the shared folder
- **move_out_subdir**: move a file out of a subdir of the shared folder into the shared folder
- **copy_in**: copy a file from outside the shared folder into the shared folder
- **copy_in_overwrite**: copy a file from outside the shared folder and overwrite a file inside the shared folder (note: SabreDAV automatically deletes the target file first before copying, so requires DELETE permission too)
- **delete**: delete a file inside the shared folder
- **mkdir**: create folder inside the shared folder
- **rmdir**: delete folder inside the shared folder

The following lists what operations are allowed for the different permission combinations (share permission is omitted as it is not relevant to file operations):
- READ (aka read-only):
	- download

- READ + CREATE:
	- download
	- upload
	- move_in
	- copy_in
	- mkdir

- READ + UPDATE:
	- download
	- upload_overwrite
	- rename

- READ + DELETE:
	- download
	- move_out
	- delete
	- rmdir

- READ + CREATE + UPDATE:
	- download
	- upload
	- upload_overwrite
	- rename
	- move_in
	- copy_in
	- mkdir

- READ + CREATE + DELETE:
	- download
	- upload
	- move_in
	- move_in_overwrite
	- move_in_subdir
	- move_in_subdir_overwrite
	- move_out
	- move_out_subdir
	- copy_in
	- copy_in_overwrite
	- delete
	- mkdir
	- rmdir

- READ + UPDATE + DELETE
	- download
	- upload_overwrite
	- rename
	- move_out
	- delete
	- rmdir

- READ + CREATE + UPDATE + DELETE (all permissions): 
	- download
	- upload
	- upload_overwrite
	- rename
	- move_in
	- move_in_overwrite
	- move_in_subdir
	- move_in_subdir_overwrite
	- move_out
	- move_out_subdir
	- copy_in
	- copy_in_overwrite
	- delete
	- mkdir
	- rmdir

**Comment by jnweiger** [comment]
![image](https://user-images.githubusercontent.com/1108546/63278700-112d8180-c2a8-11e9-9972-3242f3272ce2.png)

In 10.3 we do not see `[ ] update`. We see `[ ] change` instead. Is it the same?
