### ISSUE TITLE
Correct Apache header information for msteamsbridge

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#3617]
## WHAT Needs to be Documented?
The header information needs the `self` directive to work properly.
`Header merge Content-Security-Policy "frame-ancestors 'self' teams.microsoft.com *.teams.microsoft.com"`
References: https://github.com/owncloud/msteamsbridge/issues/5#issuecomment-833391576

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.7/admin_manual/configuration/integration/ms-teams.html#configure-the-ms-teams-bridge-app

## WHY Should This Change Be Made?
Make access functional

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@tbsbdr @micbar @jnweiger @xoxys 
Please drop a note if `self` should be added.

**Comment by xoxys** [comment]
It **must** be added otherwise it will break other features e.g. pdfviewer.

**Comment by mmattel** [comment]
Closing with: https://github.com/owncloud/docs/pull/3620
