### ISSUE TITLE
Set http.cookie.samesite to 'none' for OIDC

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#3626]
## WHAT Needs to be Documented?
As a prerequisite for a proper working oidc setup, set config value `http.cookie.samesite` to 'none' 

There is a general (small) note in https://doc.owncloud.com/server/admin_manual/configuration/server/config_sample_php_parameters.html#define-how-to-relax-same-site-cookie-settings

but this is not sufficient as nothing is described in 

https://doc.owncloud.com/server/10.7/admin_manual/configuration/user/oidc/ or here: https://doc.owncloud.com/server/10.7/admin_manual/configuration/server/config_apps_sample_php_parameters.html#app-openid-connect-oidc

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/admin_manual/configuration/server/config_apps_sample_php_parameters.html#app-openid-connect-oidc
and
https://doc.owncloud.com/server/admin_manual/configuration/user/oidc/oidc.html

## WHY Should This Change Be Made?
Completeness of docs
Fixes: https://github.com/owncloud/openidconnect/issues/157#issuecomment-855316735

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@IljaN @DeepDiver1975 @tbsbdr @fschade @jerrac fyi

**Comment by jerrac** [comment]
@mmattel Thanks for posting this. The idea of posting a docs issue was half formed in my head, but hadn't made it all the way out. :) 

Would placing the note about the setting [in the prerequisites section](https://doc.owncloud.com/server/admin_manual/configuration/user/oidc/oidc.html#prerequisites) make sense? 

Looking at the context of https://doc.owncloud.com/server/admin_manual/configuration/server/config_apps_sample_php_parameters.html#app-openid-connect-oidc makes me wonder how any note about the cookie setting would actually fit in. Would it make more sense just link to the main app docs at the start of that section? Something like "Make sure to review the main docs *here* so you don't miss any prerequisites."

**Comment by IljaN** [comment]
Here is more info on the why: https://web.dev/schemeful-samesite/
