### ISSUE TITLE
Possible update to devlopment documentation necessary

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#363]
@PVince81 as discussed on IRC

When trying to setup a development environment following https://github.com/owncloud/documentation/blob/master/developer_manual/general/devenv.rst
I ran into some issues. The most important issue was, that ``make`` did not finish sucessfully.

After digging I found the root cause on the failing make.

- It seems that the version from nodejs provided on Ubuntu 16.04 is out of date and does not meet the requirements. Currently ``nodejs`` version from the packte manager is on 4.2.6.
- Because I need to run make under sudo, make fails with ``bower`` because the parameter ``--allow-root`` is not set.

After removing npm and nodejs from the server, I installed 
``nodejs 7.x``
```
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs

sudo nodejs –v
v7.5.0
sudo npm –v
4.1.2
```

``bower``
```
sudo npm i -g bower

sudo bower -v
1.8.0
```

Now, after cloning you can run
``sudo make``

If you get an error at the end like ``bower ESUDO         Cannot be run with sudo``
finalize bower by running: ``sudo bower install --allow-root``

Additional note on ``make``:
I get the following reports. Should that be fixed?
```
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
```

The documentations says to chown directory ``data``.
But this directory is not provided when cloning core and does not extists. You have to manually create it before.
Also, you need to chown the ``config`` directory, else setup does not work.

**Comment by voroyam** [comment]
tried, works.
