### ISSUE TITLE
Document platform-wide known limitations, excluded files

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#365]
- [ ] Folder or file with a space at the end  (trailing spaces) (https://github.com/owncloud/core/issues/28164)
- [ ] .htaccess ([config/config.sample.php](https://github.com/owncloud/core/blob/v9.1.3/config/config.sample.php#L1106))
- [ ] `*.part` files (https://github.com/owncloud/core/issues/7496)
- [ ] too long filenames (https://github.com/owncloud/core/issues/25425, perhaps fixed soon?)
- [ ] [client/sync-exclude.lst](https://github.com/owncloud/client/blob/master/sync-exclude.lst)
- [ ] handling cases (https://github.com/owncloud/core/issues/17161, https://github.com/owncloud/client/issues/1348)
- [ ] Desktop.ini in root (2.4+) ([src/csync/csync_exclude.cpp#L324-L329](https://github.com/owncloud/client/blob/v2.4.1/src/csync/csync_exclude.cpp#L324-L329), https://github.com/owncloud/client/pull/6200)
- [ ] Files with leading dot (example `.12345.pdf`) are handled as hidden files on all plattforms. (user need to activate "sync hidden files" to sync them)
- [ ] … what else ?

@settermjd Where can this be located?

/cc @pmaier1 @hodyroff

**Comment by cdamken** [comment]
@settermjd Could you please add this in the documentation.

IMHO there should be a warning in the server and clients too when a folder or files is created with these limitations. @pmaier1 @michaelstingl
