### ISSUE TITLE
oC 10.7 X-XSS-Protection

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#3660]
## WHAT Needs to be Documented?
How you can configure apache to protect agains X-XXS

## WHERE Does This Need To Be Documented (Link)?

https://doc.owncloud.com/server/admin_manual/configuration/server/harden_server.html

## WHY Should This Change Be Made?
Because since 10.7 you get an error message documented in https://central.owncloud.org/t/oc-10-7-x-xss-protection/32051

**Comment by mmattel** [comment]
Closing via #3664

**Comment by mmattel** [comment]
Same issue: https://github.com/owncloud/docs/issues/3037
