### ISSUE TITLE
Previews Configuration updation

### ISSUE THREAD

**Issue by ho4ho** [owncloud/docs#3674]
## WHAT Needs to be Documented?

Link:

https://doc.owncloud.com/server/10.7/admin_manual/configuration/server/config_sample_php_parameters.html#previews

to:

https://doc.owncloud.com/server/10.7/admin_manual/configuration/files/previews_configuration.html

having better documentation on Preview config?

## WHERE Does This Need To Be Documented (Link)?

Above links

## WHY Should This Change Be Made?

Better docs

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
You are welcomed to file a PR...
