### ISSUE TITLE
New WND config key for Ldapmembership cache

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#3675]
## WHAT Needs to be Documented?
References: https://github.com/owncloud/windows_network_drive/pull/355
New config key

## WHERE Does This Need To Be Documented (Link)?
WND and config.apps.sample in core + a `config-to-docs` run

## WHY Should This Change Be Made?
completeness of docs

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@jvillafanez @JanAckermann

**Comment by mmattel** [comment]
Pls note, that beside the config key addition with the referenced PR, we also need descriptive text in the WND documentation - therefore, when the config key PR has been merged **DO NOT** close this PR, an additional descriptive PR needs to be made.

**Comment by phil-davis** [comment]
@mmattel both PRs above have been merged.

**Comment by mmattel** [comment]
Closing via #3679 and #3687
