### ISSUE TITLE
Login/Install screen got improved for 10.8

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#3685]
## WHAT Needs to be Documented?
We need new login/install screenshots 

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/admin_manual/installation/installation_wizard.html
https://doc.owncloud.com/server/user_manual/webinterface.html

## WHY Should This Change Be Made?
New login screen, references: https://github.com/owncloud/core/pull/38821 (Improve login screen)

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@JanAckermann @JammingBen @hurradieweltgehtunter

**Comment by hurradieweltgehtunter** [comment]
https://github.com/owncloud/docs/pull/3690

**Comment by mmattel** [comment]
closing via #3690
