### ISSUE TITLE
Missing period or other sentence separator

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#3689]
## WHAT Needs to be Documented?
a period

## WHERE Does This Need To Be Documented (Link)?
probably in core

https://doc.owncloud.com/server/10.7/admin_manual/configuration/server/config_sample_php_parameters.html#define-how-to-relax-same-site-cookie-settings

## WHY Should This Change Be Made?
sentence is wrong otherwise

![](https://user-images.githubusercontent.com/24212810/122033150-90227100-cdd0-11eb-8553-79085462b7aa.png)

Issue in core: https://github.com/owncloud/core/issues/38852

**Comment by mmattel** [comment]
Nice catch !
Needs to be fixed in core and transported vai a `config-to-docs` run.
