### ISSUE TITLE
[Meta] Documentation Process

### ISSUE THREAD

**Issue by felixboehm** [owncloud/docs#369]
## Define process for documentation

If things need documentation, what to do?
- open issue in this repo
- search for label "documentation" through all ownCloud repos: 
https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Aowncloud+sort%3Aupdated-desc+label%3Adocumentation
- mention team: @owncloud/doc 

## Documentation Documentation 

Where to put the documentation for the documentation?
- https://github.com/owncloud/documentation/wiki
- https://github.com/owncloud/documentation/blob/master/GETTING_STARTED.rst
- https://doc.owncloud.com/server/9.2/developer_manual/

## Planning for documentation - The Documentation Roadmap

Where do we plan and set priorites our documentation work?
- Create a Project? https://github.com/owncloud/documentation/projects

More options?? Ideas?

**Comment by voroyam** [comment]
2 Year old issue. Don't think that it's still relevant. Please reopen if relevant.
