### ISSUE TITLE
Procedure for publishing a new branded iOS app

### ISSUE THREAD

**Issue by pako81** [owncloud/docs#370]
In regards to the procedure for publishing a new branded iOS app, our documentation is still pointing to the use of  xcarchive:

https://doc.owncloud.com/branded_clients/branded_ios_app/publishing_ios_app_9.html

This is however an obsolete procedure, since xcode-> application loader should instead be used as @michaelstingl explained me. We would need therefore to update our doc accordingly.
@settermjd thanks.

**Comment by pako81** [comment]
did we make any progress in documenting this?

**Comment by michaelstingl** [comment]
> did we make any progress in documenting this?

No, deprecated in a few months because of the new iOS app. @ChrisEdS can assist if necessary.

**Comment by voroyam** [comment]
So in a few months we can close this as it will be deprecated? @michaelstingl

**Comment by michaelstingl** [comment]
> So in a few months we can close this as it will be deprecated? @michaelstingl

yes, exactly

**Comment by voroyam** [comment]
Great

**Comment by settermjd** [comment]
Can this now be closed?

**Comment by voroyam** [comment]
@michaelstingl knows more

**Comment by michaelstingl** [comment]
> Can this now be closed?

Not fixed for old iOS app, and new iOS app can't be published by others yet.

**Comment by settermjd** [comment]
Thanks for the feedback, @michaelstingl
