### ISSUE TITLE
 Use binary encoding setting for HSM

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#3704]
## WHY Should This Change Be Made?
https://github.com/owncloud/encryption/pull/261 is merged, and has a comment
"When merged, docs relevant. Pls file a docs issue."

**Comment by jnweiger** [comment]
Confirmed in encryption 1.5.1-rc1: HSM works fine with both legacy base64 encoding and new binary encoding.

**Comment by mmattel** [comment]
To make it clear, with the upcoming release 1.5.1 of the encryption app, the HSM module correctly works and uses base64 and the new binary encoding (chosen based on the config setting).

This should be noted in https://doc.owncloud.com/server/admin_manual/configuration/server/security/hsmdaemon/

and added via https://github.com/owncloud/docs/pull/3710 (hsmdaemon install consistency and accuracy)

**Comment by mmattel** [comment]
Closed via #3710
