### ISSUE TITLE
Unclear instructions how to add a <security-repo> for openSUSE

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#3711]
https://doc.owncloud.com/server/admin_manual/configuration/server/security/hsmdaemon/softhsm2.html#install-on-opensuse-and-suse-linux-enterprise-server
says

```
If there is no security repository available, then add it using the following command:

# Replace <security-repository> with the URL for your distribution and architecture.
sudo zypper addrepo \
  --check \
  --refresh \
  --name "openSUSE-Leap-15.0-Security" \
  <security-repository> \
  "repo-security"
```

To me that hard part would be to find the URL. Searching the web for security repository and openSUSE brings up almost every update repo, which claims that it contains security updates.

Target audience most likely does not know either. we should provide an example.

OBS search for softhsm brings up only one match for Tumbleweed, not for any released opensuse leap version:
https://software.opensuse.org/package/softhsm?locale=en
https://build.opensuse.org/package/show/openSUSE%3AFactory/softhsm

**Comment by mmattel** [comment]
Your finding is great, but the docs team is not responsible for this text as it was made before we started our work. To get towards a solution, can you provide a (or more) suggestions for an improvement?

Adding @EParzefall
