### ISSUE TITLE
Decryption tests for HSM Daemon

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#3717]
## WHAT Needs to be Documented?
Here is a draft, how we can test both encryption and decryption: https://github.com/owncloud/encryption/issues/263#issuecomment-864616432

## WHERE Does This Need To Be Documented (Link)?
https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc#testing

## WHY Should This Change Be Made?
Only encryption is covered in the docs. Decryption is marked as TODO.

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual -- see link.

**Comment by mmattel** [comment]
Clsoing via #3710
