### ISSUE TITLE
[ownBrander] New branding option within the desktop client for users to update their hardcoded server url between versions 

### ISSUE THREAD

**Issue by rperezb** [owncloud/docs#372]
This latest release of the ownBrander includes a new branding option within the desktop client; Update of server url. This option is expected to be used only if you want to modify the server url to which your customers  will connect from one desktop version to the following one. 

![screen shot 2016-10-04 at 11 16 25](https://cloud.githubusercontent.com/assets/1846927/19071289/99b9d13e-8a2f-11e6-8c65-cc0bbd8be68c.png)

**Comment by michaelstingl** [comment]
Documentation is in the ownBrander itself
