### ISSUE TITLE
Using occ command within docker installation

### ISSUE THREAD

**Issue by carlitox1** [owncloud/docs#3722]
## WHAT Needs to be Documented?
Using occ command within docker installation

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command.html#run-occ-as-your-http-user

## WHY Should This Change Be Made?
docker images provided for owncloud installation does not included the sudo command, so a different way needs to be documented in order to be able to execute occ command within docker containers

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
From the hosts cli and expecting that the current user is allowed to run a docker command:

`docker exec --user www-data <owncloud-container-name> php occ <your-command>`

To be added in the docker description and maybe in the occ command on top pointing to docker...

@EParzefall FYI
