### ISSUE TITLE
Confused on update process on ownCloud installed using Linux metapackage

### ISSUE THREAD

**Issue by dln949** [owncloud/docs#374]
I am sorry, but after reading through the documentation, I am still confused, I am not sure among all the pages and links of documentation which “overrules” the other or how they are to be coordinated with each other, and therefore which I should be following in my case. Thank you in advance for helping to answer these questions.
1. I installed ownCloud 9.1.0 using the linux metapackage “owncloud” for Ubuntu 16.04. The instructions at [https://doc.owncloud.org/server/9.1/admin_manual/installation/linux_installation.html](url) seem to indicate that the way I manage updating is to allow my Ubuntu package manager take care of that. Is that correct?
2. At that same link above, it also says this: “Do not move the folders provided by these packages after the installation, as this will break updates.” The data I want the ownCloud server to make available will NOT be in /var/www/owncloud , instead, it will be in a different location. Will this be a problem for me? If so, what are my options?
3. Still at that same link above, it says this as a final step: “Follow the instructions on the download page to install ownCloud. Then run the Installation Wizard to complete your installation. (see Installation Wizard).” When I read the instructions for the “Installation Wizard” found at [https://doc.owncloud.org/server/9.1/admin_manual/installation/installation_wizard.html](url) , it says the first thing to do is to set strong directory permissions. So, does that mean that installing the Ubuntu metapackage “owncloud” does NOT set the correct permissions, and I need to go through this process of changing them?
4. At the link for the “Installation Wizard”, it says this about setting strong directory permissions: “These strong permissions prevent upgrading your ownCloud server; see Setting Permissions for Updating for a script to quickly change permissions to allow upgrading.” So, does this mean that after I install the Ubuntu metapackage “owncloud”, and after I have had to correct the directory permissions using the bash script, my Ubuntu package manager system/process will NOT work for doing updates because I’ve changed the directory permissions? And, does that mean that in order to do updates, I need to use the script to temporarily change the directory permissions? And, does that also mean that if my Ubuntu package manager cannot do updates, I will have to always update manually, even though the initial installation of ownCloud was via the use of the Ubuntu metapackage “owncloud”? Finally, doesn't this, by making my Ubuntu package manager unable to do updates, contradict what I thought was the case in my question #1 above?  It just seems so contradictory to me that the instructions warn against moving the folders because that will "break updates" (see #2 above) - I am grateful for the warning! - but then later in the instructions it advises to change the permissions, along with a warning that such changes will break updates!  I am so confused.....

**Comment by michaelstingl** [comment]
I think this is super outdated. Please open a new issue in case there's still something to fix.
