### ISSUE TITLE
Publishing apps to the marketplace

### ISSUE THREAD

**Issue by vascowhite** [owncloud/docs#377]
The [documentation](https://doc.owncloud.org/server/9.0/developer_manual/app/publishing.html#app-store-publishing) currently tells a developer **what** they need to do and what standards they need to maintain to get an app published in the app store. However, it does not give any guidence on **how** to go about publishing an app.

There should be a step-by-step guide somewhere that covers at least the following.
- What are the mechanics of the process? 
- How to upload code?
- Some apps can be updated by clicking a button in the apps page of OC, does this require special code, or is it automatic?
- Signing apps

Somebody with a better understanding of the process could probably come up with a better list.

**Comment by PVince81** [comment]
We should check whether we have such instructions for uploading to marketplace

**Comment by settermjd** [comment]
@IljaN, do we have instructions for uploading to the marketplace?

**Comment by IljaN** [comment]
https://doc.owncloud.org/server/10.0/developer_manual/app/fundamentals/publishing.html
https://doc.owncloud.org/server/10.0/developer_manual/app/advanced/code_signing.html?highlight=sign

This is the only documentation I am aware of, the link posted by @vascowhite seems to be outdated.

**Comment by settermjd** [comment]
Having a look at that at the moment.

**Comment by settermjd** [comment]
I've created a trivial app and am waiting for a signed certificate so that I can upload the app to the ownCloud Marketplace, so that I can document the remainder of the process.
