### ISSUE TITLE
Error reported in docs-pdf drone CI step

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs#3774]
https://drone.owncloud.com/owncloud/docs/11820/2/6
```
asciidoctor: ERROR: modules/user_manual/pages/files/encrypting_files.adoc: line 61: include file not found: /drone/src/modules/user_manual/pages/files/admin_manual:/drone/src/modules/user_manual/pages/_partials//configuration/files/encryption/not-encrypted-files.adoc
```

I happened to have drone open and noticed this.

Investigate:
- [ ] why doesn't the drone step fail when there is an error reported like this
- [ ] fix the error

**Comment by mmattel** [comment]
I am on it, seems to be a bug, will report my findings

**Comment by mmattel** [comment]
**Found the cause:**

Long story short, for some unknown historical reason, accessing the partial directory (and others like example) was made using a depreciated method. The new way of doing this is using the so called family directory structure including predefined variable names accessing them, see https://docs.antora.org/antora/2.3/family-directories/  and https://docs.antora.org/antora/2.3/page/resource-id/#requires-family-coordinate
This impacts in particular cross refernces to other modules. While this still works doing a html build, this breaks when doing a pdf build as the partial variable for the directory needs to be assembled as fixed value and handed over on runtime. This binds partials variables always to a module and cant therefore be used when having a interdocument reference and creating a pdf.

**Quick Solution:**
* Have the document in question present in both admin and user manual 🤦‍♂️ 

**Long term Solution:**
* Fix it by using proper family coordinates
