### ISSUE TITLE
Add heartbeat path to excluded SSO paths

### ISSUE THREAD

**Issue by PVince81** [owncloud/docs#379]
Need to add the path "/heartbeat" to the paths that must NOT be redirected to the IDP here: https://doc.owncloud.org/server/8.2/admin_manual/enterprise_user_management/user_auth_shibboleth.html

In case of public upload, there is no other ajax request that would refresh the session. So if a public upload is running longer than the session timeout (or session.gc_maxlifetime), the heartbeat must be made to work to refresh the session. Failure to do so will have the ajax/upload.php call be rejected with "invalid token" because the request token will become invalid as it's stored in the session.
Note that ajax/upload.php uses POST, which means it only hits the OC code after PHP is finished receiving and storing the file to its temp folder, so the upload would not refresh the session until its very end, which is too late.

@DeepDiver1975 @butonic @felixboehm @pako81

**Comment by settermjd** [comment]
Closing as it appears to no longer be required, after discussion with @deepdiver and @michaelstingl.
