### ISSUE TITLE
Remove Community/Enterprise edition links

### ISSUE THREAD

**Issue by xoxys** [owncloud/docs#3794]
## WHAT Needs to be Documented?
Remove the links 

## WHERE Does This Need To Be Documented (Link)?
Header of ever page

![grafik](https://user-images.githubusercontent.com/3391958/124888575-83132f00-dfd6-11eb-827c-afc051dd2d91.png)

![grafik](https://user-images.githubusercontent.com/3391958/124888685-9de5a380-dfd6-11eb-9ded-876d31fa33a3.png)

## WHY Should This Change Be Made?
We don't have different editions anymore. I would suggest removing it from the header completely and add a general link to the footer (replace the Enterprise link in the footer). Besides that, owncloud.org links in the footer should be replaced by owncloud.com to reduce redirects.

**Comment by mmattel** [comment]
Note, this must be done in the docs-ui repo.
Will take care of this next week.
