### ISSUE TITLE
Document side effects of having federated sharing enabled

### ISSUE THREAD

**Issue by danimo** [owncloud/docs#380]
The comfort of federated Sharing comes with a few side effects, such as potentially leaking email addresses with the sharer. This should be documented so the user can make an informed decision on whether or not he wants to disable this feature.

**Comment by PVince81** [comment]
this is likely related to the address book sharing. I think we disabled this by default now

**Comment by settermjd** [comment]
@PVince81, what are the full list of side-effects of having federated sharing (or address book sharing) enabled?
