### ISSUE TITLE
9.1 auth changes

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/docs#382]
This is meta-issue for the auth related changes we need to document.

In 9.1 we added the following features:
- [x] Ability to track/list/kill browser sessions -> https://github.com/owncloud/documentation/pull/2479
- [x] Ability to create/kill device specific passwords -> https://github.com/owncloud/documentation/pull/2479
- [x] Password changes log out connected browsers/devices automatically
- [x] Clients use the device specific password either as password for basic auth ~~or use a new header~~ -> https://github.com/owncloud/documentation/pull/2479
- [x] Admins can enforce clients to authenticate with app specific passwords (login password is blocked then) -> documented via the sample config
- [x] Two-factor auth (which also enforces app specific passwords for devices) -> https://github.com/owncloud/documentation/pull/2479

I can open separate issues with more details next week.

**Comment by settermjd** [comment]
The final outstanding change is documented in #2019.

**Comment by settermjd** [comment]
Closing as the final item in this issue has been implemented, merged, and backported.
