### ISSUE TITLE
Installation manual improvements

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#3842]
## WHAT Needs to be Documented?
We need to document that we recommend to put the data folder outside of the web root directory on new installations as it's written in the hardening your server document:

https://doc.owncloud.com/server/10.7/admin_manual/configuration/server/harden_server.html#place-data-directory-outside-of-the-web-root

This is, in my opinion, missing from the quick installation guide and the detailed installation guide.

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.7/admin_manual/installation/quick_guides/ubuntu_20_04.html
https://doc.owncloud.com/server/10.7/admin_manual/installation/manual_installation/manual_installation.html

## WHY Should This Change Be Made?
Because files which are in the web root folder and are owned by the web server user can be accessed from the web if the admin has not yet configured his web server to forbid access. as documented here:

https://central.owncloud.org/t/how-to-fix-the-htaccess-file-does-not-work-message/823

**Comment by xoxys** [comment]
IMO the hardening guide should be considered as a part of the setup/installation guide. Admins have to read the whole hardening guide before/after/during the initial setup and before you put the server into production. There are a lot of other things described in the hardening guide for a secure setup and you would have to mention all of them in the install guide as well if we want to go this way. 

But maybe there could be a general info at the end/beginning of the install guided that links to the hardening guide as addition resource to read.

**Comment by mmattel** [comment]
Even not explicit mentioned in the detailed install guide, the use of the script guided installation in section `Installation of ownCloud Binaries` implies (highly suggests) using a data directory outside the web root. I agree with @xoxys that having a link somewhere at the beginning of detailed install guide referencing the hardening guide is a good idea. Maybe the hardening guide needs a revision too, tbd.

**Comment by mmattel** [comment]
The hardening guide contains the recommandation to put the data folder outside of the web root directory. With the merged PR #3858, the hardening guide was referenced in the quick and detailed install guides. Closing.
