### ISSUE TITLE
Improved mounting of public links shares

### ISSUE THREAD

**Issue by schiessle** [owncloud/docs#387]
https://github.com/owncloud/core/pull/24771

We improved the way people can add a public link share to their ownCloud. You no longer add  the  URL of your ownCloud to the "add to your ownCloud field", instead you enter your federated cloud id. The owner will then send you a federated cloud share and you will be re-directed to your ownCloud. After login you will get the notification about a new federated share and can accept/decline it.

This way the owner sees in the share dialog every mounted public link as a seperated share, can change the permissions, unshare it, etc.

**Comment by settermjd** [comment]
@PVince81 @DeepDiver1975 is this still required?

**Comment by settermjd** [comment]
@pmaier1 @DeepDiver1975, is this still worth actioning?
