### ISSUE TITLE
Sync Client not syncing

### ISSUE THREAD

**Issue by felixboehm** [owncloud/docs#389]
There are many reasons why it might look like the sync client is not syncing.
Collection of known reasons and checks will help users to resolve their issues.
- Sync client running? 
- Check internet connection? 
- Sync is paused?
- Files / folders not selected to sync in selective sync settings?
- Can you access the files in the web browser?
- If a new file / folder is not synced to your laptop
  - check if your local disc has sufficient free disc space
  - check if the download limit is hit, and acknowledge to sync files in the selective sync view
- Are there conflict files?
- Are the files changed on an external storage (windows network drive mount) on the server? 
- Missing file listed in Activities tab in list "not synched"?
- Are there error messages? Press F12 to find detailed infos in the sync client log

not complete ...

**Comment by settermjd** [comment]
@felixboehm, is this still required?
