### ISSUE TITLE
Cleanup duplicate content

### ISSUE THREAD

**Issue by xoxys** [owncloud/docs#3894]
## WHY Should This Change Be Made?

Currently, ownCloud docs are available at two ULRs:

- doc.owncloud.com
- doc.owncloud.org

This has historic reasons because docs for Enterprise/Community had different content in the past. To optimize SEO and cleanup our setup, I would recommend redirecting doc.owncloud.org entirely to doc.owncloud.com (as we did with owncloud.com already). But that's not that simple right now as we still deliver ownCloud 8 and 9 docs, and we still have to decide between old community/enterprise version in those cases (same for clients).

How should we proceed? Which versions of the docs need to be delivered? We just maintain the latest two releases, but what about very old docs? Keep it forever? Drop after x years?

**Comment by EParzefall** [comment]
In a discussion today with @pmaier1 @mmattel @xoxys @michl19, we decided to only keep the documentation for the latest two releases directly available on doc.owncloud.com as html versions and offer older documentation as PDF files only and keep these on a separate archive site.

**Comment by xoxys** [comment]
First steps are done for server docs:

- Docs for the master branch were renamed to `next` on doc.owncloud.com, see https://doc.owncloud.com/server/next/
- PDF documentation files were renamed and uploaded to the new location, see https://doc.owncloud.com/server/next/releases.html#owncloud-server-releases

**Comment by mmattel** [comment]
@xoxys is there anything we need to do to finalize that `doc.owncloud.org/{uri}` will be fully redirected to `doc.owncloud.com/{uri}` and we can "eliminate" `doc.owncloud.org`

**Comment by xoxys** [comment]
No, thats done.

**Comment by mmattel** [comment]
> No, thats done.

Great, closing this issue, many thanks
