### ISSUE TITLE
404 page returns wrong status code

### ISSUE THREAD

**Issue by JammingBen** [owncloud/docs#3896]
Opening links for a version which does not exist (yet) results in a 404 page, but returns a 302 status code: https://doc.owncloud.com/server/10.9/go.php?to=admin-email

The redirected URL https://doc.owncloud.com/server/10.9/admin_manual/configuration/server/email_configuration.html also shows a 404 page, only this time we get a 200 status code.

Both cases should return a 404 code, just like https://doc.owncloud.com/server/10.9/go.php?to=admin-email2 for example.

Noticed in https://github.com/owncloud/core/pull/39026#issuecomment-887465048

![image](https://user-images.githubusercontent.com/50302941/127162700-652adbff-3dff-4525-a8cc-e7db3acc3ffa.png)

**Comment by JammingBen** [comment]
I don't know who is responsible for such things, @xoxys ?

**Comment by xoxys** [comment]
```
curl -Lo /dev/null --silent --head --write-out '%{http_code}\n' https://doc.owncloud.com/server/10.9/go.php?to=admin-email;
404
```

**Comment by xoxys** [comment]
Same for the page itself...

```
curl -Lo /dev/null --silent --head --write-out '%{http_code}\n' https://doc.owncloud.com/server/10.9/admin_manual/configuration/server/email_configuration.html
404
```

**Comment by xoxys** [comment]
You can not lookup the rc in the browser as what you see is the status for every page/resource and the error page itself got delivered successfully.

**Comment by xoxys** [comment]
- https://doc.owncloud.com/server/10.9/go.php?to=admin-email2 gots a 404 in the browser because the webserver does not know this url
 - https://doc.owncloud.com/server/10.9/go.php?to=admin-email the webserver **knows** the url because the redirect rule for `go.php?to=admin-email` already exists for all future oc releases e.g. https://doc.owncloud.com/server/10.*/go.php?to=admin-email

**Comment by JammingBen** [comment]
> You can not lookup the rc in the browser as what you see is the status for every page/resource and the error page itself got delivered successfully.

Aah okay, thanks for the explanation. It's the same behavior for curl requests, too, if omitting the `--head` option.
