### ISSUE TITLE
[Developer Docs] repair steps for app migration is now in info.xml

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/docs#390]
Three new entries in `info.xml` can be used to execute repair steps:

- Before database migration
- After database migration
- As a background job to be executed asynchronously after migration, in live operations
- Install and uninstall steps

**Comment by settermjd** [comment]
> In addition console commands are registered in the info.xml now as well - see https://github.com/owncloud/core/pull/26248/files#diff-61c3c5e77e33ccd96ec3bb36af722aacR28
> 
> ```
>     <commands>
>         <command>OCA\DAV\Command\CreateAddressBook</command>
>         <command>OCA\DAV\Command\CreateCalendar</command>
>         <command>OCA\DAV\Command\SyncBirthdayCalendar</command>
>         <command>OCA\DAV\Command\SyncSystemAddressBook</command>
>     </commands>
> ```

I'll implement that in a separate PR to the documentation of the repair steps.
