### ISSUE TITLE
Document data-fingerprint

### ISSUE THREAD

**Issue by rullzer** [owncloud/docs#391]
The `data-fingerprint` is added in https://github.com/owncloud/core/pull/24054. More details in https://github.com/owncloud/enterprise/issues/966.

Basically it is a property to let the clients find out if a backup has been restored.
We should probabaly have generic restore-backup docs and what to do.

CC: @carlaschroder

**Comment by settermjd** [comment]
Closing, as it has been implemented by @voroyam.
