### ISSUE TITLE
Richdocuments/Collabora open in same tab

### ISSUE THREAD

**Issue by cdamken** [owncloud/docs#3921]
## WHAT Needs to be Documented?
https://github.com/owncloud/enterprise/issues/3807#issuecomment-600617317
occ config:app:set richdocuments open_in_new_tab --value false

## WHERE Does This Need To Be Documented (Link)?
Richdocuments /Collabora , probably in occ commands.

## WHY Should This Change Be Made?
Was never documented.

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Closed via #3923
