### ISSUE TITLE
Clarify days parameter of the occ dav:cleanup-chunks command

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#3928]
## WHAT Needs to be Documented?
Help text of occ command has changed.
Refernces: https://github.com/owncloud/core/pull/39090
Master only (10.9)

## WHERE Does This Need To Be Documented (Link)?
occ command set

## WHY Should This Change Be Made?
completeness

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@phil-davis fyi

**Comment by phil-davis** [comment]
The docs already look OK:
`dav:cleanup-chunks` cleans up outdated chunks (uploaded files) more than a certain number of days old.

https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/configuration/server/occ_commands/core_commands/dav_commands.adoc

And the "help" output of the command is not shown in the docs, so there is nothing that I can see to update.

**Comment by mmattel** [comment]
After doublechecking, @phil-davis is right, the commands output is not listed in occ --> no change needed 😄
