### ISSUE TITLE
search_elastic 2.0.0 drops support for ES5

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#3929]
Supporting now ES7 (we never supported ES6)
@mmattel please update docs accordingly

**Comment by mmattel** [comment]
The doc content does not have any restriction regarding a particular ES release.
Any check regarding an ES upgrade must be made in the elastic search app, see: https://github.com/owncloud/search_elastic

**Comment by mmattel** [comment]
Closed via #4155
