### ISSUE TITLE
Hooks documentation is missing information about pre-requisites

### ISSUE THREAD

**Issue by oparoz** [owncloud/docs#393]
I'm not even sure if hooks work as described on the hooks documentation page since almost nobody uses them that way, but one thing is for certain, documentation is missing regarding the requirements an app needs to have in order to be able to listen to filesystem hooks: the app needs to be of type filesystem, as described here: https://doc.owncloud.org/server/9.0/developer_manual/app/info.html#types

```
<?xml version="1.0"?>
<info>
....
    <types>
        <filesystem/>
    </types>
...
</info>
```

**Comment by settermjd** [comment]
@PVince81, do you or @DeepDiver1975 have time for a discussion about this?
