### ISSUE TITLE
Using static code analyzer in RST

### ISSUE THREAD

**Issue by AbdealiJK** [owncloud/docs#394]
I submitted my first contribution here a while back (https://github.com/owncloud/documentation/issues/2185) and found some minor styling issues and things frequently in the docs. I noticed that in a few places the links are invalid or style issues exist.

I think it'd be a great idea to add a static analysis tool to check rst formatting for the documentation.
In specific, I was thinking of `coala` (https://github.com/coala-analyzer/coala). I've been contributing to the project for a while - and a neat checker for "Invalid Links" was created recently to check their docs.

I think the following would be good value-adds (from the top of my head):
- InvalidLinks - Checks for invalid links (links that are broken or give 40x, 50x) in the rst files
- restLinter - To check rst syntax
- LanguageTool - To check grammar issues
- SpaceConsistency - To check for unnecessary white space and newlines

Also, there's a CI `gitmate` associated with it which directly comments with patches in github PRs - which is under beta. In case you do not want to use jenkins, travis, circleci, etc

Is this something that you'll would like to pursue ?
I could help set it up.

Edit: Note that it has the capability to auto apply patches when feasible

**Comment by settermjd** [comment]
Closing, as work is in progress to build similar checks into the Antora build process.
