### ISSUE TITLE
Support for OC-Checksum header

### ISSUE THREAD

**Issue by rullzer** [owncloud/docs#396]
see: https://github.com/owncloud/core/issues/18716

During upload a new header `OC-Checksum` can be provided which will tell the server to store this checksum. This checksum can then later be obtained via propfind and will be returned when downloading the file.

Currently the checksum is just stored. No server side verifiation or generation is done.

**Comment by settermjd** [comment]
@PVince81 @DeepDiver1975 can either of you, or someone else, provide input about this? Or should this be closed?

**Comment by PVince81** [comment]
@IljaN can you help ?

**Comment by IljaN** [comment]
@settermjd Checksums are already documented so close:
https://github.com/owncloud/documentation/issues/2964
