### ISSUE TITLE
New Functionality: Lockbreaker Groups

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#3962]
## WHAT Needs to be Documented?
See core: https://github.com/owncloud/core/pull/38222 (Add app config to allow groups of users to be lock breakers)

occ command:

config:app:get|set|delete
$this->config->getAppValue('core', 'lock-breaker-groups', '[]')

## WHERE Does This Need To Be Documented (Link)?
* occ command set
* admin_manual/configuration/files/manual_file_locking.html

## WHY Should This Change Be Made?
New functionality

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

For master (10.9) only

**Comment by jnweiger** [comment]
To set group hammer as the lock-breaker group, use
`occ config:app:set core lock-breaker-groups --value '["hammer"]'`
It only works only with doublequotes inside square brackets.
