### ISSUE TITLE
freshclam does not update like explained in the documentation.

### ISSUE THREAD

**Issue by cdamken** [owncloud/docs#3963]
## WHAT Needs to be Documented?
Freshclam is not able to run and  update the 

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/admin_manual/configuration/server/virus-scanner-support.html#clamav-virus-database-updates

## WHY Should This Change Be Made?
Because the documentation from Antivirus does not work. (Ubuntu 20.04)

```
root@carlos-daimler-rd-minimal:~# more  /var/log/clamav/freshclam.log
Wed Aug 18 12:43:12 2021 -> --------------------------------------
Wed Aug 18 12:43:12 2021 -> freshclam daemon 0.103.2 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
Wed Aug 18 12:43:12 2021 -> ClamAV update process started at Wed Aug 18 12:43:12 2021
Wed Aug 18 12:43:12 2021 -> WARNING: Your ClamAV installation is OUTDATED!
Wed Aug 18 12:43:12 2021 -> WARNING: Local version: 0.103.2 Recommended version: 0.103.3
Wed Aug 18 12:43:12 2021 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
Wed Aug 18 12:43:12 2021 -> daily database available for download (remote version: 26267)
```
## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
@cdamken your log describes that the **BINARY of ClamAV is outdated**, our documentation describes the automatic update of the **ClamAV Virus Database Updates**. These are two different things...

I expect that admins DO NOT WANT to have sw packages updated automatically compared to the virus database where they want to have automated updates.

Pls clarify what you expect

**Comment by mmattel** [comment]
Note, at the time of writing, the latest version of the `clamav` package on Ubuntu 20.04 is `0.103.2`

Use the following command to double check:
`sudo apt-cache showpkg clamav` 

Nothing to do for docs
