### ISSUE TITLE
config.php setting for sharing.showPublicLinkQuickAction

### ISSUE THREAD

**Issue by JammingBen** [owncloud/docs#3969]
## WHAT Needs to be Documented?

https://github.com/owncloud/core/pull/39130
Also see the config.sample file for a description: https://github.com/owncloud/core/blob/49a4613f735a855dfde5d884d19f1740097a3ae9/config/config.sample.php#L1230

## WHERE Does This Need To Be Documented (Link)?

Probably in the [config.php parameters section](https://doc.owncloud.com/server/10.8/admin_manual/configuration/server/config_sample_php_parameters.html).
It affects OC Core since version 10.9.

## WHY Should This Change Be Made?

Because we added a new config param.

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
After a discussion with @JammingBen, this will go into core 10.9 and therefore in docs to master only (=before docs 10.9 will be released)
