### ISSUE TITLE
Document event dispatcher to load JS/CSS into other apps

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/docs#397]
See https://github.com/owncloud/core/pull/18316 for an example 

cc @BernhardPosselt @oparoz @PVince81 @LukasReschke @nickvergessen

**Comment by settermjd** [comment]
@DeepDiver1975, who's the best to provide information on this one?

**Comment by LukasReschke** [comment]
I think @MorrisJobke has great context.

**Comment by voroyam** [comment]
closing due to lack of progress.

4 years is enough time.
