### ISSUE TITLE
config.sample.php updated with PR 39168 -> run configToDocs  command

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/docs#3994]
## WHAT Needs to be Documented?
With https://github.com/owncloud/core/pull/39168 config.sample.php has been enhanched, we need to run the config to docs command after merge 

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [x] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [x] Other

**Comment by JanAckermann** [comment]
@mmattel not yet committed, will be during the day

**Comment by mmattel** [comment]
@JanAckermann looking into the referenced core pr, I do not see any changes in config.sample.php
Did I miss something?

**Comment by JanAckermann** [comment]
@mmattel yep, my comment above yours :)

**Comment by JanAckermann** [comment]
@mmattel commited :+1:

**Comment by mmattel** [comment]
Also see: https://github.com/owncloud/docs/issues/4036

**Comment by phil-davis** [comment]
Done in PR #4041
