### ISSUE TITLE
User doc for search

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#3996]
## WHAT Needs to be Documented?
User documentation for Full Text Search (`search_elastic`).
**Reasons**
1. There is no user doc yet
2. There will be a behavior change with the next release (2.0.0)

**Input**
- Basic information about the regular search => can search by file name, always available
- Information about Full Text Search
  - Optional component that needs to be set up by the provider
  - Reference to marketplace https://marketplace.owncloud.com/apps/search_elastic
  - Allows finding files based on their content
- With version 2.0.0 there are behavior changes; those should be highlighted
  - Change from "match phrase query" to "simple query string"
  - It's not possible anymore to find the string "Welcome" in a file by entering e.g., "Wel" => users need to enter "Wel*" instead (add an asterisk / wildcard)
  - Now possible to use operators 
  => mention query type, possible operators, link to elastic docs https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html

## WHERE Does This Need To Be Documented (Link)?
A new page for "Search" under https://doc.owncloud.com/server/user_manual/files/webgui/ should provide information about
a) regular search (comes out-of-the-box)
b) Full Text Search (comes as an add-on via the `search_elastic` app in combination with Elasticsearch)

## WHY Should This Change Be Made?
1. Missing feature doc
2. New release of `search_elastic`

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Closed via #4155
