### ISSUE TITLE
PHP versions in published 10.8 docs are not correct

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs#4011]
https://doc.owncloud.com/server/10.8/admin_manual/installation/manual_installation/manual_installation_prerequisites.html#php-version incorrectly says:

```
ownCloud can run with following PHP versions: 7.3 and 7.4
```

But https://github.com/owncloud/docs/blob/10.8/site.yml#L74 has the correct data:
```
supported-php-versions: '7.2.5+, 7.3, and 7.4'
```

It seems that "something happened" (tm) in the 10.8 docs publishing process, and the correct PHP version list for 10.8 is not being published in the generated docs.

**Comment by phil-davis** [comment]
The same problem happens for 10.7 docs:
https://doc.owncloud.com/server/10.7/admin_manual/installation/manual_installation/manual_installation_prerequisites.html#php-version

**Comment by mmattel** [comment]
Will take a look on

**Comment by mmattel** [comment]
To fix this issue, I already prepared the deployment to get attributes (varaibles) from both site.yml (global) and antora.yml (branch specific) for both the html and pdf build.

We just need to:
1) move relevant attributes from site.yml to antora.yml (first PR + backports)
2) and then change in the attribute in question in antora.yml in each branch to the correct value (PR per branch if necessary)

**Comment by mmattel** [comment]
@phil-davis mind to have a look on:

Just that I do not make an error. I looked into the release notes, but 4 eyes are better than two 😅 

**[10.8]**
    minimum-php-version: 7.2
    minimum-php-printed: 7.2.5
    minimum-php-version-short-code: 725
    recommended-php-version: 7.4
    recommended-php-version-short-code: 74
    supported-php-versions: '7.2.5, 7.3 and 7.4'

**[10.7]**
    minimum-php-version: 7.2
    minimum-php-printed: 7.2.0
    minimum-php-version-short-code: 72
    recommended-php-version: 7.4
    recommended-php-version-short-code: 74
    supported-php-versions: '7.2, 7.3 and 7.4'

**Comment by phil-davis** [comment]
@mmattel that looks correct.

**Comment by mmattel** [comment]
Closing via #4500, #4504 and #4505
