### ISSUE TITLE
Encryption keys can only be moved inside data directory

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/docs#4016]
## WHAT Needs to be Documented?
It is not possible to move the encryption keys outside of the `data` directory. The documentation should state the folder placement and the example should be a folder within the `data` directory

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.8/admin_manual/configuration/server/occ_command.html#change-key-storage-root

## WHY Should This Change Be Made?
- Existing documentation states that the encryption keys can be moved to a folder that already exists `somewhere` (not clear in the documentation).
- path is not relative to ownCloud directory but relative to `data` directory
-  It also contains an example showing a key storage root change with a folder i.e. outside of the `data` dir.
 ```bash
sudo -u www-data php occ encryption:change-key-storage-root ../../etc/oc-keys
```

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

## Related issue
- found while working on https://github.com/owncloud/core/issues/39189
- found that it was a needed fix in docs after https://github.com/owncloud/core/issues/39188

**Comment by EParzefall** [comment]
Fixed with PR #4112
