### ISSUE TITLE
Setting locale to en_US.UTF-8 Please install one of these locales on your system and restart your webserver.

### ISSUE THREAD

**Issue by ho4ho** [owncloud/docs#402]
## What Type Of Content Change Is This?

- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

https://github.com/owncloud/core/issues/33543#issuecomment-440313071
> I think this could go in a troubleshooting section. Debian users that experience:
>
> ![](https://user-images.githubusercontent.com/7528337/48783476-7539ff80-ecae-11e8-9b4b-deb404a2dc73.png)
>
> Should check their /etc/apache2/envvars file and uncomment the ‘. ./etc/default/locale’ line. Restart Apache and the problem should be solved.

## Why Should This Change Be Made?

Better help

**Comment by settermjd** [comment]
Thanks for creating this PR, @ho4ho.

**Comment by voroyam** [comment]
Since the debian docs are no longer part of the official ownCloud docs I documented in in the central forum for ownCloud.
https://central.owncloud.org/t/setting-locale-to-en-us-utf-8/21076

**Comment by ho4ho** [comment]
Not only specify by Debian ?

**Comment by voroyam** [comment]
Are you capable of writing full thoughts? 

Like full sentences and not "drive-by-questions"?

**Comment by ho4ho** [comment]
I mean to add to https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc as problem not only happening by Debian?

**Comment by voroyam** [comment]
The docs are officially limited to Ubuntu. As far as I know this does not happen in Ubuntu.

You are free to propose something that I will ad to the FAQ in central.
