### ISSUE TITLE
Assign defined pages a noindex attribute

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#4032]
## WHY Should This Change Be Made?

When creating a page, this page can be a frame only which includes several sub pages to be built as complete page. As example see the occ commands page. Antora builds all pages. It builds not only the main page with all the includes, but also the individual pages. These individual pages can be accessed manually if you know the url for - but this is senseless. 

Crawlers like Google also index these sub pages and makes them availabe for searchers - which should be prevented.

## Targeted Solution
Particular include pages should have the ability to be tagged with a noindex attribute directly in the .adoc file preventing to be indexed by crawlers.

@xoxys fyi

**Comment by mmattel** [comment]
I already have found possible ways to address this issue but need to do some testing and have a in depth dive into.

See: https://docs.antora.org/antora/2.3/page/attributes/#page-attributes
which could be used via our docs-ui template with a conditional rendering

**Comment by xoxys** [comment]
Agree, feel free to implement it.
