### ISSUE TITLE
Document hide_upload_estimation

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs#4034]
## WHAT Needs to be Documented?
core PR https://github.com/owncloud/core/pull/39228 added the option to `hide_upload_estimation` when uploading files using the oC10 webUI. Document how to "enable" hiding the upload estimation.

The command is:
`occ config:app:set files hide_upload_estimation --value="yes"`

## WHY Should This Change Be Made?
New feature/option.

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Just for my interrest, why was this implemented as occ command and not as a config option in config.php?

**Comment by phil-davis** [comment]
@JammingBen ^

How do we choose which options are put in the system-wide `config.php` and which are `occ config:app:set` for a specific app?

**Comment by JammingBen** [comment]
We ask @pmaier1 what he thinks fits best for the specific use case :) At least that's how I handle it - I'm not aware of any "rules".

**Comment by mmattel** [comment]
Addressing this „naturally“ would be for me using a config option. Having a config option would read which settings are made much easier. Consequently, an occ command returning the status is missing…

**Comment by pmaier1** [comment]
This decision was taken to keep config.php clean. Hiding the upload estimation is a measure for special deployments, not a default thing.

> Consequently, an occ command returning the status is missing…

occ config:app:**get** files hide_upload_estimation --value="yes"
