### ISSUE TITLE
CSRF check for dev docs

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#404]
request token is passed into DOM automatically, and available in JS via a gloabl variable called `oc_requesttoken` - open owncloud in your browser, login, open JS console, look at the value

you can use this in your ajax requests - jquery it is attached to your requests automatically

**Comment by settermjd** [comment]
Where should this be added in the dev docs?

**Comment by settermjd** [comment]
@voroyam, I need your input here, pls.

**Comment by voroyam** [comment]
@IljaN what would be your suggestion as a developer?

**Comment by IljaN** [comment]
Somewhere in the app development documentation
Here https://doc.owncloud.org/server/10.0/developer_manual/app/fundamentals/controllers.html#authentication
or here:
https://doc.owncloud.org/server/10.0/developer_manual/app/fundamentals/controllers.html
