### ISSUE TITLE
Fix sitemap(s).xml and robots.txt

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#4044]
**Issue**
When the docs get built, crawlers (google) get all content from all products and versions (branches) we provide.
In addition that there are three branches (next, stable and stable-1), the value behind stable changes with every new release published. This leads to following situation:

* Google indexes content which is changing every view months
* We can´t use `latest` in the url as the source of truth for Google as latest redirects to stable which changes regularly. We benefit a lot, Google disadvantages redirects for SEO on the long term
* Our docs content is not found by searchers and if something got found is is confusing with regards to the version it is relevant
* We have a bad SEO because of highly duplicate content (the versions do not differ that much)
* We cant easily "fake" the canonical link provided in all the html pages. Too many obstacles on the way.

Having intense discussions with @tbsbdr and @xoxys we can provide a solution which fixes indexing (and thereby external search) and SEO

**Proposed Solution**
Because the delta between `next` (a static address component in the URL) is relatively low to stable and `next` is nowhere redirected to, we can use `next` as the base for the crawlers for indexing. Therefore, all sitmap lines not containing next must be removed post creation. Knowing that we do not provide the stable version for viewing, it is an easy implementable solution with immediate positive effect.

**Detailed Steps**
1. **sitemap.xml**
Post running the build, a script needs to be triggered in CI which deletes all lines in all dynamically generated sitemap.xml files (for each component like server, desktop ect). The available components can be defined programatically. A change of the list  is very seldom, only when a docs sub repo gets added.
This step provides crawlers (Google) a predefined map which is well appreciated by the crawler and we therefore get ranked higer. All non relevant items not to be indexed are not in the list.
2. **robots.txt**
The statement `Allow` is indirectly defined by using the Sitemap: directive. To complete the restriction here, we add `Disallow` directives post the sitemap one. There we disallow all not in the list but accessible products/versions.
This step tells crawlers (Google) not to have a deeper analysis than the provided sitemap files which further improves results and SEO.
3. Finally a small addon to the version change documentation to check the robots.txt file for actual Disallow statements
 
The steps to be made are not rocketsience and realtively easy to implement. No change on the webserver to be made, all in the framework of docs

**Comment by mmattel** [comment]
Referencing: https://github.com/owncloud/docs/issues/3528 (SEO: high rankings of old versions)

**Comment by tbsbdr** [comment]
Very nice! So all in all the goal would be to point Google to only **one source of truth** via the sitemap.xml's and the robots.txt, correct?

**Comment by mmattel** [comment]
> point Google to only one source of truth via the sitemap.xml's and the robots.txt

Correct!

**Comment by mmattel** [comment]
Closed via #4055
