### ISSUE TITLE
Remove whatsnew page in user docs

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#4046]
## WHAT Needs to be Documented?
Removal of https://doc.owncloud.com/server/next/user_manual/whats_new.html in all branches
It is outdated and has no benefits

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [x] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by EParzefall** [comment]
Fixed with PR #4109
