### ISSUE TITLE
Two Factor Auth 

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#4049]
## WHAT Needs to be Documented?
there seems to be more commands that are not covered on the page for the two factor auth here:

https://doc.owncloud.com/server/10.7/admin_manual/configuration/server/occ_commands/app_commands/2fa_commands.html

If I look at my command line output I see:

```
 twofactorauth:disable
      twofactorauth:enable
      twofactor_totp:delete-redundant-secret
      twofactor_totp:set-secret-verification-status
````

Maybe the bottom 2 commands are not related to the app itself, but I haven't seen those and don't know what they do.

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.7/admin_manual/configuration/server/occ_commands/app_commands/2fa_commands.html

I am confused we have no entry for this app in our security section of the documentation. Maybe there is not much to write about but I would expect something important to users or customers documented. How to enable, how to use, how to disable and how to troubleshoot.

<img width="311" alt="Screenshot 2021-09-17 at 14 36 50" src="https://user-images.githubusercontent.com/24212810/133783831-6b10e7c7-8e63-4fb8-a32c-6c71d686384c.png">

## WHY Should This Change Be Made?
to give users and customers a better understanding about the app

**Comment by mmattel** [comment]
Thanks for the heads up @voroyam 👍 
Nobody has told us about any missing pieces, neither on a description base nor on occ commands.
We are no experts in this topic and need help to fix this. Support is very welcomed.

**Comment by voroyam** [comment]
You are the expert, tell me how I can help. 

The text, how it is written right now, is not correct as far as I can see it, the commands have to be added as well, in my view. Lastly I would add a page in the security section of the server docs describing the app and linking to the occ command page.

I can correct / add the existing text describing the app and you can improve the writing. 

The occ commands I posted in my original post, but I can add text what they do.

**Comment by mmattel** [comment]
@voroyam I have taken a closer look in that, but things are more complicated as they appear. I have identified the proper way to implement it and will do this it asap.

**Comment by voroyam** [comment]
awesome. The doc team meeting is on Thursday at 11? If I wanted to join, I would need to know when :)
