### ISSUE TITLE
Move the release notes from admin one level up

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#4050]
## WHAT Needs to be Documented?
The server release notes are currently located at the admin manual.
![image](https://user-images.githubusercontent.com/3321281/135087769-b55ef964-2cc4-4b44-aa53-b3d1799eefdc.png)

We should make a header like "ownCloud Server" above the admin manual entry and move the release notes under the new header and above the admin manual. This would make the admin manual more clear and we would have a identifyer that we are addressing server stuff below that new header. On the longer term, we need to have a bigger rearrangement because of ocis but this move would be inline of the bigger one.

@pmaier1 agree?

**Comment by pmaier1** [comment]
No objections. Please make sure that links will not break.
