### ISSUE TITLE
Add external documentation links for HTTPS

### ISSUE THREAD

**Issue by JammingBen** [owncloud/docs#4058]
https://github.com/owncloud/core/pull/39267 fixed two doc links on the "general"-setting page:

- You are accessing this site via HTTP. We strongly suggest you configure your server to require using HTTPS instead as described in our [security tips](https://doc.owncloud.com/server/10.8/go.php?to=use-https).

The URL https://doc.owncloud.com/server/10.8/go.php?to=use-https needs to go to https://doc.owncloud.com/server/next/admin_manual/configuration/server/harden_server.html#use-https.

- The "Strict-Transport-Security" HTTP header is not configured to at least "{seconds}" seconds. For enhanced security we recommend enabling HSTS as described in our [security tips](https://doc.owncloud.com/server/10.8/go.php?to=enable-http-strict-transport-security).

The URL https://doc.owncloud.com/server/10.8/go.php?to=enable-http-strict-transport-security must lead to https://doc.owncloud.com/server/next/admin_manual/configuration/server/harden_server.html#enable-http-strict-transport-security.

**Comment by JanAckermann** [comment]
@xoxys FYI

**Comment by xoxys** [comment]
Thanks will take care.

**Comment by JanAckermann** [comment]
Thx 🙌

**Comment by xoxys** [comment]
Done
