### ISSUE TITLE
Integrate core API documentation

### ISSUE THREAD

**Issue by tboerger** [owncloud/docs#406]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content
- [x] Additional documentation

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [x] Server API by phpDocumentor

## What Needs to be Documented?
So far we got the server API documented with the help of phpDocumentor and it's available at https://doc.owncloud.com/api. With the new documentation process, this is not covered so far.

## Why Should This Change Be Made?
We must provide this functionality again or this will get lost.

**Comment by tboerger** [comment]
When the new infrastructure is done we can prepare a PR for the core repo which automatically uploads the latest API docs with an additional step within the drone pipeline. So far we are doing it similar to that within Jenkins:

```
docker run --rm -t -u $(id -u):$(id -g) -v $(pwd):/srv/app -w /srv/app webhippie/phpdoc:latest phpdoc project:run --directory=source/lib/public --target=build --title=ownCloud-API
```

**Comment by settermjd** [comment]
Do you just want a link to https://doc.owncloud.com/api in the main navigation?

**Comment by tboerger** [comment]
I personally don't need a link to it, but it got to be integrated into the docs deployment.

**Comment by voroyam** [comment]
@tboerger can you tell us where you want this documented? Admin manual user manual dev manual?

**Comment by tboerger** [comment]
The api docs will be removed, so nothing to do here.
