### ISSUE TITLE
Appliance documentation is missing

### ISSUE THREAD

**Issue by tboerger** [owncloud/docs#407]
## What Type Of Content Change Is This?

- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [x] Appliance Manual

## What Needs to be Documented?
We have not migrated the appliance documentation yet, this got to be migrated for the final switch to Antora.

## Why Should This Change Be Made?
It's an important missing part for our Antora migration.

**Comment by settermjd** [comment]
The appliance documentation's currently listed under the admin manual, as the image below shows. 
![bildschirmfoto 2018-11-22 um 16 37 42](https://user-images.githubusercontent.com/196801/48912152-27bbbf00-ee75-11e8-96ef-3fd1727da202.png)
Should it be moved so that it's easier to find?

**Comment by tboerger** [comment]
True, the appliance documentation I was refering to is just for the old 9.1 appliance. I will simply add this old folder to the fallback docs version.
