### ISSUE TITLE
where are the unix style man pages?

### ISSUE THREAD

**Issue by jdkloe** [owncloud/docs#4082]
## WHAT Needs to be Documented?

In the past the owncloud and owncloud-cmd had some traditional unix style man pages that could be generated using sphinx. In this new Antora age I cannot find them anymore and also cannot find an option anywere to generate them.

If I overlooked this option please point me to it.
If the option is no longer there please consider adding it again.

For packaging a tool in a linux distribution (in my case I am looking at fedora) it is required to have man pages for all executables, and if they are not available we have to request (or work with) the developer of the tool to provide them.

See also https://docs.fedoraproject.org/en-US/packaging-guidelines/#_manpages

**Comment by mmattel** [comment]
Hello @jdkloe thanks for getting in touch with us.

Before using Antora, we had a markdown based system which did not met our requirements. Therefore we changed to Antora some years ago successfully. I cant remember that we offererd any tool or process to generate manpages for our doc content (I assume you are referencing the occ command set).
Even Antora has the ability to provide manpages (see: 
https://docs.asciidoctor.org/asciidoctor/latest/manpage-backend/#generate-a-man-page) it requires a completely different documentation structure which is not compatible with the current used way.

Therefore I do not see any chances to create manpages from our documentation.

What are you intending to achieve?

**Comment by jdkloe** [comment]
Hi @mmattel, no I am not suggesting to fully convert all documentation to manpages. I am just asking if there is a possibility to provide man pages that give some details on how to start the main owncloud client tools owncloud and owncloudcmd. I see that there are some examples floating around the internet, for example https://www.carta.tech/man-pages/man1/owncloudcmd.1.html, but these are rather outdated. Maybe they have been generated by others using a tool like help2man starting from the help output that is provided if these tools are executed with the -h/--help option. But they clearly are not updated regularly.
From https://github.com/owncloud/client/issues/6183 and https://github.com/owncloud/client/issues/1648 I get that once there have been some files available that could be used to generate man pages.
If this is not something you are willing to provide, than that is fine with me. Just state it clearly. And I will try to use the help2man tool to generate them myself. I have to assume the --help output is updated for each new version of owncloud client, but I guess that is a safe thing to assume.

**Comment by mmattel** [comment]
We are in sorry that we are not able to provide manpage kind doc files. Consider that the issue links you provided are 4 and 7 years old and heavy outdated - a lot has been made in the meanwhile 😃 

You can find the actual doc we provide for `owncloudcmd` at: https://doc.owncloud.com/desktop/next/advanced_usage/command_line_client.html

Please file an issue at https://github.com/owncloud/docs-client-desktop if you find errors or issues with the `owncloudcmd` documentation.
