### ISSUE TITLE
Mail settings test have a reciever

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/docs#4091]
## WHAT Needs to be Documented?
With PR https://github.com/owncloud/core/pull/39297 mail settings test functionality has now a receiver field, where the test mail should be sent to, this field is mandatory and will be prefilled with the logged-in admin's email if set. 

With this enhancement, the admin does not need to set it's own email before testing the mail settings

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.8/admin_manual/configuration/server/email_configuration.html

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by JanAckermann** [comment]
PR is done

**Comment by mmattel** [comment]
@JanAckermann just seen that the test recipients address cant be set in config.php (imho missing) - will add a note in the text.
