### ISSUE TITLE
Improvement of the description of the folder in the backup section

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/docs#4096]
## WHAT Needs to be Documented?
Content of the folders to backup/ a description of the folder

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/next/admin_manual/maintenance/backup.html

## WHY Should This Change Be Made?
The documentation only mentions the name of the folder, not the containing folder structure nor the contained.
While in a native setup you can follow the guide to the point, in docker things tend to look a bit different.

If the content of a folder would be described it would be simpler to follow the instructions in a customised setup.

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Just had a call with @TheOneRing 
There are two issues:
* The listed directories could be described better, see screenshot:
![image](https://user-images.githubusercontent.com/3321281/135420082-006752c1-3f59-47cd-8af3-386937a40f73.png)
* We do not have any content about backing up an install via docker.
The page assumes a classical installation.

**Comment by EParzefall** [comment]
Right, this whole section needs a major overhaul plus a link to information on backing up and restoring docker instances. Thanks for pointing us to ist @TheOneRing
