### ISSUE TITLE
Document min samba version for using windows network drive listener and smb protocol

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/docs#411]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?
In light of our blogpost https://owncloud.com/windows-network-drive-integration-benefits-from-samba/ the documentation of the windows network drive listener and the correlation with the samba protocol versions should be documented.

When the windows network drive listener is used, and the target file server requires the usage of the protocol SMB2+, we require at least Samba 4.7.8 ( https://www.samba.org/samba/history/samba-4.7.8.html // BUG13382 ) - or Samba 4.8.1 ( https://www.samba.org/samba/history/samba-4.8.1.html // BUG13382 ) on the ownCloud server.

With any Samba version lower then the above mentioned, the windows network drive listener from ownCloud would only work on samba protocol version 1

## Why Should This Change Be Made?
Keep the documentation up-to-date and avoid known errors for windows network drive listener deployments

**Comment by settermjd** [comment]
Closing as the implementing PR's been merged.

**Comment by patrickjahns** [comment]
@settermjd - reopening as #517 is still not merged

**Comment by cdamken** [comment]
The information is only in: https://doc.owncloud.com/server/admin_manual/configuration/files/external_storage/smb.html
but this relevant issue is for WND:
https://doc.owncloud.com/server/admin_manual/enterprise/external_storage/windows-network-drive_configuration.html
Here is the whole information missing 😢 

@settermjd please add a link or add this information in the WND information.

**Comment by settermjd** [comment]
Closing, as the related PRs (#860, #976) have been merged
