### ISSUE TITLE
MariaDb 10.6

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs#4115]
## WHAT Needs to be Documented?
core issue https://github.com/owncloud/core/issues/39283 is about getting support for MariaDb 10.6 in upcoming ownCloud 10.9

core PR https://github.com/owncloud/core/pull/39286 is in progress to do that. See the discussion there, for example https://github.com/owncloud/core/pull/39286#issuecomment-934460534

The process for updating to MariaDb 10.6 (from MariaDb 10.2 10.3 10.4 or 10.5) will need to be well documented.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by JanAckermann** [comment]
Upgrade Paths:

### Fresh ownCloud 10.9 installation
- nothing to do :)

### ownCloud x => 10.9 upgrade
- Upgrade to 10.9
- Set ownCloud in maintenance mode
- Run `php occ db:convert-row-format`
- Upgrade MariaDB to 10.6
- Turn maintenance mode off

**Comment by phil-davis** [comment]
Note: for "ownCloud x => 10.9 upgrade" the upgrade can be done to 10.9 as normal, keeping MariaDB 10.2 10.3 10.4 or 10.5 and ownCloud can be run like that fine. MariaDb can be upgraded up to 10.5 without doing anything to ownCloud. So installations can get up to ownCloud 10.9 with MariaDb 10.5 without needing to do any other special stuff.

At any later time (immediately, next weekend, next month...) the sysadmin can decide to schedule the MariaDb 10.6 upgrade and do the 4 steps after "Upgrade to 10.9"

**Comment by phil-davis** [comment]
core PR https://github.com/owncloud/core/pull/39286 has been merged.

This will be in core 10.9 release.
