### ISSUE TITLE
"occ app:list -m" option for minimalistic app list view

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#4117]
## WHAT Needs to be Documented?
"occ app:list -m"

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.8/admin_manual/configuration/server/occ_command.html#app-commands

## WHY Should This Change Be Made?
because it was added by @JanAckermann 

https://github.com/owncloud/core/pull/39326

Background: the default view was changed to include the app paths, so for every app, you get a path.
This is too much info for some people, so a minimalistic view option was added.

**Comment by phil-davis** [comment]
The core PR https://github.com/owncloud/core/pull/39326 has been merged. This can be documented for upcoming core 10.9
