### ISSUE TITLE
Document Custom Groups WebDAV API

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#413]
Custom Groups already have a WebDAV API which until now was private and undocumented. As there's demand for it, we want to declare it public and add it to the official documentation. 

Input: https://github.com/owncloud/customgroups/issues/3

@settermjd @PVince81

**Comment by PVince81** [comment]
cc @DeepDiver1975 FYI

**Comment by settermjd** [comment]
@pmaier1, thanks for raising this. I'm more than happy to work on it, as I was documenting other WebDAV APIs recently.

**Comment by settermjd** [comment]
I'd estimate 1 md.
