### ISSUE TITLE
Command occ user:list has new option show-all-attributes

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/docs#4150]
## WHAT Needs to be Documented?
With the PR https://github.com/owncloud/core/pull/39366 the option show-all-attributes has been added to the `occ user:list` command, this needs to be documented.
Note: it is also possible to show all attributes with the verbose option `-v`

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.8/admin_manual/configuration/server/occ_commands/core_commands/user_commands.html

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Closing via #4243
