### ISSUE TITLE
Readme is missing the command line preparation to run the antora command

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#416]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [x] General

## What Needs to be Documented?

In the current docs/readme, there is, at least I did not find it, no guide to install/update the command line environment for antora. We have package.json, which tells what to install, but the command 
(I think it is `npm i`) is missing as prerequisite / update.
Note: it should also be noted to run `npm i` on a regular basis to update changes made in the prerequisites 

## Why Should This Change Be Made?

Fix missing antora command line preperation

**Comment by tboerger** [comment]
Do not suggest npm, yarn should be used instead.

**Comment by mmattel** [comment]
Thanks for the tip @tboerger, everything is fine to me as long it works 👍
