### ISSUE TITLE
Document LDAP disabled users filter

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#420]
We should document this filter, it disables users in ownCloud who are disabled in AD/LDAP.

https://central.owncloud.org/t/oc10-0-10-ldap-integration-and-users-sync/17048/4

just the filter

`!(userAccountControl:1.2.840.113556.1.4.803:=2)`

full example

`&(|(objectclass=organizationalPerson))(!(userAccountControl:1.2.840.113556.1.4.803:=2))(|(|(memberof=CN=Domain Users,CN=Users,DC=dp,DC=mosreg,DC=ru)(primaryGroupID=513))))`

**Comment by settermjd** [comment]
@cdamken / @pako81 do either of you have an LDAP setup and can test this?

**Comment by mmattel** [comment]
> it disables users in ownCloud who are disabled in AD/LDAP

to be more precise, it queries only `active users`, see the microsoft technet forum
https://social.technet.microsoft.com/Forums/en-US/44048e98-b191-4d18-9839-d79ffad86f76/ldap-query-for-all-active-users?forum=winserverDS.
```
The filter (objectCategory=person) returns both user and contact objects. Since contact objects do
not have a userAccountControl attribute, the clause (!userAccountControl:1.2.840.113556.1.4.803:=2)
will always be True for contacts. As noted, to restrict the query to just user objects, add the
clause (objectClass=user).
...
(&(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2))
```

**Comment by cdamken** [comment]
> !(userAccountControl:1.2.840.113556.1.4.803:=2)

This is only valid on Microsoft AD but not all other LDAP flavors.

I think we can put some examples of how to create filters, but at the end of the day, the Administrator should know what he is trying to achieve.

**Comment by mmattel** [comment]
@cdamken you are right regarding AD/other LDAP flavours. I think it would be a good idea to detail that for AD as the majority of company user is using a microsoft environment and the others get a hint waht to look for.

**Comment by settermjd** [comment]
@mmattel, are you documenting these changes?

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1500

**Comment by voroyam** [comment]
merged, backported
