### ISSUE TITLE
Letsencrypt step-by-step setup simplification (Apache)

### ISSUE THREAD

**Issue by mcarioscio-ownCloud** [owncloud/docs#4215]
## WHAT Needs to be Documented?
Setting up SSL could be clearer.

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/next/admin_manual/installation/letsencrypt/using_letsencrypt.html#web-server-setup

## WHY Should This Change Be Made?
When I set up SSL, I followed the steps in the link above. When I got to the Web Server Setup, the pages did not seem to pair well together (both pages direct users to create new certificates). Maybe have a link to https://doc.owncloud.com/server/next/admin_manual/installation/manual_installation/manual_installation_apache.html#enable-ssl on the Letsencrypt page instead of this link https://doc.owncloud.com/server/next/admin_manual/installation/letsencrypt/apache.html?

If more details are required, I'm happy to provide!
(thanks @voroyam for troubleshooting with me!)

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by voroyam** [comment]
I think that we could just add an example in here

https://doc.owncloud.com/server/10.8/admin_manual/installation/letsencrypt/using_letsencrypt.html#web-server-setup

and leave the link for further info.


Example:

Add the 

    `Certificate Path: /etc/letsencrypt/live/your-domain-name.com/fullchain.pem`
 and

    `Private Key Path: /etc/letsencrypt/live/your-domain-name.com/privkey.pem`

to your default-ssl.conf file located in `/etc/apache2/sites-available or sites-enabled`

replace the snake oil certs with your new created ones.

Then execute this command to enable ssl:

```
a2enmod ssl
a2ensite default-ssl
service apache2 reload
```


In my opinion this would cover 90% of setups.

**Comment by mmattel** [comment]
Closed via #4259
