### ISSUE TITLE
Improve Let's Encrypt docs

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#4239]
## WHAT Needs to be Documented?
remove redundant information from apache document and link it to the let's encrypt document
(create SSL certificate/ list)

@mmattel 

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.8/admin_manual/installation/letsencrypt/using_letsencrypt.html

## WHY Should This Change Be Made?
coherancy 

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Closed via #4259
