### ISSUE TITLE
Document OCS Sharee API

### ISSUE THREAD

**Issue by micbar** [owncloud/docs#426]
## What Type Of Content Change Is This?

- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

1. The core Sharees API is not documented yet.
2. @micbar will provide Information .
3. ping @DeepDiver1975 for review

## Why Should This Change Be Made?

The Sharee api is not documented yet. As the whole project is moving to SemVer, all API's need to be documented and stable.

We can use the OCS Sharing API https://doc.owncloud.org/server/10.0/developer_manual/core/ocs-share-api.html as an example.

**Comment by settermjd** [comment]
@micbar, is [this page](https://doc.owncloud.com/server/developer_manual/core/ocs-recipient-api.html) already documenting the Sharee API?

**Comment by micbar** [comment]
> @micbar, is [this page](https://doc.owncloud.com/server/developer_manual/core/ocs-recipient-api.html) already documenting the Sharee API?

Basically yes. But the "get all Shares" is misleading. "get all Sharees" would be better or "get all Share recipients"

**Comment by voroyam** [comment]
@micbar anything to add here?

![image](https://user-images.githubusercontent.com/24212810/61630377-d542d480-ac87-11e9-8777-d38000f2c4e8.png)

**Comment by micbar** [comment]
"Get Shares Recipients" has no content.

**Comment by voroyam** [comment]
So what has to be added?

I am confused because you wrote lastly to @settermjd that the only thing to change is the title of the section.

Now I see the changed section title and don't understand what is needed to close this issue. If @settermjd has more info to fix this then I would let him do the fix, but in this issue there has not been progress since 21 Dec 2018

**Comment by micbar** [comment]
1) Remove Get All Shares
2) Name it Get Shares Recipients
3) Change `Syntax: /shares` to `Syntax: /sharees`

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1523

@micbar
