### ISSUE TITLE
Let's encrypt docs improvement v2

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#4269]
## WHAT Needs to be Documented?
https://doc.owncloud.com/server/10.8/admin_manual/installation/letsencrypt/using_letsencrypt.html#run-certbot

Run Certbot command is not necessary on the place in the document. Further down you create files only with which you can obtain a certificate for your domain. Having "sudo certbot" at the beginning of the document makes no sense to me.

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.8/admin_manual/installation/letsencrypt/using_letsencrypt.html#run-certbot

## WHY Should This Change Be Made?
see above.

**Comment by voroyam** [comment]
https://doc.owncloud.com/server/10.8/admin_manual/installation/letsencrypt/using_letsencrypt.html#run-certbot

It's confusing to people. The bullet points tell the user to do stuff, but it's not intended as an instruction, it's intended as a summery what will be done with the commands below. imho we should label this as such.

**Comment by voroyam** [comment]
https://doc.owncloud.com/server/10.8/admin_manual/installation/letsencrypt/using_letsencrypt.html#cli-ini

1. we should remove nginx from the cli file. as we just recommend using apache.
2. make the lines bold, like uncomment **Web Server**

**Comment by voroyam** [comment]
we should state at the beginning that if you are just interested in a testing server and just want the certs, you only need the domain.sh and the cli.ini

**Comment by voroyam** [comment]
the `chmod +x` command is in the beginning of the document in the summery, but it should be at the end of the document when you have your scripts.

**Comment by voroyam** [comment]
Next Page: https://doc.owncloud.com/server/10.8/admin_manual/installation/letsencrypt/apache.html#create-and-configure-a-diffie-hellman-params-file

I think this Hellman file creates more confusion than it's useful.

**Comment by xoxys** [comment]
> I think this Hellman file creates more confusion than it's useful.

Where did you get this from? Without a dhparam file, Forward Security will not work, which is a major decrease of your TLS security setup.

**Comment by voroyam** [comment]
I did not see that file on any of the setups I have seen, testing or customer in production. I also don’t know what forward security is.

**Comment by xoxys** [comment]
Does it make sense to say somethings is more confusing than useful if you are not aware of what its for? Especially as the docs links to an article that explains what forward security is and why its important...

**Comment by xoxys** [comment]
If the server is not using TLS1.3 only or ECDHE ciphers only its recommended to configure a dhparams file see https://ssl-config.mozilla.org/#server=apache&version=2.4.41&config=intermediate&openssl=1.1.1k&guideline=5.6

(And a lot of servers in production still use the intermediate config to support a broad range of clients)
