### ISSUE TITLE
Client docs should provide an index.html file

### ISSUE THREAD

**Issue by tboerger** [owncloud/docs#428]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [x] Desktop Manual

## What Needs to be Documented?
So far we are linking to introduction.html, but the entrypoint for the client docs should be an index.html.

## Why Should This Change Be Made?
To display a valid index page without the need to rewrite/redirect.

**Comment by settermjd** [comment]
Closing, as there's already an `index.adoc` file, which is set (unnecessarily) as the start page.
