### ISSUE TITLE
Rename client to desktop for the client docs

### ISSUE THREAD

**Issue by tboerger** [owncloud/docs#429]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [x] Desktop Manual

## What Needs to be Documented?
Currently the client docs are linked as /client, this should be /desktop again.

## Why Should This Change Be Made?
We have named it like that before, it makes sense to keep it like that.

**Comment by settermjd** [comment]
@tboerger, https://github.com/owncloud/client/pull/6918 is ready for review.

**Comment by dschmidt** [comment]
> Why Should This Change Be Made?
> We have named it like that before, it makes sense to keep it like that.

More importantly: there are also Android and iOS clients, that's why we refer to the desktop client as desktop client ;-)

**Comment by settermjd** [comment]
This change will only affect the URL of the generated documentation.

**Comment by tboerger** [comment]
Already solved :)
