### ISSUE TITLE
User Feedback on New Docs

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#430]
- [x] ~~Quite frustrating you can't click on the text of tree items with children, you have to click the triangle (@tomneedham).~~
- [x] ~~Remove "_S3 Swift as Primary Object Store Configuration_" under the "_External Storage_" Part as Swift is deprecated (@haukman).~~
- [x] ~~Client branding titles are too long for the side menu (@tboerger).~~

**Comment by haukman** [comment]
>     * Remove "_S3 Swift as Primary Object Store Configuration_" under the "_External Storage_" Part as Swift is deprecated (@haukman).

We are mixing up things :) The whole chapter is about external storages...but this specific part is about primary storages and needs to be placed somewhere else. Additional to that, Swift is deprecated

**Comment by tboerger** [comment]
> We are mixing up things :) The whole chapter is about external storages...but this specific part is about primary storages and needs to be placed somewhere else. Additional to that, Swift is deprecated

This is a structural change, so far the documentation have been migrated from the old docs.

**Comment by settermjd** [comment]
That's right, @tboerger. But, depending on the work required, this might be worth fixing. Will see.

**Comment by settermjd** [comment]
@tboerger, which client branding titles are too long?

**Comment by settermjd** [comment]
@tomneedham, I'm syncing the updates from the `antora-default-ui` (the project which the ownCloud UI's forked from) to fix the point that you raised. Just having a slight logistical hold-up.

**Comment by tboerger** [comment]
![bildschirmfoto 2018-12-05 um 13 58 17](https://user-images.githubusercontent.com/156964/49514960-da3c4a80-f895-11e8-8de8-6e48047572e6.png)

**Comment by settermjd** [comment]
@tomneedham, the docs UI's been updated to incorporate [an update](0e403b4b5ca4b84b67c7d50363168408eb9adc16) that now lets you click navigation items to open/expand them.

**Comment by settermjd** [comment]
@tboerger, that same UI update fixes the font size issue that you reported. 

![bildschirmfoto 2018-12-05 um 14 17 34](https://user-images.githubusercontent.com/196801/49515947-95fe7980-f898-11e8-888e-780735607f7f.png)

**Comment by tboerger** [comment]
You should add the build badge of Drone to the README of the docs and of the docs-ui repo :)
