### ISSUE TITLE
Makefile: .PHONY: check-prose

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#431]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [x] General

## What Needs to be Documented?

In Makefile https://github.com/owncloud/docs/blob/master/Makefile#L126
you find `.PHONY: check-prose`. This command is not mentioned in the help context - intended ?

## Why Should This Change Be Made?

Clarification

@tboerger @settermjd

**Comment by tboerger** [comment]
It haven't been part of help before as well. And it needs additional setup. So far it's only executed manually by some writer, no automation or something like that involved.

If we document it within the help it must also be intergrated properly...

**Comment by mmattel** [comment]
I did not know that is wasn´t there before and that it would need additional setup.
What about adding a comment so readers know it ?
Else it looks forgotten to be mentioned (like I stumbled over)

**Comment by mmattel** [comment]
https://github.com/owncloud/docs/pull/440 will fix that

**Comment by settermjd** [comment]
Closed, as the implementing PR's been merged.
