### ISSUE TITLE
make html command questions

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#432]
Looking to the current docs, the antora command to generate (https://github.com/owncloud/docs/blob/master/docs/build-the-docs.md) has preceeding environment variables set
``DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr``
But this is missing in the ``make html command`` https://github.com/owncloud/docs/blob/f82c1c6bd454e3d2d9b2d5524acff76bf398169a/Makefile#L60

This is also true for `--url <URL or path to your Antora instance>` which is present as example in build the docs but nowhere set, not in Makefile or site.yml.

Is this intended ?

@settermjd @tboerger

**Comment by tboerger** [comment]
I haven't set these env variables at all... Not sure where these are gonna be used?

**Comment by mmattel** [comment]
According a question I had to @settermjd about those env vars (DOCSEARCH_ENABLED, DOCSEARCH_ENGINE):
`The environment variables are required for building the docs with integrated site search.`

**Comment by tboerger** [comment]
The search got to be built differently anyway, currently we are getting a single index with 20mb, that's not usable.

**Comment by settermjd** [comment]
Well, it might be that Lunr's not the best choice. Perhaps a service such as Algolia is.

**Comment by tboerger** [comment]
The search index got to be defined per documentation version, not globally. One for desktop latest, one for android latest, one for ios latest, one for server latest, and repeating that for 10.0, 10.1 and so on.

**Comment by mmattel** [comment]
Closing as `lunr` will not be used.
