### ISSUE TITLE
New option `local` for `dav:cleanup-chunks` command

### ISSUE THREAD

**Issue by JammingBen** [owncloud/docs#4352]
## WHAT Needs to be Documented?

https://github.com/owncloud/core/pull/39394

## WHERE Does This Need To Be Documented (Link)?

https://doc.owncloud.com/server/next/admin_manual/configuration/server/occ_command.html#dav-commands

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Closed via 4372
