### ISSUE TITLE
user:move-home is only implemented for posix file systems

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#4438]
## WHAT Needs to be Documented?
Need to add this to the documentation in section `user:move-home`: is only implemented for posix file systems

See: https://github.com/owncloud/core/blob/0ad2d16c66f24b12c82b700359873a058edd1854/tests/Core/Command/User/MoveHomeTest.php#L77-L79

## WHERE Does This Need To Be Documented (Link)?
occ command set

## WHY Should This Change Be Made?
Completeness of docs

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@DeepDiver1975 FYI

**Comment by DeepDiver1975** [comment]
> `user:move-home`: is only implemented for posix file systems

well - it is only reasonable for posix. Such a command would be pointless in an object store setup.

In object store a similar command would be reasonable in an multi bucket setup - but this requires a totally different logic.

Just FYI ....
