### ISSUE TITLE
make validate / html fails

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#444]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [x] General

Example with `make validate`, same for `make html`
```
make validate
Validating xref links of all manuals defined within configuration
antora generate --pull --cache-dir cache --redirect-facility nginx --generator ./generators/validator site.yml
error: Generator not found or failed to load.
Add the --stacktrace option to see the cause.
Makefile:50: recipe for target 'validate' failed
make: *** [validate] Error 1
```
If I run the command manually and add `--stacktrace`to the options I get more details:
```
antora generate --pull --cache-dir cache --redirect-facility nginx --generator ./generators/validator --stacktrace site.yml
Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:548:15)
...
```
The commands suceeded before.

@tboerger @settermjd

**Comment by tboerger** [comment]
Nodegit isn't installed correctly anymore, you have to execute yarn install again. That's nothing we can solve on our side.

**Comment by mmattel** [comment]
I did that before, running the command again just now:
```
yarn install
yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.93s.
```
```
make validate
Validating xref links of all manuals defined within configuration
antora generate --pull --cache-dir cache --redirect-facility nginx --generator ./generators/validator site.yml
error: Generator not found or failed to load.
Add the --stacktrace option to see the cause.
Makefile:50: recipe for target 'validate' failed
make: *** [validate] Error 1
```

**Comment by tboerger** [comment]
Than delete the node modules directory and do it again. Building nodegit is sometimes a pita, good that this will be replaced soonish.

**Comment by mmattel** [comment]
After deleting as you suggested node_modules and rerun yarn install, eveything worked as expected.
I will add a note to the docs about that. Thanks for your help.
