### ISSUE TITLE
richdocuments integration with owncloud Web

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#4463]
## WHAT Needs to be Documented?

New feature: https://github.com/owncloud/richdocuments/pull/423

References:
- README update: https://github.com/owncloud/richdocuments/commit/e477d5b2331f4e6378cb4e00e0b0e8a15e39e285
- https://owncloud.dev/clients/web/deployments/oc10-app/#integrate-owncloud-classic-features-in-owncloud-web

## WHERE Does This Need To Be Documented (Link)?

user? admin? web? pfft.

## WHY Should This Change Be Made?

release 2.7.0 of richdcuments

## (Optional) What Type Of Content Change Is This? 
- [X] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Will integrate into pfft

**Comment by pmaier1** [comment]
https://github.com/owncloud/web/pull/6282
