### ISSUE TITLE
Hard to interpret the dashes because of line breaks

### ISSUE THREAD

**Issue by s-englert** [owncloud/docs#4480]
## WHAT Needs to be Documented?

Improve the visibility of dashes in the keys of MDM configuration paramaters.

## WHERE Does This Need To Be Documented (Link)?

https://doc.owncloud.com/ios-app/next/appendices/mdm.html

## WHY Should This Change Be Made?

When looking at the key, it's hard to tell if the dash (-) is part of the key, or is because a word is too long to display and spans multiple lines.  For example:

`item-policy.local-copy-expiration`

reads on the webpage as:

```
item-
poli-
cy.local-
copy-
expira
tion
```

So it's hard to tell which dashes are part of the keyword and which are because of line breaks.

## What Type Of Content Change Is This? 
- [x] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Manual related to
- [x] iOS MDM

**Comment by michaelstingl** [comment]
@mmattel we'd need a fix in the https://doc.owncloud.com/assets/css/site.css

Current CSS rule breaks everything:

```
.doc .content, .doc .tableblock, .doc p {
    -webkit-hyphens: no;
    -ms-hyphens: auto;
    hyphens:auto
}
```

**Comment by mmattel** [comment]
> Current CSS rule breaks everything

This is not the correct approach, we need to to set the col width correctly in the table definition. ATM, there is no col width set at all, so the build process renders on best guess. Fixing this in a relatively easy task. Will do a proposal for this.

**Comment by enbrnz** [comment]
Why don't we set `word-break: break-all;` for everything formatted as code globally. That should fix the issue everywhere?

[Mozilla developer documentation about the `word-break` CSS property ](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break)

**Comment by mmattel** [comment]
I have checked this with the PR referenced. No wonder, nothing changed as the column with was set as described above. Therefore the css rule cant overwrite this. The column with needs realignment - most likely using `~` which says "auto"...
