### ISSUE TITLE
Document new install and upgrade options

### ISSUE THREAD

**Issue by VicDeo** [owncloud/docs#449]
`occ upgrade` and `occ market:upgrade` got new option `--major`

- adjust automated update:
    - when doing minor update of core, don't fetch major version updates of app from marketplace
    - when doing major update of core, fetch major version updates of app from marketplace
- admin must have a way to force major update of app
    - `occ upgrade --major`
    - `occ market update --major`
- web UI shows both minor and major update, default on minor

More implementation details are available here
https://github.com/owncloud/market/issues/387#issuecomment-439357714

**Comment by mmattel** [comment]
Already done for `occ upgrade`
https://github.com/owncloud/docs/blob/ee289f703799efb00fd665bf7fe047363cb382fd/modules/administration_manual/pages/configuration/server/occ_command.adoc#L3027

But nobody told that this is also true for `occ market:upgrade` or I missed that one.
Needs docs update
