### ISSUE TITLE
Explain the field values returned by the provisioning API

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#4490]
## WHAT Needs to be Documented?
The response to a Provisioning API GET request to the cloud/users/username
endpoint now includes the last_login time in the response.
The value is a Unix timestamp in seconds.

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/next/developer_manual/core/apis/provisioning-api.html

## WHY Should This Change Be Made?
PR https://github.com/owncloud/core/pull/39351 is being merged for release in core 10.9.0

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by jnweiger** [comment]
In #4204 @phil-davis commented:
> I didn't see where we explain what the data items are in API responses.
> 
> last_login is a Unix timestamp in seconds.
> 
> The various quota items could also be explained - maybe they are explained somewhere already?

I could not find that either. 

One more detail:

For a never-logged in user, `ocs/v1.php/cloud/users/USERNAME` contains ` <last_login>0</last_login>`

**Comment by mmattel** [comment]
@phil-davis could you take over this part?

**Comment by phil-davis** [comment]
> @phil-davis could you take over this part?

Propose PR is #4495
