### ISSUE TITLE
New config.php key `sharing.showPublicLinkQuickAction`

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#4491]
Seen in 10.9.0 beta1

New feature is implemented: https://github.com/owncloud/enterprise/issues/4718

![image](https://user-images.githubusercontent.com/1108546/145317113-c1615897-4818-4549-9d9d-e7cc9a0c96f1.png)

`'sharing.showPublicLinkQuickAction' => true,` has to be set in the config.php to make this new feature available.

**Comment by mmattel** [comment]
This just needs a `config-to-docs` run, will do asap.

**Comment by mmattel** [comment]
Closing, already implemented, see #4493
