### ISSUE TITLE
New occ commands extending user:move these are user:home:list-dir and user:home:list-users <path>

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#4492]
## WHAT Needs to be Documented?
New occ commands: `user:home:list-dir` and `user:home:list-users <path>`
Referencing: https://github.com/owncloud/core/pull/39579 (Add user:home:list-dirs and user:home:list-users commands)

## WHERE Does This Need To Be Documented (Link)?
occ command set, user section, backport only to 10.9

## WHY Should This Change Be Made?
Completness of docs

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@JammingBen @phil-davis @pmaier1 fyi

**Comment by JammingBen** [comment]
👍   but be careful, the commands both start with user:**home**. It's singular, not plural in both cases 🙂

**Comment by mmattel** [comment]
> ...the commands both start...

just a typo, fixed in the comment above 😅
