### ISSUE TITLE
2FA - Add ImageMagick as requirement

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/docs#4507]
## WHAT Needs to be Documented?
ImageMagick is a need on the server in order to create the QR-code

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/next/admin_manual/configuration/user/user_auth_twofactor.html#setting-up-2fa

## WHY Should This Change Be Made?
Providing all necessary information and avoiding problems

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
@ChrisEdS as discussed, mind to drop a note on which OS this issue was based on?
