### ISSUE TITLE
Links partly broken in Document Classification

### ISSUE THREAD

**Issue by micbar** [owncloud/docs#451]
Links partly broken in:
https://doc.owncloud.com/server/administration_manual/enterprise/classification_and_policy_enforcement.html

## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

**Comment by micbar** [comment]
Has been late.. wanted to keep track of it.

https://doc.owncloud.com/server/administration_manual/enterprise/classification_and_policy_enforcement.html in the third paragraph.

lin:https://www.iso.org/isoiec-

**Comment by tboerger** [comment]
Thanks, now I can see it :D
