### ISSUE TITLE
Update sharing settings docs

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#452]
https://doc.owncloud.org/server/10.0/admin_manual/configuration/files/file_sharing_configuration.html is out of date:

Screenshot from 10.0.10

![screenshot from 2018-12-11 10-20-20](https://user-images.githubusercontent.com/21193500/49790413-67681f00-fd2e-11e8-8d09-4e2ad78981bb.png)

**Comment by pmaier1** [comment]
Looking at the PR I'm missing explanations for new options like 
- "Automatically accept new incoming local user shares" 
- "Default sharing permissions" 
- "Restrict users to only share with groups they are a member of"
- "Extra field to display in autocomplete results"
- Granular public link password enforcement

Sorry, I thought it is kind of obvious that it's not just the picture which is outdated but also the explanations for the recently added options. If you need help in understanding, please just ask.

**Comment by mmattel** [comment]
@pmaier1 no, it was not obvious for me.
You have details in your mind but we have to look to the deltas in each detail - very challenging.
For the next issue please be more precise what to look at which reduces misunderstanding.

For this one here, please provide content for the additional options and I will implement them asap.

**Comment by pmaier1** [comment]
Ok, sorry. Let me try to give some background:

- "Automatically accept new incoming local user shares"
Disabling this option activates the "Pending Shares" feature. Users will be notified and have to accept new incoming user shares before they appear in the file list and are available for access giving them more control over their account. More input here https://doc.owncloud.com/server/10.0/admin_manual/release_notes.html#pending-shares.
- "Default sharing permissions"
Administrators can define the permissions for user/group shares that are set by default when users create new shares. As shares are created instantly after choosing the recipient, administrators can set the default to e.g. read-only to avoid creating shares with too many permissions unintentionally.
- "Restrict users to only share with groups they are a member of"
When this option is enabled, users can only share with groups they are a member of. They can still share with all users of the instance but not with groups they are not a member of. To restrict sharing to users in groups the sharer is a member of the option "Restrict users to only share with users in their groups" can be used. More info: https://doc.owncloud.com/server/10.0/admin_manual/release_notes.html#more-granular-sharing-restrictions.
- "Extra field to display in autocomplete results"
The autocomplete dropdowns in ownCloud usually show the display name of other users when it is set. If it's not set, they show the user ID / login name, I think. As display names are not unique you can run into situations where you can't distinguish the proposed users. This option enables to add mail addresses or user ID's to make them distinguishable. 
- Granular public link password enforcement
https://doc.owncloud.com/server/10.0/admin_manual/release_notes.html#new-option-to-granularly-configure-public-link-password-enforcement

- The screenshot for "Blacklist Groups From Receiving Shares" is outdated
![group_share_blacklist](https://user-images.githubusercontent.com/21193500/50098641-9d207280-021c-11e9-8806-e0f0abeaa311.png)
