### ISSUE TITLE
"App Passwords / Tokens" image miss

### ISSUE THREAD

**Issue by ho4ho** [owncloud/docs#4538]
On https://doc.owncloud.com/server/next/user_manual/personal_settings/security.html#app-passwords-tokens image "create-new-app-password-token.png" looking like missing:

![app-passwords](https://user-images.githubusercontent.com/42564859/147299195-dbf08d64-735d-4a4f-a593-7cf68b4fb6cc.png)

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by EParzefall** [comment]
Thanks for reporting this!
