### ISSUE TITLE
Broken links in docs production 

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#467]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [x] Developer Manual
- [x] User Manual

## What Needs to be Documented?

Running `make clean` and `make html` in the local docs repo in master.
After that run `linkchecker --no-status --complete --check-extern http://localhost:5000 > ../linkchecker.log`

Monitorin the output you see as example:
```
URL        `https://doc.owncloud.org/server/9.0/ownCloud_Developer_Manual.pdf'
Name       `Download PDF'
Parent URL http://localhost:5000/server/, line 1342, col 2
Real URL   https://doc.owncloud.org/server/9.0/ownCloud_Developer_Manual.pdf
Check time 1.383 seconds
Size       1KB
Result     Error: 404 Not Found
```
Running `grep -r "ownCloud_Developer_Manual.pdf"`
```
Makefile:		--out-file server/developer_manual/ownCloud_Developer_Manual.pdf \
public/server/index.html:(<a href="https://doc.owncloud.org/server/9.0/ownCloud_Developer_Manual.pdf">Download PDF</a>)</p>
public/server/index.html:(<a href="https://doc.owncloud.org/server/8.2/ownCloud_Developer_Manual.pdf">Download PDF</a>)</p>
modules/ROOT/pages/index.adoc:  (https://doc.owncloud.org/server/9.0/ownCloud_Developer_Manual.pdf[Download PDF])
modules/ROOT/pages/index.adoc:  (https://doc.owncloud.org/server/8.2/ownCloud_Developer_Manual.pdf[Download PDF])
```
Note: `https://doc.owncloud.org/server/9.0/developer_manual/` works

IMHO, the issue is located in `modules/ROOT/pages/index.adoc`

## Why Should This Change Be Made?

Fix access

@settermjd @tboerger

**Comment by settermjd** [comment]
Are you fixing this?

**Comment by voroyam** [comment]
apparently not
