### ISSUE TITLE
Admin manual is not reachable in the navigation sidebar

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#4689]
Found while discussing server installation with a trainee. 
Scenario: Look up something, that we know is in the admin manual.

The sidebar opens initially like this:

![image](https://user-images.githubusercontent.com/1108546/152152841-2f1c4409-591d-4bb8-a7a4-14cb0449fa22.png)

To find the admin manual, I click open all triangles. The tree can be unfolded into:

![image](https://user-images.githubusercontent.com/1108546/152153191-4377e4e0-8f03-4699-b77e-d91102970120.png)

Expected behaviour: Admin Manual appears under 'Server documentation'

Also the usefulness of the section 'Useful Pages' is questionable:
* Admin Manual, User Manual, Developer Manual could also be listed there.
* The naming could be misunderstood as "anything not listed here is not useful"

**Comment by mmattel** [comment]
This is currently not possible and needs a change in the UI definition.
I have a clue about how to do it, but for the migration of the server it was necessary to go a walkable way knowing that it can be improved in a later step.

**Comment by mmattel** [comment]
I am closing this as there will be soon a revision on the way how things get shown and accessed. Will not solve it fully but close.
