### ISSUE TITLE
Disable users should not log in??

### ISSUE THREAD

**Issue by cdamken** [owncloud/docs#4709]
## WHAT Needs to be Documented?
This is confusing

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.9/admin_manual/configuration/server/security/oauth2.html#limitations

## WHY Should This Change Be Made?
We already know that disabled users can't log in. why is this a warning in the limitation?
I think that is normal behavior. :)

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by ChrisEdS** [comment]
Indeed `Do not attempt to log in with a disabled user.` - what do we mean by that? @mmattel

**Comment by erwinpalma** [comment]
What is the status of this ticket?

**Comment by DdeMarneffe** [comment]
The same warning is also here : https://doc.owncloud.com/server/next/admin_manual/configuration/user/user_oauth2.html#the-oauth2-app
```CAUTION : When using OAuth2, never try to log in with a disabled user.```

Two times the same warning... there should be a reason. Could you explain what it is ?

Thanks.

**Comment by pmaier1** [comment]
1. I do not find any mention of disabled users on the referenced page :thinking:  (https://doc.owncloud.com/server/10.9/admin_manual/configuration/server/security/oauth2.html#limitations)
2. The warning [here](https://doc.owncloud.com/server/next/admin_manual/configuration/user/user_oauth2.html#the-oauth2-app) does not make sense, indeed. Therefore I remove it with this PR https://github.com/owncloud/docs-server/pull/275.

Sorry for any confusion that this might have caused.

**Comment by mmattel** [comment]
Closed via https://github.com/owncloud/docs-server/pull/275
