### ISSUE TITLE
[Activity App] "Automated Task" needs documentation

### ISSUE THREAD

**Issue by JRundfeldt** [owncloud/docs#4720]
## WHAT Needs to be Documented?

Under certain conditions, the activity app can show "Automated Task". After an inquiry from a customer, neither the CST nor the support was able to answer the question:

"Under what conditions and scenarios can this entry be created?"

![automated-task](https://user-images.githubusercontent.com/95415117/163380365-3247b8e3-5f1a-4916-a248-4532afe5de9e.png)

## WHERE Does This Need To Be Documented (Link)?

https://doc.owncloud.com/webui/next/classic_ui/apps/activity.html

## WHY Should This Change Be Made?

Because the question is valid and relevant and the documentation is missing this information. Also because Support and Consulting was not able to answer this question after research in the code and the documentation

## (Optional) What Type Of Content Change Is This? 
- [X] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [X] Admin Manual
- [ ] Developer Manual
- [X] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
@JRundfeldt could you check with the developers when that term is used, means what is the background when it got printed. Based on the info, I can do the doc change.

**Comment by JRundfeldt** [comment]
Hi Martin,
thank you for your question. 
unfortunately, I dont even know who to ask in this regard. Because nobody I asked could provide an answer, I created this ticket. maybe we should just bulk-highlight some devs and hope that one or two knows the answer?

**Comment by mmattel** [comment]
I did a search with the term `Automated Task` in my ownCloud production instance (10.10) and did not get any results back. `/var/www/owncloud$ grep -rni "automated task"`

A search in core or activity repo also did not return any results...?

Courious where this comes from

**Comment by pmaier1** [comment]
This is not part of the official ownCloud product. No idea where it comes from.

**Comment by mmattel** [comment]
I am closing this issue. The text string has no origin in ownCloud and I highly believe that this belongs to a customer internal process which cant be solved by us. We can reopen if more and exact details can be provided.
