### ISSUE TITLE
Manual File Locking changed location in UI

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#4726]
## WHAT Needs to be Documented?
the manual file locking feature was moved in 10.9 from the admin > additional to admin > general section

This means the text has to be changed and a new screenshot has to be made

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/next/admin_manual/configuration/files/manual_file_locking.html

## WHY Should This Change Be Made?
so that users and admins can find it

**Comment by mmattel** [comment]
Closed via https://github.com/owncloud/docs-server/pull/307
