### ISSUE TITLE
Canot Copy docker-compose.yml from the GitHub repository

### ISSUE THREAD

**Issue by xenolinux** [owncloud/docs#4806]
## WHAT Needs to be Documented?
The correct GitHub location needs to be updated in the documentation

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/next/admin_manual/installation/docker/#docker-compose

## WHY Should This Change Be Made?
When running the command `$ wget https://raw.githubusercontent.com/owncloud/docs-server/master/modules/admin_manual/examples/installation/docker/docker-compose.yml` it cannot connect to the raw.githubusercontent.com.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by xenolinux** [comment]
If this issue is valid, I want to work on this issue

**Comment by mmattel** [comment]
Works, see:
`wget https://raw.githubusercontent.com/owncloud/docs-server/master/modules/admin_manual/examples/installation/docker/docker-compose.yml`
```
--2023-01-27 16:52:36--  https://raw.githubusercontent.com/owncloud/docs-server/master/modules/admin_manual/examples/installation/docker/docker-compose.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1781 (1.7K) [text/plain]
Saving to: ‘docker-compose.yml’

docker-compose.yml  100%[===================>]   1.74K  --.-KB/s    in 0s      

2023-01-27 16:52:36 (10.7 MB/s) - ‘docker-compose.yml’ saved [1781/1781]
```

**Comment by xenolinux** [comment]
@mmattel Thank you for sharing this. I will close the issue. There might be a problem on my end.
