### ISSUE TITLE
Split the current docs repo into docs (build only) and docs-main (main page content)

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#4875]
References: #4874

With the current setup of docs, we combine both the build process for the complete documentation and the content for the main web page. This is suboptimal as whenever there is a change in the main page, a complete (and long lasting) build of docs is necessary. On the other hand side, we mix up the docs build process with unrelated stuff.

**Solution:**

* Create a new repo named `docs-main` with 1:1 content from docs
* Adapt in `docs-main`:
  * site.yml and antora.yml accordingly.
  * Also adapt the pipeline, similar to like branding or ocis so that no push to web is taking place.
  * Remove not needed web-build relevant folders
* Delete in `docs` the modules content and add in site.yml the new `docs-main` repo
* Adapt in each versioned repo the _creating a new version description_
  * for final releasing, docs is still the location for a version number change (appears on the web)
  * for testing, the new version need to go into docs-main (does not appear on the web)

**Comment by TheRealBro** [comment]
To me this sounds like a staging environment, which I still don't see the need for our docs, as this should be possible to test locally when making changes.

**Comment by mmattel** [comment]
Closing via:
#4921 (Remove modules directory)
https://github.com/owncloud/docs-main/pull/1 (Copy documentation content from docs to docs-main)
and follow up PR's
