### ISSUE TITLE
ownCloud 10 not PostgreSQL 10/11

### ISSUE THREAD

**Issue by ho4ho** [owncloud/docs#490]
## What Type Of Content Change Is This?

- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

ownCloud 10 not PostgreSQL 10/11, only ownCloud 11:

https://github.com/owncloud/core/issues/29342#issuecomment-387388589, https://github.com/owncloud/core/issues/29342#issuecomment-444644391, https://github.com/owncloud/core/issues/31320#issuecomment-385896511

adding to:

https://github.com/owncloud/docs/blob/master/modules/administration_manual/pages/installation/system_requirements.adoc

maybe:

https://github.com/owncloud/docs/blob/master/modules/administration_manual/pages/configuration/database/linux_database_configuration.adoc

## Why Should This Change Be Made?
Explain what supported

**Comment by settermjd** [comment]
Thanks for opening this issue, @ho4ho. After I've confirmed, exactly, which versions of PostgreSQL are supported, I'll update the docs accordingly.
