### ISSUE TITLE
Improve and harmonize changelogs in the source repos

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#4901]
# Summary

Create a streamlined and easy look and feel for changelogs.

* All CHANGELOG.md files created in their respective repo should be based on the same markdown scheme. As template we must use the ocis repo (`#` vs `=` and `-`). NOTE, no change in the render result !
* All CHANGELOG.md must contain patch releases, if available.
* All CHANGELOG.md will get an automatically created table of contents (TOC) on changes with [bitdowntoc](https://github.com/derlin/bitdowntoc#from-the-command-line).
* All repo CHANGELOG.md's are already the source for `owncloud.com/changelog` - we will therefore see these updates immediately also on the web.

TOC example (using the current available changlog of ocis)
<img src="https://github.com/owncloud/docs/assets/3321281/2bd766ba-0d49-415e-a29c-4e184c7319b7"  width="300" />

# Current Situation

When looking on `owncloud.com/changelog` we see that we have 5 products: `ocis`, `server`, `desktop`, `ios`, `android`. Each changlog is sourced from its respective CHANGELOG.md file in master. This file contains the complete changlog for the product.

* All products show patch releases, though ocis does not show them for 4.0.x --> missing.
* We show server and ocis changelogs including patch releases for ocis and server in the admin docs.
* We show ocis changlog for 5.0.0 with a release date that is not yet released.
* CHANGELOG.md files are created on two different markdown schemes, see examples below. Using the correct one (ocis) would enable us creating a TOC automatically.
* None of the changelogs show a table of contents (TOC) on top which makes it quite hard to read it. In addition, it is VERY hard to find or identify missing or "wrong" items.

# Examples
## ocis current (good)
```
# Changelog for [unreleased] (UNRELEASED)

The following sections list the changes for unreleased.

[unreleased]: https://github.com/owncloud/ocis/compare/v5.0.0...master

## Summary

* Enhancement - Bump reva: [#7629](https://github.com/owncloud/ocis/pull/7629)
* Enhancement - Add support for audio files to the thumbnails service: [#7491](https://github.com/owncloud/ocis/pull/7491)
* Enhancement - Store and index metadata: [#7490](https://github.com/owncloud/ocis/pull/7490)

## Details
```
## server current (bad)
```
Changelog for ownCloud Core [unreleased] (UNRELEASED)
=======================================
The following sections list the changes in ownCloud core unreleased relevant to
ownCloud admins and users.

[unreleased]: https://github.com/owncloud/core/compare/v10.13.2...master

Summary
-------

* Bugfix - CalDAV query where the time range is not given: [#41050](https://github.com/owncloud/core/pull/41050)
* Bugfix - Store user information in explicit variable: [#41054](https://github.com/owncloud/core/pull/41054)
* Bugfix - Disallow browsers to translate the frontend: [#41067](https://github.com/owncloud/core/pull/41067)
* Bugfix - Limit performance impact when version meta data is enabled: [#41069](https://github.com/owncloud/core/pull/41069)
* Change - Update PHP dependencies: [#41033](https://github.com/owncloud/core/pull/41033)

Details
-------
```

The TOC example was created with:
`java -jar bitdowntoc-jvm-2.0.0.jar CHANGELOG.md --max-level 1 --trim-toc --no-anchors -o test.md`
Note that there are many options available and the output can directly be written back into the source file.

**Comment by mmattel** [comment]
After a brief sync with @DeepDiver1975 the creation of CHANGLOG.md files are based on templates, see the [server](https://github.com/owncloud/core/blob/master/changelog/CHANGELOG.tmpl) as example. There are for sure the same available for the other repos.

This means that the change from `=` and `-` --> `#` is quite easy. This would allow us to also go for the TOC with minimal efforts, though creating the TOC must be a separate process AFTER the CHANGLOG.md file has been created.

**Comment by micbar** [comment]
TOC can also be part of the template 🪄

**Comment by micbar** [comment]
TOC snippet.
Prepend to the current template

```
# Table of Contents
{{ range . -}}
  * [Changelog for {{ .Version }}](#changelog-for-{{ .Version | replace "." ""}}-{{ .Date -}})
{{ end -}}
```

**Comment by mmattel** [comment]
* Agreed that we do TOC's on each product repos.
* Added them at the referenced products successfully - merged.
* There is a small problem with linking on the oc homepage side that has already been reported and will be fixed soon. Nothing to do on our side.

@micbar many thanks for your support 👍 

Closing this issue, all done.
