### ISSUE TITLE
default config given on idp documentation is not working

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/docs#4917]
## WHAT Needs to be Documented?
idp documentation

## WHERE Does This Need To Be Documented (Link)?
https://owncloud.dev/services/idp/#example-yaml-config

## WHY Should This Change Be Made?
when running ocis with the example config ocis crashes and throws error
```bash
The ldap bind_password has not been set properly in your config for idp. Make sure your /home/user/.ocis/config config contains the proper values (e.g. by running ocis init or setting it manually in the config/corresponding environment variable).
```
if i give the `bind_password` that is in `~/.ocis/config/ocis.yaml`
it again crashes with following message.
```json
{
"level":"fatal",
"service":"idp",
"error":"failed to read CA certificate(s) from '~/.ocis/idm/ldap.crt': open ~/.ocis/idm/ldap.crt: no such file or directory",
"time":"2023-12-14T14:33:54+05:45",
"line":"/home/user/ocis/services/idp/pkg/service/v0/service.go:88",
"message":"could not bootstrap idp"
}
```

in the example it uses path `~/.ocis/idm/ldap.crt` in `cacert` but ocis dose not take that as a valid path. but giving the full path (`/home/user/.ocis/idm/ldap.crt`) works.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
@rhafer can you have a look why there is a difference in resolving?
`~/.ocis/idm/ldap.crt` ❌ 
`/home/user/.ocis/idm/ldap.crt` ✔️

**Comment by rhafer** [comment]
@mmattel See https://github.com/owncloud/ocis/issues/7972#issuecomment-1855487479.  I am not sure why the issue got duplicated here. Might have been a misunderstanding. I think this is a bug in the code that generates the config examples.

* It should not put `~` into any paths (I am not sure where that comes from)
* It should be called with the correct build flags (so the the `/etc/` based config paths and `/var/lib/...` based data paths are used (instead of the homedir).

**Comment by mmattel** [comment]
Closing as it is a code issue that if resolved will show up in any docs when fixed automatically.
