### ISSUE TITLE
apache http.conf note for headers

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#498]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

Referencing:
https://github.com/owncloud/core/pull/31231
https://doc.owncloud.com/server/administration_manual/installation/manual_installation.html#configure-apache-web-server
We shoud add a note, that if in case a webserver admin has added in http.conf a header directive, this directive will not cause issues as owncloud uses in its own header generation the `always` directive.

## Why Should This Change Be Made?

Helps apache admins understanding the behaviour if there are headers defined on both http.conf and owncloud. For more info see related core issue where this was fixed.

**Comment by mmattel** [comment]
Accidentially merged: #503 and reverted by #506 
Needs maybe a new PR with merge - hold until the backport of the referenced PR gets merged

**Comment by voroyam** [comment]
PR was merged. Closing
