### ISSUE TITLE
Need help with SSL setup for Apache

### ISSUE THREAD

**Issue by jonas740** [owncloud/docs#508]
Hello.

I need help. I am NOT an experienced Linux user so be kind :slight_smile:

I have gotten stuck in trying to configure my SSL for apache.

In this guide: https://doc.owncloud.org/server/10.0/admin_manual/installation/letsencrypt/apache.html 1

I have added the SSLOpenSSLConfCmd DHParameters /etc/apache2/dh4096.pem into my ssl.conf file wich is located in /etc/apache2/mods-enabled/ directory. I hope this is the correct place to add that.

After this the guide wants me to add “/.well-known/acme-challenge” in my Virtual host directive for port 80. But what file contains this directive ? I feel like a noob for not finding this.

Further down the guide they also want me to adopt my virtual host block. Where exactly do i find this ?

Im running Raspbian on my raspberry 3 b+

Googled like a crazy man to find answers but im a bit stuck at the moment.

Please help.

**Comment by settermjd** [comment]
Hey @jonas740, thanks for raising the issue. After a quick re-read through that section of the documentation, I see that it's not as clear nor as detailed as it needs to be. So I'll use this issue as a note to review and improve it, where required. 

As you're using Raspbian, which is based on Debian, it's Apache setup stores its [VirtualHost configuration files](https://www.stewright.me/2013/08/add-virtual-hosts-and-subdomains-to-your-raspberry-pi-apache2-server/) in `/etc/apache2/sites-available/`, and symlinks them to `/etc/apache2/sites-enabled/` 

And [here's a link to some further reading on Let's Encrypt](https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-18-04) and Ubuntu/Debian/Raspbian.

The best place to ask for this kind of help is at https://central.owncloud.org. You're far more likely to receive the help that you need in a timely fashion. So I encourage you to post your future questions there.
