### ISSUE TITLE
asciidoctor: WARNING when running make html

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#514]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [x] General

## What Needs to be Documented?

When running `make html` or `make html-local` you get a bunch of following errors:
```
asciidoctor: WARNING: skipping reference to missing attribute: request_base_path
asciidoctor: WARNING: skipping reference to missing attribute: username
asciidoctor: WARNING: skipping reference to missing attribute: password
```
## Why Should This Change Be Made?

Fix build process

**Comment by voroyam** [comment]
This warning message is really annoying, but since no customer is paying for it and it does not break the docs my suggestion is that it won't be fixed any time soon.

**Comment by settermjd** [comment]
The makefile approach has been deprecated for some time. Some errors are still reported when running `yarn antora`. I'll see about getting all of them corrected.
