### ISSUE TITLE
Create an "ultra short" docs introduction guide for Non-developers

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#523]
## What Type Of Content Change Is This?

- [X] New Content Addition
- [ ] Old Content Deprecation
- [X] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

An ultra-short getting started guide for non-developers is required.

## Why Should This Change Be Made?

After talking with @voroyam, he made an excellent point that while the docs guide is excellent for developers, it's too involved for non-technical people, such as marketers and sales.

**Comment by mmattel** [comment]
Can this be closed as #525 is merged?
