### ISSUE TITLE
my new issue

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#524]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

example

## Why Should This Change Be Made?

make an example

**Comment by voroyam** [comment]
This make sense

**Comment by tomneedham** [comment]
Does it?
