### ISSUE TITLE
User-key encryption set password from env

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#531]
## What Type Of Content Change Is This?

- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## Why Should This Change Be Made?

We need to document how to set the password from env for it to be readable for the decryption command.

also the command for decrypt all with password from env is not in the command desctipion.

**Comment by mmattel** [comment]
Dupe of #258. More info can be found there.

**Comment by settermjd** [comment]
Closing, as it's a duplicate.

**Comment by voroyam** [comment]
Okay, what I wanted is to document how to set the password variable and what to be aware of.
In detail:

`export OC_RECOVERY_PASSWORD=1111
`

and that this command has to be either executed as the web server user or the occ command has to be executed with the -E flag to import the environment variables in the web server users profile. If someone doesn't know this he will fail. Maybe this is common knowledge but I wanted it documented anyway as me and a few others had run in this mistake.

@mmattel 

> More info can be found there.

I have to go to the other issue, read all the comments, figure out that what I want is maybe behind the link to the PR, read the whole PR and figure out that my info is not in the PR and then write here again.

I don't think that that's the way we want to treat people who want to contribute to the docs. This is how you get people discouraged. At least that's what I think.

**Comment by voroyam** [comment]
fixed by https://github.com/owncloud/docs/pull/1489

closing
