### ISSUE TITLE
Document OAuth2 Limitations regarding web sessions.

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#534]
## What Type Of Content Change Is This?

- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

Limitations regarding web sessions. It's not possible to end user sessions (web sessions) with OAuth.

## Why Should This Change Be Made?

A customer wanted to manage user sessions, and found no explicid documentation about the limitation of OAuth2 regarding web sessions.

------------

Why is here no "where does this need to be documented?" section like in my idea for the template.

Now if I write just what in the current template people will ask "where do you think this should be documented instead of knowing it because it is in the template...

https://doc.owncloud.com/server/administration_manual/configuration/server/security/oauth2.html#limitations

https://github.com/owncloud/docs/blob/master/modules/administration_manual/pages/configuration/server/security/oauth2.adoc

**Comment by settermjd** [comment]
You can always update the template if you like.

**Comment by settermjd** [comment]
Yes. I saw.

**Comment by voroyam** [comment]
fixed with https://github.com/owncloud/docs/pull/1507

**Comment by voroyam** [comment]
merged, backported
