### ISSUE TITLE
Merge the 2 OCC documents as well as the 2 Config sample documents

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#535]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

merger of the 2 documents in to 1.

## Why Should This Change Be Made?

makes it easier to find stuff

**Comment by settermjd** [comment]
I disagree. The reason for separating the original document into two makes sense, as that way the original document only contains commands that will always be present, and the second file can contain any number of external commands, which are, arguably, optional.

**Comment by voroyam** [comment]
if you need to look up a command you will spend less time searching in 2 pages then in 1 page.

**Comment by settermjd** [comment]
I still agree with the separation. However, search functionality would/should resolve this situation.

**Comment by voroyam** [comment]
People ( me inclusive ) can't find the commands quickly.

Merge of the 2 documents needed.

**Comment by PVince81** [comment]
if merging the docs is a concern, we could wait out until the search is deployed and see if people are still confused after that

**Comment by cdamken** [comment]
IMHO, we can have both documentation on the same page, core on the top and the additional in the bottom. the search will take a lot of time until its done.

**Comment by voroyam** [comment]
Support work is impossible in the current status, if I don't know what the key is, search isn't a help either.

I am more and more inclined to stop working on improving the online docs and start an offline personal docs.

**Comment by PVince81** [comment]
please open a PR to merge the two pages. I think we saw enough arguments that spoke in favor of this.

**Comment by mmattel** [comment]
The common source of `config` files is core. Any change that is made must be made in core and then transported via a script (https://github.com/owncloud/config-to-docs) to docs. Changes made in docs will be overwritten by the next `config-to-docs` run.

`occ` commands do not have a source in core. Their origin is in docs.

Any changes made need to be made carefully and tested as they address multiple elements.
Contentwise, script and navigation.

Note: it would be VERY wise to think about NOT again mixing up topics in config/occ documents as it was in the past and therefore challenging reading thru the documents. It was often that new elements were just added on the bottom making them hard to read. I propose therefore to think about upfront how to seperate and identify topics in a way that lasts long and satisfies readers.
Please also take care, that there will be a lot of enterprise app documentation work to be done where we currently lack.
(@PVince81 keyword: shipped/tar in various editions)

**Comment by voroyam** [comment]
merged, closing
