### ISSUE TITLE
Add msi=true to "Updating Your Branded Desktop Clients"

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/docs#537]
## What Needs to be Documented?
Add `msi=true` to "Updating Your Branded Desktop Clients" (MSI = Windows)

## Why Should This Change Be Made?
One user noticed that we should add the `msi=true parameter` to the documentation.

I have the following feedback: "So not everybody has to reverse engineer how to test the msi entry"

## Where Should This Change Be Made?
https://doc.owncloud.com/branded_clients/branded_desktop_client/update_branded_desktop_clients.html

https://github.com/owncloud/branded_clients/blob/master/branded_desktop_client/update_branded_desktop_clients.rst

## What Type Of Content Change Is This?

- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

**Comment by ChrisEdS** [comment]
@settermjd I can't find the actually used repo for the `update_branded_desktop_clients.html` 
In this file https://github.com/owncloud/branded_clients/blob/master/branded_desktop_client/update_branded_desktop_clients.rst it points to the outdated *.PHP approach.

**Comment by settermjd** [comment]
That's the old file. The new, AsciiDoc/Antora version is https://github.com/owncloud/branded_clients/blob/master-antora/modules/ROOT/pages/branded_desktop_client/update_branded_desktop_clients.adoc.

**Comment by settermjd** [comment]
@ChrisEdS, what's the reason for adding the `msi=true` parameter?

**Comment by ChrisEdS** [comment]
I added the following line in addition: 
**"So not everybody has to reverse engineer how to test the msi entry"**

**Comment by ChrisEdS** [comment]
**More information relating to this issue from the user:**

In the "Debugging client-updater-server" there are examples of urls to use to test the results. So for Windows it is:
https://mycloud.example.com/updates/?version=2.1.1.140&platform=win32&oem=mycloud
And then I change it to https://cloud-id.switch.ch/update/?version=2.1.1.140&platform=win32&oem=switchdrive and see if everything is right. 

Now there is this new platform parameter "win32msi" but https://cloud-id.switch.ch/update/?version=2.1.1.140&platform=win32msi&oem=switchdrive doesn't work.
=> "Platform could not be detected: win32msi"

So after looking into the code I figured I need to take the normal win32 link and add the msi=true parameter at the end
https://cloud-id.switch.ch/update/?version=2.1.1.140&platform=win32&oem=switchdrive&msi=true
to test wether the win32msi parameters come back ok.

**Comment by settermjd** [comment]
I've never built a branded client, nor used the Microsoft Installer. Would you mind making the relevant changes to the documentation?

**Comment by michaelstingl** [comment]
@dschmidt Could you take care?

**Comment by dschmidt** [comment]
@michaelstingl Yes, no problem. Maybe someone should let them know they should enable php on their webserver, I'm currently served php in plaintext…

**Comment by dschmidt** [comment]
And yes the behavior is correct. The reasoning is: we want to leave some control to the updater server. The client only specifies its capabilites. It says "I'm version x.y.z and I support msi." The server is then free to either serve an .exe or .msi installer because both are still supported.

The win32msi platform is sort of an internal implementation/configuration detail but it's not part of the protocol.

**Comment by settermjd** [comment]
@dschmidt, can you update the relevant sections of the documentation please?

**Comment by ChrisEdS** [comment]
@dschmidt Close?

**Comment by settermjd** [comment]
Why was the issue closed and reopened, @ChrisEdS?

**Comment by ChrisEdS** [comment]
Got no confirmation from @dschmidt - Can we close it?

**Comment by dschmidt** [comment]
This is so old, I don't remember - I will confirm.

**Comment by settermjd** [comment]
@dschmidt, any further update?
