### ISSUE TITLE
iOS and Android failure in "Distributing Your Branded Android App"

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/docs#539]
## Where Should This Change Be Made?
The documentation is wrong transfered to Antora.

https://doc.owncloud.com/branded_clients/branded_ios_app/publishing_ios_app_9.html

![image](https://user-images.githubusercontent.com/33026403/51481135-76ada400-1d93-11e9-9e8a-2772a9d1304c.png)

## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [x] Developer Manual
- [x] User Manual

**Comment by ChrisEdS** [comment]
@settermjd Can you take care?

**Comment by mmattel** [comment]
Closing, PR merged
