### ISSUE TITLE
:file:`xcarchive.zip` is deprecated in "Publishing Your New Branded iOS App"

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/docs#540]
## What Needs to be Documented?
Publishing Your New Branded iOS App
https://github.com/owncloud/branded_clients/blob/master/branded_ios_app/publishing_ios_app_9.rst

:file:`xcarchive.zip` is deprecated - this is now a *.IPA file called something like `yourCloud-3.8.0.1766_ad_hoc.ipa`

## Why Should This Change Be Made?
:file:`xcarchive.zip` is deprecated 

## Where Should This Change Be Made?
https://github.com/owncloud/branded_clients/blob/master/branded_ios_app/publishing_ios_app_9.rst

## What Type Of Content Change Is This?

- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/docs/issues/370

**Comment by settermjd** [comment]
Thanks, @michaelstingl.
