### ISSUE TITLE
Document Auto accepting of incoming federated shares from trusted servers

### ISSUE THREAD

**Issue by VicDeo** [owncloud/docs#542]
## What Needs to be Documented?
Auto accept incoming federated shares from trusted servers
https://github.com/owncloud/core/pull/33980

There is a new checkbox `Automatically accept remote shares from trusted servers` at the admin sharing settings section.
When it is checked the remote share is accepted automatically if the server is in the **Trusted servers** list.
Due to security reasons auto accepting doesn't work when **Add server automatically once a federated share was created successfully** is checked.

## Why Should This Change Be Made?
IDK

## Where Should This Change Be Made?
https://doc.owncloud.org/server/10.0/admin_manual/configuration/files/federated_cloud_sharing_configuration.html

## What Type Of Content Change Is This?

- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

**Comment by settermjd** [comment]
Currently blocked because of an error setting up a test environment (so that I can validate the functionality); specifically, the following error, when attempting to share a file to a user in a federated ownCloud instance: `cURL error 51: SSL: certificate subject name 'server-1.localdomain' does not match target host name 'server-2.localdomain'`.

**Comment by PVince81** [comment]
who can help ? @VicDeo @phil-davis @individual-it ?

**Comment by VicDeo** [comment]
@settermjd 
the most probable reason is a wrong SSL cert specified for server-2.localdomain in apache config.

you can add the following into config.php to allow using http instead of https 
```
'sharing.federation.allowHttpFallback' => true,
```

**Comment by micbar** [comment]
@settermjd See comment https://github.com/owncloud/docs/issues/542#issuecomment-483596088.

Could this unblock you? If not, please ping me :-)

**Comment by settermjd** [comment]
Will check today.
