### ISSUE TITLE
Document make test-php-style for core development

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#544]
## What Needs to be Documented?
When developing core code, see https://github.com/owncloud/core/blob/master/Makefile
`make test-php-style`
`make test-php-style-fix`

## Why Should This Change Be Made?
This is an important note for (new) developers,
that their code gets style checked and fixed with `php-cs-fixer`
Fixes most violations against PSR-1 and PSR-2
For a before/after example you may take https://mattstauffer.com/blog/using-php-cs-fixer-to-fix-up-your-php-code/

## Where Should This Change Be Made?

Maybe a new page referenced in https://github.com/owncloud/docs/edit/master/modules/developer_manual/pages/core/index.adoc

## What Type Of Content Change Is This?

- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual

@phil-davis, @PVince81 @DeepDiver1975  fyi

**Comment by settermjd** [comment]
Closing, as this was collectively implemented in #1963, & #1976.
