### ISSUE TITLE
"Hidden Users" Feature is wrong.

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#546]
## What Needs to be Documented?

"will be hidden users"

There are no hidden users in ownCloud.

----------

## Where Does This Need To Be Documented?
https://doc.owncloud.com/server/administration_manual/configuration/user/user_auth_ldap.html#user-filter

https://github.com/owncloud/docs/blob/master/modules/administration_manual/pages/configuration/user/user_auth_ldap.adoc

----------

## Why Should This Change Be Made?

Wrong information. Not reproducible.

**Comment by mmattel** [comment]
@voroyam in case you create a PR, pls link it so the issue can be closed when teh PR gets merged.

**Comment by voroyam** [comment]
Yeah, I forgot it because I was so overwhelmed by the quality of my issue :)
Thanks @mmattel

**Comment by settermjd** [comment]
Closing as the implementing PR's been merged.
