### ISSUE TITLE
When using federation, persistent locks are not guaranteed / not supported 

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#553]
Referencing core issue:  https://github.com/owncloud/core/issues/34222
(Propagate persistent lock to federated instance)

## What Needs to be Documented?

Persistant lock behaviour for federated shares are not supported or guaranteed.

## Where Does This Need To Be Documented?

Need to look where it is appropriate, will update if known.

## Why Should This Change Be Made? (Optional)

Admins need to know persistant lock behaviour for federated shares.

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@PVince81 @individual-it @settermjd FYI

**Comment by individual-it** [comment]
see also https://github.com/owncloud/core/issues/34343
a receiver of a fed-share can set local locks on the received files as if they are local, but that also has bugs

**Comment by settermjd** [comment]
@mmattel, would you be interested in and have time to implement a PR for this?

**Comment by mmattel** [comment]
Not atm, sorrry :disappointed_relieved:
