### ISSUE TITLE
Finish integrated site search

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#554]
This issue is for tracking why the integrated site search is not yet finished, and to work it through to completion. It was envisaged (and understood) to be a very straight-forward process. However, it's met with unexpected blockers. 

These have been identified as:

- Integrating [the Algolia docsearch-scraper tool](https://community.algolia.com/docsearch/crawler-overview.html) with Drone
- That Antora's composed of (effectively) two parts:
  1. The documentation generator
  2. The UI component

It's been difficult to determine at what part in the process the fault is occurring. However, the list of identified items to resolve are:

- [ ] Debug search index update
- [ ] Debug render of search bar

### Search Index Update

Currently, when running the Drone `update-search` task, it ends with the following error:

```
Nb hits: 41930
previous nb_hits: 15513

Do you want to update the nb_hits in /drone/src/search/algolia/config.json ? [y/n]:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/src/index.py", line 98, in <module>
    run_config(environ['CONFIG'])
  File "/root/src/index.py", line 87, in run_config
    config.update_nb_hits(DocumentationSpider.NB_INDEXED)
  File "src/config/config_loader.py", line 135, in update_nb_hits
    nb_hit_updater.update()
  File "src/config/nb_hits_updater.py", line 24, in update
    'Do you want to update the nb_hits in ' + self.config_file + ' ?'):
  File "src/helpers.py", line 10, in confirm
    ans = input(prompt)
EOFError: EOF when reading a line
```

The advice from Algolia support is to:

> Please use the ./docsearch docker:run <path_to_config> command. It will use a docker image that does not include the nb_hits updater.

I don't believe that's an option, as I've tried to emulate it locally, yet the same error persists. I've contacted them for support regarding this. I believe that https://github.com/owncloud/docs/pull/557 is the answer to this. But it needs to be peer reviewed before it can be merged.

### Render of search bar

The search bar should be visible and be able to use the existing index. I suspected that the relevant config variables were not being passed from the environment to the Antora build, resulting in the relevant code not being activated. 

However, after further investigation, I'm convinced that clearing the `/cache/ui` directory is the solution. After doing so, the recent UI changes — including the integrated search functionality — will then be visible.

Going forward, the build process needs to be updated to account for changes to the ui-bundle.zip file. If its timestamp's changed since the last build, the `/cache/ui` directory needs to be emptied before the next build of the docs.

**Comment by PVince81** [comment]
@settermjd is the rendering of the search bar also happening locally ?

**Comment by settermjd** [comment]
Re https://github.com/owncloud/docs/issues/554#issuecomment-458125381, yes. Everything works. I'm just trying to figure out what is different between the local version and the remote.

**Comment by settermjd** [comment]
Okay, after quite some experimentation, the reason that the search isn't appearing is because of some difference in the UI theme. As yet, I don't know what that difference is, but the problem's been isolated.

**Comment by settermjd** [comment]
Well, I thought it had, but a diff of both files shows no difference that should affect the rendering. So at this stage, I'm a bit stuck as to what's causing the issue.

**Comment by settermjd** [comment]
From what I can tell, the `cache/ui` directory needs to be removed from the s3 cache. Once that's done, the integrated site search will be available.

**Comment by PVince81** [comment]
PR here was merged: https://github.com/owncloud/docs/pull/565

anything else or does it work now ? :-D

**Comment by settermjd** [comment]
@tboerger is handling this, replacing Algolia with an ElasticSearch setup. I believe that it's almost finished.

**Comment by tboerger** [comment]
```
curl -s https://docs:cADL6DDAKEBrkFMrvfxXEtYm@search.owncloud.com/docs/_search?q=acmecloud_2.0.0-release-unsigned.apk
```

The index already gets built, now we need to add some kind of UI on our own.

**Comment by settermjd** [comment]
@tboerger, anything I can do to help here?

**Comment by PVince81** [comment]
seems this is done, close ?
