### ISSUE TITLE
Win Client Removal

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#555]
## What Needs to be Documented?

We need to document how to remove win sync client remnants from the system.

For example the Folder Icon from the Sidebar.

## Where Does This Need To Be Documented?

A new document page in the client docs

https://doc.owncloud.com/desktop/index.html

https://github.com/owncloud/client/edit/master-antora/docs/modules/ROOT/pages/index.adoc

something like:

https://github.com/owncloud/client/edit/master-antora/docs/modules/ROOT/pages/removal.adoc

## Why Should This Change Be Made? (Optional)

Because we don't have any docs to provide to users or customers on how to remove client remnants.

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [x] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
@voroyam MANY thanks for catching that one. 👍 
If you know any references for macos, linux, please add them or open another issue accordingly.

**Comment by voroyam** [comment]
According to our expect @michaelstingl the only troublesome OS is windows. The other are pretty straight forward. But if I catch something I will add it :)

**Comment by mmattel** [comment]
As far I remember, there is general no description about removing the remnants for any OS.
This could be header and subheaders for each OS - what do you think ?

**Comment by settermjd** [comment]
Does anyone have time to complete this? I don't have a Windows machine.

**Comment by voroyam** [comment]
I would take care of this myself

**Comment by voroyam** [comment]
https://github.com/owncloud/client/pull/7028

**Comment by mmattel** [comment]
https://github.com/owncloud/client/issues/5342#issuecomment-349336736

**Comment by voroyam** [comment]
Yeah, have to make a PR to include the suggestion of @mmattel about the config file that remains on the system after the client gets removed.

**Comment by tboerger** [comment]
I have merged the client docs to master branch now.

**Comment by mmattel** [comment]
I just double checked the script referenced.
This script does not seem to work as intended as paths and  parameters do not match respectively you do not know them.

**Comment by voroyam** [comment]
fixed, merged. closing
