### ISSUE TITLE
Fix the few other references to Swift in the documentation

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#556]
Referncing: https://github.com/owncloud/docs/pull/526
> Great to see, @haukman. However, there are a few other references to Swift in the documentation. Are you planning to remove them as well?
> 
> They're in:
> 
>     * modules/administration_manual/pages/configuration/server/occ_command.adoc, lines 1263 and 1450.
> 
>     * modules/administration_manual/pages/configuration/files/external_storage/openstack.adoc, lines 3 & 4.
> 
>     * modules/administration_manual/pages/installation/apps_supported.adoc, line 26
> 
>     * modules/user_manual/pages/files/access_webdav.adoc, line 336

Yes, will do!

## Where Does This Need To Be Documented?

Fix the few other references to Swift in the documentation

## Why Should This Change Be Made? (Optional)

Cleanup

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
@haukman, can you add your feedback here, pls?

**Comment by settermjd** [comment]
Ping, @haukman.
