### ISSUE TITLE
Add repro config-to-docs as submodule + make commands

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#562]
The repro https://github.com/owncloud/config-to-docs needs to be added as submodule.
This is necessary, because when there is a change in core on config.sample / config.apps.sample, we need to run config-to-docs to create a docs version of the two files.

As a second task, it would be great if there would be a make command which calls the neccesary conversion. Maybe two make commands, one for core and one for apps like `make config-core` `make config-apps`.

Some help content in make would also be useful...

## Why Should This Change Be Made? (Optional)

If not done, it would be easily overseen that changes on the source files need conversion to become part of docs.

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [x] Other

**Comment by tboerger** [comment]
Please don't add submodules. Instead of a submodule we could use composer to get the library installed and execute the command via composer.

After the drone update we could add a nightly job that updates/executes this task.
