### ISSUE TITLE
Implement New Branching & Build Strategy

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#563]
As part of the release of oC 10.1.0, the branching and build strategy needs to be updated. With the initial release of the Antora-based docs, we've only used the master branch. 

However, the plan for the future is to have up to three versions of the docs at any one time. These would be master and two prior releases. To do this, will take a bit of work, but should be, relatively, straight-forward.

### 1. Update the Antora Playbook (site.yml)

Add the next two releases of each one of the _docs_, _android_, _iOS_, _client_, and _branded_client_ repos to the branches (or tags) array of the respective content.sources.branches element in `site.yml` in the docs repo.

For example, for the docs repo, it will be configured as in one of the examples below:

#### Using Branches Only

```yaml
content:
  sources:
  - url: .
    branches: [master, 10.1.0]
```

#### Using a Mix of Branches and Tags

```yaml
content:
  sources:
  - url: .
    branches: [master]
    tags: [10.1.0,10.2.0]
```

Regardless of the approach the URLs will be as follows:

| Branch/Tag | URL Path Example |
|---|---|
| Master | `/server/index.html` |
| 10.1.0 | `/server/10.1.0/index.html` |

Here is an example of what the version switcher would render like, with more than one version per repository. You can see that there are two options for the server docs, and the currently active one is highlighted.

<img width="319" alt="ownCloud document switcher with multiple repository versions" src="https://user-images.githubusercontent.com/196801/51909550-38386a80-23cd-11e9-9f90-efc3c83bea27.png">

### 2. Update Drone

Drone needs to be updated to build a release (run antora) if any of listed branches (or tags) in the respective repositories is merged to. From reseach, I don't believe that the docs deployment process needs to change, as the generated files are self-contained, as in the following example:

```console
[docs] l public/server                                                                                                                                              
drwxr-xr-x   9 matt  staff   288B Jan 29 13:45 .
drwxr-xr-x  11 matt  staff   352B Jan 29 13:45 ..
drwxr-xr-x   8 matt  staff   256B Jan 29 13:45 10.1.0
drwxr-xr-x  15 matt  staff   480B Jan 29 13:45 administration_manual
drwxr-xr-x  12 matt  staff   384B Jan 29 13:45 developer_manual
-rw-r--r--   1 matt  staff    56K Jan 29 13:45 how_to_contribute.html
-rw-r--r--   1 matt  staff    60K Jan 29 13:45 index.html
-rw-r--r--   1 matt  staff    53K Jan 29 13:45 release_notes.html
drwxr-xr-x  12 matt  staff   384B Jan 29 13:45 user_manual
```

Note that the master (core) release's files and directories are in the root of `public/server` and any subsequent release's files and directories are in a directory named after the branch or tag, e.g., `10.1.0`.

### 3. Revise the PDF generation process

The PDF generation process needs to be restructured to account for multiple releases, as the current script only builds PDF files for a single release. It'd be ideal if Antora natively supported PDF generation, but that's not likely to be available [until Q2 2019](https://gitlab.com/antora/antora/issues/349). 

In the meantime, I think the Makefile could be refactored to parse the Playbook file (`site.yml`), extract the branches or tags, and build the PDF manuals, based on the obtained information.

## Should We Use Branches or Tags?

tbw

## What is the Branching and Tagging Naming Convention

I suggest following the convention from the previous documentation, using a `v` prefix followed by a version name that follows semantic versioning rules, such as `v10.1.0`.

## How is Content Backported?

There are two clear approaches to handling this:

1. In the latest version, include "_In Version X_" sections to document deprecations, bugs, etc.
2. Backport feature branches to all relevant previous branches

I'm not a fan of "_In Version X_" sections. From experience, while they're handy for a while, and clearly bring attention to which version a feature is available in, in which version a feature was deprecated, and when the bug existed, etc, over time they become a nightmare to maintain. 

I'm sure — in limited circumstances — they're a very effective and applicable tool. However, I'm not a supporter of using them as a normal matter of course. 

Personally, I support backporting feature branches to the relevant previous builds and letting the build pipeline deploy the docs. This approach has a much smaller maintenance overhead.

## What Needs to be Documented?

As part of this issue, the docs meta docs need to be updated to document the new process, so that it's clearly understood, and easily discoverable.

## Where Does This Need To Be Documented?

In `docs/`

## Why Should This Change Be Made? (Optional)

The change needs to be made, and the content around it discussed as from the next release, the docs is moving to a multi-version deployment. So the background and the mechanics of it need to be addressed.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content
- [X] Change to the build pipeline

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [x] Developer Manual
- [x] User Manual
- [x] Android
- [x] iOS
- [x] Branded Clients
- [x] Desktop Client
- [ ] Other

**Comment by PVince81** [comment]
we can use both branches and tags like we do in core.

so far maybe the branch needs to reflect the core version that matches, for example stable10, stable11, master... and the tag is there to mark a specific version of the docs.

one challenge with tags is that it would need to describe the version of the documentation, not the core version. imagine if the docs for 10.0.10 has some mistakes and have been tagged as v10.0.10 and we fix them, we'd need to tag them as v10.0.10.1 or something else...

**Comment by settermjd** [comment]
Let me think that over. But thanks for the info and label addition.

**Comment by tboerger** [comment]
Anything missing for that? Maybe some docs how to backport changes?
