### ISSUE TITLE
Replacement db-binlog-label with similar missing

### ISSUE THREAD

**Issue by ho4ho** [owncloud/docs#568]
## What Needs to be Documented?
e.g. db-binlog-label, db-storage-engine-label, db-transaction-label

Similar with https://github.com/owncloud/docs/issues/488

Example:

https://github.com/owncloud/docs/blob/master/modules/administration_manual/pages/installation/troubleshooting.adoc

https://github.com/owncloud/docs/blob/master/modules/administration_manual/pages/installation/system_requirements.adoc

https://github.com/owncloud/docs/blob/master/modules/administration_manual/pages/maintenance/manual_upgrade.adoc

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
@ho4ho thanks for creating this issue. However, can you add more detail to the issue please. It's hard to fully understand what you're asking.

**Comment by ho4ho** [comment]
@settermjd Example is https://github.com/owncloud/docs/blob/master/modules/administration_manual/pages/installation/troubleshooting.adoc has:

> your ownCloud log please refer to **_db-binlog-label_** for how to resolve it.

similar with others.

**Comment by settermjd** [comment]
Understood. Thanks.

**Comment by settermjd** [comment]
Closing as the issue appears to be resolved.

**Comment by ho4ho** [comment]
Looks like bugfix by https://github.com/owncloud/docs/pull/916
