### ISSUE TITLE
[Collection of Ideas] Rework Admin_Manual -> Installation Options -> Manual Installation

### ISSUE THREAD

**Issue by haukman** [owncloud/docs#577]
## What Needs to be Documented?
This ticket should collect ideas on how we can improve the manual installation part of the admin manual: https://doc.owncloud.org/server/administration_manual/installation/manual_installation.html

## Where Does This Need To Be Documented?
https://doc.owncloud.org/server/administration_manual/installation/manual_installation.html

## Why Should This Change Be Made? (Optional)
At the moment, it´s not possible to do a complete manual ownCloud installation based on the available docs. This should be improved.

## Ideas

Hauke: My idea would be to use the available installation guides from the consutlting team, as they are proven in real customer scenarios: https://github.com/owncloud/GCX/tree/master/how-to/Deployment

Regarding the structure, I would like to see something similiar as Docker has: 

<img width="239" alt="grafik" src="https://user-images.githubusercontent.com/25486818/52272933-9e326e00-2948-11e9-9726-3bcc09e01557.png">

https://docs.docker.com/install/

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by haukman** [comment]
@voroyam @michaelstingl @patrickjahns

**Comment by voroyam** [comment]
sounds good. Do we have something missing in the GCX deployments that needs to be documented?

**Comment by haukman** [comment]
No, I think we have the major distributions in there:

- RHEL
- CentOS
- SLES
- Ubuntu 

Missing:

- Debian
- Fedora

**Comment by haukman** [comment]
In general, an installation guide consists of the following parts:

1. Dependencies (OS specific)
2. Database (OS specific -> except MySQL commands)
3. Apache setup (OS specific?)
4. Post installation steps (Redis, APCU...)

**Comment by voroyam** [comment]
would you like a OS walk through approach, like for every distribution we have a from start to finish guide, or a step approach, where we have 1. dependencies for OS1 OS2 OS3 and then 2. DB for OS1 OS2 OS3?

**Comment by haukman** [comment]
> would you like a OS walk through approach, like for every distribution we have a from start to finish guide, or a step approach, where we have 1. dependencies for OS1 OS2 OS3 and then 2. DB for OS1 OS2 OS3?

This is up for discussion - the only thing that matters is that installation ownCloud is described in a way that you are able to create a proper deployment with that, w/o the need of using external guides, forums etc.

**Comment by voroyam** [comment]
Is the installation part of the docs the only thing that is going to be discussed on this meeting?

**Comment by voroyam** [comment]
Installation option have been reworked

![image](https://user-images.githubusercontent.com/24212810/63949004-01692680-ca7a-11e9-88f0-de80a3e83cd6.png)
