### ISSUE TITLE
having .com and .org as only one documentation

### ISSUE THREAD

**Issue by cdamken** [owncloud/docs#58]
IMO the theme from .com looks fine and we could use it as default

about the doc.owncloud.com and doc.owncloud.org the urls jump from one to another and both have the same documentation.

is it possible to have a redirect from one to the other and use it by default?

@felixboehm @hodyroff @pmaier1 @settermjd  What do you think about this?

**Comment by tboerger** [comment]
The new docs are still work in progress and we will have it unified when it's done.
