### ISSUE TITLE
WOPI docs

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#596]
## What Needs to be Documented?

- How to set up and configure the MS Office Online / WOPI integration
- Mention that you need a running MS Office Online Server
- https://github.com/owncloud/wopi/blob/master/README.md for input
- @DeepDiver1975 can answer questions

## Where Does This Need To Be Documented?

- Admin docs (somewhere below https://doc.owncloud.com/server/administration_manual/enterprise/ ?)

## Why Should This Change Be Made? (Optional)

- We released the Office Online integration and need to provide information on how to set it up

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@settermjd

**Comment by settermjd** [comment]
Implemented in #601.
