### ISSUE TITLE
Review the client docs for conversion errors (and outdated information)

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#603]
After migrating the desktop client docs to AsciiDoc/Antora, it needs a review to check for conversion errors.

Here is an example:
![jpeg image](https://user-images.githubusercontent.com/214010/52911739-6ca29680-32a8-11e9-8946-4329e9d045c5.jpeg)

Old on the left:
https://doc.owncloud.org/desktop/2.5/troubleshooting.html

New on the right:
https://doc.owncloud.org/desktop/troubleshooting.html

@lazawan Could you help review the client docs for conversion errors and outdated information? If you'd like to try fix the errors, check [`getting-started.md`](https://github.com/owncloud/docs/blob/master/docs/getting-started.md). In case you need help, get in touch with @voroyam or @settermjd – they're the experts.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [x] Desktop Client
- [ ] Other

**Comment by tboerger** [comment]
Looks like this is some conflict resolution that went bad

**Comment by michaelstingl** [comment]
> Looks like this is some conflict resolution that went bad

This page is only an example. @lazawan Please review all pages of the client docs.

**Comment by lazawan** [comment]
@michaelstingl will do it :-)

**Comment by michaelstingl** [comment]
@lazawan any updates?

**Comment by lazawan** [comment]
Yep , see please #618

**Comment by michaelstingl** [comment]
Not sure if https://github.com/owncloud/client/pull/7097 solve everything. @settermjd close the overview issue?

**Comment by settermjd** [comment]
Closing, as the required changes have been addressed.
