### ISSUE TITLE
External links generated the wrong way

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#604]
It seems external links are generated the wrong way:

```
https://doc.owncloud.com/server/how_to_contribute.html#https://github.com/
https://doc.owncloud.com/server/how_to_contribute.html#https://docs.antora.org/antora/
https://doc.owncloud.com/server/how_to_contribute.html#https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
https://doc.owncloud.com/server/how_to_contribute.html#https://github.com/owncloud/docs/
https://doc.owncloud.com/server/how_to_contribute.html#https://github.com/owncloud/docs/blob/master/docs/getting-started.md
https://doc.owncloud.com/server/how_to_contribute.html#https://github.com/owncloud/client/blob/master/README.md
https://doc.owncloud.com/server/how_to_contribute.html#https://github.com/owncloud/android/blob/master/README.md
https://doc.owncloud.com/server/how_to_contribute.html#https://github.com/owncloud/ios/blob/master/README.md
```

Found here:
https://doc.owncloud.com/server/how_to_contribute.html

Could sanity checks in the PR's help to prevent this? Linting?

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [x] Other

I didn't check if other parts of the docs are affected too.

**Comment by settermjd** [comment]
@michaelstingl, there are two validation tools in the build pipeline, broken link checker and an Xref validator. However, after running them manually, it appears that they're not going to pick up and errors. 

In the third line in the screenshot below, the extra URL in the link to doc.owncloud.com that exists on https://doc.owncloud.com/server/how_to_contribute.html, github.com, isn't picked up during the execution of [broken link checker](https://github.com/stevenvachon/broken-link-checker). I'll see if there are other options or tools that can be used.

![bildschirmfoto 2019-02-18 um 14 40 13](https://user-images.githubusercontent.com/196801/52954767-443f9880-338b-11e9-956e-59a4bf41be7a.png)

**Comment by settermjd** [comment]
From a scan of the entire documentation (the three core manuals), only that page is affected. I'll create a PR to fix it.

**Comment by settermjd** [comment]
I've asked in the Antora forum about the link generation issue that I found in https://doc.owncloud.com/server/how_to_contribute.html and am waiting to get further feedback.
