### ISSUE TITLE
Fix incorrect minimum stated PHP version in the current docs.

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#606]
Fix incorrect minimum stated PHP version in the current docs. It's 5.6 up to version 10.1, not 7.1. That's required from 11.0.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [X] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by voroyam** [comment]
Please merge this in 10.0 and 10.1 branch

**Comment by voroyam** [comment]
@settermjd

**Comment by settermjd** [comment]
@voroyam, done.
