### ISSUE TITLE
Small Fixes for the Desktop-Client Docs 

### ISSUE THREAD

**Issue by lazawan** [owncloud/docs#618]
## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [x] Desktop Client
- [ ] Other

on the following site there is a missing image : https://doc.owncloud.org/desktop/faq.html

![screenshot from 2019-02-19 14-44-14](https://user-images.githubusercontent.com/44814084/53021301-c40e4700-340d-11e9-8474-5382e54b90e5.png)

on the same site at the bottom there is an important warning or something like that , and I think ,it should be changed 

![screenshot from 2019-02-19 14-46-55](https://user-images.githubusercontent.com/44814084/53021425-08014c00-340e-11e9-921a-d214c3336784.png)

--------------------------------------------------------------------------------------
on the site https://doc.owncloud.org/desktop/architecture.html
there is a little word ,which is missing 

![screenshot from 2019-02-19 15-18-34](https://user-images.githubusercontent.com/44814084/53021632-7a722c00-340e-11e9-98a6-a2da27b8669c.png)

and on the same page under Ignored files there Is wild card signs ,that are missing 

![screenshot from 2019-02-19 15-21-35](https://user-images.githubusercontent.com/44814084/53021905-0e43f800-340f-11e9-9931-b258ba4a1dee.png)

**Comment by lazawan** [comment]
@settermjd i think ,there is another problem  on https://doc.owncloud.org/desktop/troubleshooting.html
sorry i noticed that just now 

![Screenshot from 2019-03-19 14-08-42](https://user-images.githubusercontent.com/44814084/54608549-3b58ea00-4a51-11e9-9583-8aaf09b62e85.png)

there is == before the titles " titles are not shown correctly "

**Comment by settermjd** [comment]
Thanks for spotting this, @lazawan. I'll make an additional change to fix it.

**Comment by settermjd** [comment]
I believe all the required fixes have been implemented.
