### ISSUE TITLE
Add option to always allow group admins to impersonate their group members

### ISSUE THREAD

**Issue by sharidas** [owncloud/docs#622]
## What Needs to be Documented?

The UI for impersonate is slightly modified. The intention behind this modification is to provide an option which would give all group admins the ability to impersonate their respective members. So eventually the admin does have option to:
1. Grant access to all group admins to impersonate their members
2. Grant access to selective group admins to impersonate their members ( which we already had )

The UI would look like this:
1. 
![impersoante_first](https://user-images.githubusercontent.com/3600427/53031451-e302ec80-3492-11e9-801c-1c4e803771d6.png)
2. If the user selects the first option 
![impersonate_second](https://user-images.githubusercontent.com/3600427/53031550-12195e00-3493-11e9-8d6d-d44ebe2a1e46.png)
all group admins in the oC instance would get access to their members.
3. If user selects the second radio button 
![impersonate_third](https://user-images.githubusercontent.com/3600427/53031634-3bd28500-3493-11e9-8710-76757112a478.png)
only selective group admins would have access to their members. This is same old behaviour.

Dev PR related to this task https://github.com/owncloud/impersonate/pull/134

## Why Should This Change Be Made? (Optional)

It helps admins to grant access to all group admins, instead of providing each group admin name individually.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
I've been researching this, but the functionality's incomplete. If I attempt to click the "_impersonate_" icon for a user, but it, unfortunately, doesn't work. I'm using [release 0.5.0RC1](https://github.com/owncloud/impersonate/releases/tag/v0.5.0RC1).

![bildschirmfoto 2019-02-25 um 14 01 32](https://user-images.githubusercontent.com/196801/53339272-2a133680-3906-11e9-9651-01147dd8abc9.png)
