### ISSUE TITLE
Beginners questions and better documentation

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/docs#625]
Hello guys

Got stuck for hours using a S3 bucket as an external storage for my own OwnCloud server I'm running.

For a starter, look at this screenshot:

<img width="1112" alt="screen shot 2019-02-20 at 17 43 35" src="https://user-images.githubusercontent.com/177641/53066992-18f9ac80-3537-11e9-945f-bf82b90254ee.png">

I've no idea what exactly to enter here. I already have an access key and secret key from my S3 account. But what to enter for
- Bucket
- Hostname
- Port

I only have the bucket name and the region, but not the hostname and port. Plus the folder name, what is that exactly? Is that a local folder on my server?

Then when I tried to fill them out with some values I think make sense, (see screenshot), I can see some weird errors in the log file:

<img width="1108" alt="screen shot 2019-02-20 at 17 47 17" src="https://user-images.githubusercontent.com/177641/53067110-a50bd400-3537-11e9-9a9b-0740d67d0acd.png">

The error messages (from the logs) are like
- `Creation of bucket failed. The authorization header is malformed; the region 'es-west-1' is wrong; expecting 'eu-west-1`
- `Creation of bucket failed. Your previous request to create the named bucket succeeded and you already own it`

Huh? Why does it tell me what region to pick when I want to set it? And why can't it reuse the one I already created? Or wait, does your plugin create buckets itself, so that I do not have to create any from the AWS console at all?

You can see, I am confused. Some answers and a beginners documentation would be good. Thanks :)

**Comment by settermjd** [comment]
@binarykitchen, thanks for reporting the issues that you experienced. I'll attempt to have the documentation updated, reasonably quickly, to avoid this happening in future. @PVince81, thanks for moving it to the docs repo.

**Comment by binarykitchen** [comment]
@settermjd thanks ... yeah please, document soon if you can cos I'm already waiting :) Or can you at least give quick answers here for now?

**Comment by PVince81** [comment]
@binarykitchen please note that this is not a support channel and there are currently other priorities.

if you need timely support, please see https://owncloud.org/help/
