### ISSUE TITLE
theme-bootstrap.sh: no usable app path

### ISSUE THREAD

**Issue by thommierother** [owncloud/docs#631]
Scripts from https://doc.owncloud.org/server/10.1/developer_manual/core/theming.html?to=developer-theming

Created theme-bootstrap.sh and read-config.php from page
Executed with "theme-bootstrap.sh oc-theme-nw /var/www/owncloud2"
Result:

```
root@ruru:/var/www/owncloud2# ./theme-bootstrap.sh oc-theme-nw2 /var/www/owncloud2
!/usr/bin/php /var/www/owncloud2/apps
Script read-config.php returned no usable app path
```

Environment: ubuntu 18.04 lts, php 7.2.15-0ubuntu0.18.04.1, OC 10.1.0.4, /var/www/owncloud2/apps is writeable. Tried execution with both root and sudo -u www-data

**Comment by mmattel** [comment]
@thommierother can you run the script `read-config.php` and post the result?
I just tested the script on two different servers with different setups and it returned the correct paths.
FYI, 
Server 1 returned: `/var/www/owncloud/core/apps` (dev machine, 18.04)
Server 2 returned: `/var/www/owncloud/apps-external` (production, 16.04)

**Comment by thommierother** [comment]
@mmattel: argh, stupid error, read-config had encoding problems, now its fine.
