### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/docs#637]
When visiting https://doc.owncloud.org/server some links are broken since it's missing the "server/" in the link address: https://doc.owncloud.org/admin_manual/index.html -> 404

Occured on Admin, dev and user manual for 10.1.0 as well as the link in "If you find errors or omissions in any of the manuals, we welcome your bug reports and contributions in fixing them. Please refer to **the contributing guide** for instructions." adn some other links.

When visiting https://doc.owncloud.org/ everything works fine.
Maybe a routing problem?

**Comment by tboerger** [comment]
Solved...
