### ISSUE TITLE
Example for shibboleth and credentials login 

### ISSUE THREAD

**Issue by tomneedham** [owncloud/docs#638]
## What Needs to be Documented?
Place the example vhost config there

```
<VirtualHost *:80>
  DocumentRoot /var/www/owncloud
  ServerName   https://www.myowncloud.com
  ServerAlias  myowncloud.com

  <Directory "/var/www/owncloud">
      Options       FollowSymlinks MultiViews
      AllowOverride All
      Order         Allow,Deny
      Allow         from All
  </Directory>

  <Location />
      AuthType shibboleth
      ShibRequestSetting requireSession false
      Require shibboleth
  </Location>
    
  # Path for shibboleth
  Alias "/index.php/login-shib" "/var/www/owncloud/index.php/login"
  <Location ~ "/index.php/login-shib">
      AuthType shibboleth
      ShibRequestSetting requireSession 1
      ShibRequestSetting REMOTE_ADDR X-Forwarded-For
      require valid-user
  </Location>

  RewriteEngine On
  RewriteCond %{HTTP_HOST} !myowncloud.com$ [NC]
  RewriteRule ^(.*)$ https://myowncloud.com/$1 [L,R=301]
  
</VirtualHost>
```

And the configure the alternative logins option with a button to point to `/login-shib` which will trigger the shibboleth session, and redirect back to login which will pickup the existing session and continue with authentication. Can be used with multi factor as well. 

## Where Does This Need To Be Documented?
https://doc.owncloud.com/server/admin_manual/enterprise/user_management/user_auth_shibboleth.html#other-login-mechanisms

## Why Should This Change Be Made? (Optional)
Helps configuration of instances

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
@tomneedham, do you want the additional text (below) to be used in this section of the documentation?

> And the configure the alternative logins option with a button to point to /login-shib which will trigger the shibboleth session, and redirect back to login which will pickup the existing session and continue with authentication. Can be used with multi factor as well.
