### ISSUE TITLE
Application Metadata, field description is documented twice

### ISSUE THREAD

**Issue by alfredbuehler** [owncloud/docs#639]
In the Developer Manual, at Application Metadata, the field  
description exists twice. Further on, the contents of the two instances differ.

## What Needs to be Documented?

Summarize the two instances to one, or decide which one is correct, remove the other.

## Why Should This Change Be Made? (Optional)

Because it's wrong and misleading.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [X] Existing Content Simplification
- [X] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [X] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by alfredbuehler** [comment]
UPD: I just saw another duplicate : category.

**Comment by settermjd** [comment]
thanks @alfredbuehler.
