### ISSUE TITLE
Recommend to hold updates to owncloud-files repository package

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/docs#641]
## What Needs to be Documented?
Recommend users/customers who are installing owncloud via repositories, to mark the `owncloud-files` package for hold

Example for ubuntu `apt-mark hold owncloud-files` 
For other supported platforms this should also be mentioned

## Where Does This Need To Be Documented?
Section on installation with packages

## Why Should This Change Be Made? (Optional)
It happened in the past, that users/customers had unintended owncloud upgrades when running upgrades for other packages. This recommendation helps to avoid that a `apt-get update && apt-get upgrade` also sneaks in a ownCloud upgrade

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
### Links

- https://manpages.debian.org/stretch/apt/apt-mark.8.en.html#PREVENT_CHANGES_FOR_A_PACKAGE
