### ISSUE TITLE
[WIP] Add SEO information to each page

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#654]
## What Needs to be Documented?

To ensure that the documentation appears in search results as much as possible, it is strongly encouraged that all pages — especially new pages — make use of [the keywords and description built-in AsciiDoc attributes](https://asciidoctor.org/docs/user-manual/#builtin-attributes).

## Where Does This Need To Be Documented?

This is both a new content addition to existing content, and a standard practice that should be done with every change and new AsciiDoc file.

## Why Should This Change Be Made? (Optional)

To progressively enhance the SEO value of the documentation

## What Type Of Content Change Is This? (Optional)
- [X] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [X] All
**_Or_** 
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
Currently, only the following pages have the `:keywords:` and `:description:` attributes:

- ./modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
- ./modules/admin_manual/pages/configuration/files/encryption/disabling-encryption.adoc
- ./modules/admin_manual/pages/configuration/files/encryption/master-key-encryption.adoc
- ./modules/admin_manual/pages/installation/letsencrypt/apache.adoc
- ./modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
- ./modules/developer_manual/pages/app/fundamentals/logging.adoc

**Comment by guruz** [comment]
See also https://github.com/owncloud/docs/issues/314

**Comment by hurradieweltgehtunter** [comment]
To improve SEO visibility I strongly suggest to have the following meta tags present:
- title
- meta: description
- Open Graph attributes:

<meta property="og:locale" content="">
<meta property="og:type" content="">
<meta property="og:title" content="">
<meta property="og:description" content="">
<meta property="og:url" content="">
<meta property="og:site_name" content="">
<meta property="og:image" content="">
<meta property="og:image:secure_url" content="">
<meta property="og:image:width" content="">
<meta property="og:image:height" content="">
<meta name="twitter:card" content="">
<meta name="twitter:description" content="">
<meta name="twitter:title" content="">
<meta name="twitter:site" content="">
<meta name="twitter:image" content="">
<meta name="twitter:creator" content="">

Those attributes should be page specific. You can make a simple check with the facebook open graph debugger: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fdoc.owncloud.com%2Fserver%2F10.3%2F
