### ISSUE TITLE
Broken /server/latest/ redirects

### ISSUE THREAD

**Issue by lefherz** [owncloud/docs#659]
Hi, I'm aware of #231, and looked if it is already included there. Apparently it isn't, but it's also not documented there at all, so I open a new issue.

## Expected behavior

https://doc.owncloud.org/server/latest/admin_manual/installation/docker/

redirects to

https://doc.owncloud.org/server/10.1/admin_manual/installation/docker/

## Actual behavior

https://doc.owncloud.org/server/latest/admin_manual/installation/docker/

redirects to

https://doc.owncloud.org/server/10.1/server/latest/admin_manual/installation/docker/

## Why Should This Change Be Made? (Optional)

We have many broken links because of this. It would be way easier to fix the redirect than correcting all those links, and we don't have a complete list of the links, so we probably wouldn't even find all of them.

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual

**Comment by tboerger** [comment]
Please check the behavior before raising issues, as mentioned on the chat this had been resolved yesterday.
