### ISSUE TITLE
Document twofactor_totp key validation OCS API

### ISSUE THREAD

**Issue by karakayasemi** [owncloud/docs#674]
## What Needs to be Documented?
https://github.com/owncloud/twofactor_totp/pull/38

## Where Does This Need To Be Documented?
- I guess, under Available API's section in developer manual

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Developer Manual

**Comment by settermjd** [comment]
Hi, @karakayasemi. As part of completing this issue, I've installed the latest version of `twofactor_totp` from the ownCloud Marketplace (v0.6.0) in my development installation of ownCloud, but have been unable to replicate the stated change in functionality, as described in https://github.com/owncloud/twofactor_totp/pull/38.

If "**Activate TOTP**" is checked, the following JSON response is returned:

```json
{
  "ocs": {
    "meta": {
      "status": "failure",
      "statuscode": 997,
      "message": "Unauthorised",
      "totalitems": "",
      "itemsperpage": ""
    },
    "data": []
  }
}
```

However, if "**Activate TOTP**" is _not_ checked, then I receive the following response (which I'd rather expect, to be fair).

```json
{
  "ocs": {
    "meta": {
      "status": "failure",
      "statuscode": 404,
      "message": "OK",
      "totalitems": "",
      "itemsperpage": ""
    },
    "data": {
      "result": false
    }
  }
}
```

**Comment by karakayasemi** [comment]
In your tests, you are activating totp for the admin and trying to use same admin account for api call. Currently, when 2FA is activated on an account, authorization with username-password is not possible via API's. The account should authenticate via App passwords when using API's. It is similar on clients. When 2FA is enabled for an user, the user can only login clients via app password.

So, either you can use app password on api call or you can disable 2FA for the admin and create another user for querying its totp validation.

**Comment by settermjd** [comment]
Thank you for the clarification.
