### ISSUE TITLE
Make corrections based on feedback from Dusan Cirkovic

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#680]
@jnweiger passed on an annotated version of the user manual PDF from Dusan Cirkovic. Based on this, I see that there are a number of areas where it can be improved, so am creating this issue to ensure that the applicable changes are made.

[ownCloud_User_Manual_überarbeitet von Cirkovic Dusan-2.pdf](https://github.com/owncloud/docs/files/2925806/ownCloud_User_Manual_uberarbeitet.von.Cirkovic.Dusan-2.pdf)

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [X] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by voroyam** [comment]
Wow. He looked through 64 pages of this document. Nice work. Most of his suggestions are formatting corrections though.

The question is whether it makes sense to do the work and implement the corrections or rework the whole document. I can do the corrections. For reworking the document we would need input from @michaelstingl and @jnweiger at least. I am not sure if those 2 have the time to make suggestions.

**Comment by michaelstingl** [comment]
> whether it makes sense to do the work and implement the corrections

That's a first step. You could also divide it in smaller subtasks.

> For reworking the document we would need input from @michaelstingl and @jnweiger at least.

We can answer questions of course.
