### ISSUE TITLE
We need a description how to backport in readme.md

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#682]
## What Needs to be Documented?
Description how to backport

## Where Does This Need To Be Documented?

README.md

## Why Should This Change Be Made? (Optional)

Support writers in how to backport a master PR to a particular doc branch

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [x] Other

@settermjd fyi

**Comment by tboerger** [comment]
Wasn't that already part of the docs folder?

**Comment by mmattel** [comment]
https://github.com/owncloud/docs/blob/master/docs/the-branching-workflow.md#how-it-works
only tells that backporting is needed but does not say how it is done.

**Comment by settermjd** [comment]
Fair enough. @mmattel, are you happy to add that content?

**Comment by mmattel** [comment]
Fixed in https://github.com/owncloud/docs/pull/699
Closing
