### ISSUE TITLE
Supported + Minimum Sync Client Versions should be documented

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#69]
A user has brought to my attention that we don't have the client versions documented.

What is the oldest supported version for the current server version?

Desktop Client / Android / iOS

We should also mention that users should check the change log for latest server features:

For example if it's important for the client to use oAuth the client has to be a specific version. (2.3.3)

We should also mention that we support only the latest version in this section that will be written.

I know it's written at the top, but it should also be written here.

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/73

**Comment by settermjd** [comment]
Closing as the implementing PR's been merged and deleted.
