### ISSUE TITLE
How to "ownCloud log file download" missing

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#693]
We need to document ( with pictures ) how to get the ownCloud log file. 

As for now we only have:

https://doc.owncloud.com/server/admin_manual/configuration/server/logging_configuration.html

For new customers  / users we need something to point to that shows how to get the log file.

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
@voroyam, under https://doc.owncloud.com/server/admin_manual/configuration/server/logging_configuration.html#owncloud, is the following:

> By default, a log file named owncloud.log will be created in the directory which has been configured by the datadirectory parameter in config/config.php.

Is that not enough for admins to know where to download the file from? Or was that not what you meant?

**Comment by settermjd** [comment]
@voroyam, pls provide further feedback.

**Comment by voroyam** [comment]
I created a separate page for this to be documented:

https://doc.owncloud.com/server/admin_manual/troubleshooting/providing_logs_and_config_files.html

And regarding your question: No I don't think a long sentence is sufficient. We have always to simplify instructions as good as we can. Reading a long paragraph that includes a dependency is not what the usual admin/user/ is looking for in a manual. He wants a picture with the topic he typed in to the search that instructs him what he should do to get what he wants.

If a customer is writing that he can't find how to get the logs, that usually means that he looked on google and did not find it quick enough or simplified enough. My goal is to make it simply enough for the customers and users to understand and to reduce the load on the support team.

**Comment by voroyam** [comment]
fixed. closing
