### ISSUE TITLE
Antivirus rework

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#74]
https://github.com/owncloud/docs/blob/master/modules/ROOT/pages/configuration/server/antivirus_configuration.adoc

some of the information on this page are wrong.

For example the title of daemon and daemon socket is different, but the screenshot is the same.

Also the section about the rules contains a screenshot that can not be read.

**Comment by voroyam** [comment]
PR fixing the daemon screenshot

https://github.com/owncloud/docs/pull/75

**Comment by settermjd** [comment]
Closing, as [the implementing PR](https://github.com/owncloud/docs/issues/75) has been merged.
