### ISSUE TITLE
files:scan command will now support both --group and --groups options

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs#742]
## What Needs to be Documented?
Sort out the `files:scan --group` and `files:scan --groups` options now that both options will be available.

Ref: 
core PR https://github.com/owncloud/core/pull/31719 modified `files:scan --groups` to be `files:scan --group` - that change was not backward-compatible and so has not been released in `10.*` series.

core PR https://github.com/owncloud/core/pull/34753 now makes both `--group` and `--groups` available. So that existing command usage continues to work, and the change is an additional command option (which is useful if the group name itself contains a comma like `Finance,Sydney`)
That has been back-ported into `core` `stable10` and will be released in the next core release, which is expected to have the number `10.2`

## Where Does This Need To Be Documented?
`0cc_command.adoc`

## Why Should This Change Be Made? (Optional)
Because correct documentation is "a good thing" (tm) ;)

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Closing, doc PR merged to master
