### ISSUE TITLE
Missing examples in developer docs

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#757]
## What Needs to be Documented?
`developer_manual/pages/examples/` contains example files which:
- should be moved to `developer_manual/examples/`
- are currently orphaned. Means present but "nowhere" used.
Example:
`developer_manual/pages/examples/curl/create-share.sh`
Should be included in file `developer_manual/pages/core/ocs-share-api.adoc` line 286
- The example above is important as there are example files in `curl, ruby, php, go` to be added accordingly

## Where Does This Need To Be Documented?
developer docs

## Why Should This Change Be Made? (Optional)
Move and fix missing examples so that they are shown

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

One first step fixing this issue is addressed in: https://github.com/owncloud/docs/pull/756
(the part with cron)

**Comment by mmattel** [comment]
@phil-davis referencing also #758, this is a kind of hen-egg problem.

Should we try to first move/match the existing scripts to the page(es) so we see the content and afterwards fix script errors or the other way round? docs can´t do script validation...

I also propose to do things in multiple PR´s step by step because this is a bigger challenge...
If all script validations/corrections and includes are fixed, we can close this issue but not before.

**Comment by phil-davis** [comment]
@mmattel IMO get whatever code examples can be found, and link them into the appropriate doc.
If there is nowhere to link an example, and it really looks like it is a drifting random bit of code, then delete the file.

When the code is all linked, then someone can review/correct detailed code itself.
