### ISSUE TITLE
Broken external (http) Links in documentation

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#765]
## What Needs to be Documented?
Running: `yarn antora --url http://localhost:5000`
Running: `yarn linkcheck http://localhost:5000 | grep "BROKEN"`
We get a noticable quantity of broken external links like:

http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/
https://support.microsoft.com/de-at/help/841215
https://www.doctrine-project.org/api/dbal/2.9/Doctrine/DBAL/Schema/Schema.htmlClass
...

## Where Does This Need To Be Documented?
On various pages

## Why Should This Change Be Made? (Optional)
Docs quality

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [x] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

Found while working on: https://github.com/owncloud/docs/pull/764

@settermjd

**Comment by settermjd** [comment]
Is this still a problem?

**Comment by mmattel** [comment]
I think I fixed them all but needs a re-check to finally close
