### ISSUE TITLE
Suggestion to use the backporting script

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#767]
This is just a note because of positive responses to use the backporting script located in:
https://doc.owncloud.com/server/developer_manual/general/backporting.html

For those who have a GUI I also can recommend to add the extra two line at the end of the page as it opens the browser and sets the target branch automatically.

This script
- checks that the commit you want to backport is already merged in the source branch and assumes you use the PR merge sha for backporting which makes life easier
- sets the naming for the branch:
`target branch-original merge commit sha-referenced PR`
`10.1-d7f44e1-756`
- sets the naming for the PR headline:
`[target branch] [referenced PR] original PR headline text`
`[10.1] [PR 756] Fix wrong include directives in the developer manual`
- presets the message text to:
`Backport of PR #xyz`
`Backport of PR #756`

Which helps identifying and referencing a backport easily.

In case the script exits because of conflicts, the new PR headline name is echoed before and you can copy paste this name after resolving the conflict manually to stay inline with the naming when you create the PR.

@settermjd @phil-davis

**Comment by voroyam** [comment]
@mmattel @settermjd as far as I can see the changes were implemented since the script does exactly what @mmattel wanted. Right?
