### ISSUE TITLE
ACL support for WND

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/docs#768]
## What Needs to be Documented?

https://github.com/owncloud/windows_network_drive/pull/234

## Why Should This Change Be Made? (Optional)

New content planned for the next WND release. It will require documentation because there are several things to notice about the implementation.

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@settermjd there is some information in the PR, but there could be more information that we might need to add. This should be for the next WND (not sure when). I can provide additional information about the implementation, so feel free to ping me.
Also pinging to @felixboehm and @PVince81 for them to be aware

**Comment by settermjd** [comment]
Closing, as the implementing PR has been merged.
