### ISSUE TITLE
Android 2.10.0

### ISSUE THREAD

**Issue by jesmrec** [owncloud/docs#771]
## What Needs to be Documented?

Version 2.10 Android app new features

## Where Does This Need To Be Documented?

official documentation of the platform

## Why Should This Change Be Made? (Optional)

keep docu upgraded

## What Type Of Content Change Is This? (Optional)
- [X] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [x] User Manual
- [X] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by jesmrec** [comment]
I will write here the changes and detail the content

**Comment by tboerger** [comment]
But the android docs are part of the Android repository?

**Comment by jesmrec** [comment]
i talked with @PVince81 to post here the new features' documentation. For me it is not a problem to write here or in a different place, wherever you feel more comfortable. But let me know your preferences.

**Comment by jesmrec** [comment]
I will detail the features to include in the documentation. Fixes and other support issues in the changelog are not stuff to handle in manuals/docs. I have selected the following two to be included in the user manual https://doc.owncloud.com/android/. If you miss something, any question, anything needed, please ping us to fix. 

### 1. Allow light filtering apps 

#### Description:

By enabling the option, app will not be obscured by light filtering apps, giving the choice of using them together. At the time it is enabled, security warning is enabled. It is optional to enable.


#### Screenshot to illustrate:

![07faa839ecb178e56b202f703b5cbb1cc4cb1712](https://user-images.githubusercontent.com/14894746/54536616-4e0bea00-4991-11e9-82cd-9dd33dc01370.png)

#### Where to include it:

as part of the settings options: https://doc.owncloud.com/android/#application-settings

_________

### 2. Select all and inverse in Uploads view

#### Description:

You can select the whole list of files in any folder of your device to be upload to ownCloud. The option "Select all" will allow you to do it. The option "Select inverse" will select automatically all the unselected items and viceversa

#### Screenshot to illustrate:

![8bd6635f352f4daec03bcccb412256fa605ffb67](https://user-images.githubusercontent.com/14894746/54536682-7267c680-4991-11e9-8603-69baacf7f256.png)


#### Where to include it: 

In section "Create new content": https://doc.owncloud.com/android/#creating-new-content,  where uploads are mentioned

______

On the other side, i noticed that the section "Release notes" is outdated: https://doc.owncloud.com/android/release_notes.html

Sections to add:

#### Changes in 2.10:

Additions: 

- Android 9 (P) support 
- Allow light filtering apps 
- Show additional info (user ID, email) when sharing with users with same display name
- Support more options to enforce password when sharing publicly
- Select all and inverse when uploading files
- Sorting options in sharing view
- Batched notifications for file deletions
- Commit hash in settings
- UI improvements, including: disable log in button when credentials are empty, warning to properly set camera folder in camera uploads

Fixes: 

- Some camera upload issues in Android 9 (P) 
- Fix eye icon not visible to show/hide password in public shares
- Fix welcome wizard rotation


#### Changes in 2.9:

Additions:

- Switch apache and jackrabbit deprecated network libraries to more modern and active library, OkHttp + Dav4Android
- Search in current folder
- Select all/inverse files
- Improve available offline files synchronization and conflict resolution (Android 5 or higher required)
- Sort files in file picker when uploading (contribution)
- Access ownCloud files from files apps, even with files not downloaded
- New login view
- Show re-shares

Fixes: 

Fix some crashes: when rebooting the device, when copying, moving files or choosing a folder within camera uploads feature, when creating private/public link.
Fix some failing downloads
Fix pattern lock being asked very often after disabling fingerprint lock

**Comment by jesmrec** [comment]
i have assigned @settermjd by default, but feel free to change the asignee if someone else wants/can take care. 

Thanks.

**Comment by PVince81** [comment]
@settermjd please have a quick look to see if this is enough information. I'll schedule this in the next sprint if workload permits.

**Comment by PVince81** [comment]
@settermjd if this is too much for a sprint feel free to itemize (checkboxes) or raise individual parts as separate ticket for further planning

**Comment by settermjd** [comment]
@PVince81, getting this done today.
