### ISSUE TITLE
Redirect .com version of v9.1 of the developer docs to .org

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#775]
I just noticed that all the links in [version 9.1 of the .com version of the developer manual](https://doc.owncloud.com/server/9.1/developer_manual/) 404. However, the .org version works just fine. Please redirect the .com version of v9.1 of the developer docs to .org.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [X] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [X] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by PVince81** [comment]
@tboerger FYI.

**Comment by tboerger** [comment]
I'm downloading the old Docker image and I will check if the files are present, if they are I will copy them to the current deployment.

**Comment by tboerger** [comment]
The content is available again.
