### ISSUE TITLE
Blank Section in Help & Communication Section of Version 9.0 of the Developer Docs

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#776]
There is a blank Section in the [Help & Communication Section](https://doc.owncloud.com/server/9.0/developer_manual/commun/) of version 9.0 of the Developer Manual that needs to be either filled in or removed.

![Bildschirmfoto 2019-03-19 um 11 16 51](https://user-images.githubusercontent.com/196801/54598450-d396a500-4a38-11e9-9e32-108936cb8b64.png)

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [X] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [X] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by tboerger** [comment]
IMHO we should not touch the old docs anymore.

**Comment by settermjd** [comment]
Fair call.
