### ISSUE TITLE
Config report webUI =/= CLI

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#777]
Currently we state that the config report is the same if you generate it over CLI or webUI

But this is currently not true, that's why we recommend the webUI.

This should be clearly stated in the documentation section, with a picture where to find the download button.

https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command.html#config-reports

Also I noticed the anchor for the config report is not working:

https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command.html#config-reports-commands

maybe because the anchor is `config-reports` and the article is `config-reports-commands`.

this should be fixed.

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/778

**Comment by mmattel** [comment]
Closing, #778 is merged and backported
