### ISSUE TITLE
yarn validate does not output broken xref links to page section titles

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#786]
## What Needs to be Documented?
No broken xref´s returned even there are some
```
yarn validate
yarn run v1.15.2
$ antora --stacktrace generate --cache-dir cache --redirect-facility disabled --generator ./generator/xref-validator.js --clean site.yml
Done in 163.24s.
```
## Where Does This Need To Be Documented?
Needs checking in the repro code

## Why Should This Change Be Made? (Optional)
Doc quality

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [x] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@settermjd @tboerger

**Comment by tboerger** [comment]
Why should it print broken links when there aren't broken links?

**Comment by mmattel** [comment]
Order !
- master got a merge today which fixed a broken xref - so this should not return a result
- while 10.0 / 10.1 do not have that merge and should return a broken xref

see merged PR #778 and open pr #784/#785

I also tried before the merge and did not got a result...

**Comment by tboerger** [comment]
Last build with validation errors had been https://drone.owncloud.com/owncloud/docs/1739/5 which seems to be totally fine. So I don't get your point where you are questioning the processes again.

**Comment by mmattel** [comment]
hmmm,
**First Try**
- created a branch based on an pulled/rebased master and checked it out
- changed nav.adoc in modules/admin_manual from
xref:installation/system_requirements.adoc[System Requirements]
to
xref:hinstallation/system_requirements.adoc[System Requirements]
- run yarn validate
- **xref error shown**

**Second Try**
- setback the change from above
- changed in occ-command.adoc  in modules/admin_manual/pages/configuration/server
xref:config-reports[Config Reporting Commands]
to
xref:config-reports-commands[Config Reporting Commands]
- run yarn validate
- **xref error NOT shown**

**Result**
xref to .adoc files are reported
xref to in-page links not (but should)

**Comment by tboerger** [comment]
I'm not sure if `xref:config-reports-commands[Config Reporting Commands]` would work at all.

**Comment by tboerger** [comment]
IMHO that should anyway not work, otherwise the validator won't check for links including adoc only: https://github.com/owncloud/docs/blob/master/generator/xref-validator.js#L22

**Comment by settermjd** [comment]
afaik, the example in https://github.com/owncloud/docs/issues/786#issuecomment-474755431 does work, as it looks for an anchor of that name in the current document, and creates a link to it, if it exists.
