### ISSUE TITLE
Antivirus - missing occ command background true/false

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#79]
missing occ command

The occ command is not yet in the documentation. As soon as it is, it should be documented here.

The command is question sets a value for the antivirus background job.

@cdamken for more info

**Comment by settermjd** [comment]
Do you mean that an existing occ command for working with an Antivirus tool is missing, @voroyam?

**Comment by voroyam** [comment]
As far as I understand there is occ command or it's planned to create one.

Then, when it's available, it should be documented.

**Comment by VicDeo** [comment]
Why invent the wheel here?
https://doc.owncloud.org/server/10.0/admin_manual/configuration/server/occ_command.html#config-commands-label
```
config:app:set         Set an app config value
```
can be used for any app/any value

**Comment by settermjd** [comment]
Does @VicDeo's [comment](https://github.com/owncloud/docs/issues/79#issuecomment-420693155) answer your question, @voroyam?

**Comment by voroyam** [comment]
not really, because it's still not clear what value is to be set to configure the background anti virus check.

**Comment by voroyam** [comment]
This can be closed imho, I don't know the command, don't know what to document.

Issue can be re-opened if we have further info.

**Comment by mmattel** [comment]
@voroyam FYI
for apps not part of core like ldap or brute force protection, use the occ_apps_command.adoc file.
In particular when it comes to antivirus you can look at the brute force protection.
The only thing to be identified are the strings and their defaults which must be taken out of the code.

**Comment by VicDeo** [comment]
According to https://github.com/owncloud/files_antivirus/pull/213/files#diff-0bd1ff9f0e0e556dfda091330bf237dfR53
options is called `av_scan_background`

**Comment by mmattel** [comment]
Did a small research on the file above.

Following are the existing keys with their default values:
```
'av_mode' => 'executable',
'av_socket' => '/var/run/clamav/clamd.ctl',
'av_host' => '',
'av_port' => '',
'av_cmd_options' => '',
'av_path' => '/usr/bin/clamscan',
'av_max_file_size' => -1,
'av_stream_max_length' => '26214400',
'av_infected_action' => 'only_log',
'av_scan_background' => 'true',
```

Following are the existing keys with their possibe values, type and  text:
```
'av_mode' => 'executable', 'daemon', 'socket' (string)
'av_socket' => '/var/run/clamav/clamd.ctl', (string)
'av_host' => '', (string, 'Hostname or IP address of Antivirus Host')
'av_port' => '', (number, 'Port number of Antivirus Host, 1-65535')
'av_cmd_options' => '', (string, 'Extra command line options (comma-separated)')
'av_path' => '/usr/bin/clamscan', (string, 'Path to clamscan executable')
'av_max_file_size' => -1, (number, 'File size limit, -1 means no limit')
'av_stream_max_length' => '26214400', (string, 'Max Stream Length')
'av_infected_action' => 'only_log', 'delete' (string)
'av_scan_background' => 'true', (???)
```

@VicDeo FYI, ``'av_scan_background'`` has no mentioning in the code except in ``private $defaults``. Seems to be a dead code element?

**Comment by VicDeo** [comment]
@mmattel https://github.com/owncloud/files_antivirus/blob/master/lib/BackgroundScanner.php#L91

**Comment by mmattel** [comment]
@VicDeo Is this intended that ``'av_scan_background'`` has no possibility to be changed by the user like the oder parameters ? If this is the case, then this somehow wired if you can´t change on th UI but on the command line...

**Comment by VicDeo** [comment]
it's generic:
```
> php occ config:app:set --help
Usage:
  config:app:set [options] [--] <app> <name>

Arguments:
  app                    Name of the app.
  name                   Name of the config to set.

Options:
      --output[=OUTPUT]  The output format to use (plain, json or json_pretty, default is plain). [default: "plain"]
      --value=VALUE      The new value of the config.
      --update-only      Only updates the value, if it has not already been set, it will not be added.
  -h, --help             Display this help message
  -q, --quiet            Do not output any message
  -V, --version          Display this application version
      --ansi             Force ANSI output
      --no-ansi          Disable ANSI output
  -n, --no-interaction   Do not ask any interactive question
      --no-warnings      Skip global warnings, show command output only
  -v|vv|vvv, --verbose   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Set an app config value.
```

`php occ config:app:set files_antivirus av_scan_background --value 'false'`

**Comment by VicDeo** [comment]
it doesn't matter what app/config option needs to be changed, the command always will be `occ config:app:set`

**Comment by mmattel** [comment]
Regarding the "missing?" UI interface of ``av_scan_background``, I created a issue in files_antivirus: 
https://github.com/owncloud/files_antivirus/issues/262

**Comment by voroyam** [comment]
> it doesn't matter what app/config option needs to be changed, the command always will be `occ config:app:set`

Yes, but the fact that there is an configurable option needs to be documented, would you not agree?

**Comment by mmattel** [comment]
Just to mention and for a better understanding. We already started to document apps which are maintained by oC but not part of core with their possible commands in a separate occ_apps file. As an example, the brute-force-protection app has no pure occ command but values which can be changed by occ via config:app. This documentation is a necessary step and improves documentation quality massive.

**Comment by settermjd** [comment]
Thanks for all the input, everyone!
