### ISSUE TITLE
Share renaming process documentation

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#798]
Currently we have

https://doc.owncloud.com/server/admin_manual/configuration/files/file_sharing_configuration.html

https://doc.owncloud.com/server/user_manual/files/webgui/sharing.html

But neither of these documents explain how the renaming of shares works.

Right now, both the one who shares and the recipient of the share can edit the name of the share.

I.e. I share folder "from_me_to_carlos" to carlos. He renames it to "from_dmitry_to_me"
I still see the share called "from_me_to_carlos", carlos sees "from_dmitry_to_me".

these needs to be documented so our users know that this is intended and not a bug.

**Comment by settermjd** [comment]
Well said. I remember raising this in the engineering channel some time ago after feeling that it was a bug as well.
