### ISSUE TITLE
Document translation sync process for app developers

### ISSUE THREAD

**Issue by tboerger** [owncloud/docs#80]
Currently we have not documented the process for app developers how to automatically sync translations with Transifex.

1) Create a initial Transifex config within the app repository:
    
```
[main]
host = https://www.transifex.com
lang_map = ja_JP: ja

[owncloud.APP_NAME]
file_filter = <lang>/APP_NAME.po
source_file = templates/APP_NAME.pot
source_lang = en
type = PO
```

2) Give write permissions to the [ownclouders](https://github.com/ownclouders) user, within the ownCloud GitHub organization just add the @owncloud/ci team with admin permissions.

3) Create a pull request at https://github.com/owncloud/translation-sync/blob/master/.drone.yml, just add another list item to the matrix at the bottom (the apps are sorted alphabetically)

4) After merging the pull request the translations will initially already synced, afterwards it will happen every night.

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/83

**Comment by voroyam** [comment]
PR is merged, closing
