### ISSUE TITLE
Can't link to category root

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#800]
Some navigation items items don't have real links.

<img width="1028" alt="What_is_the_Appliance_____ownCloud_Documentation" src="https://user-images.githubusercontent.com/214010/54770176-04c2d100-4c03-11e9-94c6-367e7058f374.png">

It would be important to link to the category root. Here is an example:
https://owncloud.com/download/

Idea is to link to the Appliance section, not to the first sub-section.

BTW: The old link is broken:
https://doc.owncloud.com/server/10.1/admin_manual/appliance/

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [x] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [x] Branded Clients
- [x] Desktop Client
- [ ] Other

/cc @haukman @MichaelvanLaar

**Comment by tboerger** [comment]
That's because there is no index.html/adoc

**Comment by settermjd** [comment]
Thanks for pointing this out, @michaelstingl.

**Comment by michaelstingl** [comment]
@settermjd Why did you close this issue. Only 1 menu entry got fixed.

**Comment by settermjd** [comment]
Sorry @michaelstingl, I thought that the points were fixed in related PRs.

**Comment by settermjd** [comment]
Do you want all category roots linked to a page, @michaelstingl?

**Comment by michaelstingl** [comment]
Yeah, all items in the left navigation would be useful to get as link, so support, presales or marketing can use it to help users.

**Comment by michaelstingl** [comment]
Looks like Developer Docs are affected too:
https://doc.owncloud.com/server/10.1/developer_manual/

<img width="1438" alt="ownCloud_Developer_Documentation____ownCloud_Documentation" src="https://user-images.githubusercontent.com/214010/58346052-2e45e600-7e5a-11e9-9904-5fdf0b7ca762.png">

<img width="847" alt="Graylog_-_Dashboard_Docs_errors" src="https://user-images.githubusercontent.com/214010/58346093-4ddd0e80-7e5a-11e9-84ce-05d4121a8615.png">

Related: #1135
