### ISSUE TITLE
Server Migration Documentation Fix

### ISSUE THREAD

**Issue by pclemins** [owncloud/docs#803]
## What Needs to be Documented?
In the server migration documentation, coping of the apps directory needs to be included in the following rsync command:

rsync -Aavxt apps config data root@new_server_address:/var/www/owncloud

If the apps directory isn't copied, the new ownCloud instance will think it needs to be updated.

## Where Does This Need To Be Documented?
https://doc.owncloud.com/server/admin_manual/maintenance/migrating.html

## Why Should This Change Be Made? (Optional)
If the apps directory isn't copied, the new ownCloud instance will think it needs to be updated.

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [X] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [X] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
@pclemins seems that you have found something that needs improvement, but it is very hard from the info you provide to get what it is.

**Comment by pclemins** [comment]
Sorry... I'm lame.  I put my text inside the comment blocks in the markdown template when I first posted.  I fixed it... see above!  I now know that <! -> = markdown comment!

**Comment by mmattel** [comment]
We need to add some descriptive text based on your comment plus there is not only `apps` but also the a secondary apps directory like `apps-external`, if it exists.

**Comment by pclemins** [comment]
Great... Thanks!

**Comment by settermjd** [comment]
Closing, as it's been implemented. Thanks, @pclemins.

**Comment by pclemins** [comment]
Happy to contribute... if even just a little :)
