### ISSUE TITLE
local storage page is not working

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#815]
https://doc.owncloud.com/server/undefined/server/10.0/admin_manual/configuration/files/external_storage/local.html

seems not to work

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Which one of the document in: https://doc.owncloud.com/server/10.0/admin_manual/configuration/files/external_storage_configuration.html you cant access?
![image](https://user-images.githubusercontent.com/3321281/54921637-8ae25e80-4f06-11e9-90f4-6ad07f113acc.png)

**Comment by voroyam** [comment]
the documents are there, the search is pointing to an undefined branch / version

**Comment by mmattel** [comment]
your issue content is less than basic, no reader can know what your problem is...?

**Comment by voroyam** [comment]
I just told you my issue

**Comment by mmattel** [comment]
Close that issue and write one with a complete set if information, else this cant work. Thanks
