### ISSUE TITLE
Doc Search is poiting to an "undefined" server version/branch

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#816]
If you type in to search on the doc.owncloud.com site, your match is directed to a "undefined" place, which causes a 404

-------------------------

example:

https://doc.owncloud.com/server/undefined/server/10.0/admin_manual/configuration/files/external_storage/local.html

leads to a 404.

---------------------------

**Comment by mmattel** [comment]
Can you add what you have serched for? We might identify better what causes this with this information

**Comment by voroyam** [comment]
"Local storage"

**Comment by voroyam** [comment]
every search is pointing to undefined

**Comment by felixboehm** [comment]
reproducible. Inspector shows that Backend returns undefined in key"url":

![docs search](https://user-images.githubusercontent.com/1204907/54934831-7494cc80-4f1f-11e9-85ab-837b9b95658c.png)

**Comment by tboerger** [comment]
Somebody pushed https://github.com/owncloud/docs/commit/f415bbf4d46422b51ce6264ee20f31c1c93f1653 directly without a pr, that's why I haven't seen that. This pr got to be reverted as the search index can only be updated from the master branch. Somebody got to create a revert pr for this specific commit.

**Comment by voroyam** [comment]
Somebody? :)

**Comment by tboerger** [comment]
Yeah, not me... I have committed it to the master branch only, not any other branch.

**Comment by voroyam** [comment]
Wasn't hinting that I thought it was you. I thought on GitHub everything was traceable and blameable :)

**Comment by voroyam** [comment]
![grafik](https://user-images.githubusercontent.com/24212810/54937198-3e0d8080-4f24-11e9-8c43-b83c99ca55e1.png)

**Comment by voroyam** [comment]
so basically we need to make this PR but on another branch? @tboerger 

https://github.com/owncloud/docs/commit/340e1e9687def56a895a0a9ad1896576135170fc

**Comment by tboerger** [comment]
Solved via #821, search will work after next master build which will be done by https://drone.owncloud.com/owncloud/docs/1864
