### ISSUE TITLE
Logging recommendation ( x-request-id )

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/docs#817]
Building on-top of https://github.com/owncloud/docs/issues/358 - ownCloud also allows a `x-request-id` to be used (ref: https://github.com/owncloud/core/blob/stable10/lib/private/AppFramework/Http/Request.php#L481-L490 )

This would also allow to trace a request from a LoadBalancer up to the application server that received the final request. This is still helpful if client's (like the webui do not deliver a x-request-id yet - the loadbalancer could provide one by itself )

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
Other than sending `x-request-id` (such as with Postman), does this functionality need anything specific to be installed or configured? And, will the id be logged in the web server logs, or the ownCloud log file?

**Comment by patrickjahns** [comment]
`x-request-id` is currently already used by ownClouds Desktop client and is sent with every request.


ownCloud itself will log `x-request-id` in the owncloud log file with every request, if that head is present ( otherwise it will generate a random id itself ).
However, for any other component involved, the logging needs to be adjusted to also write out the content of the header. 

Possible components that need adjustment
- apache ( access // error ) log 
- any loadbalancer inbetween ( i.e. nginx, traefik, BigIP )

It is especially useful to have the request id with every "hop" involved until the request finally arrives at ownCloud ( php process). This way it is possible to track ("trace") requests through "larger" environments.

Example for apache:

```
CustomLog /var/log/apache2/access.log "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" \"%{X-Request-ID}i\""
```
( it is debatable if the `X-Request-ID` should be at the end or the beginng 🤷‍♂ - however it is there and one can check if the request arrived at apache before it was handed to owncloud )

**Comment by settermjd** [comment]
Thanks for such detailed feedback!

**Comment by michaelstingl** [comment]
> `x-request-id` is currently already used by ownClouds Desktop client and is sent with every request.

Not only ownCloud desktop sync client (https://github.com/owncloud/client/issues/5647#issuecomment-298224016), also ownCloud Android app (https://github.com/owncloud/android/issues/2055), new ownCloud iOS app (https://github.com/owncloud/ios-sdk/issues/1) and the new ownCloud web UI "Phoenix" (https://github.com/owncloud/owncloud-sdk/issues/140) support this…
