### ISSUE TITLE
How To Build Docs locally is confusing

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#818]
This document:

https://github.com/owncloud/docs/blob/master/docs/build-the-docs.md

![grafik](https://user-images.githubusercontent.com/24212810/54928887-f7645a00-4f14-11e9-8177-ec272dae1dcd.png)

I want to build an documentation server locally to see if it's possible following our documentation.

I stumble over the first things. My questions:

-  how do I install yarn? 
The wording is very confusing 

> Before you can build the documentation, you need to install the required dependencies. To install them, you need to run yarn install. This will install all the dependencies specified in package.json.

- What is in package.json? Where is this file?
- "To install them, you need to run yarn install." So if I copy paste "yarn install" I will have all the dependencies?

What is GNU? This is a documentation, why are we using abbreviations? This should be a place where you get stuff explained and not the place  were certain knowledge is expected and if you don't have it - go away.

- "you can run make setup instead." Okay, so if I type "run make" then all my dependencies will be installed?

**Comment by settermjd** [comment]
Thanks for creating the issue. I'll see about getting this implemented.

**Comment by mmattel** [comment]
For installing yarn we can reuse: https://github.com/owncloud/docs-ui#yarn
