### ISSUE TITLE
Update on config samples for nginx needed to be inline with core

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#82]
Referencing core: https://github.com/owncloud/core/pull/31858/ ([stable10] Handle SSL certificate verifications for others than Let's Encrypt)

https://github.com/owncloud/docs/blob/master/modules/ROOT/examples/installation/nginx/default-configuration.conf#L13
and
https://github.com/owncloud/docs/blob/master/modules/ROOT/examples/installation/nginx/subdirectory-configuration.conf#L13

``location /.well-known/acme-challenge/ {`` --> ``location /.well-known/(acme-challenge|pki-validation)/ {``

**Comment by settermjd** [comment]
Closing, as [the implementing PR](https://github.com/owncloud/docs/pull/89) has been merged
