### ISSUE TITLE
Document recommended upgrade path

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#827]
recently I have seen a lot of questions on how to upgrade from an old ownCloud, like 8.1 or 9.0 to the current release.

In the docs I have found 2 things that kinda contradict each other:

https://doc.owncloud.com/server/admin_manual/maintenance/upgrade.html

In the general document we tell that:

> Skipping major releases is not supported. However you can migrate from 9.0.9 straight to 10.0.

Why some one used "migrate" instead of upgrade is questionable to me. But okay. If we look at the second page I found:

https://doc.owncloud.com/server/admin_manual/maintenance/package_upgrade.html#upgrading-across-skipped-releases

There is the recommended upgrade path I know and want to document, but why is it hidden in the packages document?

I think we should validate that document and copy/move it to the general upgrade document with a reference to the manual upgrade document because most people will search for it there.

@PVince81 @settermjd @mmattel 

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
Thanks for creating this. As it's a very worthwhile topic to have right, @PVince81, can we get this into a sprint?

**Comment by JKawohl** [comment]
This addressed, and hopefully to your satisfaction.
