### ISSUE TITLE
add to theming guide that the config.php way of theming is deprecated

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#838]
add to theming guide that the config.php way of theming is deprecated

We need to add to the theming guide a mention that the old way of theming is deprecated for our users and customer to know.

This was the old way:  `'theme' => '',` but now we use apps as themes.

https://doc.owncloud.com/server/developer_manual/core/theming.html

https://github.com/owncloud/docs/edit/master/modules/developer_manual/pages/core/theming.adoc

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
I just had a quick review and found the following, just below the preamble:

> Before ownCloud 10, theming was done via the config.php entry 'theme' ⇒ ''. This is deprecated in ownCloud 10. Users who have this entry in their config.php should remove it and use a theme app to customize their ownCloud instance instead.

Is this sufficient?

**Comment by voroyam** [comment]
Yes. I think it was my PR that added this to the docs.

This is my process, always make an issue so that I don't forget it, then make PR. Sometimes I forget to link the PR in the issue or to close the issue after PR merge.

Thanks for noticing.
