### ISSUE TITLE
Need a page with instructions of collecting logs and configs

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#841]
We need a page in the admin manual instructing users and customers how they can provide important log files and config files. Those files could help experienced users/support engineers to find the cause of the issue and providing a solution.

I would propose a new page, in the root folder of the admin manual named "Troubleshooting". Since if a user/customer is looking for a way to collect logs/configs he has already a problem.

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/845

**Comment by settermjd** [comment]
Closing, as it's been implemented.
