### ISSUE TITLE
activity docs page is insufficient

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#844]
https://doc.owncloud.com/server/10.0/admin_manual/configuration/server/activity_configuration.html

This page has broken links and no information how to configure the activity app.

**Comment by settermjd** [comment]
One small thing; there are no links on that page.

**Comment by voroyam** [comment]
> Furthermore it is recommended to configure the background job Webcron or Cron as described in **background_jobs_configuration**.
> 
> There is also a configuration option activity_expire_days available in your config.php (See **config_sample_php_parameters**) which allows you to clean-up older activities from the database.

I think the bold ones should be links inside the docs, shouldn't they? That's what I meant with links :)

**Comment by settermjd** [comment]
Thanks!

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1474

**Comment by voroyam** [comment]
merged, backported
