### ISSUE TITLE
Document occ incoming-shares:poll for update detection with federated shares

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#856]
## What Needs to be Documented?
With core https://github.com/owncloud/core/pull/34903 (Add a command to poll incoming federated shares for updates)
a new occ command needs to be documented: `incoming-shares:poll`

## Where Does This Need To Be Documented?
admin_manual, occ command set

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@PVince81 Pls let us know if it is correct to have this for 10.2 + no backporting to older releases
@VicDeo @jvillafanez FYI
@settermjd

**Comment by PVince81** [comment]
@VicDeo can you provide a quick summary that could be incorporated into the documentation ?

If there is a section about federated shares, it could be linked back to the section for this command for improving update detection and syncing.

**Comment by VicDeo** [comment]
summary: due to performance reasons federated shares are not updated automatically.
The particular directory of the federated share is updated only when user browse into it via web UI. 

 CLI command `occ incoming-shares:poll` could be added into the system crontab in order to poll federated shares for updates automatically.

**Comment by mmattel** [comment]
Just for the record, this command polls all fed shares recieved, there is no path necessary to provide.

**Comment by pmaier1** [comment]
What is the recommended interval for running the background job? @VicDeo @micbar

**Comment by pmaier1** [comment]
Does the command provide any options?

**Comment by micbar** [comment]
@pmaier1 The first question is currently discussed in our testing.

This command does not provide any options.

**Comment by VicDeo** [comment]
> What is the recommended interval for running the background job?

The recommended is `never`. :)
Since it iterates through all federated shares in one go the interval depends on the federated shares amount.
Once per 12 hours should be safe enough for any instance. It could be reduced to once per 2 hrs for instances with low federated shares amount.

**Comment by pmaier1** [comment]
Can we add some more information like I tried in the release notes (starting here https://github.com/owncloud/docs/pull/967/files#diff-ba12788edde90b189cd9bb4d1b5492afR90)? I think that makes it more clear for admins how to handle the interval for the background job.

**Comment by settermjd** [comment]
Closing, as the implementing PR, #1134, has been merged.
