### ISSUE TITLE
Add to the "Retrieve Log Files and Configuration Settings"

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#859]
Here we should collect things the support team needs to be on this document.

@pako81 mentioned that in the case of the ownCloud log file being to large, the user could get a timeout error. That's why we need to document the default location of the ownClould log file.
`/data/owncloud.log`

@micbar mentioned that on clustered setups the ownCloud logs and the web server logs have to be collected from every server.

**Comment by mmattel** [comment]
Reading the new document we just merged, it might be of help creating a (php or bash) script which would call all the necessary sub commands and generates the files needed for support. These files could then also be automatically zipped to further reduce work and size. We already have good experiences with bigger scripts like the permission script for installation and updates or the backporting script.

**Comment by mmattel** [comment]
For all the contributors, following proposal:
1) Let´s `identify` all things which are necessary for support to be known, independent if we have it already in an other page or not (reference in case).
A list is fine
2) Let´s `define` how this `output` should look like.
Single files, zipped file whatever.
Which content needs possible reduction (or enhancement).
Again just writing things down
3) Let´s create `procedures` how to get to this information.
Single commands, scripts ect.
Write down which info is gathered by which way.
Do we want to create a script for ease of handling ect.
4) Let´s `document` all the info above
Do the work of creating the text framework plus writing scripts, whatever is neccessary

**Comment by cdamken** [comment]
You have to explain that the log file will be by default in the data directory,  the user has to check their `config.php` file:
as example:
```
  'datadirectory' => '/mnt/owncloud/data',
```

it's also possible to change the location of the file in the `config.php`:
```
  'logfile' => '/home/www-data/owncloud.log',
``` 
The apache user has to have rights to write in that folder 

That information is also described in the `config.samlple.php`

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1473

**Comment by voroyam** [comment]
merged, backported
