### ISSUE TITLE
Provide location of ransomware file extension blacklist in docs

### ISSUE THREAD

**Issue by va1entin** [owncloud/docs#86]
According to the [docs](https://doc.owncloud.org/server/10.0/admin_manual/enterprise/ransomware-protection/) the file extension blacklist used by the ransomware protection app **should** be reviewed and updated by the user, because there's no sync/update mechanism for the list so far.
However, the location of that file is nowhere to be found. I tried to find it in the official Docker container but failed.

It would be nice to know at least the default location or even name of that file to be able to review and make changes to it.

**Comment by voroyam** [comment]
is this what you were looking for?

blacklist.txt.dist

inside of the app folder?

**Comment by va1entin** [comment]
I looked for it in the apps folder but I don't even have a ransomware* folder there after the app is installed. find apps/ -name blacklist.txt* doesn't show anything either

**Comment by patrickjahns** [comment]
@va1entin 
As you are talking of the docker containers, you need to evaluate the path where ownCloud has installed the app. This is in the container usually at `/mnt/data/apps`

**Comment by va1entin** [comment]
@patrickjahns  Thanks for the hint! The file is located at the following path in my case: `/var/lib/univention-appcenter/apps/owncloud/data/custom/ransomware_protection/blacklist.txt.dist`
Since the path varies I'd already be happy if the filename was added to the docs. Maybe with the path in Debian, Red Hat, UCS, the standard container... whatever you find most important.
With the filename users can do a `find /` or `locate`

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/87

**Comment by settermjd** [comment]
Closing, as [the implementing PR](https://github.com/owncloud/docs/pull/87) has been merged.
