### ISSUE TITLE
Remove deprecated Shibboleth Sync example

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/docs#875]
Short digest - the option for shibboleth sync here is no longer valid with ownCloud 10
https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command.html#shibboleth

Quoting @DeepDiver1975 

```
maybe I'm years behind - but in autoprovision mode shibboleth is storing users in it's own table

oc_shibboleth-users or something
and on sync these users are read from the table and put to the accounts table
let me have a look at the code 😉
ah - no - this table only did exist before the accounts table
the process above was only used on migration
https://github.com/owncloud/user_shibboleth/blob/33c01404aaf4e7dce595bd8677c348280b161d4e/appinfo/Migrations/Version20170410135807.php#L30
so - there is no user sync with shib - you cannot ask an IdP for a list of user
```

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
@patrickjahns, so removing the Shibboleth sub-section there is all that's required?

**Comment by settermjd** [comment]
Appears to have been implemented.

**Comment by davitol** [comment]
I have seen that the example are still alive in the documentation

**Comment by settermjd** [comment]
What references have you found, @davitol?

**Comment by davitol** [comment]
@settermjd https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command.html#shibboleth



`sudo -u www-data php occ user:sync "OCA\User_Shibboleth\UserBackend"`

**Comment by settermjd** [comment]
I'll get it removed.
