### ISSUE TITLE
DB conversion errors

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#879]
If you run occ `db:convert-mysql-charset` you get redirected to this site for help:

https://doc.owncloud.org/server/10.1/go.php?to=admin-db-conversion

But this site has no info what so ever about this command.

The right site would be this

https://doc.owncloud.com/server/admin_manual/configuration/database/linux_database_configuration.html

which is named Linux Database configuration, but in the listing it's just "database configuration" ... why?

Also this is wrong:

If you are setting up a new ownCloud installation, using version 10.0 or above, and you’re using a minimum MySQL version of 5.7, then you don’t need to do anything, as support is checked during setup and used if available.

You still need to do the steps in this document as 4-byte Unicode Support is not enabled by default.

**Comment by voroyam** [comment]
@DeepDiver1975

**Comment by settermjd** [comment]
I ran this, but all that happened was "Change collation for oc_migrations ..." was output to the console. Can you add a copy of your console output, or an animated gif showing you being redirected, please?

**Comment by settermjd** [comment]
On reading this issue again, it seems that the best place to add this issue is in core not in the docs. @DeepDiver1975?

**Comment by settermjd** [comment]
On reading the linked page, I don't completely agree that it's incorrect. However, the user at lease should be redirected to the specific section in the page that talks about [running the conversion](https://doc.owncloud.org/server/10.1/admin_manual/configuration/database/db_conversion.html#run-the-conversion). Secondly, this page could be extended to cover the topic in more detail.

**Comment by voroyam** [comment]
What env are you running @settermjd ? :D 11.0 branch?

Setup a clean 10.0.10 on Ubuntu 18.04 with a fresh maria-db server and run that command. You will get an error.

The issue here, as I described, is that it's the wrong page. The command is to convert character sets. The page it links is to convert the DB.

Why the section on that character set conversion is on a different page beats me.

This is the important stuff:

![grafik](https://user-images.githubusercontent.com/24212810/55714345-d14db800-59f2-11e9-9842-fe7df1bb5434.png)

which is on this page:

https://doc.owncloud.com/server/admin_manual/configuration/database/linux_database_configuration.html#configure-mysql-for-4-byte-unicode-support

the link in the error message is this:

https://doc.owncloud.com/server/admin_manual/configuration/database/db_conversion.html

So this 
https://doc.owncloud.com/server/admin_manual/configuration/database/**db_conversion**.html
is not this
https://doc.owncloud.com/server/admin_manual/configuration/database/**linux_database_configuration**.html

If a user is redirected to the wrong page he does not know what to do with that page.

**Comment by voroyam** [comment]
@settermjd If you don't mind, I would like to take care of this issue myself.

**Comment by settermjd** [comment]
@voroyam, please do.

**Comment by voroyam** [comment]
Closing this, opened issue in core

https://github.com/owncloud/core/issues/35856
