### ISSUE TITLE
[Appliance] Navigation tree should follow user journey (PO input needed)

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#917]
## What Needs to be Documented?

ownCloud/UCS appliance docs structure/order doesn't look right (when I think about the user journey)

https://github.com/owncloud/docs/blob/e27fb339a5ec17dcdac681285518de08548d1d22/modules/admin_manual/nav.adoc#L117-L131

![ownCloud_Documentation_Overview____ownCloud_Documentation](https://user-images.githubusercontent.com/214010/55731322-500a1b80-5a1a-11e9-872b-7af5143b5bbe.png)

@voroyam From your experience as the product owner, could you propose a better structure?

## Where Does This Need To Be Documented?

- https://github.com/owncloud/docs/blob/master/modules/admin_manual/nav.adoc
- https://github.com/owncloud/docs/tree/master/modules/admin_manual/pages/appliance

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by michaelstingl** [comment]
This probably supersedes the appliance changes proposed in https://github.com/owncloud/docs/issues/917

**Comment by voroyam** [comment]
Thank you for creating this. We are currently collecting issues that we could tackle for the docs afternoon hack day :) This could be mine.

**Comment by settermjd** [comment]
@michaelstingl, can you add an appropriate priority label, pls?

**Comment by voroyam** [comment]
My PR is merged, was this what you had in mind @michaelstingl ?

**Comment by michaelstingl** [comment]
> My PR is merged, was this what you had in mind @michaelstingl ?

Yeah, this looks much better now! 👍
