### ISSUE TITLE
10.2 branch is out-of-sync

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs#935]
There is a recently-created `10.2` branch. It is out-of-date with respect to `master`
Changes merged to `master` are getting back-ported as needed to `10.1` and `10.0` branches - good.
But now they also should be backported to `10.2` branch.

Either:
1) catch up with backports to `10.2` or
2) delete the `10.2` branch and only create it closer to the actual release (to save constant backports in the next days)

@settermjd

**Comment by settermjd** [comment]
I realised this yesterday. I'll aim to get it updated later today.

**Comment by settermjd** [comment]
afaik this is now resolved, @phil-davis. Please re-open if not.
