### ISSUE TITLE
Create a writing style guide

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#95]
A good style guide ensures that written documentation is of a consistently high standard, by ensuring that the quality of the documentation is consistent on each and every page, there is no ambiguity as to what terms mean, and is a final source of truth for questions from contributors.

The main points of reference that I'm using as the basis for a guide for ownCloud are:

- [The Gnome Style Guide](https://developer.gnome.org/gdp-style-guide/2.32/gdp-style-guide.html)
- [The Open SUSE Style Guide](https://doc.opensuse.org/products/opensuse/Styleguide/opensuse_documentation_styleguide_sd/)

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/blob/master/docs/style-guide.md

This is what we came up in the Knowledge sharing session.

Do you have something to add to this or can this issue be closed?

**Comment by voroyam** [comment]
A guide has been created. So the goal of this issue has been met. Closing.
