### ISSUE TITLE
occ command: add encryption version fix command

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#963]
## What Needs to be Documented?
Upcoming new occ command
https://github.com/owncloud/core/pull/35000 ([stable10] Backport of Add encryption version fix command)
Just for the record, a master forward port needs to be created
```
->setName('encryption:fixencryptedversion')
->setDescription('Fix the encrypted version if the encrypted file(s) are not downloadable.')
```

## Where Does This Need To Be Documented?
occ command set

## Why Should This Change Be Made? (Optional)
New core functionality
@sharidas pls add the rational behind that command

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

Backporting to 10.1 or below based on feedback

@sharidas @PVince81 @settermjd

**Comment by pmaier1** [comment]
Will be part of Server 10.3. Needs to be documented soon therefore.
