### ISSUE TITLE
Document Secure View with Collabora Online

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs#968]
## What Needs to be Documented?

New oC Enterprise feature: Secure View (https://github.com/owncloud/enterprise/issues/2917)

## Where Does This Need To Be Documented?

- [ ] User docs
  - What is secure view?
  - How to use secure view if available (e.g., permissions in sharing)
- [ ] Admin docs
  - What is secure view?
  - Setup: oC Enterprise >= 10.2 / richdocuments app (currently unreleased, need to check about min. version) / Collabora Online >= 4.0.3 for good performance.
  - How to enable Secure View => Richdocuments admin settings
  - How to change the watermark wording
  - Setting defaults for permissions (secure view permissions + hint on sharing permission defaults)

## Why Should This Change Be Made? (Optional)

New Enterprise feature release with Server 10.2.

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@PVince81 @mrow4a @settermjd

**Comment by micbar** [comment]
@settermjd please provide a status update.

**Comment by micbar** [comment]
@settermjd please provide a status update

**Comment by settermjd** [comment]
@micbar, just reading through this now.

**Comment by settermjd** [comment]
@micbar, I read through this last week. I estimate 1 working day, at the most, to get this completed.

**Comment by micbar** [comment]
@settermjd Thank you.
