### ISSUE TITLE
Antivirus doc add command to start service.

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#987]
https://doc.owncloud.com/server/10.1/admin_manual/appliance/Clamav.html

https://doc.owncloud.com/server/10.1/admin_manual/configuration/server/antivirus_configuration.html

We should include  `service clamav-daemon start`

Without this command there is no `clamd.ctl` in `/var/run/clamav/`

Also We should rename the Antivirus Configuration to Virus Scanner Support.

Because:

![grafik](https://user-images.githubusercontent.com/24212810/56144254-5f511200-5fa2-11e9-9ff1-43b8f7a9a7e3.png)

Looks to similar.

Also we should include 

![grafik](https://user-images.githubusercontent.com/24212810/56144332-80b1fe00-5fa2-11e9-8c2e-a84deddc2726.png)

In the normal antivirus config document. Happens way to often.

**Comment by settermjd** [comment]
@voroyam, on line 126 & 127, clamav-daemon is enabled and started:

```asciidoc
....
systemctl enable clamav-daemon.service
systemctl start clamav-daemon.service
....
```

Secondly, regarding "Also We should rename the Antivirus Configuration to Virus Scanner Support.", what's the motivation for changing the text? I'm not against it necessarily, just wondering what the motivation is.

**Comment by settermjd** [comment]
Regarding the final section of the document, i.e., `lsof` reference, where did that come from?

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1463

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1462

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/1464/files

**Comment by voroyam** [comment]
fixed, merged, backported
