### ISSUE TITLE
Update project README & documentation

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#99]
## TODO

- [ ] Document difference between when you should use the live preview plugin and when you should use Antora build tools

> Update your toolset so that it supports both AsciiDoc and Antora.

The intent of „toolset“ in the above sentence isn’t the clearest.

[Docs pages](https://github.com/owncloud/docs/blob/master/docs/install-antora.md) doesn’t include reference to install the site-generator component.

**Comment by PVince81** [comment]
I also suggest to add the npm commands directly: `npm install @antora/site-generator-default @antora/cli` and for building `node_modules/.bin/antora site.yml`.

**Comment by settermjd** [comment]
@PVince81, do the changes in #110 satisfy your feedback?

**Comment by PVince81** [comment]
@settermjd fine by me
